### ISSUE TITLE
Rappelling is client side only?

### ISSUE THREAD

**Issue by bethbtw** [CMGStudios/issue-tracker#100]
**Describe the issue you're facing**
When rappelling from the NHS Big Red Heli, only the person that is rappelling can see themselves in the animation
**Steps to reproduce**
Take out the NHS Big Red Heli or the HEMS-1 Heli as a pilot. Then get a passenger to sit in the back and rappel. 
**Expected behaviour**
Rappel should be visible for everyone, not just the person who is rappelling.
**Screenshots/Video**
https://streamable.com/yzja87
**Additional context**
N/A
**Any Texture Packs (if so list)**
N/A
**Perm ID**
182742

**Comment by alfiellds** [comment]
Hello Bethany, are you able to confirm whether this issue only occurs worth this specific helicopter or others also?

There is also PD version of this helicopter so it may be worth attempting to reproduce the issue using that one.

Any info you can provide is greatly appreciated and will help the developers fix the issue.

Many thanks.

**Comment by bethbtw** [comment]
There is also a problem with the NPAS Helicopter as seen in the video below:

https://streamable.com/yw70hk

**Comment by rubbertoe98** [comment]
Unable to reproduce.
