### ISSUE TITLE
[Bug]: TRUCKING PANICS

### ISSUE THREAD

**Issue by Mitch01159** [CMGStudios/issue-tracker#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when I'm trucking when one of my gang panics on advanced gang radios it clears my destination on my trucking job

### Expected behaviour

fix it

### Steps to reproduce

?.........

### Any Texture Packs? (If so list)

?..........

### CMG User ID

362140

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
