### ISSUE TITLE
[Bug]: HELICOPTER DIAMOND MINE

### ISSUE THREAD

**Issue by Mitch01159** [CMGStudios/issue-tracker#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

if you take a helicopter to diamond mine it automatically kicks you out the helicopter and puts you underneath the map

### Expected behaviour

stop it from happining 

### Steps to reproduce

?..........

### Any Texture Packs? (If so list)

?..........

### CMG User ID

362140

**Comment by crazychris2404** [comment]
Is there a clip of this? @Mitch01159

**Comment by crazychris2404** [comment]
Tested and not occuring please reopen with a clip and more steps to reproduce
