### ISSUE TITLE
[Bug]: pictures dont show after taking them

### ISSUE THREAD

**Issue by Ognhd** [CMGStudios/issue-tracker#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i take pictures using the phone i can see it straight after but if i go to my gallery or send it to someone i cant see them 

### Expected behaviour

I wanna see my pictures

### Steps to reproduce

I just take p8cture nothing there

### CMG User ID

414960

**Comment by crazychris2404** [comment]
Linked with a similar bug report
