### ISSUE TITLE
[Bug]: Craft BMX (Hammer emote begins, when complete, bmx spawns and disappears instantly

### ISSUE THREAD

**Issue by kelanLAWLOR** [CMGStudios/issue-tracker#1005]
https://github.com/CMGStudios/issue-tracker/assets/70713456/0d2ed210-3af4-45e2-bf89-675e8f448cef

https://github.com/CMGStudios/issue-tracker/assets/70713456/6a835704-d957-40ed-85d3-06ef0174ae40
 Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am nitro boosting the cmg discord, any time i try to craft a bmx it begins working just fine but when it spawns it instantly despawns

### Expected behaviour

/Craftbmx should cause the bmx to spawn with not issue

### Steps to reproduce

1, /craftbmx

### CMG User ID

182734

**Comment by crazychris2404** [comment]
This is not a ongoing issue 
Please re open this if it occurs again
