### ISSUE TITLE
[Bug]: ALCATRAZ bugs

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Listing a few bugs/issues with the new Alcatraz map

### Expected behaviour

Shouldn't be able to walk through a wall

Walking over a radar shouldn't mess up your gameplay

Spectating should work so you can spectate different people shouldn't

### Steps to reproduce

https://streamable.com/awtcpz - Can walk through a wall 

https://medal.tv/games/gta-v/clips/238z3RCk_lW3aH/d1337lZtkE56?invite=cr-MSxEUG4sNDE3Mzg1MDgs - if you walk on the radar on top of the Alcatraz messes up your view 

https://medal.tv/games/gta-v/clips/238wJcIEkda19i/d1337MAr6UXf?invite=cr-MSwzM0IsNDE3Mzg1MDgs - spectating battlegrounds on Alcatraz is broken or overall broken

### Any Texture Packs? (If so list)

N/A

### CMG User ID

9975

**Comment by packfile** [comment]
Due to the map files being protected from modification we're unfortunately unable to fix these bugs
