### ISSUE TITLE
[Bug]: game crashing and closing as soon as i load in

### ISSUE THREAD

**Issue by aidenshaw543** [CMGStudios/issue-tracker#1008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

as soon as i load in the game will crash and shut down

### Expected behaviour

can not do anything
![Screenshot 2024-03-27 193312](https://github.com/CMGStudios/issue-tracker/assets/165208279/19af6bab-c35b-4c89-b48b-08bbaa70be50)

### Steps to reproduce

n/a

### Any Texture Packs? (If so list)

no

### CMG User ID

373532

**Comment by packfile** [comment]
This vehicle has since been fixed and you should no longer crash
