### ISSUE TITLE
[Bug]: car plate not adding to car

### ISSUE THREAD

**Issue by R1-btw** [CMGStudios/issue-tracker#1009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Custom plate not adding to the velostern18unmarked

### Expected behaviour

The car spawn code, **velostern18unmarked** when ever I add a plate to the car it never adds to the cars, I went to Ryan’s and try to see if it’s on the plates so I can add it there but isn’t on there. I have tried to add a different plate and then add mine back on and still doesn’t work, tried 100 times and waiting 2 weeks still not on the car in at Ryan’s

### Steps to reproduce

Go city hall add the plate, go Ryan’s to bumpers - rear bumpers and find yours.

### CMG User ID

320186

**Comment by R1-btw** [comment]
@cmg-droid

**Comment by packfile** [comment]
The plates on the this vehicle are not changeable through city hall, they are a texture contained within the vehicle files. Only vehicles that use the GTA license plates will work with the city hall (typically they are smaller and don't have a custom font).

**Comment by R1-btw** [comment]
> The plates on the this vehicle are not changeable through city hall, they are a texture contained within the vehicle files. Only vehicles that use the GTA license plates will work with the city hall (typically they are smaller and don't have a custom font).

Ok so this vehicle will not be able to get a custom plate on it, I have just bought a plate lock slot and it don’t work can I get a refund

**Comment by R1-btw** [comment]
@cmg-droid
