### ISSUE TITLE
Admin menu whitelists

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#101]
**Describe the issue you're facing**
When trying to view/add/remove whitelists ingame the "SOA" one will always show as not given therefore leaving you unable to remove it. I believe it also has the issue of giving the whitelist to the person giving it aswell as whoever you try to give the whitelist to.
**Steps to reproduce**
Press F2 
Open Groups
Select SOA whitelist
Give Whitelist
**Expected behaviour**
Shows as given / not given allowing to remove said whitelist.
**Screenshots/Video**
Cant provide currently
**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
168906

**Comment by alfiellds** [comment]
Hello Chris, I can confirm this is an issue and will forward it to the developers.

Many thanks.

**Comment by rubbertoe98** [comment]
Fixed.
