### ISSUE TITLE
[Bug]: Casino Money Lost glitch

### ISSUE THREAD

**Issue by VeryDarkPenguins** [CMGStudios/issue-tracker#1010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bet 5mil on the casino and it just glitched and made me lose my money

### Expected behaviour

I lost all the money i had on casino due to the glitch, i hope i can get compensated 
https://medal.tv/games/gta-v/clips/247a27fmpd1veZ/d1337o8lsWfC?invite=cr-MSxHM0UsMjIyMDc3NDQ2LA Part 1 of glitch
https://medal.tv/games/gta-v/clips/247aTBotvv7LJZ/d1337sNlZ5Fa?invite=cr-MSxwOVEsMjIyMDc3NDQ2LA Part 2 of glitch

### Steps to reproduce

No idea, idk what the problem was

### Any Texture Packs? (If so list)

no

### CMG User ID

280978

**Comment by packfile** [comment]
Please refer to https://cmgstudios.net/forums/index.php?/topic/9391-information-regarding-compensation-requests/
