### ISSUE TITLE
[Bug]: get stuck crouching when looting a bag 

### ISSUE THREAD

**Issue by Flinny-k** [CMGStudios/issue-tracker#1011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When looting a bag, or searching a bag on PD once I exit the inventory i am then unable to come out of a crouch. I have been sorting it with t/reset.

### Expected behaviour

Loot bag, exit inventory by pressing L. Then stand up and carry on as usual 

### Steps to reproduce

Press button to loot bag, press L to exit inventory 

### Any Texture Packs? (If so list)

No

### CMG User ID

9733

**Comment by Flinny-k** [comment]
29/03/24 at 2050 another user had the same issue

**Comment by Keegasity** [comment]
Confirmed, Thank you for the report!

Steps To Reproduce:

1. Press E to loot a bag
2. Click Move on an item and then press L / Click Loot on and stay on the menu
3. This causes your character to get stuck in the crouched position

Other Information

1. This issue occurs once your character has done the uncrouch move seen in the clip attached. If you have exited the bag before the uncrouch move happens the bug does not occur

Video -> https://youtu.be/TgEmJh1I9a0

**Comment by Flinny-k** [comment]
Thank you

**Comment by packfile** [comment]
Thanks for the report, this has been fixed since Mondays restart
