### ISSUE TITLE
[Bug]: barbers is fucked cant change my face bare fat fam

### ISSUE THREAD

**Issue by knockdownginger** [CMGStudios/issue-tracker#1012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

can u fix the barbers my face is bareee fat blud

### Expected behaviour

no

### Steps to reproduce

aa

### Any Texture Packs? (If so list)

no

### CMG User ID

2801

**Comment by crazychris2404** [comment]
Can I get a proper description of the issue not just “barber is fucked” please
