### ISSUE TITLE
[Bug]: wl access not working

### ISSUE THREAD

**Issue by Gogetlacaag** [CMGStudios/issue-tracker#1013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It doesn’t let me access my wl gun even tho I have everything for it ?

### Expected behaviour

Idk why it’s not working

### Steps to reproduce

Idk 
Idk 
Idk

### CMG User ID

363214

**Comment by crazychris2404** [comment]
This is not something to report here
Make a donation support issue about your problem
