### ISSUE TITLE
[Bug]: Galaxy Nightclub MLO broken/unusable 

### ISSUE THREAD

**Issue by dannydodar** [CMGStudios/issue-tracker#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Video: https://youtu.be/UR9d-Hbr7iA

The interior is not loading as shown in the video. this is the case for all people trying to access the MLO. I discovered this when I was supposed to have my event there this last Saturday, when unfortunately we discovered the issue and had to improvise by having the event in the carpark outside, lol. If you could fix this as soon as possible it would be greatly appreciated as we rely on this location for regular RP.

### Expected behaviour

MLO interior loads.

### Steps to reproduce

Walk inside.

### Any Texture Packs? (If so list)

no

### CMG User ID

616

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report!
