### ISSUE TITLE
[Bug]: Payment plan 

### ISSUE THREAD

**Issue by TS12210** [CMGStudios/issue-tracker#1016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

got many cars on payment plan and they are not coming back

### Expected behaviour

Not sure

### Steps to reproduce

Not sure

### Any Texture Packs? (If so list)

NVE

### CMG User ID

1038

**Comment by packfile** [comment]
Can you please provide the spawncode(s) of the affected vehicle(s)?

**Comment by packfile** [comment]
Thanks for the report, this should be fixed since Monday's scheduled restart. Please check the "Failed return date" again to see when they will come back
