### ISSUE TITLE
[Bug]: how do i fix the you need to update your artifact verison i think its only admins whos can

### ISSUE THREAD

**Issue by jamietheguy12345** [CMGStudios/issue-tracker#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

get back to me asp

### Expected behaviour

dont let me on a admin needs to update this for me

### Steps to reproduce

help help help

### Any Texture Packs? (If so list)

no

### CMG User ID

344448

**Comment by crazychris2404** [comment]
Use f8 to connect 
Press f8 then connect s1.cmg.city
