### ISSUE TITLE
[Bug]: says i need to update my artefact files but only admins can do it?

### ISSUE THREAD

**Issue by smelty21** [CMGStudios/issue-tracker#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

pls help i’ve tried everythi f

### Expected behaviour

i go to load in cmg but says i have to update my art a fact flies witch only the person who owns the server can do 

### Steps to reproduce

i need help

### Any Texture Packs? (If so list)

no

### CMG User ID

344448

**Comment by crazychris2404** [comment]
https://github.com/CMGStudios/issue-tracker/issues/1017
