### ISSUE TITLE
[Bug]: /setuptrap

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you do /setuptrap , any further people who join the server cannot see it on the map where you placed it. 

### Expected behaviour

be able to do /setuptrap and people who load in can see it

### Steps to reproduce

do /setuptrap
someone loads in 
cannot see the trap

### Any Texture Packs? (If so list)

none

### CMG User ID

1220

**Comment by crazychris2404** [comment]
Confirmed
This has been a long term bug
