### ISSUE TITLE
[Bug]: outfit resets every time i relog

### ISSUE THREAD

**Issue by yellty12** [CMGStudios/issue-tracker#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

every time i relog i get set to default danny clothes but character remains the same and have tried clearing cache but no fix

### Expected behaviour

my outfit saves after logging out and back in

### Steps to reproduce

1. log in 2. change clothes 3. log out 4. log back in and clothes have reset

### Any Texture Packs? (If so list)

no

### CMG User ID

217691

**Comment by packfile** [comment]
Can you please attach your log file so this can be investigated. You can find it at `%localappdata%/FiveM/FiveM.app/logs`

**Comment by yellty12** [comment]
![image_2024-04-09_135859548](https://github.com/CMGStudios/issue-tracker/assets/129113962/de9684ed-3770-492c-8b4a-06bdac4d8571)
i have a lot of logs which one do i do? or send the whole log folder

**Comment by packfile** [comment]
Please delete (or cut & paste elsewhere if you want to revert) your KVS folder at `%appdata%/CitizenFX/kvs` and let us know if this fixes the issue. If not, then sending the latest log file from when the issue occured should be sufficient
