### ISSUE TITLE
BALLER ID SWAP NOT WORKING.

### ISSUE THREAD

**Issue by THEFISH98** [CMGStudios/issue-tracker#1023]
I recently purchased Baller Rank, but when I try to choose a new ID it says "FAILED TO PERFORM ID SWAP (ERROR 3)". 
![IMG_9851](https://github.com/CMGStudios/issue-tracker/assets/165983863/0aa73ad1-0a61-44e4-bbeb-8ae65f56c3b6)

**Comment by packfile** [comment]
This has been fixed since the latest restart, please try again
