### ISSUE TITLE
[Bug]: You cannot unclamp a car once clamped

### ISSUE THREAD

**Issue by GodlyTed** [CMGStudios/issue-tracker#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a police officer clamps a car, they cannot unclamp it. It instead tries to add another clamp.

### Expected behaviour

The clamp should be removed when the /clamp command is used on a car that is already clamped

### Steps to reproduce

1. Clamp a civilian vehicle with /clamp
2. Unclamp the vehicle with /clamp
3. Keep trying 

### CMG User ID

7756

**Comment by Keegasity** [comment]
Hello Ted,

I cannot replicate this issue, do you have a clip you can provide of this occurring?

Thanks

**Comment by GodlyTed** [comment]
Hello,

Here is a clip of the issue. After several failed attempts the clamp did remove, however, I am unsure as to why. 

https://youtu.be/3dd5VCcpl2o
