### ISSUE TITLE
[Bug]: Drive through side of bridge.

### ISSUE THREAD

**Issue by Pilly1** [CMGStudios/issue-tracker#1026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

You can drive through both sides of this bridge:
Clip Provided - https://streamable.com/6iofg5

### Expected behaviour

For the barrier too have collisions.

### Steps to reproduce

Go to the bridge in any car.
Drive through the side.

### Any Texture Packs? (If so list)

N/a

### CMG User ID

111719

**Comment by Keegasity** [comment]
Confirmed. Thank you for the report.

This is the case on both sides of the bridge 

(Coordinates - 569.55072021484,-356.60339355469,42.941551208496)

**Comment by packfile** [comment]
Thanks for the report, this has been fixed since 13th May
