### ISSUE TITLE
[Bug]: small banks are fooked

### ISSUE THREAD

**Issue by Grandaddy74** [CMGStudios/issue-tracker#1027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

after hacking the vault doors, i go to loot the safes, once looting i get no loot apart from the last safe which only gives me a total of 500k making me lose money

### Expected behaviour

to get loot from the safes after drilling them

### Steps to reproduce

im not sure if there is a way but i can screenshare in a different bucket to prove the outcome

### Any Texture Packs? (If so list)

NVE

### CMG User ID

1143

**Comment by packfile** [comment]
Thanks for the report, unfortunately without reproduce steps this can not be investigated. If you're able to provide a video we can take a look further
