### ISSUE TITLE
[Bug]: Payment Planned car not returning

### ISSUE THREAD

**Issue by pucynyce** [CMGStudios/issue-tracker#1028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I payment planned out a car, hes failed it but the car hasn't returned.

### Expected behaviour

Car gets returned

### Steps to reproduce

![pp car](https://github.com/CMGStudios/issue-tracker/assets/153567492/13018f6f-e0ba-4953-991d-d23d009cc5c7)
![pp car](https://github.com/CMGStudios/issue-tracker/assets/153567492/3adf488b-3ea7-4935-9b25-0e3b014d6cc0)

### Any Texture Packs? (If so list)

no

### CMG User ID

45535

**Comment by Lotfy11** [comment]
Got the same problem with my car.

**Comment by packfile** [comment]
Thanks for the report, this should be fixed since Monday's scheduled restart. Please check the "Failed return date" again to see when they will come back
