### ISSUE TITLE
[Bug]: Floating Bed Prop In Property (unable to delete move etc)

### ISSUE THREAD

**Issue by Volxcano** [CMGStudios/issue-tracker#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is a floating bed in the living room of the house i purchased, which is unremovable, please help on this matter 
![Screenshot 2024-04-19 233144](https://github.com/CMGStudios/issue-tracker/assets/167586420/11b095e9-71a8-43bc-b393-dc1f77a0c391)

### Expected behaviour

 unremovable floating props in property 

### Steps to reproduce

.

### Any Texture Packs? (If so list)

.

### CMG User ID

1820

**Comment by crazychris2404** [comment]
Appears to be similar to #1040 Will await a developer to investigate

**Comment by Volxcano** [comment]
@packfile still hasnt fixed lad, im unsure whats going on

**Comment by packfile** [comment]
Please use the "Delete Closest Prop" button that displays in the customisation menu
