### ISSUE TITLE
[Bug]: pps just not working 

### ISSUE THREAD

**Issue by Hypers87** [CMGStudios/issue-tracker#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i have had a pp out for 9 days and they havent done any payments and it hasnt even taken there miss week away. whats going on and when am i going to get my money or car back.

### Expected behaviour

for the miss week to be taken. 

### Steps to reproduce

i dont think there is a way other than u guys sorting it 

### CMG User ID

1341

**Comment by packfile** [comment]
Thanks for the report, this should be fixed since Monday's scheduled restart. Please check the "Failed return date" again to see when they will come back
