### ISSUE TITLE
[Bug]: Can't kick from F5 gang with correct permissions.

### ISSUE THREAD

**Issue by Pilly1** [CMGStudios/issue-tracker#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a member of a gang has the invite and kick permissions, they are unable too kick people from the gang.

I have found that only the permission "Leader" has permission to kick from the gang, and that isn't really a role that everyone who should be able too kick should have.

### Expected behaviour

Players with kick permissions can kick people from the gang.
Give correct permissions to players (Kick guest and kick players) but not leader role, and see that you're unable to kick.
Give leader role and see that you can now kick.

### Steps to reproduce

1. Be in an F5 gang with kick permissions but not leader permissions.
2. Attempt to kick and see you cannot.

If any more evidence is needed, I can provide, it would be nice to see this fixed as it has been an issue for a while and has been reported multiple times and also causes some problems for the bigger gangs who don't just rely on the "leader" roles.

### Any Texture Packs? (If so list)

N/a

### CMG User ID

111719

**Comment by packfile** [comment]
Thanks for the report, this should have been fixed since May 13th
