### ISSUE TITLE
[Bug]: Can't start new trucking job after storing truck.

### ISSUE THREAD

**Issue by kake69420** [CMGStudios/issue-tracker#1032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you start a trucking job and collect your trailer then store your truck with the trailer on the back, the job cancels immidiately. Then it doesn't let you start a new job. It will start the job for a second then cancel it automatically. 

### Expected behaviour

When you start a trucking job and collect your trailer then store your truck with the trailer on the back, the job cancels immidiately. Then it should let you start a new job.

### Steps to reproduce

1. Start a trucking job.
2. Spawn truck.
3. Pick up trailer.
4. Store Truck.
5. Go back to start new trucking job.
6. Job will cancel automatically.

### Any Texture Packs? (If so list)

No.

### CMG User ID

372683

**Comment by crazychris2404** [comment]
I have not experienced this and havent heard any reports please reopen this issue with a clip if still persistent
