### ISSUE TITLE
[Bug]: severe packet loss

### ISSUE THREAD

**Issue by 2slickrick** [CMGStudios/issue-tracker#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently every time i log in my character is etiher reset or invisible, when i go to change that 80% of the time nothing happens. so what i ignore that and continue playing. Another major issue is my car, whenever im driving my car it starts flying through the floor as if theres no floor same thing happens some times on foot. My other problem is the fact that if i ever walk into new buildings they dont load in, i cant see doors walls practically anything . In addition when im trying to make money being a lorry driver, my lorry just gets stuck in random places on the road and i have to wait up to 10 mins for anything to change and then finally when i get to my destination where i deliver my cargo nothing happens it doesnt work. Probably half my hours on this server are due to facing bug issues

### Expected behaviour

To not have these problems

### Steps to reproduce

Unsure

### Any Texture Packs? (If so list)

N/A

### CMG User ID

422531

**Comment by crazychris2404** [comment]
We would need more details to be able to fix this problem as the info you have provided indicates a user specific error
