### ISSUE TITLE
[Bug]: Cant spawn car in cinematicworld

### ISSUE THREAD

**Issue by 7mando** [CMGStudios/issue-tracker#1035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Im trying to spawn a car in cinematic world but it wont and it says you are in the incorrect session.

### Expected behaviour

Car should spawn 

### Steps to reproduce

try spawn the car 

### Any Texture Packs? (If so list)

NVE,QuantV,Reshade,ENB,Raytracing

### CMG User ID

1850

**Comment by crazychris2404** [comment]
this is Intentional and not a bug
