### ISSUE TITLE
[Bug]: Car Door doesn’t open

### ISSUE THREAD

**Issue by OnlySola** [CMGStudios/issue-tracker#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I brought a car last night and my mates were telling me that the doors don’t work on the car but it was fine for a few tries, after I brought it and went in the city I tried to get back in my car and it would just make me walk into the door for around 20 seconds and then maybe teleport me into the car and it is a nice model I just want to be able to drive it and the doors actuallly work

### Expected behaviour

The door will not open at all

### Steps to reproduce

…

### CMG User ID

417692

**Comment by crazychris2404** [comment]
Some cars are unfortunately like this and as a model issue will not be fixed

a workaround would be pressing q before you enter the car
