### ISSUE TITLE
[Bug]: Cleaning dirty money gives no clean cash

### ISSUE THREAD

**Issue by francesko799** [CMGStudios/issue-tracker#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Went to clean dirty money 3 times got 300k, 700k and lost 1.3M+ last time

### Expected behaviour

get clean money

### Steps to reproduce

Burner phone from car, store burner to car and go to clean money

### CMG User ID

421256

**Comment by packfile** [comment]
Thanks for report, please provide a video for this to be investigated further (the logs suggest this money was given)
