### ISSUE TITLE
[Bug]: When i am doing a diamond Run sometimes the boot of my truck spawns empty

### ISSUE THREAD

**Issue by B33SY** [CMGStudios/issue-tracker#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue has happend around 9-10 Times within the last 3 days, I have been doing diamond runs and I will mine and fill up all of my trucks and will go to processing or even go to the port to sell and one of my trucks boot spawns empty.

### Expected behaviour

To not have the inventory of the vehicle be empty 

### Steps to reproduce

1. Go to mine
2. Fill up all trucks
3. go to processing and process trucks 
4. once process all diamonds head to the port/seller
5. pull out a truck sell 
6. sometimes a truck will spawn with no boot

### Any Texture Packs? (If so list)

no texture pack

### CMG User ID

47102

**Comment by crazychris2404** [comment]
Do you have a clip of this?

**Comment by B33SY** [comment]
unfortunately i do not as none of my recording devices work

**Comment by packfile** [comment]
Thanks for the report, unfortunately without reproduction steps this can not be investigated. Due to no other reports of this, will close until a video can be obtained
