### ISSUE TITLE
Cant buy ump45 from platinium large arms in vip islands

### ISSUE THREAD

**Issue by W1ll-K** [CMGStudios/issue-tracker#1039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I cant buy the ump45 from the vip island even though i have plat and premium rank

### Expected behaviour

Want to be able to buy the gun

### Steps to reproduce

https://medal.tv/games/gta-v/clips/2aXMk16xePTRoI/d1337Sky3DUt?invite=cr-MSxta1gsMjA0NDA0NzMxLA

### Any Texture Packs? (If so list)

NO

### CMG User ID

388832

**Comment by packfile** [comment]
Thanks for the report, please purchase the "Gang License" from City Hall to be able to access any Large Arms gunstore
