### ISSUE TITLE
business centre 7

### ISSUE THREAD

**Issue by sk3ng** [CMGStudios/issue-tracker#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

inside my business center i have gold piles floating in the air and i cant delete them

### Expected behaviour

should be able to delete

### Steps to reproduce

please can u guys remove all of the gold piles

### Any Texture Packs? (If so list)

no

### CMG User ID

1619

**Comment by packfile** [comment]
Please use the "Delete Closest Prop" button that displays in the customisation menu
