### ISSUE TITLE
[Bug]: Killfeed no longer highlights in red when you kill someone / you get killed 

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#1041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

before the most recent headshot icon change when you kill someone your name doesnt get highlighted like it used to before the change. dk if this is intentional or what
![image](https://github.com/CMGStudios/issue-tracker/assets/90797980/ca42c580-8f3a-491a-b519-28973a9b565c) this is what it looked like before
![image](https://github.com/CMGStudios/issue-tracker/assets/90797980/508a41f7-3d39-4da8-84f7-bad4f905faea) it is no longer highlighted in red
![image](https://github.com/CMGStudios/issue-tracker/assets/90797980/89653feb-5e1f-4a71-a9d5-2484104508aa) not just for headshots as well as it happened after the addition of the headshot icon

### Expected behaviour

when you kill someone you name no longer gets highlighted in red

### Steps to reproduce

kill someone
doesnt highlight in red

### Any Texture Packs? (If so list)

none

### CMG User ID

1220

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
