### ISSUE TITLE
[Bug]: When I try to sell/rent FIB Building, it says I have unpaid house tax however there isn't an option to pay the existing house tax.

### ISSUE THREAD

**Issue by Rae-uk** [CMGStudios/issue-tracker#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to sell/rent FIB Building, it says I have unpaid house tax however there isn't an option to pay the existing house tax. I have tried renting another building to see if that would allow me to pay the house tax on FIB but sadly it didn't work. 

### Expected behaviour

An option which allows me to pay the house tax, so I can then rent/sell the building.

### Steps to reproduce

Go to FIB Building
Press Sell building or Rent Building

### Any Texture Packs? (If so list)

n/a

### CMG User ID

288340/1405

**Comment by packfile** [comment]
Thanks for the report, are you able to enter the building or does it prevent you too?

**Comment by Rae-uk** [comment]
> Thanks for the report, are you able to enter the building or does it prevent you too?

Evening, I'm not sure if this is closed or not but I figured it out after some investigating:

You need to find out which building you had on rent before, which house tax was not paid on (In this case Playboy Mansion)
You then need to get that building on rent (which can be a pain), where you can then pay of the house on the building you rented FIRST. Then after that, you can go to the building where you couldn't pay the house tax previously and you'll find you now can.

I'm sure multiple people have had this issue before, someone even came to me today asking for help so would be great if a slight amendment was made.
