### ISSUE TITLE
[Bug]:  1:1 lock broken now a car dev has removed all 3 ytd in livery. Waa changed 4/5. Car been in 5 years no ussues till now

### ISSUE THREAD

**Issue by OG-SPLINTER** [CMGStudios/issue-tracker#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Spawncode - rmodgt63police

Cant report car through bot as its already had a report in. Car has been in for past 4/5 years and is a 1:1 baller lock.
![image-29](https://github.com/CMGStudios/issue-tracker/assets/144470008/1b91e8fa-4155-4dfc-ba9a-1bcb72e31e87)
![image-33](https://github.com/CMGStudios/issue-tracker/assets/144470008/18116a8a-e47e-4b93-874e-49dcc6fb0be2)
. No issues, till a car dev removed all 3 liveries and now broke the car. Car is stuck in a slime green and can't change colour. Needs reverting back to how it was. 

### Expected behaviour

Revert changes to fix. Car been in 5 years. Now Livery been removed after being in this long.  Revert back to fix.

Picture how it was before 
![image-24](https://github.com/CMGStudios/issue-tracker/assets/144470008/ce5268a0-1020-467d-a866-21e889bf6f61)

### Steps to reproduce

Spawn car   rmodgt63police,  see car Livery is broken - go back and replace the original ytd files - load car back in and make sure it'd fixed.

### Any Texture Packs? (If so list)

No

### CMG User ID

2725

**Comment by Keegasity** [comment]
Thank you for the report!

However, this is not a bug this is a car issue. This will be closed but will be passed onto the Car Developers
