### ISSUE TITLE
[Bug]: UKBF Radios still not organised 

### ISSUE THREAD

**Issue by ScarabMonkeyy** [CMGStudios/issue-tracker#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have already wrote a detailed description about this in
https://github.com/CMGStudios/issue-tracker/issues/963
It was supposedly fixed but it isn't 

### Expected behaviour

Already explained 

### Steps to reproduce

Already explained 

### Any Texture Packs? (If so list)

NVE

### CMG User ID

369718

**Comment by Keegasity** [comment]
Confirmed.

This issue still exists and has not be resolved.

Steps to reproduce
1: Have two players clock on UKBF with different ranks
2: There will be no organisation to these ranks (Higher rank can display at bottom)

**Comment by packfile** [comment]
Thanks for the report, this should have been fixed since May 13th
