### ISSUE TITLE
[Bug]: gang funds cant withdraw

### ISSUE THREAD

**Issue by bstocker006** [CMGStudios/issue-tracker#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

says gang bank in use when trying to withdraw from gang funds - name is Dole Dossers - it is not advanced gang

### Expected behaviour

can deposit but when press withdraw it says gang bank in use

### Steps to reproduce

open gang funds
press withdraw
type 1,000,000
should say gang bank in use

### Any Texture Packs? (If so list)

N/A

### CMG User ID

180260

**Comment by packfile** [comment]
Thanks for the report, please try again from tomorrows restart
