### ISSUE TITLE
[Bug]: piloting job in general

### ISSUE THREAD

**Issue by interstellarfrog** [CMGStudios/issue-tracker#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. When driving through a plane whilst piloting, there is no issues on your side but on others screens there is a potential to cause massive FPS drops (60+ in my experience when it gets bad) and stutters as the planes collide with each other and glitch about.

2. The carts that spawn in cannot be seen or collide with others planes but they can and have collided with the missiles on the aircraft carrier (which can ruin someones day) I have a clip of this happening to me.

### Expected behaviour

1. I expect other peoples planes not to glitch about and collide with each other when piloting.

2. I'd expect the carts to not be able to explode the missiles on the aircraft carrier killing other people.

### Steps to reproduce

1. simply start a piloting job and go to a high congestion airport drop off/pick up area, and watch planes collide.

2. go to the aircraft carrier with piloting job and collect / drop off passengers positioning the plane so the cart spawns on the missiles (causing a chain reaction of explosions)     or    just use admin powers to drop the spawned cart onto the missiles (its pretty obvious what the outcome is going to be either way)

### CMG User ID

257484

**Comment by packfile** [comment]
Sandy shores was removed as a drop off location so collisions shouldn't affect general players anymore
