### ISSUE TITLE
[Bug]: Bank heist setup 2 ( the train ) freeze

### ISSUE THREAD

**Issue by interstellarfrog** [CMGStudios/issue-tracker#1048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A while back I did the bank heist setup number 2 where you have to drive to the train tracks and block the train with one of the cars, the only problem was that I was the host and I was inside of the boot of the car when we parked on the tracks, this caused me to see the camera view at the train tunnel, which the train drove past leaving me staring at the tunnel, from my friends POV's the train did not stop at the tracks and flew straight through the car and continued down the tracks which was kinda funny at the time but I was still stuck in the boot, after some time it allowed me to exit it but I could not use any keys apart from F8, so my friends had to call admin to save us, the admin could not do anything to fix it but kill me and my friends but when he did it instantly brought me back to the real world in the place I was killed bleeding out on the floor, then when he tp'd me back to the heist setup I just kept falling through the map until I did a full restart as the solid ground had not spawned in, just the distant LOD.

### Expected behaviour

Person inside of the boot should be moved aside like the rest of the players, without facing any issues.

### Steps to reproduce

I have no idea if this was a one off issue but here is the steps either way

1. start setup number 2, with at least one other person
2. have the host enter the boot of the nissan looking car, without admin powers as this may interfere with the controls locking in the cutscene
3. get person number 2 to drive the nissan onto the train tracks at the mission location whilst the host is still inside of the boot
4. Wait

### CMG User ID

257484

**Comment by Simonstv** [comment]
Thanks for the Report!.
After reading the above would you be able to provide a clip of the situation as i don't have any experience with the heists nor do them so any provided clips would be useful.

**Comment by interstellarfrog** [comment]
Unfortunately I do not have a clip of this bug, but its pretty easy to reproduce (if it is reproducible), just by starting heist setup 2 and driving to the first marker with the host inside of the boot of the car
