### ISSUE TITLE
Catalogue bug/issue 

### ISSUE THREAD

**Issue by ItsZeeDon** [CMGStudios/issue-tracker#105]
**Describe the issue you're facing**
My friend imported the Norwegian Sea king heli but received a base gta heli that shouldn’t be in the server. It can shoot from a mini gun…
**Steps to reproduce**

**Expected behaviour**

**Screenshots/Video**
![BE79EE7C-0596-4666-9FCE-49A743D3A5E2](https://user-images.githubusercontent.com/88059110/127222998-20212462-f272-4c16-958c-52052e408b20.jpeg)
![B07C75E3-ABC5-405A-A3DD-C754EFE49CCE](https://user-images.githubusercontent.com/88059110/127223002-54c6ac53-9e21-4a47-8a8c-febda5b7600f.png)

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
176641

**Comment by alfiellds** [comment]
Forwarded for review by Robbster.

**Comment by rubbertoe98** [comment]
Fixed from next restart.
