### ISSUE TITLE
[Bug]: Stuck In Cars

### ISSUE THREAD

**Issue by SharkyGit** [CMGStudios/issue-tracker#1050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically, whenever i get in a car or any other vehicle my bind will not work even though my bind is set to F. This is extremely painful as I've lost money and been shot in my car even though i cant get out. 

### Expected behaviour

When you sit in a car and press your bind the game doesn't react at all.

### Steps to reproduce

Get in a car and try to exit

### CMG User ID

424644

**Comment by Keegasity** [comment]
Good evening,

Can you provide a clip of this occurring please
