### ISSUE TITLE
[Bug]: no clipboard animation when at processing LSD for woman

### ISSUE THREAD

**Issue by MewPrincess5** [CMGStudios/issue-tracker#1051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have the timer and process happens for stage 2/processing LSD, but I don't have the Clipboard animation 

### Expected behaviour

Click to process, process happens but no animation 

### Steps to reproduce

.

### CMG User ID

407833

**Comment by Simonstv** [comment]
After testing this my self and reviewing this i can confirm when your at the Military Base Stage that if your in a female gender you have no clipboard which appears to me i don't think its a big issue, as the process timing is still the same.
