### ISSUE TITLE
[Bug]: Heist setup stuck on same mission.

### ISSUE THREAD

**Issue by S1llious** [CMGStudios/issue-tracker#1052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

I was setting up the heist for the pacif standard bank and completed setup 1. When I go back into the heist setup factory, it wants me to do heist setup 1 again and isn't progressing as it should. I've re-started the game and the issue is still occuring.

### Expected behaviour

I have done the first heist setup before (there was a bootwipe before I got to do the second hence I know how it should work and have had to do it again) and when I went back into the heist setup factory, the second setup mission was ready to go because I had already completed the first. This is no longer the case and the second mission is not coming up as it should. 

### Steps to reproduce

Get to second heist setup mission on pacific standard bank.

### CMG User ID

421335

**Comment by Declare5M** [comment]
I believe the game doesn't automatically move it to the next required setup, Have you pressed the Right Arrow key when on the mission? it should move you to the next setup

**Comment by interstellarfrog** [comment]
You have to click the Right Arrow to go to the next setup, you can do them in any order at any time now.

**Comment by S1llious** [comment]
If you were to press the right arrow key, it takes you to a different heist entirely, not the next setup mission for the same heist. Once you have completed a mission on a heist, it should automatically be ready for the next one when you go on it. This is what has happened before.
________________________________

**Comment by S1llious** [comment]
When you hit right arrow key, it doesn't take you the next heist setup mission for the same heist, it takes you to a new heist setup entirely. I have done the first mission before and when I went back it was ready to do the second. Since then, there was a boot wipe so I have had to re-start my progress. I've done the first mission now and when I go back to the heist setup factory, the second mission is not available. It wants me to do the first one again.

________________________________

**Comment by S1llious** [comment]
I sincerely apologise for the previous email, you were absolutely right. Brain fart moment on my part there, no clue what I was thinking. Sorry.
________________________________

**Comment by Simonstv** [comment]
Thank you for the Report!
After reading the above, i believe there is no issue with the heist there for I'll close this issue.
