### ISSUE TITLE
[Bug]: "don't fully dead player automatically if nhs are nearby" glitched, kills player again after revive.

### ISSUE THREAD

**Issue by jemeii** [CMGStudios/issue-tracker#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With the new feature implemented with NHS being nearby you would not "bleed out" as fast as normally, myself and another were revived and then died within a second or two afterwards, restarting the death timer.

https://medal.tv/games/gta-v/clips/2dn2lq4oLceRxS/d1337uUqJDyE?invite=cr-MSxncGQsNzcxODk3MDAs

### Expected behaviour

I am not 100% sure if this is the intended behavior, however I would assume it instead isn't supposed to kill you again, instead letting you get up.

### Steps to reproduce

1. Die 
2. Let your timer run out with NHS in the vicinity.
3. Let NHS revive you.

### CMG User ID

397117

**Comment by Simonstv** [comment]
Tested and can confirm after being revived with NHS nearby with timer being at 00:00, after about 30 to 60 seconds you instantly die again.
Thank you for your reported this has been forwarded on to the developers.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed since Monday's scheduled restart
