### ISSUE TITLE
[Bug]: Border force chat glitches with pd chat

### ISSUE THREAD

**Issue by ScarabMonkeyy** [CMGStudios/issue-tracker#1054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you are on pd and have a callsign there
And decide to clock on UKBF and use the border force chat normally and sending a message, you will find that next to your name is your PD callsign and not your UKBF callsign

If you do not have a pd callsign then it remains blank

### Expected behaviour

When typing a message on border force chat while clocked on as border force, when sent next to your name should be ur UKBF callsign and not ur pd one if if you have one

### Steps to reproduce

1- be on pd and have a callsign there
2- clock on UKBF and type a message in border force chat
3- you will find your pd callsign next to your UKBF message 

### Any Texture Packs? (If so list)

NVE

### CMG User ID

369718

**Comment by Simonstv** [comment]
https://medal.tv/games/gta-v/clips/2efnn5p_K4Ao_5/d1337HouLgH0?invite=cr-MSxhVTQsMTk3MDgyMDc2LA

After gaining more information i will pass this onto the developer team however can't reproduce as i currently don't have a callsign within Border Force.
