### ISSUE TITLE
[Bug]: Cell in UKBF roster that doesnt give callsign

### ISSUE THREAD

**Issue by ScarabMonkeyy** [CMGStudios/issue-tracker#1055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

in the UKBF Roster when someone is assigned to the B23 cell callsign being D-1, it doesnt give the person a callsign after server restart

### Expected behaviour

when someone is assigned to that callsign they should have the D-1 callsign

### Steps to reproduce

1- have access to the UKBF roster
2- set your perm ID to the B23 cell callsign 
3- upon the next server restart the callsign will not appear but all the others would update perfectly

### Any Texture Packs? (If so list)

Natural Vision Evolved 

### CMG User ID

369718

**Comment by crazychris2404** [comment]
This would be more something regarding how your roster is made i would assume 
However i will leave this as trivial for a developer to investigate

**Comment by packfile** [comment]
Please hide that row and continue to use the others as normal
