### ISSUE TITLE
high roller blackjack [Bug]: 

### ISSUE THREAD

**Issue by hadzasco** [CMGStudios/issue-tracker#1057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i bet 1.5 million on the blackjack and it kicked me off the table and the bet went through i recorded it on my phone right when it kicked me off the table my medal did not let me clip anything 

https://github.com/CMGStudios/issue-tracker/assets/170454326/d7e2cf97-76cd-4a65-9b64-61b845c47095

### Expected behaviour

blackjack bug

### Steps to reproduce

sat on table bet 1.5mill and it took the money without me betting

### Any Texture Packs? (If so list)

reshade

### CMG User ID

232543

**Comment by crazychris2404** [comment]
Unfortunately without reproduceable steps this cannot be fixed and the minimum compensation requirement is a loss of 5m
