### ISSUE TITLE
[Bug]: Blue pop-up box from the plat menu is not working

### ISSUE THREAD

**Issue by kinderkinder1** [CMGStudios/issue-tracker#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello all,

Hope you are well.
I have this bug of the blue pop up menu from plat not opening up. I have enough plat days to sell and tried to restart pc/game but nothing fixed it.
It happened to me yesterday as well, it got fixed with the servers restart and now it happened again.
Is there anything I can do on my end to prevent this from happening ? 

Thank you in advance

### Expected behaviour

The blue-box should appear in order to be able to sell plat.

### Steps to reproduce

1. type in chat /cmgclub
2. Click Manage Subscription -> Sell Platinum Sub days.
3. the blue pop-up box is not appearing at all.

### Any Texture Packs? (If so list)

no

### CMG User ID

206765

**Comment by crazychris2404** [comment]
I know this issue was around ages ago but haven't had any reports since meaning it is likely a isolated issue if you can find any more info on it please reopen this issue and the development team will investigate

**Comment by L14M86** [comment]
NOT A ISOLATED ISSUE
