### ISSUE TITLE
I got the blackjack glitch 2 days in a row now 

### ISSUE THREAD

**Issue by hadzasco** [CMGStudios/issue-tracker#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

lost 3 mill past 2 days in a row now like i bought that money from the store and because of a glitch it gets rid of my chips and dealer keeps betting can i please get comp for this because im losing money for free. i got a clip to prove this also 1.5 mill yesterday and 1.5 mill today gone with the same glitch.

https://youtu.be/lRMKxxjMC14?si=-th9sYsN8j212pkn

### Expected behaviour

high roller blackjack glitch

### Steps to reproduce

blackjack

### Any Texture Packs? (If so list)

reshade

### CMG User ID

232543

**Comment by crazychris2404** [comment]
Unfortunately without reproduceable steps this cannot be fixed and the minimum compensation requirement is a loss of 5m
