### ISSUE TITLE
HMP Clock On Ranks

### ISSUE THREAD

**Issue by nSpexx** [CMGStudios/issue-tracker#106]
**Describe the issue you're facing**
People are not being able to clock on as their rank and getting the pay they deserve for their duties.

**Steps to reproduce**
Add following ranks:
Trainee Prison Officer
Prison Officer
Senior Officer
Specialist Officer
Principal Officer
Supervising Officer
Custodial Supervisor
Assistant Governor
Deputy Governor
Governor

As well as a pay rise. LFB get more than Supervising Officer.

**Expected behaviour**

Fix ranks and money.

**Screenshots/Video**

N/A

**Additional context**

N/A

**Any Texture Packs (if so list)**

N/A

**Perm ID**

147339

**Comment by arthur-rl** [comment]
This is not what the **bug** reporting system is for.
