### ISSUE TITLE
[Bug]: TV bug in garden

### ISSUE THREAD

**Issue by stinkyminge6** [CMGStudios/issue-tracker#1060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i bought a house ( Mega Luxury n07)
the tv in the garden the picture works but no audio comes from the TV 

### Expected behaviour

the TV not working in the garden

### Steps to reproduce

/TV

### Any Texture Packs? (If so list)

NVE quant V and reshade

### CMG User ID

75412

**Comment by crazychris2404** [comment]
This is also occurring on my MLO where one of the tvs work so I decided to just place a tv in front as a work around thinking it’s to do with the custom props however I’ll leave this for confirmation from devs

**Comment by crazychris2404** [comment]
https://github.com/CMGStudios/issue-tracker/issues/1061 Another mention of this issue

**Comment by packfile** [comment]
You must be inside of the home for the video and audio to work, as this is a teleport interior (i.e. unable to access garden whilst inside) unfortunately there is not a way around this at this time.
