### ISSUE TITLE
[Bug]: Tv not working in Business Centre 2

### ISSUE THREAD

**Issue by FinnWWFC** [CMGStudios/issue-tracker#1061]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

whenever you try and play a vid in Business Centre 2 you can only here the sound but not the actual video 

### Expected behaviour

the tvs does not work

### Steps to reproduce

/tv then play the vid you want then it shows up on the screen

### Any Texture Packs? (If so list)

no

### CMG User ID

364

**Comment by crazychris2404** [comment]
Duplicated issue same as previous one just about seperate buildings
