### ISSUE TITLE
[Bug]: /p chat not mentioning you

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#1063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

if someone attempts to @ you in /p chat it does not highlight in yellow similar to in ooc or global chat

### Expected behaviour

someone attempts to @ you in /p chat
it doesnt highlight in yellow

### Steps to reproduce

get someone to @ you in /p chat
doesnt highlight in yellow

### Any Texture Packs? (If so list)

none

### CMG User ID

1220

**Comment by Keegasity** [comment]
Good Evening,

After testing @ing someone within OOC, I can confirm this still works and highlights in yellow.

Any further issues please feel free to dm me.

Thanks,
Keegan

**Comment by 004Luke** [comment]
Nah u can @ ppl in ooc. You can't @ ppl in /p chat

**Comment by Keegasity** [comment]
Good Evening,

Following reopening and retesting this. I can confirm it is an issue.

![image](https://github.com/CMGStudios/issue-tracker/assets/85527390/35423f03-1a11-4e49-9ad9-cb668887da9c)
