### ISSUE TITLE
[Bug]: I purchased a cash bag off the store and never recieved the money in game

### ISSUE THREAD

**Issue by KrisKonuker** [CMGStudios/issue-tracker#1064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I purchased a cash bag off the store and never recieved the money in game

### Expected behaviour

to receive my money

### Steps to reproduce

try to buy off store i guess? 

### CMG User ID

425611

**Comment by 2140CMG** [comment]
This likely isn't a bug do /store ingame and you can claim your items there or if you need help open a ticket in the Cmg support discord
