### ISSUE TITLE
[Bug]: HMPS issues

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#1065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Couple issues related to HMPS.

1. /reset allows inmates to go from any point in the prison (Including yard, segregation and such) to tp back to their cell
2. Can't tase people in segregation/Gym/Shower due to some area bug
3. /wc only showing rank/callsign, not the guards name

### Expected behaviour

1. FOr them to stay on the same spot
2. To be able to tase them
3. To display the guards name

### Steps to reproduce

1. Be arrested, go anywhere. /reset
2. Go into Seg/Gym/Shower. tase someone. suffer
3. Self explanitory

### CMG User ID

14009

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by wooffighter** [comment]
Hi, Thanks for fixing the warrant card and the /reset issue
However it seems like the tasers still don't work in the gym, and seg. and partially in the shower too. Could this be looked at firther please
