### ISSUE TITLE
[Bug]: supporter rank showing import cars 

### ISSUE THREAD

**Issue by kitch0121** [CMGStudios/issue-tracker#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when buying supporter rank in the description it only shows a vip import but when you press on the link to be shown the vehicles u can get with the vip car slot it takes you to the import cars list not the vip cars list 

### Expected behaviour

should be taken to vip cars list not import cars list 

### Steps to reproduce

1, press on supporter rank
2.  press on [here]. A list of vehicles available to import can be found [here]

### Any Texture Packs? (If so list)

N/A

### CMG User ID

1186

**Comment by Morggs27** [comment]
This is a problem for all ranks not just supporter

**Comment by packfile** [comment]
Thanks for the report, this has been changed
