### ISSUE TITLE
[Bug]: Regarding the new vehicle update 

### ISSUE THREAD

**Issue by Mez970** [CMGStudios/issue-tracker#1069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a Obey RS6 which is a sports super, and it is limited to 150mph, it should be 250mph. I have footage available if needed

The Spawncode: Mansrs6666

kind regards,
Mez

### Expected behaviour

Should do 250mph only does 150mph

### Steps to reproduce

change the vehicle settings 

### Any Texture Packs? (If so list)

n/a

### CMG User ID

1437

**Comment by crazychris2404** [comment]
This due to you being clocked on as a trucker
