### ISSUE TITLE
I won the car off the premium wheel abd i havent recieved it 

### ISSUE THREAD

**Issue by Ksutton06** [CMGStudios/issue-tracker#107]
**Describe the issue you're facing**i span the wheel for 50k and won the car but i have not recieved it and admin told me to come here
i want to recieve the car i won

*need help

**Any Texture Packs (if so list)**supreme

**Perm ID**217847

**Comment by loganuk** [comment]
Hello Ksutton06,

Can I ask which admin you spoke to?

Also do you have proof of winning the car from the wheel via POV video or anything else?

**Comment by loganuk** [comment]
No information given - Closed

**Comment by loganuk** [comment]
No information given - Closed
