### ISSUE TITLE
[Bug]: handshaking not loading

### ISSUE THREAD

**Issue by Maximilian-Hagman** [CMGStudios/issue-tracker#1073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i can not load true handshaking. im having on vpn, off vpn, reistalling fivem, restaring my pc, f8 whit ip.

### Expected behaviour

not loading

### Steps to reproduce

connect to server

### Any Texture Packs? (If so list)

no

### CMG User ID

i dont have one cant get on

**Comment by crazychris2404** [comment]
Seek assistance in game support as this is not a widespread bug
