### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wizzwizzwizz** [CMGStudios/issue-tracker#1074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you go to take your drivers license, it just keeps you in the screen saying "you will end your test here" or smth and it doesnt let u drive the car it just stays in one screen.

### Expected behaviour

When you go to take your drivers license, it just keeps you in the screen saying "you will end your test here" or smth and it doesnt let u drive the car it just stays in one screen.

### Steps to reproduce

a

### Any Texture Packs? (If so list)

N/A

### CMG User ID

326744

**Comment by jazza212** [comment]
thats happening to me two

**Comment by crazychris2404** [comment]
Linked with https://github.com/CMGStudios/issue-tracker/issues/1075
