### ISSUE TITLE
[Bug]: it wont let me do my driving test and put me on a frozen screen

### ISSUE THREAD

**Issue by jazza212** [CMGStudios/issue-tracker#1075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i go into and start the driving test i wait for it to start but it leaves me on a frozen screen

### Expected behaviour

When you go to take your drivers license, it just keeps you in the screen saying "you will end your test here" or smth and it doesnt let u drive the car it just stays in one screen.

### Steps to reproduce

a

### CMG User ID

415533

**Comment by NiallJW** [comment]
I am currently having the same issue, I have tried 4 times and spent 80k so far. Any ideas on a fix? 

User ID - 429971

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
This will be fixed ASAP by developers

**Comment by packfile** [comment]
This should be fixed from the next scheduled restart
