### ISSUE TITLE
[Bug]: i own vineyard mlo and i cannot hear the tvs  

### ISSUE THREAD

**Issue by iamsteve169** [CMGStudios/issue-tracker#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i cannot hear the tvs or use them but others in the house can it shows on my screen cannot play video please sign in and yes i am entered into the house 

### Expected behaviour

for the tv to work in everyones eyes including my own whilst in mlo 

### Steps to reproduce

/tv or /djmenu and whatever song you choose 

### Any Texture Packs? (If so list)

no

### CMG User ID

236070

**Comment by packfile** [comment]
Can you please attach a clip of this occuring (from entering the house to using the menu)
