### ISSUE TITLE
[Bug]: Legacy Inventory 

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#1078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Legacy inventory no longer has the ability to equip (x) amount of bullets into your gun. I understand as a server you want people to use the new one since time and effort was put into it. But I think it’s a bit cheeky to remove a pretty important aspect of the old inventory.

### Expected behaviour

Expected Behaviour: equip (x) amount of ammunition.

### Steps to reproduce

1. Open inventory 
2. Select ammo of choice
3. Click Use (which no longer has the option to decide on the amount)

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
