### ISSUE TITLE
[Bug]: learning test L plate

### ISSUE THREAD

**Issue by jazza212** [CMGStudios/issue-tracker#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i go do my test for my license it leaves me on frozen screen

### Expected behaviour

it wont let me do my test

### Steps to reproduce

https://youtu.be/5wzxfkkhevE

### Any Texture Packs? (If so list)

no

### CMG User ID

415533

**Comment by packfile** [comment]
This should be fixed from the next scheduled restart
