### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by exmmz** [CMGStudios/issue-tracker#108]
**Describe the issue you're facing**

always talking In game when I have push to talk on and not pressing the push to talk button but people can still hear me in game

**Steps to reproduce**
Relog

**Expected behaviour**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

None
**Perm ID**

199923

**Comment by loganuk** [comment]
Can you get a clip showing us this taking place? - What happens when you relog? How often does this take place?

**Comment by exmmz** [comment]
It has not done it again since I made the bug report

**Comment by loganuk** [comment]
No information given - Closed
