### ISSUE TITLE
[Bug]: taser issue

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#1080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

#1065 has fixed 2/3 issues, however it seems like the tasers are still not working yet its been marked completed

### Expected behaviour

Tase someone whilst in seg/Shower/Gym. have em drop

### Steps to reproduce

1. tase someone whilst in seg/shower/gym area
2. have em tank it like an absolute unit

### CMG User ID

14009

**Comment by packfile** [comment]
Can you provide a clip and/or reproduce steps to cause this? When testing locally the taser fires fine

**Comment by wooffighter** [comment]
Whilst the taser itself fires fine, the person hit doesn't get affected, I will send a clip tonight if necessary.

Exact STR:
Try to tase an inmate within sec
Taser doesn't affect inmate when hit. They also can tank less than lethal shotgun shells if I remember correctly but would have to verify to be certain. Tackling does work.

**Comment by wooffighter** [comment]
Clip:
https://medal.tv/games/gta-v/clips/ibiuheSycZn_xuiJ7/d1337UJT4FNt?invite=cr-MSwxZFcsMTg5MTg4NzgyLA
