### ISSUE TITLE
[Bug]: Driving Test

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#1081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you start the driving test you get stuck on the first cutscene ( https://imgur.com/TGZA6XV )

CLIP: https://imgur.com/zyBWAu7

### Expected behaviour

Driving test should go through the other scenes and voice dialogue and you begin the test

### Steps to reproduce

1. Have 20,000
2. go to driving centre
3. begin test

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124 (I want my 40k back)

**Comment by kajblm** [comment]
f8 info: https://imgur.com/9MLWVNW

**Comment by Hakeemblack** [comment]
I also face this issue, how do I sort this

**Comment by packfile** [comment]
This should be fixed from the next scheduled restart
