### ISSUE TITLE
[Bug]: Driving Test Glitch

### ISSUE THREAD

**Issue by Hakeemblack** [CMGStudios/issue-tracker#1082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Driving test should go through the other scenes and voice dialogue and you begin the test

### Expected behaviour

It stays on a weird camera angle and the car doesnt move and allow me to begin the driving test. I’ve wasted 60k on this already  

### Steps to reproduce

Have 20,000
go to driving centre
begin test

### CMG User ID

309365

**Comment by crazychris2404** [comment]
thanks for the report

This is already a known issue and a fix for it is pending
