### ISSUE TITLE
[Bug]: SandyPD Cells

### ISSUE THREAD

**Issue by KurtPritchardIT** [CMGStudios/issue-tracker#1083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Within Sandy PD you are able to sit on the benches in the Cells, and clip through the walls - it appears as though this is the case due to the benches facing the wrong way, sitting on them allows for you to initially sit with your body through the wall, and then from there you can clip through.

### Expected behaviour

Bench should face the opposite way, and sitting should not result in falling through the map.

### Steps to reproduce

Go into Sandy PD Jail Cells.
This has been done within the far right Jail Cell as far as I'm aware, has not been tested on any others.
Sit on a bench within a cell.
Stand up from sitting on the bench.
Clip through map, spawn outside of the Police Department.

This can be replicated for you if you'd like, please reach out on discord (alvinhardin)

### Any Texture Packs? (If so list)

None

### CMG User ID

243621

**Comment by KurtPritchardIT** [comment]
Just checked at the Metropolitan HQ - doesn't seem as though this is an issue there due to the style of beds and not being able to use them as furniture.

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report.
