### ISSUE TITLE
[Bug]: On/Off Duty Bug (potentially)

### ISSUE THREAD

**Issue by georgeongh** [CMGStudios/issue-tracker#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever I put myself on duty in the AA work and then come off of that page to check messages, it always turns it back off to me being off duty.

### Expected behaviour

In theory it shouldnt do this and should just stay on duty at all times so I can always receive work calls and messages and view them without it clocking me out of work

### Steps to reproduce

Join the AA Recovery work and go to the services app
Then open up the actions section of the services app.
Go on duty and then switch to the messages tab where you can recieve peoples live locations etc
Then switch back to the actions tab and it will say "Off duty" again.

### CMG User ID

431560

**Comment by Keegasity** [comment]
Confirmed!

Thank you for the report.

Steps to reproduce:
1. Clock on AA 
2. Bring out your mobile phone
3. Open the Services App
4. Click Actions in the bottom right
5. Click "Go on Duty"
6. Switch to the Messages tab on the bottom
7. Switch back to the Actions tab and it will say "Go on Duty"

**Comment by packfile** [comment]
You should still be able to receive calls/messages regardless of the onduty state of the phone, at the moment we can't fix this
