### ISSUE TITLE
[Bug]: Vehicle Rental

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you rent a vehicle for 2 hours it will only rent to you for 80/90 minutes before it gets returned to the persons garage.

### Expected behaviour

Rental should last the full 120 minutes.

### Steps to reproduce

1. Go to a garage
2. Rent a vehicle for 2 hours
3. Wait 90 minutes and it won’t be there.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by crazychris2404** [comment]
Unfortunately during testing this bug was unable to be replicated

If this still persists feel free to reopen this issue
