### ISSUE TITLE
[Bug]: DRIVING TEST

### ISSUE THREAD

**Issue by jazza212** [CMGStudios/issue-tracker#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

it still leaves you on a frozen screen 

### Expected behaviour

you wasted 20k and you loose ability's to jobs

### Steps to reproduce

go dmv and start the task the you will stay on frozen screen until you f8 
https://youtu.be/C4nk9228WCU

### Any Texture Packs? (If so list)

no

### CMG User ID

415533

**Comment by crazychris2404** [comment]
Already reported and being resolved
