### ISSUE TITLE
[Bug]: Driving License

### ISSUE THREAD

**Issue by BoyanK1** [CMGStudios/issue-tracker#1087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Your screen freezes once you start the driving test

### Expected behaviour

You cannot move your car or your camera , u are stuck

### Steps to reproduce

Have >= 20k
Start the Test

### CMG User ID

432150

**Comment by BoyanK1** [comment]
can i get my 40k back please.

**Comment by sirnolag** [comment]
Just did this, can I have my 20k back? ID: 107772

**Comment by WhoIsDinky** [comment]
just lost 80k ive tried doing it 4 times i dont need the money back pls just patch it

**Comment by packfile** [comment]
This should be fixed from the next scheduled restart
