### ISSUE TITLE
[Bug]: Ticket Authentication failed (can't log in)

### ISSUE THREAD

**Issue by fockinhellmush** [CMGStudios/issue-tracker#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Desktop Screenshot 2024 06 25 - 14 05 51 93](https://github.com/CMGStudios/issue-tracker/assets/173805958/d7dc86fa-c97e-422a-a683-98c023ee974a)

I'm not the only person with this issue. others are talkin gabout it in discord too

### Expected behaviour

Can't log in, whether i restart fivem or whatever i cant join the server

### Steps to reproduce

1) start fivem
2) try to join
xD

### Any Texture Packs? (If so list)

no

### CMG User ID

281936 maybe i cant log in to tell you

**Comment by crazychris2404** [comment]
This is a occasional issue outside the hands of cmg attempt to f8 connect if this does not work try again later
