### ISSUE TITLE
[Bug]: Throwables not working when you have a gun out

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#1089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you have throwables equipped and have a gun out, you should be able to press g while aiming and throw a throwable e.g. flashbangs and smoke grenades. Instead of throwing the throwable, it just does the pull out weapon animation.

### Expected behaviour

https://www.youtube.com/watch?v=OXu9-w1Mmsc this clip 

### Steps to reproduce

Get a gun out 
Equip throwable
Aim gun
Press G
Does the animation to pull out a gun instead of throwing the throwable

### Any Texture Packs? (If so list)

None

### CMG User ID

1220

**Comment by Keegasity** [comment]
Confirmed

Thank you for the report!
