### ISSUE TITLE
Cant stop speaking in game

### ISSUE THREAD

**Issue by JohnnyMush** [CMGStudios/issue-tracker#109]
**Describe the issue you're facing**

Voice chat randomly gets stuck on and I cant stop speaking in game.

Happens randomly some days and wont stop for hours.

**Steps to reproduce**

Not a clue tbh just happens.

**Expected behaviour**

Talking/Whispering/Shouting will always be blue and will constantly be talking in game.

**Screenshots/Video**

**Additional context**

Reset all my keybinds and changed my push to talk button.

Relogged multiple times.

Reinstalled fivem to fix another issue but this still happened.

**Any Texture Packs (if so list)**

NVE (Dont think it would have anything to do with this)

**Perm ID**

279

**Comment by alfiellds** [comment]
Hello, thank you for the report. I have been unable to reproduce this issue. Has this issue occurred since you filed this report and can players hear you when your Whisper/Talking/Shouting UI is lit up blue? 

Any information you can provide will help us resolve the issue.

Many thanks.

**Comment by loganuk** [comment]
No replies in 5 days - Issue closed
