### ISSUE TITLE
[Bug]: Hair Colour

### ISSUE THREAD

**Issue by Ck183** [CMGStudios/issue-tracker#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can't change color of my hair I called a admin they said it'll fix it's self after a while, so clearly its a common issue and it's still not fixed a lot of people have also said to me it dont work for them either it's been 2 month after i spoke to a admin about it.

### Expected behaviour

Basically I can't change the color of my hair i cant change them in the hair dressers and it doesnt work in the clothing store either 

### Steps to reproduce

Clothing store
Textures dont work
Hairdressers I
Index dont work

### Any Texture Packs? (If so list)

No

### CMG User ID

370933

**Comment by Keegasity** [comment]
This cannot be replicated by myself or other players.

If this issue is still occurring please contact me via discord!

Thanks,
Keegan
