### ISSUE TITLE
[Bug]: diamond casiono bug

### ISSUE THREAD

**Issue by ckayyyyy** [CMGStudios/issue-tracker#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i went to the casino to do blackjack and i put 8 million down and it hasn’t even let me play the game or show my cards or show what card i got my game just froze and then i lost 8million and i have a clip of it and here’s my evidence i posted on youtube https://youtu.be/WPzcnLcDLxY?si=3FSkcVPjobiunyIf

### Expected behaviour

https://youtu.be/WPzcnLcDLxY?si=3FSkcVPjobiunyIf there is my video

### Steps to reproduce

i want my 8 million back

### Any Texture Packs? (If so list)

e.g NVE

### CMG User ID

344763

**Comment by packfile** [comment]
Compensation requests are not dealt with through bug reports
