### ISSUE TITLE
[Bug]: Can't finish (illegal) trucking job

### ISSUE THREAD

**Issue by BrickPlayz** [CMGStudios/issue-tracker#1092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For some reason I can't finish my trucking job, video link of it.
https://streamable.com/b78zem

### Expected behaviour

Finish the trucking job and get money.

### Steps to reproduce

1. Start the trucking job
2. Get unlucky like me

### CMG User ID

432258

**Comment by Keegasity** [comment]
Cannot replicate this issue. If the issue still occurs please contact myself via discord.

Thanks,
Keegan
