### ISSUE TITLE
[Bug]: Pulling out gun when pulling out car from garage

### ISSUE THREAD

**Issue by babyrhino69** [CMGStudios/issue-tracker#1093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When pulling out the car from any garage it pulls out my primary weapon and therefore getting me into trouble, a cop then put me in cuffs for it

### Expected behaviour

It shouldnt do it

### Steps to reproduce

Just see what happens

### Any Texture Packs? (If so list)

No

### CMG User ID

432578

**Comment by packfile** [comment]
Please provide reproduction steps for this to be investigated
