### ISSUE TITLE
i’ve been banned for no reason 

### ISSUE THREAD

**Issue by Mrsips19** [CMGStudios/issue-tracker#1094]
i have just started 5m literally got my pc today and i’ve been banned from the cmg server for apparently Reason1.11 Ban Evading even tho i haven’t ever played this before my ID is 433325 i would please like to be unbanned as i haven’t even done anything literally just completed my first trucking job
![image](https://github.com/CMGStudios/issue-tracker/assets/174545621/bd95242c-ee55-49a8-9ab5-c7061e13b192)

**Comment by packfile** [comment]
Not a bug report, please create an appeal at https://cmgstudios.net/forums/index.php?/forms/4-unban-appeal/
