### ISSUE TITLE
house bug [Bug]: 

### ISSUE THREAD

**Issue by ty-ler12** [CMGStudios/issue-tracker#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i own a house near the golf course and the pools have no water plus the front sliding gate doesnt work, is there a way of fixing these issues

### Expected behaviour

please can someone take a look at getting these fixed thankyou

### Steps to reproduce

.

### CMG User ID

307881

**Comment by packfile** [comment]
Unfortunately no support is provided for buildings in the base game.
