### ISSUE TITLE
[Bug]: Cursor glitch for phone and inventory

### ISSUE THREAD

**Issue by AnderDingus398** [CMGStudios/issue-tracker#1098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have an issue when trying to open my inventory my cursor glitch's and when I'm trying to get an item it wont let me ive got a clip of it and will send it 

https://github.com/CMGStudios/issue-tracker/assets/174828419/1ae07eb8-cdd9-4746-80ce-659849e62e0d

### Expected behaviour

I have an issue when trying to open my inventory my cursor glitch's and when I'm trying to get an item it wont let me ive got a clip of it and will send it 

### Steps to reproduce

1. open your inventory or open your phone
2. 2. the cursor wont move or will glitchs

### Any Texture Packs? (If so list)

nope

### CMG User ID

432731

**Comment by Keegasity** [comment]
Please can you provide more information on how to replicate this issue?
