### ISSUE TITLE
ASKING ME TO VERIFY MY ACCOUNT AFTER PC RESET

### ISSUE THREAD

**Issue by RAZLAD11** [CMGStudios/issue-tracker#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I HAVE RESET MY PC TO PUT A NEW SSD IN I HAVE DRAGGED EVERYTHING  ONTO THIS SSD CARD AND ITS ASKING FOR ME TO VERIFY MY ACCOUNT I JUST DONT KNOW WHAT TO DO ALL I PLAY IS CMG I HAVE SPENT ALOT OF MONEY IN THE SERVER  MY ACCOUNT NAME IS RAZLAD11 ALSO MY DISCORD PLZ MESSAGE ME ON THERE AS I DONT CHECK THESE I WILL GIVE THE PROOF U NEED 

### Expected behaviour

???

### Steps to reproduce

NEED IT SORTING

### CMG User ID

395339

**Comment by packfile** [comment]
Please log in to the Rockstar Games account you used to connect to CMG the first time

**Comment by RAZLAD11** [comment]
Everyone has been saying this 2 weeks ago on the Friday I was in CMG on the
same account I tried to get onto the day after when I’ve changed my ssd n
I’ve lost all my hours I’ve lost over 2000 worth of irl money I’ve spent so
much into it same things happened to someone I know they got there account
recovered in a few days I don’t understand why is it taking this long just
need to update the hardware id really not fair on me as it does affect my
mental health as it’s a escape from life just really does need sorting.
I’ve got all the proof u will need that the account it mine  but plz listen
I’m in the same rockstar account 10000% I don’t have another one
