### ISSUE TITLE
cant upgrade bugatti

### ISSUE THREAD

**Issue by mizzy2busy** [CMGStudios/issue-tracker#110]
**Describe the issue you're facing**
i cant seem to upgrade certain thing on the bugatti 
**Steps to reproduce**

**Expected behaviour**

**Screenshots/Video**
https://streamable.com/o1kotc

**Additional context**
for me it just the engine i cant upgrade i cant apply windows on and theres no armour upgrade slot
**Any Texture Packs (if so list)**

**Perm ID**
222398

**Comment by loganuk** [comment]
Hello mizzy,

Can you get the spawncode for the vehicle please?

When you spawn it out of your garage - Press F8 to see what the spawncode is in the console.

**Comment by Jordzz-pc** [comment]
I have the same issue with my 1:2 Bugatti, I can’t change the window to pure black or any of the other options. ( Veyronoakley )

**Comment by loganuk** [comment]
Ok this is something for car reports to be raised for and not a developer bug folks.

I am going to close this issue as if it issues with specific car models it is for the car dev team or an issue with that model.
