### ISSUE TITLE
[Bug]: not being able to bid on auctions

### ISSUE THREAD

**Issue by KC0161** [CMGStudios/issue-tracker#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

No matter where the money is stored I am not able to bid on auctions, I have tested this by having £250,000,000 in my bank, offshore and gang funds at the same time and still not being able to bid and also have tried bidding with commas included and every other possible way of bidding

### Expected behaviour

to be able to bid without issue

### Steps to reproduce

1. wait for auction
2. attempt to bid
3. error no money

### CMG User ID

508

**Comment by packfile** [comment]
Thanks for the report, you should be able to bid now (you had linked your Discord account to a different Perm ID)
