### ISSUE TITLE
[Bug]: HMP Parole/Ankle tracker

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It seems that the ankle tracker blip for inmates put out on parole only works for people with long range blips

### Expected behaviour

WHen someone is put on parole for all members of HMP or atleast a certain whitelist role within HMP discord to see them. instead of only people with long range blips

### Steps to reproduce

1. Get HMP/PD to put an inmate on parole
2. DOnt have long range blips
3. dont see em

### Any Texture Packs? (If so list)

Reshade

### CMG User ID

14009

**Comment by packfile** [comment]
This is intentional behaviour, please make a feature request if you want this changed
