### ISSUE TITLE
Mass is at the top of trucks, not the bottom. So fast lorrys aare ass[Bug]: 

### ISSUE THREAD

**Issue by Wexyrrr** [CMGStudios/issue-tracker#1104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://youtu.be/a-yJaVIusCk

### Expected behaviour

Just tips over, video above.

### Steps to reproduce

Get a baller lorry, then accelerate quickly. It will just tip

### Any Texture Packs? (If so list)

N/A

### CMG User ID

429134

**Comment by packfile** [comment]
Thanks for the report, this is being resolved by the car devs
