### ISSUE TITLE
[Bug]: Unlootable Bag

### ISSUE THREAD

**Issue by Unlisted7** [CMGStudios/issue-tracker#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ive had a fight with some people and due to the garage im unable to loot the bag thats there
Clip: (not sure why no audio)  https://medal.tv/games/gta-v/clips/ifxuSZ6eMl1O_Hwmz/d1337WaLqkzu?invite=cr-MSxNaUksMjM5MTUwMjgs

### Expected behaviour

Wondering if i can get compensation

### Steps to reproduce

Compensation

### Any Texture Packs? (If so list)

No

### CMG User ID

313304

**Comment by packfile** [comment]
Unable to reproduce this on the new or legacy inventory UI, when using either caps or pointing at the bag and opening that way
