### ISSUE TITLE
[Bug]: dont get payed for scuba

### ISSUE THREAD

**Issue by bartholomew1435** [CMGStudios/issue-tracker#1106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i never get payed for scuba i do the whole thing but dont get payed for it and someitmes it says mission failed on my journey back so essentially i am just wasting my time doing it and not getting payed

### Expected behaviour

i dont get any money when doing scuba below will be a vid of it happenenuing https://youtu.be/tSSpqPaBlNc

### Steps to reproduce

do scuba nad come press claim reward and u get nothing

### Any Texture Packs? (If so list)

no

### CMG User ID

413145

**Comment by packfile** [comment]
Thanks for the report, this should have been fixed a week ago
