### ISSUE TITLE
/hideids

### ISSUE THREAD

**Issue by lokiiq** [CMGStudios/issue-tracker#111]
**Describe the issue you're facing**

**Steps to reproduce** /hideids

**Expected behaviour** = to hide ids

**Screenshots/Video** not needed

**Additional context**

**Any Texture Packs (if so list)** NVE, not relevant 

**Perm ID** 170443

**Comment by alfiellds** [comment]
Thank you for the report. This will the forwarded to the developers and fixed shortly.

**Comment by MrLexo** [comment]
This has been fixed now. Please can a bug manager close this. @alfiellds @loganuk
