### ISSUE TITLE
[Bug]: asoon as i press windows or sometimes when i just put my hands up my game bugs and my hands dont go down and doesnt allow me do jump or do most things.

### ISSUE THREAD

**Issue by owen205** [CMGStudios/issue-tracker#1111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://youtu.be/wLkjYj-lOXE            as u may see in the video everything is normal and then at like 1min and half into the video u can see when i stopped i opened up my windows well just clicked my windows button came back on the game and my hands automatically go up and never go down and it doesnt let me just or do most things ive had this issue for like 2 weeks now and ive heard some other people complain about it an admin teleported to me yesterday i explained to him and he said it was a bug from like 2-3 years ago.

### Expected behaviour

cant do much on the game when it happens ive died and been robbed a lot of times due to this bug it just messes the game up for me.

### Steps to reproduce

i click the windows button or sometimes it just happenes randomly and then it happens straight away

### CMG User ID

428578

**Comment by owen205** [comment]
i meant 30 seconds into the video my bad.

**Comment by packfile** [comment]
Do you have a controller plugged into your PC? If so, what is your "Use Phone" keybind set to under "Cellphone"

**Comment by owen205** [comment]
> Do you have a controller plugged into your PC? If so, what is your "Use Phone" keybind set to under "Cellphone"

![Screenshot 2024-07-22 150449](https://github.com/user-attachments/assets/971acd35-a99f-46a6-8e22-ea7b16ac9c63)
yes i have a controller connected but i dont use it on the game could that be an issue and thats my keybind for phone

**Comment by packfile** [comment]
> > Do you have a controller plugged into your PC? If so, what is your "Use Phone" keybind set to under "Cellphone"
> 
> ![Screenshot 2024-07-22 150449](https://private-user-images.githubusercontent.com/175854389/350994498-971acd35-a99f-46a6-8e22-ea7b16ac9c63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTg2NzUsIm5iZiI6MTcyMTY1ODM3NSwicGF0aCI6Ii8xNzU4NTQzODkvMzUwOTk0NDk4LTk3MWFjZDM1LWE5OWYtNDZhNi04ZTIyLWVhN2IxNmFjOWM2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNDI2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjMxNjg2MmE2MmU2ZDkxZmI0NzliNjYwZGUzZTU4ODkwODYyYmE5NTlmZWI3NDgxMDM4YmM3YzU2MTgwZWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.syXOJhq678bexBsQcPFcM9VOl6fqki5M4SvnO9Da5-U) yes i have a controller connected but i dont use it on the game could that be an issue and thats my keybind for phone

Potentially yes

**Comment by owen205** [comment]
> > > Do you have a controller plugged into your PC? If so, what is your "Use Phone" keybind set to under "Cellphone"
> > 
> > 
> > ![Screenshot 2024-07-22 150449](https://private-user-images.githubusercontent.com/175854389/350994498-971acd35-a99f-46a6-8e22-ea7b16ac9c63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTg2NzUsIm5iZiI6MTcyMTY1ODM3NSwicGF0aCI6Ii8xNzU4NTQzODkvMzUwOTk0NDk4LTk3MWFjZDM1LWE5OWYtNDZhNi04ZTIyLWVhN2IxNmFjOWM2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNDI2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjMxNjg2MmE2MmU2ZDkxZmI0NzliNjYwZGUzZTU4ODkwODYyYmE5NTlmZWI3NDgxMDM4YmM3YzU2MTgwZWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.syXOJhq678bexBsQcPFcM9VOl6fqki5M4SvnO9Da5-U) yes i have a controller connected but i dont use it on the game could that be an issue and thats my keybind for phone
> 
> Potentially yes

okay so how to i prevent this problem because i have a controller headset so i cant use it without my conroller i dont think is they any way i can?

**Comment by packfile** [comment]
> okay so how to i prevent this problem because i have a controller headset so i cant use it without my conroller i dont think is they any way i can?

I've added an option to settings (F2) under miscellaneous for next week that may fix this use case. Will be posted in dev updates once in

**Comment by owen205** [comment]
> > okay so how to i prevent this problem because i have a controller headset so i cant use it without my conroller i dont think is they any way i can?
> 
> I've added an option to settings (F2) under miscellaneous for next week that may fix this use case. Will be posted in dev updates once in

okay thanks alot!
