### ISSUE TITLE
[Bug]: Lifepak machine not functioning properly

### ISSUE THREAD

**Issue by CurtyIsTheBest69** [CMGStudios/issue-tracker#1112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As an NHS worker, when reviving downed patients, sometimes when they are dead and you connect the Lifepak it'll show that they have a pulse. Other times it'll correctly say they're dead.

### Expected behaviour

Described above

### Steps to reproduce

Press E to do CPR on the downed person > Press U and select the Lifepak

### CMG User ID

124009

**Comment by packfile** [comment]
Please attach a video to this report when it next occurs
