### ISSUE TITLE
Putting a Truck into most Los Santos Customs (Garage Style) Bug

### ISSUE THREAD

**Issue by mccornish** [CMGStudios/issue-tracker#1114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When putting  a trucking truck into Los Santos Customs its gets stuck inside and gets damaged, can no longer use the truck unless you rejoin the server.

### Expected behaviour

Should be able to drive out with the truck and should be bable to use all of the garages.

### Steps to reproduce

Drive in or reverse a trucking truck into Los Santos customs , try to leave and the issue will arise, you need to leave the vehicle to get out
![Screenshot 2024-07-22 074428](https://github.com/user-attachments/assets/9cce0db9-9d11-4782-a571-e329d5359770)
![Screenshot 2024-07-22 074516](https://github.com/user-attachments/assets/3076b268-d209-4040-83be-3ec63e0966bd)

### Any Texture Packs? (If so list)

N/A

### CMG User ID

435935

**Comment by packfile** [comment]
Thanks for the report. For upgrading a truck it is recommended to use a larger garage such as Ryan's Customs or Vinewood Customs as we won't be changing the size of the smaller customs
