### ISSUE TITLE
Truck is Destroyed - trying to start new trucker job

### ISSUE THREAD

**Issue by mccornish** [CMGStudios/issue-tracker#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If my truck or trailer gets destroyed whilst on job, you cannot start a new job without having to rejoin the server

### Expected behaviour

When returning back to start a new job after having your truck or trailer destroyed you should be able to start a new job without having to rejoin the server

### Steps to reproduce

Start an illegal job as a trucker, have either trailer or truck destroyed, return to start a new job, see the message truck destroyed pop up

### CMG User ID

435935

**Comment by Keegasity** [comment]
Hello, 

Can you provide a clip of this occurring as I cannot seem to replicate the issue

**Comment by DzKarim09** [comment]
> Hello,
> 
> Can you provide a clip of this occurring as I cannot seem to replicate the issue

If you go to the legal lorry garage to rent a HGV you can total it and then get out and let the vacant vehicle despawn timer destroy the vehicle. then go back to the place to start/stop the job. Rent annother or the same HGV and try to start a new job. Text will appear that says "truck was destroyed." and the job will not start.

**Comment by mccornish** [comment]
It appears that there was a part mispelled. It is meant to say 'Illegal trucking' rather than 'Legal'. This should replicate the error

Many Thanks

Kallum Cornish

________________________________

**Comment by packfile** [comment]
Thanks for the report, this should have been fixed since Monday
