### ISSUE TITLE
Halo sword issue 

### ISSUE THREAD

**Issue by jmb20002** [CMGStudios/issue-tracker#1116]
When equipping the halo sword, i cant swing the weapon, cant hold right click to aim like other melees. Also, i cant get into a car with the halo sword equipped either. its completely bugged.

**Comment by Keegasity** [comment]
Hello,

Please contact me via discord. Discord - Keegasity.

Thanks

**Comment by packfile** [comment]
See the above message from Keegan, alternatively open a weapon support ticket
