### ISSUE TITLE
[Bug]: Casino Bunker

### ISSUE THREAD

**Issue by TS12-CMG** [CMGStudios/issue-tracker#1118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you go into the door sometimes you fall through the map and i think i general the door is too small

### Expected behaviour

When you go into the door sometimes you fall through the map and i think i general the door is too small

### Steps to reproduce

It needs to be fixed

### Any Texture Packs? (If so list)

Quant v

### CMG User ID

1038

**Comment by crazychris2404** [comment]
Unfortunately this is a issue with some MLO’s and as of currently from my knowledge no fix is currently planned
