### ISSUE TITLE
[Bug]: f2 weapon options menu not working

### ISSUE THREAD

**Issue by OGSP1R1T** [CMGStudios/issue-tracker#1119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

f2 weapon options menu not working, for example, AR cant be switched from appearing at the front to the back, etc.

### Expected behaviour

f2 weapon options menu should work along with all the feature

### Steps to reproduce

1. Press F2
2. Select weapons options
3. Change AR appearance from back to front

### Any Texture Packs? (If so list)

No

### CMG User ID

1845

**Comment by Keegasity** [comment]
Hello,

After testing this, the issue cannot be replicated. Therefore I am closing this report.

Thanks
