### ISSUE TITLE
[Bug]: Less Lethal Shotgun

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#1121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Same issue as #1080 except with the shotgun

The less then lethal shotgun does apply the affect, somewhat stun them but doesn't trip them over as it does outside of the area

### Expected behaviour

For the person to fall over instead of stumbling and going on further

### Steps to reproduce

https://medal.tv/games/gta-v/clips/inFCd0ohzXvZjU9cy/d1337TO0H4Yl?invite=cr-MSxsa3YsMTg5MTg4NzgyLA

1. get blasted in the face with a shotgun
2. Survive?

### Any Texture Packs? (If so list)

Reshade

### CMG User ID

14009

**Comment by Keegasity** [comment]
Confirmed

Thank you for the report.

This only occurs within the shower block and segregation areas
