### ISSUE TITLE
[Bug]: All avenger based/style helicopters unable to transform to 'plane mode' since vehicle update

### ISSUE THREAD

**Issue by jjh5874** [CMGStudios/issue-tracker#1122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

since the vehicle update, every single avenger style vehicle i have tested has been unable to transform to its 'plane mode' when pressing E, making them much slower than every other helicopter in the city
### Expected behaviour

press E, heli blades rotate and it flys with plane controls

### Steps to reproduce

1) (actual behaviour)
1: pull out avenger style helicopter (such as the osprey)
2: press E
3: nothing happens

### CMG User ID

31351

**Comment by ItsJunction** [comment]
The key was changed a few GTA updates ago. You need to **hold** G (or whatever you decide rebind it to) - can be changed in Settings -> Key Bindings -> Aircraft -> Landing Gear / VTOL Mode (Hold)

![image](https://github.com/user-attachments/assets/ab90a6d9-fa89-4d3c-9c60-9e34c202be7a)

**Comment by packfile** [comment]
Resolved by @ItsJunction's post above
