### ISSUE TITLE
[Bug]: Boot closes after pressing e during mining diamonds and processing

### ISSUE THREAD

**Issue by TescoTea** [CMGStudios/issue-tracker#1124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Boot closes after pressing e during mining diamonds and processing i have to open the boot each time i finish the action. i have a clip https://medal.tv/games/gta-v/clips/ipMZM7PapdPnf15uN/d1337T9uga8t?invite=cr-MSxFTGIsMjQzODY2MDU5LA

### Expected behaviour

the boot use to not close after each time i done the action and just kept the boot open. idk if its a anti macro thats bugging with me or what 

### Steps to reproduce

not sure it happens to me and my mate but it works fine with my mate 

### Any Texture Packs? (If so list)

i have reshaders but this started before i got them

### CMG User ID

195940 / 401044

**Comment by crazychris2404** [comment]
Unable to reproduce please find the steps causing this then make another issue
