### ISSUE TITLE
[Bug]: cant spawn at VIP island even tho i have supreme

### ISSUE THREAD

**Issue by nate8x** [CMGStudios/issue-tracker#1127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

basically i got this thing where i cant spawn at VIP island even tho i have had supreme for like 2 years now
iv spoke to joey but he isn't responded for a long time now
I'm just wondering if u can speak to someone about it at all and get it sorted
because i haven't cared that much but I'm fragging a lot now so its kind of annoying 

### Expected behaviour

when i choose a spawn location

### Steps to reproduce

i think this is just a game engine issue

### Any Texture Packs? (If so list)

no

### CMG User ID

255399

**Comment by Keegasity** [comment]
Hello,

After testing this issue I have been unable to replicate it. If you are still experiencing the issue, please message me on discord. Discord - Keegasity.

This report will be closed.

Thanks
