### ISSUE TITLE
[Bug]: Casino machine shows incorrect bet amount

### ISSUE THREAD

**Issue by wxmcasual** [CMGStudios/issue-tracker#1128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When placing a bet on a machine, the machine displays 10,500 but takes 10,500,000

![image_2024-08-11_170714790](https://github.com/user-attachments/assets/24db885c-b99d-4c3d-a744-edc17c46b1d5)

### Expected behaviour

I expected it to take 10,500 as the machine displays

### Steps to reproduce

1. Visit a casino machine
2. Place a bet of 10,500
3. Enter to submit the bet
4. Lose 10,500,000

### Any Texture Packs? (If so list)

N/A

### CMG User ID

240671

**Comment by crazychris2404** [comment]
This is not incorrect and is stated in the slot menu as a way of getting round GTA UI limitations
