### ISSUE TITLE
[Bug] Damaged plane cause money loss even though I haven’t crashed my plane

### ISSUE THREAD

**Issue by Rtzzs** [CMGStudios/issue-tracker#1129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I’m currently using a rmr1 plane and when I do the piloting job I’m am not getting any money as it says that 100% damage to the plane even though I haven’t crashed my plane in the slightest. I have piloted for 3 hours today and have only been paid once which still wasn’t the full amount

### Expected behaviour

Get full amount if I don’t crash my plane 

### Steps to reproduce

Not sure

### Any Texture Packs? (If so list)

No

### CMG User ID

357896

**Comment by Keegasity** [comment]
Hello Rtzzs,

Following a recent change to piloting (can be seen within dev-updates) you will lose money for rough climbs or descents.

The dev-update reads "If exceeding -3G in a climb or descent a % cut will be taken from your profits"

Any problems please feel free to dm myself.

Many Thanks,
Keegan
