### ISSUE TITLE
Truck Despawning after exiting the meth processor.

### ISSUE THREAD

**Issue by Kurfh** [CMGStudios/issue-tracker#113]
**Describe the issue you're facing**

Most of the time when I exit the meth processor my truck seems to disappear despite locking it and watching chat for vehicle cleanup/entity cleanup.

**Perm ID**

221709

**Comment by loganuk** [comment]
Hello Kurfh, 

Can you get a POV clip of this happening for me please.

**Comment by Kurfh** [comment]
https://www.youtube.com/watch?v=p9K1MIQfi8E

**Comment by loganuk** [comment]
Potentially might be doing a soft cleanup due to the distance between the players owned vehicle and when he is inside an interior?

**Comment by Kurfh** [comment]
It seems to only happen on the first server btw. On the second server it's usually fine.

**Comment by crazychris2404** [comment]
https://github.com/CMGStudios/issue-tracker/issues/189 duplicate issue
