### ISSUE TITLE
[Bug]: i dont have a phone 

### ISSUE THREAD

**Issue by turbofast775** [CMGStudios/issue-tracker#1130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i don't have a phone i have tried everything  

### Expected behaviour

i just dont have a phone when i press k i get nothing 

### Steps to reproduce

dont have a phone 

### CMG User ID

441282

**Comment by PIKAlmao** [comment]
Try **f1** monkey

**Comment by Keegasity** [comment]
Hello Turbo,

If you are still experiencing issues with access your phone, please message me on discord. Discord - Keegasity.

Due to this not affecting other players this report will be closed.

Thanks
