### ISSUE TITLE
[Bug]: Unable to sell my Plat Days

### ISSUE THREAD

**Issue by Cosdetmataer** [CMGStudios/issue-tracker#1131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Im unable to sell my Plat days as the blue box doesn't come up to input id  

### Expected behaviour

Allow me to enter id and sell 

### Steps to reproduce

1. open /cmgclub 2.Manage Sub 3. press enter

### CMG User ID

440335

**Comment by L14M86** [comment]
having same problem 3 days in a row this has happened to me now.... losing out on a lot of money

**Comment by L14M86** [comment]
any luck on this its 5 days in a row now!?

**Comment by 004Luke** [comment]
How did you get the plat? Did you get the collectibles?

**Comment by L14M86** [comment]
No I'm buying plat off the store and 30 days off if other people... I'm
going to stop now until bug is fixed as I can't sell it

**Comment by packfile** [comment]
@L14M86 @Cosdetmataer Is this issue still occuring for either you?

**Comment by L14M86** [comment]
still happening... not as much tho
