### ISSUE TITLE
[Bug]: cant load into small bank setups

### ISSUE THREAD

**Issue by d06744** [CMGStudios/issue-tracker#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I try to load on to get the hacking devices to do small banks but whenever i start them i get stu9ck on a grey screen that says dtiv to cayo perico

### Expected behaviour

shouldnt be stuck on screen should just be able to do the setup not be stuck on the screen for like 15 minutes

### Steps to reproduce

1. Go  to lesters factory
2. go to the last setup
3.Start the setup

### Any Texture Packs? (If so list)

no

### CMG User ID

407989

**Comment by packfile** [comment]
Can you please provide a clip of this occuring (and your log file for when it happened)
