### ISSUE TITLE
[Bug]: taco seller job

### ISSUE THREAD

**Issue by JayN2727** [CMGStudios/issue-tracker#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The taco seller job is bugged, when you go to the place to fill up your van and begin to fill your van, it says 0 stock no matter how much you put in and doesn’t let you sell.

### Expected behaviour

Not being able to fill van with stock

### Steps to reproduce

Clock on as taco seller
Get your taco van
Take it to the taco place
Start filling van
Attempt to sell your tacos
Van will say 0 stock

### Any Texture Packs? (If so list)

None

### CMG User ID

419523

**Comment by crazychris2404** [comment]
Duplicate
