### ISSUE TITLE
[Bug]: Map Issue

### ISSUE THREAD

**Issue by remoxee** [CMGStudios/issue-tracker#1135]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description

Inside HMP outside medical bay there are benches, If you sit on these when you stand up you glitch in the wall.
![pasted](https://github.com/user-attachments/assets/064de8d6-d218-4db4-95bd-8d1a6f9343d6)

After standing up

![pasted](https://github.com/user-attachments/assets/6edcdf79-174b-49cc-92a6-b3d4e29b409a)

### Expected behaviour

This will glitch you into the wall, Nothing severe just a way for people to hide, inmates etc.

### Steps to reproduce

1. Sit on the bench
2. Get off

### Any Texture Packs? (If so list)

N/A

### CMG User ID

437174

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report
