### ISSUE TITLE
[Bug]: The Island not spawning in for Pilots.

### ISSUE THREAD

**Issue by Alfiebp** [CMGStudios/issue-tracker#1136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I’ve died countless time. Wasted my time flying to the Island only to have to suicide as it just wasn’t there. Almost impossible to earn money from piloting when there is no drop off / pick up

### Expected behaviour

Just very annoying to deal with and time consuming.

### Steps to reproduce

Fly to the island when piloting . It’s often not there 

### CMG User ID

439932

**Comment by packfile** [comment]
Temporary solution would be to enable "High Detail Streaming While Flying" under "Advanced Graphics". A more permanent solution will be looked into at the next bug pass however.
