### ISSUE TITLE
[Bug]: atms and anything with the countdown ui thing 

### ISSUE THREAD

**Issue by mortysmith69** [CMGStudios/issue-tracker#1137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the atms clothing stores bins and anything else with the countdown mod is invisible like it lets u do it but u cant see so its impossible to rob atms and clothing stores

### Expected behaviour

i expect to be able to rob them and not face issues i already let ryans customs know but he didnt do anything sooo..

### Steps to reproduce

u cant fix it by ur self needs to fixed in the files

### Any Texture Packs? (If so list)

none

### CMG User ID

438105

**Comment by crazychris2404** [comment]
Fixed for tommorow
