### ISSUE TITLE
[Bug]: cash machine robbery not working

### ISSUE THREAD

**Issue by rymbrt1** [CMGStudios/issue-tracker#1139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i brake the cash machine the bar does not show up but i still go into the scene where im meant to be doing the wires and then after i reset and get off the msg to cut the wires is still in the top right i have logged on and off multiple times and still hasnt fixed it ive also tried different ATMs but still the same i wanna know if its a bug or its a problem on my end

### Expected behaviour

![image_2024-08-20_094603298](https://github.com/user-attachments/assets/64321dd2-56f9-47da-89e1-57a823e15e55)
![image_2024-08-20_094617088](https://github.com/user-attachments/assets/75bcfd40-4667-4595-bbd7-f362559707f2)

### Steps to reproduce

.

### Any Texture Packs? (If so list)

no

### CMG User ID

439881

**Comment by packfile** [comment]
Thanks for the report, please try again from the next restart (in 20 or so minutes)

**Comment by rymbrt1** [comment]
ok thank you
