### ISSUE TITLE
Sandy house needs fixing cant enter in or sell it.

### ISSUE THREAD

**Issue by SmokeyyCmgg** [CMGStudios/issue-tracker#114]
**Describe the issue you're facing**
The sandy house caravan 56 or 55 it comes up as both, you cannot enter the house or sell the house even though it comes up when someone rings your bell, i tried relogging multiple times but doesn't work.

**Steps to reproduce**
Needs fixingf so you can enter it
**Expected behaviour**
Enter the house and sell it
**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
515

**Comment by arthur-rl** [comment]
Any reason for the closure?
