### ISSUE TITLE
[Bug]: Custom Wheels

### ISSUE THREAD

**Issue by KC0161** [CMGStudios/issue-tracker#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not being able to use any of the custom wheels in customs and when you are scrolling through the options the wheels on the car dont change and the only time it changes is when you scroll over all the stock GTA online wheels and not the custom ones.

### Expected behaviour

 For you to be able what the custom wheels looks like and be able to apply them to your car

### Steps to reproduce

1. Go into any customs shop with your car
2. Try to put on one of the custom wheels
3. Nothing happens

### CMG User ID

508

**Comment by packfile** [comment]
Custom wheels were removed as part of the debranding process (back in March), the buttons will be removed soon as well
