### ISSUE TITLE
[Bug]: Not being able to shoot off PD Helis

### ISSUE THREAD

**Issue by Lewis50956** [CMGStudios/issue-tracker#1141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The PD Helicopters (Polbird & the baller lock EC130) are affected.

When a player is in the shooting seats with an assault rifle, they can aim in however when pressing their left click to shoot nothing is done. 

Multiple people are experiencing this. 

https://medal.tv/games/gta-v/clips/ivWq9jw6XuPtX9MDb/d1337V6Zxsdf?invite=cr-MSxROU8sMjI3MzM3NTUxLA

### Expected behaviour

When the Heli is off the ground, the player should be able to use an AR when on shooting seats. 

### Steps to reproduce

**THIS MAY ONLY BE AN ISSUE FOR PD HELIS**

Pull a Heli out the garage.
Get someone else to fly it up in the air while you are in a shooting seat. 
Attempt to shoot with an assault rifle. 

### Any Texture Packs? (If so list)

no

### CMG User ID

403938

**Comment by Flinny-k** [comment]
This is still an issue

**Comment by packfile** [comment]
Thanks for the report, this has been fixed since Monday
