### ISSUE TITLE
[Bug]: cant enter house or pay tax

### ISSUE THREAD

**Issue by Jameel0113** [CMGStudios/issue-tracker#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when attempting to enter my home on cmg a prompt pops up in bottom left informing me that i have outstanding housing tax however there is no option for me to pay it thus making me unable to enter my house. I am unsure how many people are facing this issue as my friend hasnt encountered it with his home. also other people are still able to enter the home by ringing the doorbell.

### Expected behaviour

walk up to dore bell and ent6er or option to pay house tax

### Steps to reproduce

1)walk up to milton flats
2) try to enter 
3)told to pay tax
4)no option to pay
link: https://medal.tv/games/gta-v/clips/ixEXkNHbY6_UOyk-X/d1337NMxGdoL?invite=cr-MSx2dUUsODM4NzIwNDIs

### Any Texture Packs? (If so list)

no

### CMG User ID

463

**Comment by packfile** [comment]
Thanks for the report, this has been fixed since last Tuesday's scheduled restart
