### ISSUE TITLE
[Bug]: my vehicle code is not working when i do !gco in discord

### ISSUE THREAD

**Issue by rxx-xx** [CMGStudios/issue-tracker#1148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I spawn my car is says its spawn code which is etronwb.
Then I put in !gco etronwb to see who the other owner is cuz it's 1:2 and nothing comes up.

### Expected behaviour

I want to see who owns my car when I put in the spawn code again 

### Steps to reproduce

!gco etron 

### Any Texture Packs? (If so list)

No

### CMG User ID

425679

**Comment by crazychris2404** [comment]
This command requires you to have baller rank or 1k hours and to be used in bot-commands channel if you don’t meet these requirements you can ask someone else to do it for you
