### ISSUE TITLE
[Bug]: Cayo Setup Heist

### ISSUE THREAD

**Issue by sparks255** [CMGStudios/issue-tracker#1149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

You dont leave the sky
https://medal.tv/games/gta-v/clips/iyqFGu09HvKXF_82K/d1337FEGpCMy?invite=cr-MSxrTnMsMjUxODQ0MzIs

### Expected behaviour

Stuck in the sky animation

### Steps to reproduce

Just start the heist

### Any Texture Packs? (If so list)

none

### CMG User ID

444222

**Comment by packfile** [comment]
Duplicate of #1132, please reupload the video and comment on that issue instead
