### ISSUE TITLE
Window Tints

### ISSUE THREAD

**Issue by kaulix** [CMGStudios/issue-tracker#115]
Some cars when you purchase the full blacked out window tints it doesnt actuall go on the car only on the back windows, however there are some cars out there that have full,

I think you should update the window tint modification, and make it go on the entire car, so it looks nicer and more people are satisfied with their cars

![FiveM -  UK_EU  CMG Public #1 ___ British Themed ___ Economy ___ Arma 3 Vibe ___ discord gg_cmg 03_08_2021 16_23_48](https://user-images.githubusercontent.com/88392318/128042163-e66a056c-9c86-4fd3-a120-1191ee0bc3fa.png)

220690

**Comment by loganuk** [comment]
Hello there Kaulix,

This is entirely dependant on each unique model of the cars on import - Different car makers will do the windows differently.

This is not one for the server development team to fix sadly. I myself own different cars which handle the tint value differently, It is to do with the model.
