### ISSUE TITLE
[Bug]: Ban for no reason

### ISSUE THREAD

**Issue by xVezoh** [CMGStudios/issue-tracker#1150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i have recently came back to playing fivem, i havent played fivem/ the cmg server in over 7 month and the last time i played i can definitely say i was not banned i spent money time and effort into the server it was my favourite now im perm banned for ban evading after trying to make my return on fivem and im shocked

### Expected behaviour

please try and unban me i miss the server :(

### Steps to reproduce

/unban 387918

### Any Texture Packs? (If so list)

no

### CMG User ID

387918

**Comment by xVezoh** [comment]
yes

**Comment by crazychris2404** [comment]
Appeal on forums cmgstudios.net
