### ISSUE TITLE
[Bug]: car colour changing back to original

### ISSUE THREAD

**Issue by ligmasmeg** [CMGStudios/issue-tracker#1152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

car colour changing back to original when you store the vehicle at a garage and take it back out

### Expected behaviour

went to change my car to purple, after i did that and took it back to store it at a garage, then when i take it back out its gone back to red.

### Steps to reproduce

take a car and change the colour.
take it to a garage and store it.
take it back out.

### CMG User ID

443697

**Comment by packfile** [comment]
Could you please provide the spawncode of this vehicle and/or attach a video as this doesn't reproduce locally?
