### ISSUE TITLE
[Bug]: Mispelling in F9

### ISSUE THREAD

**Issue by CurtyIsTheBest69** [CMGStudios/issue-tracker#1154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not really a bug as such but when you press F9 to view the trader tab, the word 'Civilian' is mispelled.

### Expected behaviour

Press F9

### Steps to reproduce

Press F9

### Any Texture Packs? (If so list)

No

### CMG User ID

124009

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report.
