### ISSUE TITLE
[Bug]: garages

### ISSUE THREAD

**Issue by solarcozza** [CMGStudios/issue-tracker#1155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

all the garages are bugged and cars keep despawning

### Expected behaviour

the cars will despawn and you can not have 2 cars out at once

### Steps to reproduce

idk

### Any Texture Packs? (If so list)

no

### CMG User ID

342445

**Comment by Keegasity** [comment]
The following Dev changes have been made today.

Automatically deletes vehicles with 5 meters of the spawner (if there for more than 5 seconds).

Therefore this is not a bug, move the vehicle further away.
