### ISSUE TITLE
[Bug]: Mission Row Intoximeter Room Door

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unlike other doors in Mission Row Police Station, the Intoxication Room door has a lock which doesn't actually lock the door.

https://streamable.com/pihf4f

From door editor:
```lua
{position = vector3(480.69732666016,-1003.5856933594, 24.91498374939), modelPosition = vector3(480.04095458984,-1003.5308227539, 25.02586555481), model = `v_ilev_arm_secdoor`},
```

### Expected behaviour

Door should lock/unlock as intended, or not have a lock at all (one or the other).

### Steps to reproduce

1. Clock on PD and go to the cells
2. Try and lock/unlock the intoxication room door

### CMG User ID

2000

**Comment by crazychris2404** [comment]
Confirmed thanks for the report
