### ISSUE TITLE
sandy caravan 5 entrance disappears 

### ISSUE THREAD

**Issue by lewiseste** [CMGStudios/issue-tracker#116]
**Describe the issue you're facing**
sandy caravan 5 isnt not showing up and cannot be entered
**Steps to reproduce**
load in
go to house location 
caravan entrance sometimes isnt there
**Expected behaviour**
fix house location
**Screenshots/Video**
https://imgur.com/a/OcMsddX
**Additional context**
half the time it shows up and the other half of the time it doesnt show up and changes from sandy caracan 5 to sandy caravan 6, relogged many times and doesnt fix it, 
**Any Texture Packs (if so list)**
no
**Perm ID**
473

**Comment by loganuk** [comment]
I will look into this as it seems very strange. - I'll test it today and come back to you.

**Comment by alfiellds** [comment]
Need an update on this @loganuk

**Comment by rubbertoe98** [comment]
Fixed
