### ISSUE TITLE
[Bug]: New garage system/sound bugging out.

### ISSUE THREAD

**Issue by SmugSug** [CMGStudios/issue-tracker#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Garages making a lot of noise when driving/walking over them if there's two that are too close to eachother.
Menu resets constantly, making it difficult if not impossible to get a vehicle out.
https://streamable.com/3seek5
https://streamable.com/tj6u0s
https://streamable.com/bw7y2f

### Expected behaviour

Not ear rape me with the sound of an A-10 Warthog (just expecting it not to do that tbh)
Have the menu not bug out.

### Steps to reproduce

Walk around/ontop of the garage(s), that are too close to one another.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

922

**Comment by Keegasity** [comment]
Confirmed!

Thank you for the report.

**Comment by packfile** [comment]
This should have been fixed since Tuesday's restart
