### ISSUE TITLE
[Bug]: Can't take photos with your phone

### ISSUE THREAD

**Issue by PeacePvP** [CMGStudios/issue-tracker#1161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you pull out your phone and decide to take a photo, it gives you the error "Failed to upload, tell the server owner to check their API keys in lb-phone/server/apiKeys.lua"
"Unexpected token A in JSON at position 0"

### Expected behaviour

The phone takes a photo and is stored.

### Steps to reproduce

Take a phone
Click on the camera
Take a photo
You get the error

### CMG User ID

437967

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report!

**Comment by packfile** [comment]
This should've been fixed since Wednesday's restart

**Comment by PeacePvP** [comment]
Still not fixed
