### ISSUE TITLE
[Bug]: New setting "Keep GTA Crosshair Enabled" forced you to do /showui everytime when logging in

### ISSUE THREAD

**Issue by 474Denis** [CMGStudios/issue-tracker#1164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

New setting "Keep GTA Crosshair Enabled" forced you to do /showui everytime when logging in if turned on.

### Expected behaviour

New setting "Keep GTA Crosshair Enabled" forced you to do /showui everytime when logging in if turned on. It also seems to randomly hide ui at other times too.

### Steps to reproduce

1. Turn on "Keep GTA Crosshair Enabled" setting in F2 settings.
2. Close FiveM
3. Join CMG
4. UI will be hidden and you need to /showui to re-enable.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

1327

**Comment by packfile** [comment]
This is no connection between the crosshair and visibility of the other UIs. Could you check "UI Visibility" under settings to see if you have anything enabled there?
