### ISSUE TITLE
[Bug]: Sun bloom getting brighter each selection instead of reducing 

### ISSUE THREAD

**Issue by nyzrnyzrnyzr** [CMGStudios/issue-tracker#1168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When selecting any option on the sun bloom instead of reducing the bloom, it makes the bloom way worse, and even after trying to disable it, it still goes brighter on the disabled option meaning i have to relog to fix my sun bloom settings and set it back to normal

https://streamable.com/gh0m5s

### Expected behaviour

Reduce sun bloom 

### Steps to reproduce

F2 settings
Graphics settings
Sun bloom then select any option looking at the sun

### Any Texture Packs? (If so list)

Custom NVE reshade build

### CMG User ID

1144

**Comment by packfile** [comment]
Thanks for the report - this was an experimental feature, given it did not have any success it will likely be removed in the next update push
