### ISSUE TITLE
[Bug]: Gun glitch on PD

### ISSUE THREAD

**Issue by Flinny-k** [CMGStudios/issue-tracker#1169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i work NHS then go clock on as PD I cant then draw my gun.  I have them equipped but i can not use them.
I have to relog to be able to get it to work properly.  https://www.youtube.com/watch?v=vc_YAqVyRpk

### Expected behaviour

press tab to open gun wheel - select gun -  draw gun - use gun

### Steps to reproduce

1. press tab to open gun wheel
2. select gun
3. gun draw annimation happens
4. no gun drawn.

### Any Texture Packs? (If so list)

no

### CMG User ID

9733

**Comment by Keegasity** [comment]
Confirmed!

Thank you for the report. (I believe this maybe linked to another report that is already open #1174)

**Comment by packfile** [comment]
This has been fixed since last Tuesday's scheduled restart
