### ISSUE TITLE
My PD whitelist doesn’t show up in the armory 

### ISSUE THREAD

**Issue by iTobiasz** [CMGStudios/issue-tracker#117]
**Describe the issue you're facing**
3 days ago my vector whitelist disappeared from the armory and I can’t buy it, it has been working fine before
**Steps to reproduce**

**Expected behaviour**
To show up and let me buy it
**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**
Nope
**Perm ID**
179491

**Comment by loganuk** [comment]
This is not a bug - Please open a donation support ticket.
