### ISSUE TITLE
[Bug]: Fuel trailer Trucking job

### ISSUE THREAD

**Issue by Cx11um** [CMGStudios/issue-tracker#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever i have the fuel trailer on a rented truck i cannot go above 30mph  but do not have this issue with other trailers

### Expected behaviour

to go faster than 30mph

### Steps to reproduce

Fuel trailer 

### Any Texture Packs? (If so list)

no

### CMG User ID

445716

**Comment by packfile** [comment]
What rented trucking are you using? I was able to pull this trailer around 80mph with the Benefactor Acros.
