### ISSUE TITLE
[Bug]: no offshore or monzo on phone

### ISSUE THREAD

**Issue by babz97** [CMGStudios/issue-tracker#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

sometimes i log in and i got no monzo and offshore on my phone usually i restart and it comes back but today i restarted 4 times and still no app. https://medal.tv/games/gta-v/clips/iEaWRLE4tNhaiYepe/d1337gnYewzm?invite=cr-MSxXRUQsMjA3ODk0MDM2LA

### Expected behaviour

i expect the banking apps to be on my phone

### Steps to reproduce

1. log in
2. open the phone
3. NO BANKING APPS

### Any Texture Packs? (If so list)

NONE

### CMG User ID

390747

**Comment by ongangnem** [comment]
Got this same bug and its not on the bug progress thing.

**Comment by xodaisie** [comment]
i have this issue too, ive been out of the city for a few months and now i cant access any of my money :/

**Comment by jemiea** [comment]
The Monzo & Offshore app are now downloaded by going to the application on the phone named ‘Apps’, after downloading them go to your Offshore and take 1 out of the account so that it shows the correct value in your account. If the apps disappear again, follow the same process.

**Comment by packfile** [comment]
Thanks for the report, the phone will be updated next Monday to resolve this issue (bug was caused by phone provider, not us). In the meantime please follow the steps provided above as a workaround.
