### ISSUE TITLE
Heli needs fixed 

### ISSUE THREAD

**Issue by rxx-xx** [CMGStudios/issue-tracker#1172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

]: When i spawn my heli it doesnt move when i get out it explodes in my face.

### Expected behaviour

Able to fly so i do diamond 

### Steps to reproduce

heli garage. spawn heli. heli doesnt like me. blows up and kills me.

### Any Texture Packs? (If so list)

nope

### CMG User ID

425679

**Comment by packfile** [comment]
What is the spawncode?

**Comment by rxx-xx** [comment]
hcm140iheli

**Comment by Keegasity** [comment]
Cannot replicate the issue, please can you confirm if the helicopter is now working.

**Comment by packfile** [comment]
No response from OP, closing. If this issue still persists, please also provide the garage you're attempting to spawn the helicopter at
