### ISSUE TITLE
[Bug]: Not letting me bet

### ISSUE THREAD

**Issue by rainyix** [CMGStudios/issue-tracker#1173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I recently just bought a high rollers membership and it doesnt let me bet at all, hopefully i can get a refund for this i have a clip of this not working

### Expected behaviour

usually the chips should come up but they dont work even after i restarted cmg

### Steps to reproduce

1. go to the table 2. sit down 3. bet

### CMG User ID

423629

**Comment by crazychris2404** [comment]
Add clip here please

**Comment by rainyix** [comment]
> Add clip here please

https://medal.tv/games/gta-v/clips/iERWWpRiVK7uJ7rwc/d1337Skfi4CQ?invite=cr-MSxjT3YsMjIxMzg2NTk3LA

**Comment by Keegasity** [comment]
Please can you provide a clip of this, the above clip has been deleted.

**Comment by packfile** [comment]
You're account is showing as having the high roller membership, please reupload if this is still an issue.
