### ISSUE TITLE
[Bug]: NHS Bug

### ISSUE THREAD

**Issue by Cam3ron1888** [CMGStudios/issue-tracker#1174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when clocking off a faction like nha for example, 
1. clock on nhs 
2. clock off nhs 
3. can still drag people, cant loot bags, can still open call manager, cant take out guns,

### Expected behaviour

1. clock off nhs 
2. go and do what ever you want 

### Steps to reproduce

1. clock on nhs 
2. clock off nhs 

### CMG User ID

231586

**Comment by Keegasity** [comment]
Confirmed!

Thank you for the report. You will be able to open the call manager despite being a civilian.


Steps to reproduce:
1: Clock on NHS
2: Clock off NHS
3: Try and Alt+A drag someone (Its still possible)
4: Try and loot a bag or pull out a weapon

**Comment by packfile** [comment]
This has been fixed since last Tuesday's scheduled restart
