### ISSUE TITLE
[Bug]: Cursor laggy on inventory 

### ISSUE THREAD

**Issue by chase097** [CMGStudios/issue-tracker#1175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have got my inventory on legacy and for some reason the cursor is really laggy 

### Expected behaviour

For the cursor to be smooth and normal 

### Steps to reproduce

Press L and move mouse 

### Any Texture Packs? (If so list)

No

### CMG User ID

435097

**Comment by packfile** [comment]
Please provide reproduction steps and/or a video demonstrating the issue, ideally with `cl_drawPerf 1` (in F8) enabled so your CPU & GPU usage can be shown for this to be investigated
