### ISSUE TITLE
[Bug]: Renting certain 300kgs from the "Market Place App"

### ISSUE THREAD

**Issue by Wexyrrr** [CMGStudios/issue-tracker#1176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you go to rent a "£Scooby Scooby Doo" van it gives you a paradise van.

### Expected behaviour

https://medal.tv/games/gta-v/clips/iGEkYbPXwNgtLIwhc/d1337n9z6CkN?invite=cr-MSx5VGgsMjQyNTExNTc4LA

### Steps to reproduce

Here in the clip: https://medal.tv/games/gta-v/clips/iGEkYbPXwNgtLIwhc/d1337n9z6CkN?invite=cr-MSx5VGgsMjQyNTExNTc4LA

### Any Texture Packs? (If so list)

N/A

### CMG User ID

429134

**Comment by packfile** [comment]
This should be fixed now, if you still experience this issue let us know
