### ISSUE TITLE
[Bug]: Jobs

### ISSUE THREAD

**Issue by Fudge25901** [CMGStudios/issue-tracker#1177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When working some jobs they don’t register as completed sometimes or even started.

### Expected behaviour

Jobs should be able to be completed.

### Steps to reproduce

1. Start a job
2. Try complete the job.

### CMG User ID

446222

**Comment by Keegasity** [comment]
Please provide more information about the types of jobs you are trying to complete.

**Comment by Fudge25901** [comment]
On scuba diving I got back onto the boat but it didn’t register properly.
And on truck driving I’ve had 2 issues, one is where the trailer didn’t
spawn and the second one was that it told me my truck was destroyed when it
was outside and not destroyed.

**Comment by packfile** [comment]
Unfortunable we are unable to reproduce this, if you get a clip of this occuring please attach.
