### ISSUE TITLE
[Bug]: Not receiving pay check

### ISSUE THREAD

**Issue by pucynyce** [CMGStudios/issue-tracker#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

one of the cat cafe workers isnt receiving a pay check when clocked on. from the videos they sent it looks like the paycheck timer goes down very slowly. they have been working a good amount and haven't been paid once

### Expected behaviour

receive pay from the job

### Steps to reproduce

1. Clock onto a job at cat cafe
2. 30 mins later a pay check to be able to be claimed

https://medal.tv/games/gta-v/clips/iGy1gGcUkM7je4BgQ/d1337obslHAX?invite=cr-MSxpTTUsMTg3Mzc4Njg5LA

https://medal.tv/games/gta-v/clips/iGyodlKyICDRoLqz5/d1337XKNQxFB?invite=cr-MSxncEMsMTg3Mzc4Njg5LA

https://medal.tv/games/gta-v/clips/iGyBlrjPtLlWLFYio/d1337umHXjKo?invite=cr-MSxWVlcsMTg3Mzc4Njg5LA

### CMG User ID

45535

**Comment by packfile** [comment]
If the timer is going down slowly it's likely they're being considered AFK. Interacting with the business, or completing tasks will prevent that from happening. Currently you are set AFK if you haven't done anything in 5 minutes relating to the business.
