### ISSUE TITLE
[Bug]: hair colour changing

### ISSUE THREAD

**Issue by JessicaMegan22** [CMGStudios/issue-tracker#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when re logging in female ped i always load up to a different colour of hair.

### Expected behaviour

.

### Steps to reproduce

.

### Any Texture Packs? (If so list)

no

### CMG User ID

31

**Comment by Gooobie** [comment]
Confirmed, thank you for the report.

**Comment by packfile** [comment]
Thanks, a fix is pending and will be posted in dev-updates once live.
