### ISSUE TITLE
Texture and modkit fix

### ISSUE THREAD

**Issue by Nuxiie** [CMGStudios/issue-tracker#118]
I bought a 1:1 baller lock annis roxanne and it had a modkit problem where none of the body kit customisations and upgrades worked. There has been a problem with the loss of interior texture, I've had 2 car devs have a look at it and neither of them could get it sorted. Just wondering what I could do.

**Steps to reproduce**

**Expected behaviour**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID** 189257

**Comment by Nuxiie** [comment]
SPAWNCODE - ROXANNE

**Comment by loganuk** [comment]
Nothing to do with server developers - It is a fault with the model and if car devs cannot fix it then it is likely a flaw with the model. - This form is for actual server coding/development issues.
