### ISSUE TITLE
[Bug]: Lorry airport

### ISSUE THREAD

**Issue by Breeze-del6077** [CMGStudios/issue-tracker#1181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever I go to the airport for a lorry delivery with the helicopter, it will never let me see the lorry delivery confirm circle.

### Expected behaviour

I dont understand

### Steps to reproduce

1. Start the lorry delivery job. 2. Make sure it is a helicopter and to the airport (not sure if its only with the helicopter)

### Any Texture Packs? (If so list)

no

### CMG User ID

448171

**Comment by Gooobie** [comment]
Thanks for the report, please can you attach a video of this occurring

**Comment by packfile** [comment]
No response from OP, closing.
