### ISSUE TITLE
[Bug]: Long Range Emergency Blips not working for me

### ISSUE THREAD

**Issue by Kermitontherun** [CMGStudios/issue-tracker#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

purchased Long Range Emergency Blips but it does not come up on my map. i have purchased gang license aswell. i have done /turnonblips but dont work. 

### Expected behaviour

i should see police and nhs on my map

### Steps to reproduce

idk

### CMG User ID

445818

**Comment by jemiea** [comment]
To see Police & NHS long range blips you first need to be clocked on said faction, then do /blipson with an Emergency Radio.

If you want to see tour friends, you both need to be in the same F5, with a civilian radio. Said F5 Gang must also have the Advanced Gang License purchased. You then can do /blipson, making sure in your gang settings you have the blip colours, the user pinned etc all for ease of access.

**Comment by packfile** [comment]
@Kermitontherun Please see the response from jemiea above. If you're still encountering issues after let us know
