### ISSUE TITLE
[Bug]: Offshore money wiped

### ISSUE THREAD

**Issue by sssou** [CMGStudios/issue-tracker#1183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I log in after several days of inactivity. 
The offshore app is gone from CMG phone. 
I reinstall offshore app from the CMG phone app store. 
I open the offshore app and my balance is £0. 

I reset my CMG phone. 
I reinstall the offshore app. 
My offshore balance is still 0. 

I don't have records of my exact offshore balance history.
However, I am certain that it was never 0.

### Expected behaviour

the offshore app should firstly not be missing
the offshore app should not be displaying £0 when that was not the balance the last time I was logged on

### Steps to reproduce

Be gone from cmg for several days
log back on
open phone 

### Any Texture Packs? (If so list)

no

### CMG User ID

164449

**Comment by jemiea** [comment]
Go to the offshore app and withdraw 1 from your  balance. This will show the appropriate balance afterwards, it’s just a visual bug that it’s reset to 0.
