### ISSUE TITLE
[Bug]: Flashbangs Affect People in Other Buckets

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#1184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The flashbang effect goes through different buckets. For example, if you join a training world and throw a flashbang into a populated area, it'll flash everyone else close to it regardless of bucket they are in.

### Expected behaviour

Flashbangs should not have any effect across different buckets.

### Steps to reproduce

1. Get one person in the main bucket (0) and another in any other bucket
2. Get both people to be stood around the same location
3. A person in either buckets throws one flashbang
4. Notice how the flashbang affects the person in the other bucket 

### CMG User ID

2000

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report
