### ISSUE TITLE
[Bug]: Left Alt not allowing camera to be moved.

### ISSUE THREAD

**Issue by ashfaq2345** [CMGStudios/issue-tracker#1185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Usually when the camera is open, you can click left Alt in order to lock the mouse and move the camera around.
When I do it now, the mouse just disappears and I cannot move the camera.

### Expected behaviour

The mouse should lock and allow me to move the camera

### Steps to reproduce

1. Open phone
2. Camera
3. Start recording
4. Click Left Alt and try look around.

### CMG User ID

409712

**Comment by Gooobie** [comment]
Confirmed, thank you for the report. This will be sent to forward to our developer.

**Comment by packfile** [comment]
Thanks, this is being looked into

**Comment by packfile** [comment]
This has been fixed since the latest restart
