### ISSUE TITLE
[Bug]: Cayo Perico Setup not working. Lost 750k

### ISSUE THREAD

**Issue by ashfaq2345** [CMGStudios/issue-tracker#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I set up the heist and invited my friends, they joined and i started the hiest. They loaded in however i didnt, i was stuck in the clouds and it said drive to cayo perico. I have a clip of this. I lost 750k please can I get refunded as thats a lot of money to me.

### Expected behaviour

it should put me in the game and allow us to complete the setup

### Steps to reproduce

1. start 3rd Hiest at lesters factory, the cayo perico one,
2. invite friends
3. start heist
4. host will be stuck in clouds while others have loaded in
5. cry about losing 750k

### CMG User ID

409712

**Comment by Gooobie** [comment]
Please can you provide your log file located here `%localappdata%/FiveM/FiveM.app/logs`

**Comment by ashfaq2345** [comment]
[CitizenFX_log_2024-10-01T135919.log](https://github.com/user-attachments/files/17214071/CitizenFX_log_2024-10-01T135919.log)
[CitizenFX_log_2024-10-01T135939.log](https://github.com/user-attachments/files/17214073/CitizenFX_log_2024-10-01T135939.log)
It happened around 3:36PM

**Comment by packfile** [comment]
Thanks, this is being looked into.
