### ISSUE TITLE
Car spawner ain't working.

### ISSUE THREAD

**Issue by GGGamerGG1** [CMGStudios/issue-tracker#1187]
I bought a benefactor/Audi a8 but I can't spawn it in and it says to contact car devs but I'm new so I don't know how to do that.

**Comment by Gooobie** [comment]
Thank you for your report. This is an intentional feature, as branded cars aren't allowed in CMG for copyright reasons. Please contact someone from the debranding team, and they will walk you through the debranding process.

**Comment by GGGamerGG1** [comment]
Fair but I also bought a BMW m5 
![image_2024-10-02_193602191](https://github.com/user-attachments/assets/e6045409-9adc-44f9-bf19-65f1a21b7f4a)
e39 and it allowed me to spawn?
