### ISSUE TITLE
[Bug]: Banned for apparently ban evading??

### ISSUE THREAD

**Issue by eyeofconscious** [CMGStudios/issue-tracker#1188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have been perm banned for ban evading when I haven't ban evaded this is my only account. I am new to cmg and i joined the game 3 days ago. can you help me fix this issue?

### Expected behaviour

I have been perm banned for ban evading when I haven't ban evaded this is my only account. I am new to cmg and i joined the game 3 days ago. can you help me fix this issue?

### Steps to reproduce

help

### Any Texture Packs? (If so list)

help

### CMG User ID

449365

**Comment by Gooobie** [comment]
This isn’t a bug, please contact a member of staff if you would like help with this issue.
