### ISSUE TITLE
[Bug]: Phasing through wall at hmp

### ISSUE THREAD

**Issue by PeacePvP** [CMGStudios/issue-tracker#1189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

You can phase through the wall

### Expected behaviour

You wouldn't be able to phase through the wall

### Steps to reproduce

It'll be shown in the video, you just got to hit the gap
https://youtu.be/n_65LBgRVYM

### CMG User ID

437967

**Comment by Gooobie** [comment]
Confirmed, thank you for this report. This will be sent forward to our developer.

**Comment by packfile** [comment]
Thanks, a fix is pending and will be posted in dev-updates once live.
