### ISSUE TITLE
VC always on when push to talk is on

### ISSUE THREAD

**Issue by Ko-r-oo** [CMGStudios/issue-tracker#119]
**Describe the issue you're facing** I am on push to talk but it acts like I am on open mic and it won't change

**Steps to reproduce** Idk, relog? It happened randomly

**Expected behaviour**push to talk will act like open mic

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID** 159812

**Comment by loganuk** [comment]
As you have opened two tickets for the same issue - I will be closing this one - Please refer to https://github.com/CMGStudios/issue-tracker/issues/123
