### ISSUE TITLE
[Bug]: HMP drone absolutely fricked

### ISSUE THREAD

**Issue by goodguy69420** [CMGStudios/issue-tracker#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I just explode when I use the drone

### Expected behaviour

Its supposed to not blow up

https://medal.tv/games/gta-v/clips/iPBXRkfcg47oIH3Gs/d1337eb1O42l?invite=cr-MSxCdlEsMjEwNzU2MDg3LA

### Steps to reproduce

/drone

https://medal.tv/games/gta-v/clips/iPBXRkfcg47oIH3Gs/d1337eb1O42l?invite=cr-MSxCdlEsMjEwNzU2MDg3LA

### Any Texture Packs? (If so list)

NVE

### CMG User ID

343416

**Comment by packfile** [comment]
Thanks, a fix is pending and will be posted in dev-updates once live.
