### ISSUE TITLE
[Bug]: Reducing Time In HMPS

### ISSUE THREAD

**Issue by remoxee** [CMGStudios/issue-tracker#1191]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

First issue is with reducing time within HMP, whenever trying to reduce time it will say "Player not in prison" Even after re logging.

Second issue is with the /drone command. When doing it the animation is different and it will say "Access is denied engaging self defence and blows up 

**Reducing Time Video** "https://youtu.be/stouH3k2OfI"

**Drone Video** https://youtu.be/9aVkq_SpH1w

### Expected behaviour

Reducing time would jsut say its not allowed even after re logging

Drone animation changed into me being in a helicopter, and then blowing up after saying access is denied.

### Steps to reproduce

Get an prisoner Temp ids, do /reducetime and try.

Do / drone as HMP 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

437174

**Comment by JakeBrown03** [comment]
Can confirm the same thing happens on NHS https://medal.tv/games/gta-v/clips/iPFubeYsbUT7dQmCj?invite=cr-MSx1MUMsMTYxNDc5NTYxLA

**Comment by Gooobie** [comment]
confirmed, our dev is aware of this issue and this will be looked into soon. thank you.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed since last Monday's scheduled restart
