### ISSUE TITLE
[Bug]: Flashbang on HMP dosent work.

### ISSUE THREAD

**Issue by remoxee** [CMGStudios/issue-tracker#1194]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Flashbang dosent work on HMPS

### Expected behaviour

Flashbang dosent work on HMPS

### Steps to reproduce

Throw flashbang
wait for nothing

### Any Texture Packs? (If so list)

no

### CMG User ID

437174

**Comment by Gooobie** [comment]
confirmed, Thank you for your report. this will be sent forward to our Lead Developer.

**Comment by packfile** [comment]
Thanks, a fix is pending and will be posted in dev-updates once live.
