### ISSUE TITLE
[Bug]: Losing equipped weapons on restart.

### ISSUE THREAD

**Issue by ashfaq2345** [CMGStudios/issue-tracker#1195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you restart the game guns and melees that are equipped are lost.
1st time i did it i had to reset the game as my textures bugged out, i logged back in and lost my tec9. an hour later my game crashed and after logging back on i lost my rook40. both times i had no combat timer.

### Expected behaviour

you shouldnt lose guns after loggin back into the game

### Steps to reproduce

1. Equip gun/melee
2. disconnect
3. reconnect
4. cry over the guns that just vanished.

### CMG User ID

409712

**Comment by Gooobie** [comment]
Confirmed. Thank you for this report. It will be forwarded to our developer.

**Comment by packfile** [comment]
Thanks, this has been fixed for the next restart
