### ISSUE TITLE
[Bug]: HMPS GUI

### ISSUE THREAD

**Issue by remoxee** [CMGStudios/issue-tracker#1196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you are a prisoner, when your times gets reduced, or do tasks such as doing gym activities, or moping floors your time don't change on the GUI, but on the /viewprisoners as HMPS it changes.

### Expected behaviour

GUI Issue

### Steps to reproduce

Become an prisoner
Do gym actives / moping
Get hmps to confirm your time

### Any Texture Packs? (If so list)

N/A

### CMG User ID

437174

**Comment by packfile** [comment]
Thanks for the report, this is believed to be fixed since last weeks update push.
