### ISSUE TITLE
[Bug]: Cant put away my car or helicopter no matter what i do 

### ISSUE THREAD

**Issue by leoparkes123** [CMGStudios/issue-tracker#1197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ive came on after the 10am restart and was faced with this issue when i spawn a car it doesn't let me spawn it ive redownloaded the game restarted my pc and game multiple time to no help is says failed to load the vehicle and then lets me spawn it  but i cant place it away 

### Expected behaviour

just say fail to load vehicle 

### Steps to reproduce

1. open the garage 2. click on nhs vehicles 3.spawn the car 4. try to place it away 5. i doesn't place away    

### Any Texture Packs? (If so list)

none 

### CMG User ID

223618

**Comment by packfile** [comment]
Please provide the spawncode of the vehicle (can be found in F8 after spawning it) and any error message(s) you are getting for this to be investigated.
