### ISSUE TITLE
[Bug]: Redzone Drops not appearing for some players

### ISSUE THREAD

**Issue by MrMikeyTV** [CMGStudios/issue-tracker#1198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello friendly bug managers and mr lead developer. I hope you are having a splendid day.

Please see below a clip showing clear OOR:
1 - https://www.youtube.com/watch?v=SC0GyWzAEJU - in this clip in the bottom left the DROP redzone is clearly shown
2 - https://streamable.com/spjp1r - This is from another players perspective at the same time showing no DROP redzone.

### Expected behaviour

Redzone to appear for everybody

### Steps to reproduce

Go to drop

### CMG User ID

604

**Comment by packfile** [comment]
Thanks, a fix is pending and will be posted in dev-updates once live.
