### ISSUE TITLE
[Bug]: I keep spawning in dead

### ISSUE THREAD

**Issue by Gmason12** [CMGStudios/issue-tracker#1199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Every time I spawn in I die

### Expected behaviour

i die everytime i spawn in

### Steps to reproduce

just leave and join

### Any Texture Packs? (If so list)

no

### CMG User ID

450890

**Comment by crazychris2404** [comment]
Please can you provide more info as this is not reproducible
