### ISSUE TITLE
[Bug]: Trucking Cargo disappearing with vehicle cleanup

### ISSUE THREAD

**Issue by Tayserr** [CMGStudios/issue-tracker#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a vehicle cleanup occurs, it also removes your trucking cargo.
https://streamable.com/xji7q1

### Expected behaviour

It would be great if the cargo remained after a vehicle cleanup, so I don’t have to return to pick up a new one.

### Steps to reproduce

If your truck gets rammed and the cargo falls off, a vehicle cleanup might happen, causing the cargo to disappear.

### Any Texture Packs? (If so list)

NVE

### CMG User ID

309840

**Comment by packfile** [comment]
Thanks, a fix is pending and will be posted in dev-updates once live.
