### ISSUE TITLE
[Bug]: crosshair reseting

### ISSUE THREAD

**Issue by chase097** [CMGStudios/issue-tracker#1201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have my cursor size set to -3 and I also have it always on but every time I die I keep having to turn it on and off again because my cursor goes back to its normal size 

### Expected behaviour

When I respawn it should be still on -3 sizs

### Steps to reproduce

Die with cursor always on and set to size -3 then respawn

### Any Texture Packs? (If so list)

No 

### CMG User ID

435097

**Comment by packfile** [comment]
Could you please elaborate on what 'cursor size' you are referring to? Our `/crosshair` does not have any references to 'cursor' or 'size' options.

If you are using one of the F8 commands, these are builtin to FiveM and not maintained by us.
