### ISSUE TITLE
[Bug]:  bike/scooter bug

### ISSUE THREAD

**Issue by SoloFett112** [CMGStudios/issue-tracker#1202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

cant get on bike once you get off it

### Expected behaviour

cant get on bike once off it

### Steps to reproduce

spawn bike so your on it
get off it
try getbac kon it

### Any Texture Packs? (If so list)

.

### CMG User ID

1968

**Comment by crazychris2404** [comment]
This is not occuring for me
Please reopen with a clip and more detailed explanation
