### ISSUE TITLE
[Bug]: Not spawning a car in

### ISSUE THREAD

**Issue by Wexyrrr** [CMGStudios/issue-tracker#1203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

car does not exist

### Expected behaviour

after restart all of my cars dont exist

### Steps to reproduce

Just try spawn a car in
wont spawn in

### Any Texture Packs? (If so list)

N/A

### CMG User ID

429134

**Comment by packfile** [comment]
Thanks for the report, server is restarting to resolve the issue.
