### ISSUE TITLE
[Bug]:  cant pay house tax

### ISSUE THREAD

**Issue by SoloFett112** [CMGStudios/issue-tracker#1205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i go to pay my house tax then it keeps saying payment is being delayed

### Expected behaviour

house tax not payable

### Steps to reproduce

go to pay house tax
says payment is being delayed 
wont let u in ur house

### Any Texture Packs? (If so list)

.

### CMG User ID

1968

**Comment by Keegasity** [comment]
Thank you for the report!

Tom has confirmed the issue
