### ISSUE TITLE
[Bug]: customizations aren't there

### ISSUE THREAD

**Issue by markjhmm** [CMGStudios/issue-tracker#1206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

with one of my cars some of the customizations like : engine, bumpers, brakes, transmission suddenly disappeared and cant access them of change them.
![Screenshot 2024-10-26 151004](https://github.com/user-attachments/assets/03c7ae00-2150-410b-ab55-6b5de3d5b756)
![Screenshot 2024-10-26 151020](https://github.com/user-attachments/assets/88436606-69ff-4075-a824-4fc54431e628)
this is what is left

### Expected behaviour

.

### Steps to reproduce

.

### Any Texture Packs? (If so list)

no

### CMG User ID

40340

**Comment by Keegasity** [comment]
Thank you for the report.

Please can you provide me with the spawncode of the vehicle without the customisation options.

Thanks,
Keegan

**Comment by markjhmm** [comment]
> Thank you for the report.
> 
> Please can you provide me with the spawncode of the vehicle without the customisation options.
> 
> Thanks, Keegan

The spawn code is crratedr

**Comment by Keegasity** [comment]
Thanks for the report.

This has been resolved
