### ISSUE TITLE
[Bug]: Clocked on visual bug

### ISSUE THREAD

**Issue by remoxee** [CMGStudios/issue-tracker#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm not sure how to re-create this issue but, sometimes there will be an officer on HMP clocked on via HOME Menu but on status it doesn't say they are clocked on, _etc 6 people on home menu, on status it says 5._

### Expected behaviour

Visual bug, says your clocked on home menu, when your not.

### Steps to reproduce

Again not sure how to re create this issue, it could be how you leave the game, it could be internet going off any reason.

![image](https://github.com/user-attachments/assets/4abc7cde-8271-4bf2-9862-d9de6815fa8a)

### Any Texture Packs? (If so list)

N/A

### CMG User ID

437174

**Comment by jemiea** [comment]
To re-create this issue, be clocked on a Faction whether that’s NHS, PD, or HMP then join one of the events hosted within the server such as battlegrounds or the racetrack. When you lose/die and you F8 Quit instead of going back, it will glitch it and say on the home menu that you’re still on that faction.

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report.


Numbers on the homepage do not correspond with the status page within the discord

**Comment by remoxee** [comment]
@Keegasity right but on hmp clock on and off logs it says they clocked off hours ago, and yet still on home menu

**Comment by packfile** [comment]
Unable to reproduce this, even with the steps provided by @remoxee
