### ISSUE TITLE
[Bug]: Reducing Time In HMPS 2.0

### ISSUE THREAD

**Issue by remoxee** [CMGStudios/issue-tracker#1209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

First issue is with reducing time within HMP, whenever trying to reduce time it will say "You are trying to remove to much time from the player" Even after re logging.

### Expected behaviour

Get an prisoner Temp ids, do /reducetime and try.

### Steps to reproduce

Get an prisoner Temp ids, do /reducetime and try.

### Any Texture Packs? (If so list)

no

### CMG User ID

437174

**Comment by crazychris2404** [comment]
The other day this worked fine for me both adding and removing please ensure you are within the HMP limits for time reduction

**Comment by remoxee** [comment]
> The other day this worked fine for me both adding and removing please ensure you are within the HMP limits for time reduction

This has already been completed, I'm assuming it hasn't been marked as completed. Thank you anyway
