### ISSUE TITLE
LFB get fined by speed cameras and from PD speed guns.

### ISSUE THREAD

**Issue by BorgyBen** [CMGStudios/issue-tracker#121]
**Describe the issue you're facing**
LFB get fined by speed cameras and from PD speed guns. I think its to do with the firetruck spawn code - firetruk is not on the emergency vehicle list so it gets fined.
**Steps to reproduce**
Drive the firetruck through speed cameras or from PD speed gun and you will get fined
**Expected behaviour**
Not to get fined
**Screenshots/Video**
N/A
**Additional context**
None
**Any Texture Packs (if so list)**
N/A
**Perm ID**
8402

**Comment by alfiellds** [comment]
Confirmed - this will be reviewed by the developers. Thank you for the report.

**Comment by arthur-rl** [comment]
Fixed
