### ISSUE TITLE
[Bug]: Can't see the island

### ISSUE THREAD

**Issue by BAZZ-X** [CMGStudios/issue-tracker#1210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As a pilot when i get a job to the island the island is not there, i see the markers but for me it's in the middle of the ocean.

I can see other planes/players but on my screen they're just constantly falling into the ocean

I've also tried maxing out the extended textures and tweaking distance scaling. Multiple game restarts and it still persists, basically unable to play as pilot with this issue.

### Expected behaviour

The island should be visible

### Steps to reproduce

1. Become pilot
2. get job to island
3. go to island
4. island not there

### Any Texture Packs? (If so list)

No, game is standard

### CMG User ID

10133

**Comment by BAZZ-X** [comment]
Changed all my settings to medium and distance scaling settings to 0 now seems to work ok however would be nice to be able to play on max settings.

**Comment by packfile** [comment]
> Changed all my settings to medium and distance scaling settings to 0 now seems to work ok however would be nice to be able to play on max settings.

Enabling "High Detail Streaming While Flying" under "Advanced Graphics" has also known to fix this in the past if you wish to retain high settings.

**Comment by BAZZ-X** [comment]
> > Changed all my settings to medium and distance scaling settings to 0 now seems to work ok however would be nice to be able to play on max settings.
> 
> Enabling "High Detail Streaming While Flying" under "Advanced Graphics" has also known to fix this in the past if you wish to retain high settings.

Thanks, will try that.
