### ISSUE TITLE
[Bug]: laggy chat 

### ISSUE THREAD

**Issue by chase097** [CMGStudios/issue-tracker#1212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After a few hours when typing in chat words and letters don’t load in on the chat bar and all peoples chats that come through are laggy 

### Expected behaviour

To be normal and not laggy 

### Steps to reproduce

Wait a few hours type in chat then look at chat 

### CMG User ID

435097

**Comment by crazychris2404** [comment]
In fivem before loading into the server press the settings icon in top right and enable “fix UI lag” this should resolve the issue for you
