### ISSUE TITLE
[Bug]: Able to pull out attack dog while in prison, dog is able to attack while being dead.

### ISSUE THREAD

**Issue by GreenFruit1** [CMGStudios/issue-tracker#1213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When someone pulls out a dog in prison, and it gets killed its still able to attack people while dead.

https://www.youtube.com/watch?v=o5LTeKmpNPQ

### Expected behaviour

While the dog is dead, then it is dead and cant do anything.

### Steps to reproduce

1. Pull out a dog
2. send it to attack someone
3. kill it
4. it still attacks the person.

### CMG User ID

376656

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
