### ISSUE TITLE
[Bug]: Heist setup, Stuck in clouds

### ISSUE THREAD

**Issue by fockinhellmush** [CMGStudios/issue-tracker#1214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Most times when you start the small bank setup, id call it atleast 1 : 3 times, once loading in you'll get stuck in the clouds
All other players will load in except for the host, the heist can't be completed without all players being in the boat so ultimately, you've lost the £750,000 for the setup

### Expected behaviour

Nothing can really be expected, the only thing you can expect is admins to tell you to 'firms it'

### Steps to reproduce

1: Start the small bank setup
2: Get stuck in the clouds
3: Shout in discord about how shit this is and be upset for the next few hours

### Any Texture Packs? (If so list)

None

### CMG User ID

281936

**Comment by packfile** [comment]
Can you please provide you log file(s) for when this last occured? They can be found at `%localappdata%/FiveM/FiveM.app/logs`

**Comment by fockinhellmush** [comment]
Of course, theres 2 logs around the time this event happened so i'll upload both 

[CitizenFX_log_2024-11-14T152649.log](https://github.com/user-attachments/files/17750808/CitizenFX_log_2024-11-14T152649.log)
[CitizenFX_log_2024-11-14T140035.log](https://github.com/user-attachments/files/17750810/CitizenFX_log_2024-11-14T140035.log)

**Comment by fockinhellmush** [comment]
Hi, i have valuable information
Im confident that the heist setup glitches when someone else is already in the setup. i've tested this 3 times with other members and i have the clip to back it up
After millions wasted trying to figure this out, i think i may of found the answer
i did make a comp request, if you could pull any strings and help me recoup any of the millions lost to this setup, it would be greatly appreciated

**Comment by packfile** [comment]
> Im confident that the heist setup glitches when someone else is already in the setup. i

Thanks, was able to narrow it down from this. Fix is pending for next weeks restart.
