### ISSUE TITLE
[Bug]: Section 60

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#1215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cannot place Section 60 as a member of gold command

### Expected behaviour

Section 60 to be placable by Silver Command+

### Steps to reproduce

Clock on PD (Silver Command+) in my case i was clocked on Deputy Commissioner

### CMG User ID

1458

**Comment by crazychris2404** [comment]
Confirmed 
Due to recent pd roles issue all role related instances need to be redone
