### ISSUE TITLE
[Bug]: PHONE NOT OPENING

### ISSUE THREAD

**Issue by babz97** [CMGStudios/issue-tracker#1216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

RESTARTED THE GAME LIKE 5 TIMES, TRIED EVERYTHING, WHEN I PRESS F1 MY PHONE DOESNT COME OUT AND I GET A DEBUG MESSAGE IN MY F8 WHICH IS: https://imgur.com/a/Wpyxibx
edit: now im getting these messages too: https://imgur.com/a/ks8bEnf (removed voice target)

THERE IS NO OTHER MESSAGES ON MY SCREEN

### Expected behaviour

i expect the phone to come out as normal

### Steps to reproduce

1. load in
2. press f1
3. *no phone*

### Any Texture Packs? (If so list)

NO

### CMG User ID

390747

**Comment by crazychris2404** [comment]
Try pressing K your phone should then open if not feel free to reopen this issue
