### ISSUE TITLE
[Bug]: i been banned 

### ISSUE THREAD

**Issue by abdiski21** [CMGStudios/issue-tracker#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 i been banned for more then a year and half i would like to be unbanned i am sorry for my behavoir i wont do the same stuff and i am very sorry and would like to be unbanned.everyone makes mistake and i want to get new chance. thank you. id is 371479

### Expected behaviour

?

### Steps to reproduce

?

### CMG User ID

371479

**Comment by DjDoon** [comment]
Hello,
You can appeal your ban on the cmg forums - https://cmgstudios.net/forums/index.php?/forms/4-unban-appeal/
