### ISSUE TITLE
[Bug]: PD Ammo doesnt save after you relog

### ISSUE THREAD

**Issue by TheRealWicks** [CMGStudios/issue-tracker#1218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you have ammo in your gun it doesnt save on pd when you leave. If you leave with 250 ammo in your gun you join back with 0

### Expected behaviour

Keep the ammunition

### Steps to reproduce

Get PD
Get a gun
relog
no ammo

### Any Texture Packs? (If so list)

no

### CMG User ID

255

**Comment by remoxee** [comment]
I can confirm this issue persist on HMP as well.

**Comment by Gooobie** [comment]
Confirmed, this has been sent forward to our dev.
