### ISSUE TITLE
[Bug]: House TV not working 

### ISSUE THREAD

**Issue by Liam0204** [CMGStudios/issue-tracker#1219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![house image](https://github.com/user-attachments/assets/6a3eac83-ead9-4e45-882e-b77419fe6e70)
![house map](https://github.com/user-attachments/assets/c99ba69e-2686-46c5-b1d6-4f1eaa42b7a3)

House TV isn't working.. Brought the tv upgrade but only the music plays and no video appears 

### Expected behaviour

House TV isn't working.. Brought the tv upgrade but only the music plays and no video appears 

### Steps to reproduce

I've used the tv in other peoples house so I know the steps but it dont work in my house 

### CMG User ID

24682

**Comment by packfile** [comment]
Is the TV model preinstalled in the house, or have you placed it yourself?

**Comment by Gooobie** [comment]
I've contacted you via DM on Discord. I would like to confirm this issue with you. I've tested it in a rented house; it has worked for me and the player who came along to test it with me.

**Comment by Gooobie** [comment]
Preinstalled TV, enjoy your new TV.
