### ISSUE TITLE
pets not working

### ISSUE THREAD

**Issue by mudski** [CMGStudios/issue-tracker#122]
just bought a retriever pet for 4 mil but the attack aka knock someone out targeting doesn't work as i cant select anyone 

its meant to highlight someone and you press enter and the pet will attack them

https://youtu.be/2ctDmrMnyMs

204602

**Comment by arthur-rl** [comment]
![image](https://user-images.githubusercontent.com/43324346/128614053-91024672-0120-4346-9c66-57a0ff17878b.png)
**AIM**

**Comment by mudski** [comment]
you cant right click with it
so you cant select anyone / aim

**Comment by arthur-rl** [comment]
Need to use a gun...

**Comment by mudski** [comment]
i have to have a weapon out for my dog to knock someone out

**Comment by loganuk** [comment]
Yes - This is not a bug but a design feature. Otherwise people could use pets in stealth mode like Agent 47.
