### ISSUE TITLE
[Bug]: Username Bug

### ISSUE THREAD

**Issue by Jay-cmg** [CMGStudios/issue-tracker#1220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Since the new username update when people @ me I don't get pinged and the text doesn't highlight so I was wondering if this could get fixed or I get a free name change.          CMG Name= Jay.**

### Expected behaviour

i dont know hwne people are @ing me

### Steps to reproduce

idk

### CMG User ID

377478

**Comment by Keegasity** [comment]
Hello Jay,

@ing a player now works off of the username you have selected. For example my in-game name is Keegasity so @Keegasity pings myself.

Hope this helps.

Thanks,
Keegan
