### ISSUE TITLE
[Bug]: speeder2 boat

### ISSUE THREAD

**Issue by babz97** [CMGStudios/issue-tracker#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i just bought a speeder2 boat from the store, i try to spawn it and it doesnt spawn! says contact a car dev

### Expected behaviour

cant spawn speeder2 after i JUST bought it and test drove it and everything

### Steps to reproduce

1: go to boat store and buy a speeder2
2: try to spawn the speeder2

### CMG User ID

390747

**Comment by crazychris2404** [comment]
Please pm someone from the rebranding team listed under staff on right side of the discord
