### ISSUE TITLE
[Bug]: Dog Attack

### ISSUE THREAD

**Issue by Fuegosdad** [CMGStudios/issue-tracker#1223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when a dog is killed in a red zone it will still knock u out and do damage when going near it

### Expected behaviour

the dog shouldnt knock u out or do damage when its dead

### Steps to reproduce

spawn a dog, kill it and go near it

### Any Texture Packs? (If so list)

no

### CMG User ID

379406

**Comment by GreenFruit1** [comment]
Happens in prison too.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
