### ISSUE TITLE
[Bug]: Deleted Custom Folder's Showing In Garage

### ISSUE THREAD

**Issue by LeKyroh** [CMGStudios/issue-tracker#1224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I Created a custom folder in the garage and when i go to delete it it says it's been deleted but its still in my garage

### Expected behaviour

should just delete and no longer show

### Steps to reproduce

.

### Any Texture Packs? (If so list)

ReSahde

### CMG User ID

1158

**Comment by CanucklePuckette** [comment]
I have this same problem
