### ISSUE TITLE
[Bug]: Character resets every time i load in 

### ISSUE THREAD

**Issue by harry1233453** [CMGStudios/issue-tracker#1225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Everytime i load in my character resets to default with green hair and default clothes u load in with at first

### Expected behaviour

Everytime i load in my character resets to default with green hair and default clothes u load in with at first

### Steps to reproduce

Everytime i load in my character resets to default with green hair and default clothes u load in with at first

### Any Texture Packs? (If so list)

None

### CMG User ID

225100

**Comment by harry1233453** [comment]
and my offshore account bugs out it says 0 and i have it and deposit it again to show

**Comment by packfile** [comment]
Please attach your latest CMG log file from `%localappdata%/FiveM/FiveM.app/logs`
