### ISSUE TITLE
[Bug]: Glitched collisions over sandy

### ISSUE THREAD

**Issue by RTH-Retribution** [CMGStudios/issue-tracker#1226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://drive.google.com/file/d/13jSRkmSsHj-JdoIm77rkSAAaCOoxpPlc/view?usp=sharing

https://drive.google.com/file/d/11TRtyKD2DehwQwE4ynr56DPzyZojcDSn/view?usp=sharing

I need no words to describe this. It's fine when i get out the car but soon as i get in 1 it bugs like crazy.

### Expected behaviour

It shouldn't happen

### Steps to reproduce

??? There probs isn't one, its never happened before

### CMG User ID

449452

**Comment by packfile** [comment]
Videos do not appear to load, please upload them to YouTube, Streamable et al.
