### ISSUE TITLE
[Bug]: HOUSE DOORS BROKEN

### ISSUE THREAD

**Issue by Liam0204** [CMGStudios/issue-tracker#1227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Doors won't open and I can't access my house 
![map](https://github.com/user-attachments/assets/ae93150d-a976-4d5a-b7c9-f06e39603a76)
![gate](https://github.com/user-attachments/assets/44afb315-d08c-4986-8c4e-6343af110a12)

### Expected behaviour

Doors won't open and I can't access my house 

### Steps to reproduce

drive into doors, they should open but dont 

### CMG User ID

24682

**Comment by Keegasity** [comment]
Hello Liam,

This has been confirmed, the gates do not open.

(Cords - vec3(-1381.783813, 472.450348, 104.547585))

Thank you for the report,
Keegan

**Comment by packfile** [comment]
This is part of the base game, the doors do not open in standalone GTA either
