### ISSUE TITLE
[Bug]: Phone Disabled

### ISSUE THREAD

**Issue by dannydodar** [CMGStudios/issue-tracker#1228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After using the motion doorbell camera, the phone becomes un-openable.

### Expected behaviour

Phone should work as normal after using motional doorbell camera.

### Steps to reproduce

Preview a camera on motion doorbell, exit camera and menu, try to pull up phone.

### CMG User ID

616

**Comment by Keegasity** [comment]
Hello Danny,

Please can you provide a clip of this.

Thanks,
Keegan
