### ISSUE TITLE
[Bug]: Hair at clothing shop is bugged.

### ISSUE THREAD

**Issue by CanucklePuckette** [CMGStudios/issue-tracker#1230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some of the hairstyles are missing sections. This is for the females. I am not sure about the males. 

### Expected behaviour

No having missing sections. Thank you!

### Steps to reproduce

none

### Any Texture Packs? (If so list)

No

### CMG User ID

986

**Comment by packfile** [comment]
Thanks for the report, this has been forwarded
