### ISSUE TITLE
[Bug]: cant spawn my heli car

### ISSUE THREAD

**Issue by Liam0204** [CMGStudios/issue-tracker#1231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

brought a heli car on auction and can't spawn it - Benefactor GLS Heli 

![image](https://github.com/user-attachments/assets/906aafb6-5f32-424a-bb33-a1e6a97ba69d)

### Expected behaviour

brought a heli car on auction and can't spawn it - Benefactor GLS Heli 

### Steps to reproduce

brought a heli car on auction and can't spawn it - Benefactor GLS Heli 

### CMG User ID

24682

**Comment by Keegasity** [comment]
Hello Liam,

Due to this not being a bug I will close this report. However, please message me on discord with the vehicle spawncode. I can then ask a member of the Car Development team to look into this for you.

Discord -> Keegasity

Thanks,
Keegan
