### ISSUE TITLE
[Bug]: House DJ

### ISSUE THREAD

**Issue by SteffFivem** [CMGStudios/issue-tracker#1233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Renting an mlo from someone - house has dj system but wont work

### Expected behaviour

i open the menu, paste the link press pltay and no music

### Steps to reproduce

dj menu
input yt link
no sound soming from it

### Any Texture Packs? (If so list)

none

### CMG User ID

401948

**Comment by Keegasity** [comment]
Hello Steff,

DJ Menu takes abit of playing around with to get working correctly, for example.

If I wanted to play this song -> https://www.youtube.com/watch?v=ZyhrYis509A&ab_channel=AquaVEVO I would need to modify the URL slightly by removing _channel=AquaVEVO

https://www.youtube.com/watch?v=ZyhrYis509A&ab

Please try this and let me know if you have any other issues.

Thanks,
Keegan

**Comment by packfile** [comment]
Tested with the provided steps, renting a house and then using /djmenu it worked as expected. Make sure you also have a TV screen placed down and bought.
