### ISSUE TITLE
[Bug]: I'm stuck under map

### ISSUE THREAD

**Issue by Lelandop** [CMGStudios/issue-tracker#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![17331563881638753707467374788812](https://github.com/user-attachments/assets/ad63f183-9ced-48bf-b6d1-c2240bfae96c)

### Expected behaviour

Stuck

### Steps to reproduce

Help

### Any Texture Packs? (If so list)

No

### CMG User ID

407135

**Comment by Keegasity** [comment]
Hello Lelandop,

Please do /calladmin in game and an admin will help you get out of here.
