### ISSUE TITLE
[Bug]: Cant bid on auctions in CMG discord.

### ISSUE THREAD

**Issue by Jamie1142** [CMGStudios/issue-tracker#1236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Every time I try to !bid [amount] on a auction is says I don't have enough funds. Even though I do.

Just tried to bid £10M on a auction that just went live with a current bid of £1. I have £190M in my offshore.
![Screenshot_20241202_191208_Discord](https://github.com/user-attachments/assets/e70d16e8-e710-4a2a-a1fb-441e06caad9b)
![Screenshot_20241202_191212_Discord](https://github.com/user-attachments/assets/5dce9056-6fd3-428f-bdbb-9f53f80cfd7f)
![WtVN5QE](https://github.com/user-attachments/assets/ebde28ae-c6e0-4743-8647-1ec222817519)

### Expected behaviour

For it to place my bid.

### Steps to reproduce

1. Have money in offshore or bank account 
2. !bid 50000000 (example amount) on a active auction 
3. Bot replies with "You do not have enough money to make this bid."

### Any Texture Packs? (If so list)

NVE

### CMG User ID

341

**Comment by Keegasity** [comment]
Hello Jamie,

Please try withdrawing the fund from your offshore account.

**Comment by Jamie1142** [comment]
I've tried it. Didn't work, just lost money paying taxes.

**Comment by packfile** [comment]
Please try again, this should be resolved
