### ISSUE TITLE
[Bug]: phone gets disabled after accessing doorbell/cctv on your house

### ISSUE THREAD

**Issue by KC0161** [CMGStudios/issue-tracker#1237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you have purchased a doorbell/cctv cameras for your house, and then you type the command to go into the cameras like /doorbell and then exit it you can no longer use your phone.

### Expected behaviour

to be able to pull up your phone

### Steps to reproduce

1. have access to a house with doorbell or cctv
2. run the command /doorbell and access the camera
3. exit it and try to pull out your phone

### Any Texture Packs? (If so list)

no

### CMG User ID

508

**Comment by packfile** [comment]
Thanks for the report, this has been fixed since Mondays restart
