### ISSUE TITLE
[Bug]: Whitelist Forgi Truck can barely move with the fuel tanker trailer.

### ISSUE THREAD

**Issue by RTH-Retribution** [CMGStudios/issue-tracker#1239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The whitelisted trucking truck called the "Custom Forgi Truck" basically struggles to even move with the fuel trailer attached this is especially clear when you pick the trailer up in an offroad area or an area where you are forced to go uphill, you basically have to keep attaching and detaching the trailer to try and get it away from that offroad area however its also a serious issue when the sections you have to go through are uphill, I've had to adopt the wiggle boost strategy a few times now (basically where you have to keep turning left and right to wiggle the trailer to gain speed). Here's a video so you can see what I mean about the truck moving incredibly slowly and stopping in the clip: https://streamable.com/507owi   On a side note, blowing the fuel tanker trailer up does actually make the trailer movable by the truck as though it was any of the other trailers.

### Expected behaviour

The truck should at least be able to get out the area and move at a reasonable speed not struggle its way through or not be able to make it without you attaching and detaching it multiple times since this Isn't an issue I've had with any other truck all other trailers work perfectly fine for this truck too, It's just the fuel tanker that it struggles with.

### Steps to reproduce

1. Get a Forgi truck 
2. Start trucking with that truck 
3. Get the fuel trailer as a pickup (preferably one where you have to go offroad or up hills with it.)
4. Collect the trailer 
5. Try to move, the truck will basically barely move or move slowly to the point that it may stop moving entirely or go 1mph.

(this Isn't an issue with the Transbenzarocs the £200k 8 wheeled one which can make it perfectly fine with that trailer)

### CMG User ID

449452

**Comment by packfile** [comment]
Thanks for the report, this has been forwarded to the car team.
