### ISSUE TITLE
Met PD - /flag /unflag - Custom Reg Plates

### ISSUE THREAD

**Issue by loganuk** [CMGStudios/issue-tracker#124]
**Describe the issue you're facing**

It is currently not possible to flag any vehicle which has a custom reg plate. We can do /flagf or /flagr but cannot /unflag after

This might be due to the fact that every car uses a string of numbers and the custom reg plate is cosmetic but is not the value used in the flagging process.

**Steps to reproduce**

1. Clock on as PD
2. Get in a police car
3. Find a custom reg plate vehicle
4. Attempt to /flag CUSTOM plate
5. When you /flagf try to /unflag CUSTOM plate

**Expected behaviour**

Whether you type numbers or letters - You should be able to flag or unflag vehicles.

**Screenshots/Video**

Not needed

**Additional context**

Not needed

**Any Texture Packs (if so list)**

NVE

**Perm ID**

7382

**Comment by arthur-rl** [comment]
By custom reg plate do you mean the ones you buy at the job centre?

**Comment by loganuk** [comment]
Yeah at city hall - So anything that is not the standard set of numbers.

**Comment by crazychris2404** [comment]
This bug is still ongoing and affecting PD. This will be moved to high priority. When using a custom plate from city hall the the vehicle will not show as being flagged with either /flagf or /flag (plate) etc

**Comment by crazychris2404** [comment]
After speaking to developers there is no easy fix for this problem so will not currently be fixed.

**Comment by crazychris2404** [comment]
Custom plates are currently disabled pending a rework and this will be looked into once this is complete.

**Comment by tom-gun** [comment]
Closing - No reports since the licence plate update, commands work fine in the live server
