### ISSUE TITLE
[Bug]: NPAS helicopter camera zoom is unrealistically slow

### ISSUE THREAD

**Issue by Flinny-k** [CMGStudios/issue-tracker#1240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The camera zoom has been changed recently and is significantly slower zooming in and out.  IT makes it almost unusable when flying .

### Expected behaviour

zoom in and out at a reasonable pace so that i dont crash when doing it

### Steps to reproduce

1. get in npas helicopter
2. press e to enter camera
3. zoom in and out at a painfully and unrealistically slow pace
4. exit camera happy you didnt crash into something 
5. stop flying npas because it is so frustrating. 
6. have a part of the faction neglected as it is reduced the enjoyment alot

### Any Texture Packs? (If so list)

no

### CMG User ID

9733

**Comment by packfile** [comment]
Thanks for the report, a fix is pending for next weeks scheduled restart.

**Comment by packfile** [comment]
This has been fixed since Mondays restart
