### ISSUE TITLE
[Bug]: /reset breaks game

### ISSUE THREAD

**Issue by Ryddddd** [CMGStudios/issue-tracker#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenver you do the /reset command it makes you see weird colours then black screen untill you re start your game, happend 3 times now

### Expected behaviour

You do /reset and you go to admin island after 3 secs come back and your games nice again smoothly 

### Steps to reproduce

1. T/Rest or f8--> reset

### Any Texture Packs? (If so list)

NO

### CMG User ID

210

**Comment by Ryddddd** [comment]
https://youtu.be/8YFzKIGpteY Clip here

**Comment by packfile** [comment]
Tried /reset in dev & live server, both seem to work fine. If you find other reproduction steps or other people with this issue please let us know.
