### ISSUE TITLE
[Bug]: Pets Cannot Attack

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#1242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After Monday's restart, pets can longer attack other players/peds. In the following clip, you can see that both the Brown Bear and the Retriever do not attack the player. If this affects anything, my ability to attack was removed from 17th November, and was given back on 21st November.

https://streamable.com/doc5lx

### Expected behaviour

Pets should be able to attack other players/peds.

### Steps to reproduce

1. Spawn a pet that can attack
2. Initiate an attack
3. Equip a weapon and point it at a player
4. Set the pet on someone with "Enter"

### Any Texture Packs? (If so list)

N/A

### CMG User ID

2000

**Comment by packfile** [comment]
Thanks for the report, a fix is pending for next weeks scheduled restart.

**Comment by packfile** [comment]
This has been fixed since Mondays restart
