### ISSUE TITLE
[Bug]: Offshore and monzo disappearing again

### ISSUE THREAD

**Issue by Hypers87** [CMGStudios/issue-tracker#1243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

just like we all had before the offshore and monzo disappearing its happening to me again. though it was a one off thing but it isnt it like the 10th time now.

### Expected behaviour

for it not to disappear

### Steps to reproduce

1. load in 
2. look at phone
3. see it is gone
4. or
5. play the game
6. look at ur phone at one point
7. it will be there
8. next it wont :)

### Any Texture Packs? (If so list)

reshade

### CMG User ID

1341

**Comment by packfile** [comment]
Can you please attach your log file for when this happens, found at:
`%localappdata%/FiveM/FiveM.app/logs`
