### ISSUE TITLE
[Bug]: finishing a payment plan dupes car in garage

### ISSUE THREAD

**Issue by Yiqqa** [CMGStudios/issue-tracker#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when paying off the final week of your payment plan for a vehicle, sometimes 2 of the same vehicle appear in your garage. no it doesnt let you spawn both.

### Expected behaviour

vehicle to be duped in garage menu

### Steps to reproduce

1. pay off the last week of your payment plan
2. open your garage and check to see if the vehicle duped

### CMG User ID

1131

**Comment by packfile** [comment]
Thanks for the report, a fix has been put in for a future restart.
