### ISSUE TITLE
[Bug]: HMP Vehicles not spawning 

### ISSUE THREAD

**Issue by PNibbles** [CMGStudios/issue-tracker#1245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Go up to garage spawn HMPS Gallivanter or Incident Support Unit Van in and they fail to spawn other vehicles spawn normally.

### Expected behaviour

The vehicles spawn in.

### Steps to reproduce

Go to hmps garage and try to spawn cars in. 

### Any Texture Packs? (If so list)

na

### CMG User ID

1182

**Comment by remoxee** [comment]
This issue only occurs when trying to spawn in these vehicles

**HMPS Gallivanter**
**Police Incident Support Unit** _has HMPS Livery_

As well as the same issue is on civilians garages and police / pd garages.

**Comment by ItsJunction** [comment]
> This issue only occurs when trying to spawn in these vehicles

This issue affects anything that is in multiple garage folders by default (i.e., the Ultralight plane can only be pulled out of "VIP Helicopters" and not "Standard Aircraft").

https://streamable.com/frr9xe

**Comment by remoxee** [comment]
> This issue affects anything that is in multiple garage folders by default (i.e., the Ultralight plane can only be pulled out of "VIP Helicopters" and not "Standard Aircraft").

Don't think so, i can spawn HMP vehicles that are in the same folder as the vehicles having issues to spawn

**Comment by packfile** [comment]
Thanks for the report, a fix has been put in for a future restart.
