### ISSUE TITLE
[Bug]: VIP cars not spawning , takes vehicle tax but car does not load 

### ISSUE THREAD

**Issue by ASBOebikes** [CMGStudios/issue-tracker#1246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

VIP cars not spawning , takes vehicle tax but car does not load . The regular cars work fine 

### Expected behaviour

Cars not loading 

### Steps to reproduce

Try to spawn vip car (my bmw m4 CS ICB lock )

### Any Texture Packs? (If so list)

No

### CMG User ID

454921

**Comment by packfile** [comment]
This does not appear to be an issue anymore, if it is please reopen
