### ISSUE TITLE
[Bug]: When dragging people and opening doors, the E radial menu opens up

### ISSUE THREAD

**Issue by GreenFruit1** [CMGStudios/issue-tracker#1247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When dragging people and opening doors, the E radial menu opens up. I cant even drag people normally.

[ ] https://youtu.be/DDgP0JTUhW0

### Expected behaviour

Drag people, press E to open door and it doesn't open the radial menu.

### Steps to reproduce

1. Drag a person
2. Open a door

### CMG User ID

376656

**Comment by packfile** [comment]
Thanks for the report, this has been changed for a future restart
