### ISSUE TITLE
Permanent GTA Crosshair Doesn't Function As Expected.

### ISSUE THREAD

**Issue by butterfIies** [CMGStudios/issue-tracker#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since i have been unbanned i have been using the new Permanent GTA White Dot Crosshair, this works flawlessly until you die. Once you respawn it sets your crosshair size to default which is huge and you have to do numerous steps to fix it.

### Expected behaviour

turn it on, die, respawn, and it still be the same as before.

### Steps to reproduce

Turn on the GTA Permanent Crosshair under UI Visibility in F2

Die

Wait the respawn timer

Respawn

the size has been reset back to the default value of 0 even when you have changed it in settings or your f8 console.

### Any Texture Packs? (If so list)

nah mush

### CMG User ID

220225

**Comment by packfile** [comment]
Can you provide the F8 commands you use your change your GTA crosshair size so we can attempt reproduce this

**Comment by butterfIies** [comment]
i personally use profile_reticuleSize -3, after i die the only way to make it smaller again is by changing the size (profile_reticuleSize 0) then putting it back to my desired value and finally turning on and off the option in F2 Settings

**Comment by packfile** [comment]
Thanks, this has been fixed for a future restart
