### ISSUE TITLE
[Bug]: HMP Kitchen Door 2 

### ISSUE THREAD

**Issue by remoxee** [CMGStudios/issue-tracker#1249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a lockdown starts at HMP via the /lockdown command, all doors shut as intended. When it ends and the said command is given to remove it, **Kitchen Door 2** remains open. That door shouldn't automatically open; this means prisoners could gain access to the reception area.

### Expected behaviour

When a lockdown starts at HMP via the /lockdown command, all doors shut as intended. When it ends **Kitchen Door 2** should remains closed. 

### Steps to reproduce

Check Kitchen Door 2
Lockdown the prison via /lockdown
Disable lockdown via /lockdown ( 5 minute cooldown)
Check Kitchen Door 2 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

437174

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for a future restart
