### ISSUE TITLE
[Bug]: Dont get a ping sound when i am tagged in chat

### ISSUE THREAD

**Issue by SUTTO999** [CMGStudios/issue-tracker#1250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i am tagged to @ chat i don't get a ping sound nor is it highlighted in chat, its because i have a - in my name i think. My name is Jon-Jones on CMG

### Expected behaviour

When i am tagged to @ chat i don't get a ping sound nor is it highlighted in chat, its because i have a - in my name i think. My name is Jon-Jones on CMG

### Steps to reproduce

Im not sure

### Any Texture Packs? (If so list)

Reshade

### CMG User ID

444990

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for a future restart
