### ISSUE TITLE
[Bug]: DJMENU WORKS FOR otherpeople not me

### ISSUE THREAD

**Issue by TheRealWicks** [CMGStudios/issue-tracker#1251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

They can hear the music i play but i cant hear it 

### Expected behaviour

They can hear the music i play but i cant hear it 

### Steps to reproduce

play music u cant hear it they can

### CMG User ID

255

**Comment by Ryddddd** [comment]
Check that your ''Fivem Chromium Subprocess'' is on mav volume in ur pc sound mixer settings

**Comment by packfile** [comment]
There is also the "Maximum DJ Volume" under Settings -> Misc
