### ISSUE TITLE
[Bug]: Driving test bugged

### ISSUE THREAD

**Issue by CurlyyDom** [CMGStudios/issue-tracker#1253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After purchasing a driving test from the DVLA for £20,000, I was placed into a new server unable to access any of the cars in my garage and encountered the error message: "You're in the wrong session, please relog." I chose to leave the server and rejoin, but in doing so, I lost the £20,000 previously deposited.

### Expected behaviour

Due to this bug, I have unfortunately lost $40,000, which is a significant impact on my finances.

### Steps to reproduce

1. Purchase a driving test from the DVLA
2. Attempt to access garage
3. Reload game

### Any Texture Packs? (If so list)

N/A

### CMG User ID

458803

**Comment by TheRealWicks** [comment]
Your fault for not doing the driving test.

Message me on discord and il sort you out bbywicksxo

**Comment by packfile** [comment]
When you start the driving test it will direct you to the car to drive outside of the DVLA center
