### ISSUE TITLE
No vehicle blip on the map

### ISSUE THREAD

**Issue by BobbyTheBuildery** [CMGStudios/issue-tracker#126]
**Describe the issue you're facing**
When spawning in a car it doesn't show on the map.
**Steps to reproduce**
spawn a vehicle and there won't be a blip on the map.
**Expected behaviour**
Vehicle blip/icon to show on the map.
**Screenshots/Video**
N/A
**Additional context**
N/A
**Any Texture Packs (if so list)**
N/A
**Perm ID**
169174

**Comment by loganuk** [comment]
I myself have encountered this as well - There is an issue with the green vehicle icon not being there a lot of the time now.

**Comment by loganuk** [comment]
Duplicate issue - https://github.com/CMGStudios/issue-tracker/issues/137 - Closed that issue and left here.

**Comment by rubbertoe98** [comment]
Fixed.
