### ISSUE TITLE
[Bug]: Island not loading in

### ISSUE THREAD

**Issue by Breeze-del6077** [CMGStudios/issue-tracker#1267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When doing piloting island does not load in properly for me! Fix this issue as it has been going on for ages.

### Expected behaviour

As described in the first paragraph island does NOT load it properly.

### Steps to reproduce

1. Start piloting. 2. Get island. 3. Encounter the issue

### Any Texture Packs? (If so list)

no

### CMG User ID

448171

**Comment by Keegasity** [comment]
Hello,

Please contact me via discord and I can go through some steps to fix this with you.

Discord - Keegasity

Thanks
