### ISSUE TITLE
Boosting Discord server and still cant craft BMXs

### ISSUE THREAD

**Issue by Itsethanoc** [CMGStudios/issue-tracker#128]
Boosted the discord server two days ago and still cannot create a BMX in game, it just says to boost the discord server, my accounts are all linked and there’s nothing wrong there, perm id 127897 discord is Еthan#0001

**Comment by arthur-rl** [comment]
Is your discord linked to FiveM? You can check this in your FiveM settings.

**Comment by loganuk** [comment]
@Itsethanoc Have you checked your FiveM Settings yet? If so is it now sorted?

**Comment by arthur-rl** [comment]
I've marked this issue as inactive. If there is no reply in 4 days from now, I will close this issue.

**Comment by alfiellds** [comment]
Closed due to inactivity.
