### ISSUE TITLE
Handcuffs and Handcuff keys

### ISSUE THREAD

**Issue by HotJesusMilk** [CMGStudios/issue-tracker#132]
Handcuffs + keys don't work in the server for civ use i'm always receiving them from the casino and noticed what a good use for RP they have especially within gang RP. 
It would be nice if the price of the handcuffs could be increased a fair amount so that people are more inclined to use them for RP purposes and not just to mess around and keep the handcuff key price lower so it's more accessible to get out of them if it does happen. 
202422

**Comment by loganuk** [comment]
Can you get a clip of them not working @HotJesusMilk please

**Comment by loganuk** [comment]
If you cannot provide POV of this not working I will close this issue in 24 hours.

**Comment by alfiellds** [comment]
Closed due to inactivity.
