### ISSUE TITLE
You cannot ride a horse that is purchased the pet store 

### ISSUE THREAD

**Issue by daviesharry** [CMGStudios/issue-tracker#134]
Describe the issue you're facing
I cannot ride a horse purchased from the pet store
Steps to reproduce
Buy a horse from the pet store
Try and ride the horse
You will find that you cannot ride the horse
Expected behaviour
You should be able to ride horses as you paid lots of money for it
Screenshots/Video
None
Additional context
N/A
Any Texture Packs (if so list)
N/A
Perm ID
N/A

**Comment by JunctionNinja** [comment]
As per https://discord.com/channels/458382797103693867/598108077786529812/635315781667651584, only the MET (could) ride horses. However I haven't seen them at all in my time on CMG.

In addition, it says nowhere you can ride them. 
![image](https://user-images.githubusercontent.com/62995181/129093992-b472ffe9-9025-419a-a3ee-0f7902b18186.png)

However, this is a great suggestion and you can [suggest it here](https://cmgforums.com/forums/index.php?/forum/45-your-suggestions/&do=add).

**Comment by arthur-rl** [comment]
This isn't a bug.
