### ISSUE TITLE
Traffic Menu Bug

### ISSUE THREAD

**Issue by MrMikeyTV** [CMGStudios/issue-tracker#135]
**Describe the issue you're facing**
After fixing the traffic menu noclipping, the traffic menu now doesn't place where the preview shows which is causing a lot of issues when placing down scene control.

**Steps to reproduce**
- Place down a Gazebo
- Place a Gate Barrier in line with the Gazebo

**Expected behaviour**
- Gate Barrier should line up with the gazebo when placed

**Screenshots/Video**
https://clips.twitch.tv/NastyAcceptableCarabeefPunchTrees-sdoJpW5MrNRGdnvt

**Additional context**
Used a lot with Fast Response

**Any Texture Packs (if so list)**
None

**Perm ID**
604

**Comment by rubbertoe98** [comment]
Thank you, fixed.
