### ISSUE TITLE
Cars Bug Out With Glitched Uncuff

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#136]
**Issue:** Getting in cars with handcuffs off but visually on will bug out cars. Cars will go everywhere, flip, get damaged and not stay in one spot until the player gets out.

This is due to the cuffs being stuck on the player with a little representation (don't have an image, will try and get one).
![image](https://user-images.githubusercontent.com/62995181/129252398-20b0db1f-93dd-4039-af88-71d774ccaa4f.png)

(sorry for low quality, the only way I get performance on the server will get a better image when I can)

**Steps to reproduce:** 
- Have the glitched cuffs (basically when they stay on visually even though you've been uncuffed. It doesn't break everytime but sometimes it will (image above of how it should look, but usually stays at the side of your arms).
- Hop into any vehicle (passenger seat works too). Now your car should be flinging everywhere.

**Expected behaviour:** Should just let you sit in the car without it bugging out.

**Screenshots/Video:** None ATM (if anyone has one, please reply with it).

**Any Texture Packs (if so list):** N/A

**Perm ID:** 194575

**Comment by JunctionNinja** [comment]
Did some extra testing and this most likely isn't the cause of the issue.

I haven't seen the issue since a few hours before I made this bug report.

**Comment by JunctionNinja** [comment]
Turns out this is actually due to the cuffs. It doesn't happen everytime though and the glitched cuffs I couldn't get at all, however I did see it just before todays restart.

**Comment by JunctionNinja** [comment]
Just for this, I re-opened this issue.

**Comment by loganuk** [comment]
Hmmm - I wonder if this is a coincidence from a known FiveM bug that makes the cars flip around.

Can you get this on clip next time it happens please?

**Comment by JunctionNinja** [comment]
Sure can!

**Comment by loganuk** [comment]
Any joys getting a clip of it? @JunctionNinja

**Comment by JunctionNinja** [comment]
Saw one earlier but I couldn't get a clip.

Still trying to get one.

**Comment by loganuk** [comment]
I am almost certain this is not a bug with the cuffs prop and is linked to the unfortunate timing of the FiveM car flipping bug. - As that bug happens frequently without PD or cuffs visible involved either. - I've tried re-creating this manually with no success, anything else you could add to this?

**Comment by JunctionNinja** [comment]
Honestly, not something I have seen as common in the past couple of days.

I shall close the issue until I find anything else relating to this issue.
