### ISSUE TITLE
Car icon won’t show on my map

### ISSUE THREAD

**Issue by relyzx** [CMGStudios/issue-tracker#137]
**Describe the issue you're facing**
When ever I pull out a car it doesn't show up with the green icon on my map
**Steps to reproduce**
Fix the script
**Expected behaviour**
Show a green vehicle icon on mal
**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**
NVE
**Perm ID**
193326

**Comment by loganuk** [comment]
Hello - This is a duplicate of an already open issue - So I will close this issue but I have referenced it there - https://github.com/CMGStudios/issue-tracker/issues/126
