### ISSUE TITLE
Car Never Comes Out

### ISSUE THREAD

**Issue by ethznnnn** [CMGStudios/issue-tracker#140]
my mercedes maybach brabus wont pull out and didnt pull out for the previous owner either

**Expected behaviour**

https://streamable.com/gvocqt

Whenever i try and pull out the car it taxes me and no car appears 

No

197224

**Comment by rubbertoe98** [comment]
Confirmed issue, will be fixed soon.

**Comment by rubbertoe98** [comment]
Fixed on next restart.
