### ISSUE TITLE
[Bug]: CMG Phones

### ISSUE THREAD

**Issue by smackeee** [CMGStudios/issue-tracker#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you ring someone you cant answer most of the time and cant end it. Most of the time when press K to put your phone down, the ringtone carries on until you relog :(.

### Expected behaviour

phone being a bit special tbh

### Steps to reproduce

Make a contact
Call the number
Try end it or answer a call from another player.

### Any Texture Packs? (If so list)

NVE

### CMG User ID

54321

**Comment by JunctionNinja** [comment]
I too have this issue.

The issue has been around for about 3 or 4 days but I had it more just after #90 (but I don't think this is the cause).

**Comment by ItsJunction** [comment]
Clip of @smackeee's issue occurring to me.

https://streamable.com/aiknuf

Also if you want to mute audio when the issue occurs then turn down "FiveM Chromium subprocess" in volume mixer (by rightclicking the volume icon in your taskbar) to 0. This will also mute the loading music etc. so make sure to turn it back up later if you need. 


![image](https://user-images.githubusercontent.com/62995181/129446464-a4e2ee44-0893-4554-8352-33e43b52318a.png)

**Comment by crazychris2404** [comment]
Does this still occur @smackeee

**Comment by crazychris2404** [comment]
No longer a active issue
