### ISSUE TITLE
Car never comes out

### ISSUE THREAD

**Issue by ethznnnn** [CMGStudios/issue-tracker#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my mercedes maybach brabus never pulls out from the garage, it was the same for the previous owner aswell (tailgater2 - spawn code)

### Expected behaviour

Wont pull out from the garage

### Steps to reproduce

Try and pull it out from the garage

### Any Texture Packs? (If so list)

no

### CMG User ID

197224

**Comment by rubbertoe98** [comment]
Closing due to duplicate of #140
