### ISSUE TITLE
[Bug]: Sandy PD

### ISSUE THREAD

**Issue by lokiiq** [CMGStudios/issue-tracker#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Invisible PD, makes game look shit, hard to RP in. https://cdn.discordapp.com/attachments/856940716264915035/876254438656970762/unknown.png

### Expected behaviour

The PD look normal????

### Steps to reproduce

1. Use your feet, walk into the PD
2. Look around?

### Any Texture Packs? (If so list)

No

### CMG User ID

170443

**Comment by arthur-rl** [comment]
What is your extended texture budget on?

**Comment by lokiiq** [comment]
> What is your extended texture budget on?

50% - only put the report in as it doesn’t just happen to me.

**Comment by MrLexo** [comment]
After checking on the server, I can't seem to replicate this problem as it loads fine. This is most likely something to do with your settings or loading into the sever while inside the room causing the issue until you go outside the building and back in.

**Comment by loganuk** [comment]
This is an intermittent bug which is hard to re-produce consistently but it is valid. It is a temporary glitch only affecting that location.
