### ISSUE TITLE
[Bug]: CMG Club - Plus

### ISSUE THREAD

**Issue by MrParkerCMG** [CMGStudios/issue-tracker#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Purchased CMG Plus - The Majority of the cars I own do not auto clean.  Example spawn code: Barney 
Spawn Code: THTMegane

### Expected behaviour

should auto clean when spawning a car 

### Steps to reproduce

enter the car and wait for it to clean. and it doesnt.

### Any Texture Packs? (If so list)

no

### CMG User ID

306

**Comment by rubbertoe98** [comment]
Fixed on next restart.
