### ISSUE TITLE
[Bug]: Weapons flicker when on front or back

### ISSUE THREAD

**Issue by AndiPoop** [CMGStudios/issue-tracker#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a weapon is on either the back or front of your character the model will flicker and looks really bad. 
Video: https://streamable.com/wgwvey

Gun does not flicker when you are actually holding it, only when on your front or back.

People I know are also having the same issue.

### Expected behaviour

To not flicker.

### Steps to reproduce

1. Get a gun
2. Put it on your back or front

### Any Texture Packs? (If so list)

NVE

### CMG User ID

169263

**Comment by loganuk** [comment]
Hello AndiPoop,

Does this only happen in that interior?

Does it happen with both the shotgun and the AR equipped or either or?

**Comment by loganuk** [comment]
Happens all the time for every officer - Not just large arms weapons but shotguns too.

**Comment by rubbertoe98** [comment]
Fixed
