### ISSUE TITLE
[Bug]: New Island wont load in.

### ISSUE THREAD

**Issue by Sicko5M** [CMGStudios/issue-tracker#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I come down the bridge of the new island and theres no road after that, i only see houses and some grass that i cant walk on, i tried restarting, clearing cache, reinstalling and changing settings to normal, nothing worked.

### Expected behaviour

Island loading in
![Screenshot (88)](https://user-images.githubusercontent.com/89050766/129648864-ae7df53a-91ab-4189-a318-068d11c4d198.png)

### Steps to reproduce

N/A

### Any Texture Packs? (If so list)

none atm (i deleted them after reinstalling the game)

### CMG User ID

128253

**Comment by loganuk** [comment]
This is likely a client side issue on your system and not a server side bug.

If it was a server side code bug, it would not be loading for any player consistently. - I suspect you may have a broken cache or you'll need to check your graphics settings for extended texture budget.

When you next do technical fixes make sure you are not logged in at the island - Go away from it.

Please refer to #game-support on the CMG Discord for issues like this as well.
