### ISSUE TITLE
[Bug]: Casino is rigged

### ISSUE THREAD

**Issue by zaythademon** [CMGStudios/issue-tracker#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Everytime i gamble casino is fucking me over on 13 and if I stand he goes from 2 to 20 but if i hit i get 23 I've tried both tables and its the same pls check if its broken or not bc this is so annoying its happened to me for the past week on highrollers and the other table.

### Expected behaviour

Fix this please

### Steps to reproduce

??

### Any Texture Packs? (If so list)

None

### CMG User ID

222917

**Comment by arthur-rl** [comment]
Just sounds like you have bad luck.
