### ISSUE TITLE
[Bug]: Garages 

### ISSUE THREAD

**Issue by lokiiq** [CMGStudios/issue-tracker#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Started occurring yesterday, asked in a few chats and it’s not just my game. Garages are taking 5-6 seconds to show/work? Never used to be this laggy since a few days ago. Same with the UI of a house storage, takes a while to work/show.

### Expected behaviour

The garages to be quick, and smooth. (Like normal)

### Steps to reproduce

1. Drive to a garage.
2. Try and find it as it doesn’t load in for a while.

### Any Texture Packs? (If so list)

No

### CMG User ID

170443

**Comment by loganuk** [comment]
I can confirm this is a current issue and it does not affect just garages it affects any circle with a context menu - Including arms / faction clock offs - Seems everything UI related has a significant delay now.

**Comment by lokiiq** [comment]
any update?

**Comment by rubbertoe98** [comment]
Fixed from next restart.
