### ISSUE TITLE
[Bug]: Weapons not going off back when clocking off PD.

### ISSUE THREAD

**Issue by AndiPoop** [CMGStudios/issue-tracker#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When clocking off from PD, weapon models are still displayed on your character despite all weapons being cleared from inventory. Also, when trying to change gender to fix it, it does not work anymore and the model continues to stay.
Not just me this has been happening to and it gets quite annoying.
https://youtu.be/nOaz_OAjMJk

### Expected behaviour

When clocking off, weapon models should be removed from character.

### Steps to reproduce

1. Clock on PD.
2. Get a Shotgun/SMG/AR/Sniper.
3. Equip it
4. Clock off

### Any Texture Packs? (If so list)

NVE

### CMG User ID

169263

**Comment by loganuk** [comment]
Confirmed this is a problem affecting quite a few players and causing issues of "Initiation" because of the visual glitch.

**Comment by loganuk** [comment]
Issue is affecting a lot more than just PD members as well - See screenshot.

![Weapon Bug](https://user-images.githubusercontent.com/47579821/130283357-095edd81-4ffd-4fa5-8aeb-42921726f04e.PNG)

**Comment by JunctionNinja** [comment]
I too have this after I get rid of weapons/have them seized. I have had this with melees too.

Luckily never been initiated on for it but I have been arrested because of it.

**Comment by dann123321** [comment]
im not on pd never have been so how do i have this shotgun on me?

**Comment by rubbertoe98** [comment]
Fixed from next restart.
