### ISSUE TITLE
[Bug]: Going Under the Map After Being Sent to Prison Won't Spawn You In The Bus

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically, if you get sent to prison and you fall under the map, you won't be situated into the bus. This is especially annoying when you have low performance (such as low/mid-range hardware at lets say 9PM (when the server is usually at its peak).

Alternatively, if you get back to the top before the bus actually sets off, you can steal the bus (others plays cannot see this).

I myself have encountered this way too many times.

(A fix is to situate you in the bus straight away instead of making you get into the bus, however the bus may fall under the map.)

### Expected behaviour

Supposed to act as normal on most "alright" hardware.

### Steps to reproduce

1. Get sent to prison on a "meh" GPU while the server isn't performing well.
2. You shall fall under the map before you get into the bus.

### Any Texture Packs? (If so list)

Some Working FPS Booster Pack I found on YT

### CMG User ID

194575

**Comment by alfiellds** [comment]
Hello JunctionNinja, are you please able to provide a clip of this issue occuring?

**Comment by JunctionNinja** [comment]
My game has been running a bit smoother and I haven't had it since. 

I'll try and get you a clip when I can.

**Comment by alfiellds** [comment]
Closed due to inactivity and issuing being resolved. Please open another bug report if the issue persists.
