### ISSUE TITLE
[Bug]: Cant take shoes off using Y menu

### ISSUE THREAD

**Issue by glazah** [CMGStudios/issue-tracker#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

cant take my shoes off using the Y menu , instead it equips other shoes

### Expected behaviour

Fix it

### Steps to reproduce

Firm it and wear shoes

### Any Texture Packs? (If so list)

no

### CMG User ID

154357

**Comment by loganuk** [comment]
Add a POV of this happening please.
