### ISSUE TITLE
[Bug]: everytime i go to get a car out at prison garage it fucks my garages and no longer lets me access the garages around the map untill i restart multiple times or clear my cache

### ISSUE THREAD

**Issue by zLumGG** [CMGStudios/issue-tracker#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

everytime i go to get a car out at prison garage it fucks my garages and no longer lets me access the garages around the map untill i restart multiple times or clear my cache

### Expected behaviour

garages not working after trying to use the one at prison

### Steps to reproduce

go to prison go to the garage then it doesnt work then go to another garage on the map and now that wont work either

### Any Texture Packs? (If so list)

NEVEK -FPS

### CMG User ID

159003

**Comment by alfiellds** [comment]
Hello, thank you for the report. Are you able to provide a clip of this issue occurring - please include your F8 console after using the prison garage?

@Atzue

**Comment by alfiellds** [comment]
Closed due to inactivity.
