### ISSUE TITLE
[Bug]: Text UI

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The impound UI says 25k but its 10k

### Expected behaviour

![image](https://user-images.githubusercontent.com/36340714/130326853-37e47d71-50da-4b66-b95b-74e2e42b6349.png)

### Steps to reproduce

Go to impound

### CMG User ID

168906

**Comment by alfiellds** [comment]
Hello, this issue has been fixed for the next 3PM restart.
