### ISSUE TITLE
[Bug]:  spawning in air and taking damage

### ISSUE THREAD

**Issue by YoungGrubcio** [CMGStudios/issue-tracker#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i joing the server or go out of an interior i spawn in air and my parachute tries to open i fell and take damage 

### Expected behaviour

Takind damage and waisting a parachute

### Steps to reproduce

Have a parachute in inventory.
Spawn in/or go out of an interior

### CMG User ID

218830

**Comment by alfiellds** [comment]
Hello, is this issue still occurring? If so, could you please provide information regarding the hardware in your PC?

**Comment by alfiellds** [comment]
Closed due to inactivity. If the issue persists please open another bug report.

_For future reference please keep an eye on your report in case we need any further information._
