### ISSUE TITLE
[Bug]: rs7 glitch with paint on car

### ISSUE THREAD

**Issue by kai1046** [CMGStudios/issue-tracker#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my auldi rs7 as i move my camera the camo changes its very annoying and the spawn code is rs72020

### Expected behaviour

can you just fix it so its like every other car with the paints please

### Steps to reproduce

.

### Any Texture Packs? (If so list)

.

### CMG User ID

197818

**Comment by arthur-rl** [comment]
Please fill in the required information. Instead of putting a full stop. And re answer the `Expected behaviour` question.

Thanks.

**Comment by alfiellds** [comment]
Closed due to inactivity for 7 days.
