### ISSUE TITLE
[Bug]: Random Entity in middle of the road

### ISSUE THREAD

**Issue by MrMikeyTV** [CMGStudios/issue-tracker#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Near the MLO Building near Vinewood, there is a random chip in the middle of the road that we crash into on a daily basis

https://media.discordapp.net/attachments/846388394333962251/878865807717830726/unknown.png?width=1202&height=676

### Expected behaviour

To be able to drive through the road easily

### Steps to reproduce

1. Head to the house next to vinewood and use your car to find it

### Any Texture Packs? (If so list)

None

### CMG User ID

604

**Comment by MrLexo** [comment]
Thanks for the report @MrMikeyTV, I will get this fixed :)

**Comment by MrLexo** [comment]
Fixed.
