### ISSUE TITLE
[Bug]: Rims turning back to stock when i respawn my car.

### ISSUE THREAD

**Issue by wapitie** [CMGStudios/issue-tracker#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i went to the customization place i wanted to change my rim and rim colour. so I looked for some rims and bought I couple of them. when I equipped the rim nothing weird happened but after storing my car and respawning it my rims were back to stock. i can still equip the rims again because I bought them and they showed up as bought in the customization menu but every time I try to respawn my car they go back to stock. I think this bug is only happening to a couple of cars that are in the game as my Bmw 750li has no issue spawning with the changed rims. the car I tried changing the tires on are the Audi rs7 and the Lamborghini Veneno. i only tried rims of the sports and highend class so I have no idea if other rims work.

### Expected behaviour
Rims Don't change back to stock when I respawn my car

### Steps to reproduce

1. change the rims of your car 
2. change the colour of the rims
3. take your car for a small drive and then store it
4. respawn the car

### CMG User ID

223939

**Comment by loganuk** [comment]
Can you take a clip of this for me @wapitie

**Comment by wapitie** [comment]
i will try to get a clip, sorry for the late respondse

**Comment by wapitie** [comment]
https://youtu.be/A1hPqfK1Sgw
Clip of the bug

**Comment by alfiellds** [comment]
Closed due to invalid clip.
