### ISSUE TITLE
[Bug]: Issues with metallic secondary colours on cars

### ISSUE THREAD

**Issue by MrParkerCMG** [CMGStudios/issue-tracker#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Had a look through and I know this has been happening since day one for me but you are unable to apply any metallic secondary colour. Once applied, if you put the car away and respawn the car, the secondary colour disappears from the main paint job. Would be great to be able to customise and adjust your cars with metallic colours to make them two-tone is possible for this to be fixed? The only way to get metallic on your car at the moment is to have it permanent in the car file which isn't ideal. 

Thanks

### Expected behaviour

Car should apply the secondary colour and stay two-tone once car has been respawned from the garage.

### Steps to reproduce

1. Enter a Pay & Spray
2. Chose first colour
3. Choose secondary colour as metallic
4. Apply the change and leave the garage
5. Drive to a garage and attempt to respawn the car
6. Metallic colour has gone.

### Any Texture Packs? (If so list)

no

### CMG User ID

306

**Comment by MrParkerCMG** [comment]
little video to see it

**Comment by MrParkerCMG** [comment]
https://streamable.com/2skzc1

**Comment by loganuk** [comment]
This issue is linked to https://github.com/CMGStudios/issue-tracker/issues/169 - So I am going to copy paste your detail Parker and close this issue.
