### ISSUE TITLE
drop not showing when you log in after the reveal

### ISSUE THREAD

**Issue by ynzkdc** [CMGStudios/issue-tracker#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

basically when you log in after the dropredzone has been revealed it wont show on your map

### Expected behaviour

.

### Steps to reproduce

,

### Any Texture Packs? (If so list)

none

### CMG User ID

287

**Comment by arthur-rl** [comment]
You've provided us with little to no info about this. Please fill in the **required** options.

**Comment by alfiellds** [comment]
Closed due to inactivity for 5 days.
