### ISSUE TITLE
[Bug]: NHS MotorBike SeatBelt Sound

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using The NHS MotorBike It makes the sound of not turning on the seatbelt feature which shouldnt be happening since there are no seatbelts.

### Expected behaviour

When Using the Bike This Sound Should Not be Happening since there are no seatbelts.

### Steps to reproduce

Get the NHS MotorBike from the Garage (SpawnCode: nhsbike)
Listen Closely for the sound.
Clip Here:
https://streamable.com/9mdnq1

### Any Texture Packs? (If so list)

No Packs

### CMG User ID

71613

**Comment by loganuk** [comment]
Hello Zenabbs,

This is not a script bug but a specific bug with that vehicle - I.e something in the car file - So something for a car dev.
