### ISSUE TITLE
Speed limiter not working[Bug]: 

### ISSUE THREAD

**Issue by luke3005** [CMGStudios/issue-tracker#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you try to set speed limiter, it does not work

### Expected behaviour

To Put your limit to the speed limiter

### Steps to reproduce

Get in a car try to set a speed

### Any Texture Packs? (If so list)

RESHADER

### CMG User ID

3005

**Comment by dann123321** [comment]
im not on pd

**Comment by thomas-m04** [comment]
Thank you for this report, it has now been fixed.
