### ISSUE TITLE
[Bug]: Rock collision issue at MLO

### ISSUE THREAD

**Issue by AshyCMG** [CMGStudios/issue-tracker#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://streamable.com/m9va0b - Can walk into the rock - hide and shoot from it 

### Expected behaviour

https://snipboard.io/GCIoSr.jpg 
https://streamable.com/m9va0b 

### Steps to reproduce

Just walk there. 

### Any Texture Packs? (If so list)

None

### CMG User ID

80085

**Comment by MrLexo** [comment]
Fixed.
