### ISSUE TITLE
[Bug]: LFB Unplayable - hose bug

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

LFB Fire Hose Doesn't Spray Water Due To A Lua Script Error The Fire Hose Is Currently Unusable with Both LFB Vehicles.

### Expected behaviour

After Setting up the supply Line in /LFB>Water>Setup Supply Line and Pressing enter to connect to the supply Line you should be able to infinetly spray water.

### Steps to reproduce

1. Clock on as any LFB Rank.
2. Pull any LFB Vehicle From a Garage
3. Use /LFB>Wate>Setup Supply Line.
4. Press enter on the Vehicle to connect to the supply Line.
5. Attempt to spray water with the hose.

Video Evidence Here:
https://streamable.com/vti949

### Any Texture Packs? (If so list)

Redux

### CMG User ID

71613

**Comment by zenabzz** [comment]
Still not working After 3 Days.

**Comment by alfiellds** [comment]
Hello, zenabzz, thank you for the report, this will be reviewed by the developers.

**Comment by rubbertoe98** [comment]
Fixed.
