### ISSUE TITLE
[Bug]: Bolt cutters issue.

### ISSUE THREAD

**Issue by daleric-xyz** [CMGStudios/issue-tracker#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using bolt cutters on a house when the owner of the house is not online removes the bolt cutters without returning them, or providing an error that the house can't be broken into.

### Expected behaviour

Bolt cutters not removed from inventory, or returned after online check has occurred.

### Steps to reproduce

1. Pick a house with no online owner
2. Try to break into it
3. Bolt cutters are removed from inventory without breaking into house

### CMG User ID

395

**Comment by rubbertoe98** [comment]
Fixed from next server restart.
