### ISSUE TITLE
Bug: G4S Job - kidnap and killed - job still there after respawning

### ISSUE THREAD

**Issue by dsme94** [CMGStudios/issue-tracker#183]
I was completing a G4S job and was asked to pull over by a gang. 

The gang kidnaps me and shortly after shoots me.

Respawned with the job still active, returned to my G4S vehicle but can't continue with the job.

The vehicle boot can't be opened as it's not owned by me.

![Screenshot_1](https://user-images.githubusercontent.com/24738535/131192303-00a58d3f-076b-4e52-a136-bc5a361a2487.png)

**Comment by loganuk** [comment]
Have you got a clip of this taking place please?

**Comment by alfiellds** [comment]
Closed due to inactivity.
