### ISSUE TITLE
[Bug]: Cannot Sell CMG Platinum Days

### ISSUE THREAD

**Issue by CharlzCMG** [CMGStudios/issue-tracker#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It doesn't let me sell my platinum days I have 7 left and haven't claimed my weekly kit. And it doesn't give me the blue screen on my right to sell them. #

### Expected behaviour

Doesn't let me sell platinum days.

### Steps to reproduce

uhm what does this mean

### Any Texture Packs? (If so list)

Tyler Pack

### CMG User ID

203711

**Comment by alfiellds** [comment]
Hello Charlz, thank you for the report. Could you please provide a screenshot of the error which you received upon trying to sell your platinum days?

Many thanks.

**Comment by alfiellds** [comment]
Closed due to inactivity.
