### ISSUE TITLE
[Bug]: stuck in the boot of the car when locked and person dies 

### ISSUE THREAD

**Issue by Cryptiicxxx** [CMGStudios/issue-tracker#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when in the boot of a car and the owner of the car dies you are stuck in the boot of the car cannot type in ooc the only way to get out is to relog or to wait for car cleanup which is long 

### Expected behaviour

^^^

### Steps to reproduce

idk get in the car when it locked and it stuck after the person dies ?

### Any Texture Packs? (If so list)

no 

### CMG User ID

182018

**Comment by loganuk** [comment]
Confirmed bug - Various issues with the boot being permanent

**Comment by rubbertoe98** [comment]
Fixed from next restart.
