### ISSUE TITLE
[Bug]: hs sounds not working

### ISSUE THREAD

**Issue by snuffy1x** [CMGStudios/issue-tracker#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Headshot sounds in the f2 menu doesnt not function, i've found out this happens to many other people i have tried relogging with it off / turning it on and off nothing seems to fix the issue

### Expected behaviour

there is no headshot audio with hs sounds on 

### Steps to reproduce

/??????

### Any Texture Packs? (If so list)

NVE

### CMG User ID

178209

**Comment by arthur-rl** [comment]
Please fill in the `Steps to reproduce`
