### ISSUE TITLE
[Bug]: Staff Have Gave Me Groups For NHS AND HMP But When I Relog They Dont Save-

### ISSUE THREAD

**Issue by Caz-Developer** [CMGStudios/issue-tracker#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically Staff Have Tried Giving Me Groups But When I Relog They Disapear 

### Expected behaviour

I get the group and can clock on

### Steps to reproduce

1. staff gives (me) group
2. i relog
3. groups gone

### Any Texture Packs? (If so list)

n/a

### CMG User ID

113291

**Comment by arthur-rl** [comment]
You need the discord roles.

**Comment by Caz-Developer** [comment]
when i have the role in discord?
