### ISSUE TITLE
[Bug]: Long Range Blip's Now Working

### ISSUE THREAD

**Issue by YoFlqme** [CMGStudios/issue-tracker#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have bought long range blips from the licence shop and they worked for a few hours when i clocked on however i clocked of for a hour and clocked back on and they don't work, i have tried to re log and do many other things many of times and nothing seems to work.

### Expected behaviour

Long Range Blips Not Working at all

### Steps to reproduce

Not too sure

### Any Texture Packs? (If so list)

N/A

### CMG User ID

550

**Comment by loganuk** [comment]
I am assuming you are a PD member?

Is this issue affecting just you or anyone else?

Do you have a clip of this not working?

**Comment by alfiellds** [comment]
Closed due to inactivity.
