### ISSUE TITLE
[Bug]: Car disappearing when u enter METH PROCESS

### ISSUE THREAD

**Issue by Gooooold** [CMGStudios/issue-tracker#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dont know if its just me, but when i enter meth process, i come out and my cars gone, happens 9 times out of 10, (they are not getting removed due to car / entity wipe) just a weird and annoying thing to deal with when grinding

### Expected behaviour

Dont know if its just me, but when i enter meth process, i come out and my cars gone, happens 9 times out of 10, (they are not getting removed due to car / entity wipe) just a weird and annoying thing to deal with when grinding

### Steps to reproduce

1. enter meth 
2. process meth
3. exit meth
4. car gone

### Any Texture Packs? (If so list)

none

### CMG User ID

193641

**Comment by loganuk** [comment]
Tested and does happen to this job.

**Comment by tom-gun** [comment]
Thanks for the report - Closing as this is due to no player being near the vehicle and it de-spawning naturally. This will be fixed in the future when we refactor how we create vehicles.
