### ISSUE TITLE
[Bug]: headshot sounds not functioning

### ISSUE THREAD

**Issue by snuffy1x** [CMGStudios/issue-tracker#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the F2 settings menu the hs sounds option does not work and the sounds never occur 

### Expected behaviour

When you click f2 and try to enable hs sounds it doesn’t work and when I try everything such as relog W it off and turn it on and off etc . I think this definitely should be given a lot of attention to as I have asked others and it never seems to work for them either and such admins do not know how to resolve this

### Steps to reproduce

Press f2 
Enable headshot sounds

### Any Texture Packs? (If so list)

NVE

### CMG User ID

178209

**Comment by loganuk** [comment]
Have you got a clip of this taking place so we can see :)

**Comment by loganuk** [comment]
Original issue raised with missing steps: https://github.com/CMGStudios/issue-tracker/issues/191

**Comment by snuffy1x** [comment]
> Have you got a clip of this taking place so we can see :)

i will upload one now

**Comment by snuffy1x** [comment]
> Have you got a clip of this taking place so we can see :)

https://streamable.com/xvotvj

**Comment by rubbertoe98** [comment]
Have you got your FiveM chromium process muted or volume all the way down?

**Comment by alfiellds** [comment]
Closed due to inactivity.
