### ISSUE TITLE
[Bug]: Car drives through walls

### ISSUE THREAD

**Issue by Nublar0** [CMGStudios/issue-tracker#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My 1:16 non cat drives straight through walls and if it flips it falls straight under the map it has the spawn code lr100

### Expected behaviour

it to work like a normal car

### Steps to reproduce

1. spawn it with the code lr100
2. drive at a wall at like 30 mph and it will drive straight through

### Any Texture Packs? (If so list)

Reshade 

### CMG User ID

208124

**Comment by alfiellds** [comment]
Hello, you need to raise your concerns regarding this vehicle via a car developer.

A bug report is not a place to request a vehicle buff.
