### ISSUE TITLE
[Bug]: Applying multiple backpacks

### ISSUE THREAD

**Issue by Drkiller99** [CMGStudios/issue-tracker#194]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

First of all, I'm not expecting any comp for this especially since boot wipe is today. 

I had a rebel and a green hiking backpack on me and pressed use on them both due to double-clicking and they both applied used /storebackpack and only got one back 

### Expected behaviour

A return message stating I already had a backpack applied and that I can only use one at a time.

### Steps to reproduce

Apply two backbacks

### Any Texture Packs? (If so list)

No

### CMG User ID

222259

**Comment by rubbertoe98** [comment]
Fixed from next restart.
