### ISSUE TITLE
[Bug]: Mistaken whitelist abuse

### ISSUE THREAD

**Issue by Drkiller99** [CMGStudios/issue-tracker#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm not sure if this happens on server one, however, it happens a lot to MADCAP when logging online it shows on users home menus that he's clocked on as PD even when he's not (proven by the "#status" channel in discord showing he's not actually clocked on.  

Picture: https://i.imgur.com/EWqKFN3.png
Date for logs: 08/24/2021  | 9:57 AM

### Expected behaviour

Only show he's online and not clocked on as police.

### Steps to reproduce

1. Log on server two
2. Press 'home'
3. See if it shows for you or just others.

### Any Texture Packs? (If so list)

No

### CMG User ID

222259

**Comment by Drkiller99** [comment]
Only one I could find similar to this was: https://github.com/CMGStudios/issue-tracker/issues/158

**Comment by alfiellds** [comment]
This is a visual issue with the home menu which rarely occurs (and doesn't necessarily occur for all players at the same time). 

I will put this to be reviewed by developers. Thank you for the report.

**Comment by Drkiller99** [comment]
Oh sorry, it's just something that's rare around CMG and hasn't happened recently.

**Comment by alfiellds** [comment]
Seems to happen quite often for NHS especially when there's more online.

Probably why it's quite rare.
