### ISSUE TITLE
[Bug] /interops and /tacops

### ISSUE THREAD

**Issue by Heaton3** [CMGStudios/issue-tracker#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the in game commands to move members from normal radio channels to either an interop or tacop channel, they are not moved correctly due to an error displayed in game.
![image](https://user-images.githubusercontent.com/58630078/131643382-93b83b93-6e86-4125-bd3d-360f1c10cfd1.png)

### Expected behaviour

After using a /interops or /tacops the user should be moved from their current channel, to a new channel.

### Steps to reproduce

In game, type /interops or /tacops

### Any Texture Packs? (If so list)

Nope

### CMG User ID

9

**Comment by alfiellds** [comment]
Hello Heaton, thank you for the report. When you received this error did you have your callsign in your TeamSpeak username (as formatted on the roster, including capitalisation)?

**Comment by Heaton3** [comment]
Hey Alfie,

Yes, yes it did! It's previously worked, and it no longer works for anyone...  I suspect something has happened with the query that runs in TS.

Thanks,

________________________________

**Comment by crazychris2404** [comment]
This is no longer relevant due to future changes and will just need removing from ingame once there are new additions
