### ISSUE TITLE
[Bug]: Phone contacts blank

### ISSUE THREAD

**Issue by MuriDubs** [CMGStudios/issue-tracker#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open my phone and contacts list it is completely blank. I factory reset the phone and readded a contact and it happened again almost instantly. 

### Expected behaviour

When I open the contacts list it should display my saved contacts. 

### Steps to reproduce

Simply open the contacts list

### Any Texture Packs? (If so list)

None

### CMG User ID

226191

**Comment by alfiellds** [comment]
Hello, thank you for the report. Could you please provide a clip of this occurring @MuriDubs ?

**Comment by loganuk** [comment]
No follow up in 13 days - Closing issue.,
