### ISSUE TITLE
[Bug]: ALT bug

### ISSUE THREAD

**Issue by ReviloCMG** [CMGStudios/issue-tracker#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When in water 'swimming; and you press ALT whilst on PD its kills you insta

### Expected behaviour

You die when you press ALT in water.

### Steps to reproduce

Swim in water, whilst clocked onto PD, then simply press ALT when swimming.

### CMG User ID

135

**Comment by alfiellds** [comment]
Could you please provide a clip of this issue occuring? @ReviloCMG

**Comment by loganuk** [comment]
I've asked if any PD members can test this - Will close issue in 24 hours if no response by then.

**Comment by loganuk** [comment]
https://streamable.com/bah1en

Confirmed bug

**Comment by rubbertoe98** [comment]
Fixedfrom next restart.
