### ISSUE TITLE
[Bug]: You can CPR finished people

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Pretty much what it says on the tin but you can revive someone who is fully finished off via CPR and they will act normal again with no side effects (besides of course the injured walk and revived visual effects etc.).

### Expected behaviour

Should just not let you get the person up from being dead.

### Steps to reproduce

1. Find a fully finished off person
2. Press E on them and then click on the CPR option.
3. Keep repeating step 2 until you revive the person (may take many tries but you will get it eventually if they don't respawn).

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by alfiellds** [comment]
Confirmed - this will be reviewed by the developers. Thank you for the report.

**Comment by rubbertoe98** [comment]
Fixed from next restart.
