### ISSUE TITLE
[Bug]: Trucker job, several issues. 

### ISSUE THREAD

**Issue by SmugSug** [CMGStudios/issue-tracker#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Bug #1: Can't start a job if you own one of the trucks that you can buy/already own a baller locked truck. You have to rent one first to be able to start the job.   

Bug #2: Cannot finish trucker job with a baller locked truck. It'll say "You do not own or rent this vehicle", and softlock itself.

### Expected behaviour

Allow one to use an already bought/baller locked truck to start a job. 
Allow one to finish a job with a baller locked truck.

### Steps to reproduce

Bug #1: 
1. Employ as a lorry driver.
2. Own a buyable truck for the job. (from the truck shop outside the workplace at the docks)
3. Try starting the job without renting a truck first. 
4. It'll say you can't start the job because you do not own or rent any trucks. 

Bug #2:
1. Employ as lorry driver.
2. Rent a truck, pull out your baller locked truck (to fix bug#1) 
3. Start a job and drive to marked location.
4. Attempt to finish it.

### CMG User ID

123310

Video of Bug#2 listed in this thread. 
https://streamable.com/8la8xt

**Comment by SmugSug** [comment]
Has there been any updates on this? Understandable if not with the low priority and all.

**Comment by crazychris2404** [comment]
Thanks for contacting me about this issue. I confirm developers are still looking into the problem.
