### ISSUE TITLE
[Bug]: When Clocked On PD, You Can Not Store Weapons.

### ISSUE THREAD

**Issue by Ghast1k** [CMGStudios/issue-tracker#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ok so, I am on a custom assault rifle whitelist for PD, and I sometimes store them to give to friends, however after restart this has become impossible as when i go to store the weapon, it doesn't store, yet I get the cooldown. Has this issue in the F8 Console
![Bug Report](https://user-images.githubusercontent.com/90056150/132037417-d377e6f0-8796-4160-a89a-48721cdea340.png)

### Expected behaviour

The weapon to store and be in my L inventory

### Steps to reproduce

Purchase any weapon from the PD armory, try and store it by doing /storeallweapons

it may work once after relogging but not any time after

### Any Texture Packs? (If so list)

No

### CMG User ID

621

**Comment by BigBoyReece** [comment]
Is is possible for you to make a clip of this happening to you.

**Comment by Ghast1k** [comment]
Yeah, bear with me 1 second i will try and get one.

**Comment by Ghast1k** [comment]
https://streamable.com/dd4cz4

**Comment by rubbertoe98** [comment]
Fixed from next restart.
