### ISSUE TITLE
[Bug]: Camrea E>Interact Menu

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Pressing E to Use the New Camera and you're stood close to someone It brings up the E-Interaction Menu.

### Expected behaviour

Disable The E>Interact Menu When Using one of the News Features: Camera, Boom arm, Microphone.

### Steps to reproduce

Use Camera/Boom arm/Microphone
Press E When stood next to a person
Video: https://streamable.com/1a1fw3

### CMG User ID

71613

**Comment by alfiellds** [comment]
Hello zenabz, thank you for the report. This issue is extremely easy to both prevent and fix if it occurs and therefore this will not be fixed. You can simply resolve this by not looking at a player when changing into RECORDING mode.
