### ISSUE TITLE
[Bug]: Recording mode is a bit higher than the camera

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the camera, the angle is a bit higher than what it should be.

It's one of those attention to detail things but buggers me and could do a few others.

Little video of it:
https://streamable.com/h7bjv2

### Expected behaviour

Camera is where it should be and not higher.

### Steps to reproduce

1. Get camera
2. Use camera
3. Press "E" to have the overlay and camera
4. Observe that it is higher than it should.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by alfiellds** [comment]
Hello, thank you for the report. This will be reviewed by the developers and changed shortly.

**Comment by JunctionNinja** [comment]
Perfect.
