### ISSUE TITLE
Buying double of stuff at large arms

### ISSUE THREAD

**Issue by luke3005** [CMGStudios/issue-tracker#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I dont use it but i went to large and bought lvl 2 armour, i clicked enter twice and it bought 2 armours leaving me on 0 cash and 50% armour

### Expected behaviour

For when u got armour it not to take out of account

### Steps to reproduce

Go to large get money and click enter more than once

### Any Texture Packs? (If so list)

reshade

### CMG User ID

3005

**Comment by loganuk** [comment]
Sadly the solution is don't click enter twice.

I've been in such a rush I did the same with rebel armour at lvl 4 (That was painful for the wallet)
