### ISSUE TITLE
[Bug]: Phone number broken

### ISSUE THREAD

**Issue by max186x** [CMGStudios/issue-tracker#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My phone number isn't working - its just #'s and I've reset it multiple times and it still doesn't work. here's a lightshot with the picture - https://prnt.sc/1r7htvz

### Expected behaviour

^

### Steps to reproduce

not sure how to reproduce - seems to be only me

### Any Texture Packs? (If so list)

.

### CMG User ID

128373

**Comment by loganuk** [comment]
Could be an isolated issue with just this player

**Comment by max186x** [comment]
so can it get reset?

**Comment by Drkiller99** [comment]
If you’re still having this issue, I believe you should contact @crazychris2404 who can put it through for the relevant people to help you.

**Comment by crazychris2404** [comment]
@arthur-rl Could you look into this as user specific

**Comment by crazychris2404** [comment]
No longer a active issue.
