### ISSUE TITLE
[Bug]: handcuffs dont work from rebel 

### ISSUE THREAD

**Issue by lewisfinlay12** [CMGStudios/issue-tracker#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

handcuff issue 

### Expected behaviour

when i try to handcuff a player it says given handcuffs but the player doesnt get cuffed 

### Steps to reproduce

go rebel buy handcuffs 
click use on player, it says given handcuffs 

### Any Texture Packs? (If so list)

none

### CMG User ID

104

**Comment by loganuk** [comment]
Handcuffs and handcuff keys have been glitchy for some time - Moved to next step.

**Comment by rubbertoe98** [comment]
Fixed.
