### ISSUE TITLE
[Bug]: headshot sounds not working

### ISSUE THREAD

**Issue by snuffy1x** [CMGStudios/issue-tracker#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the F2 settings menu the hs sounds option does not work and the sounds never occur

### Expected behaviour

When you click f2 and try to enable hs sounds it doesn’t work and when I try everything such as relog W it off and turn it on and off etc . I think this definitely should be given a lot of attention to as I have asked others and it never seems to work for them either and such admins do not know how to resolve this

I do have a clip for evidence 

https://streamable.com/xvotvj

### Steps to reproduce

Press f2
Enable headshot sounds
 shoot somebody 

### Any Texture Packs? (If so list)

no

### CMG User ID

178209

**Comment by loganuk** [comment]
Is that the same for just the Mosin or on every gun?

What happens when you test it on someone who does not have god mode?

**Comment by alfiellds** [comment]
Closed due to inactivity.
