### ISSUE TITLE
[Bug]: Gun sticks out though car

### ISSUE THREAD

**Issue by winte-rrr** [CMGStudios/issue-tracker#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

a scoped sniper or mosin bugs through the roof of most cars - https://streamable.com/ycpby2

### Expected behaviour

a scoped sniper or mosin bugs through the roof of most cars 

### Steps to reproduce

put a sniper on back and drive in a car

### CMG User ID

94

**Comment by loganuk** [comment]
Grand Theft Auto was not designed to have visible weapons on backs - So some gun models are tall enough to clip through.

Use /storeallweapons before getting into a vehicle - You could also invest in bigger vehicles.
