### ISSUE TITLE
[Bug]: Microphone working on push to talk when my bind isn't pressed.

### ISSUE THREAD

**Issue by Lynchye** [CMGStudios/issue-tracker#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Microphone working on push to talk when my bind isn't pressed. I know it sounds weird but I have rebound it another key/mouse button still the same issue. I have change my microphone to see if that was it, nothing. Relogged didn't effect it either. I have searched the issue, someone else had the issue, Andrew Logan responded but they didn't respond back.

### Expected behaviour

When the push to talk bind I should be able to talk not like I'm on a permeant voice activity.

### Steps to reproduce

1. Talk as normal.

### Any Texture Packs? (If so list)

Private One

### CMG User ID

356

**Comment by loganuk** [comment]
It sounds like an issue with your local binds/game settings.

Please visit #game-support on the CMG Discord to see if someone can help you with this.
