### ISSUE TITLE
Can't verify new Discord account to FiveM account[Bug]: 

### ISSUE THREAD

**Issue by xRhys** [CMGStudios/issue-tracker#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have previously linked my old Discord account (banned) to my FiveM account. This has led me to being unable to verify my new account to my FiveM account - This is most likely not a bug and is something that I am doing retarded but someone help me, please xxx

### Expected behaviour

Issue is written above

### Steps to reproduce

Not reproducable 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

125898

**Comment by loganuk** [comment]
This is not a server bug - This is not the purpose of this bug reporting system.

Please seek help from TeamSpeak / Forums if you cannot get onto the Discord.
