### ISSUE TITLE
[Bug]: Sometimes in killfeed now weapon image show's up as an empty file like it's been deleted.

### ISSUE THREAD

**Issue by jack-cmg** [CMGStudios/issue-tracker#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/90296780/132436079-124f5c2b-640b-41b2-aef1-08dab8cd4217.png As you can see the weapon image seems like it has been deleted sort of?

### Expected behaviour

Weapon image should show up normal

### Steps to reproduce

Not sure yet

### Any Texture Packs? (If so list)

N/A

### CMG User ID

182889

**Comment by rubbertoe98** [comment]
Fixed
