### ISSUE TITLE
[Bug]: Can use phone in prison nowhere near the booths with /cmgphone

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Literally what it says on the tin. Quite simple.

### Expected behaviour

Shouldn't let you do it (not near phone booths).

### Steps to reproduce

1. Go to prison 
2. Do /cmgphone anywhere in prison

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by rubbertoe98** [comment]
Fixed from next restart.
