### ISSUE TITLE
[Bug]: Take A Turf You Aren't Currently Present In

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically, I took the coke trader and failed because someone needed help. I decided to take one of the other traders and that stopped after about 80 seconds and took coke, which I was nowhere near (this screenshot shows):

![image](https://user-images.githubusercontent.com/62995181/132978921-91c76bbf-58c0-49c3-9a56-3447d540e669.png)

### Expected behaviour

I should be able to take the other turf without the one I took first.

### Steps to reproduce

1. Attempt to take any turf
2. Fail the turf (by leaving the area etc.)
3. Go take another one when there is time left.
4. You have successfully taken the turf you were present at a few minutes ago

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by rubbertoe98** [comment]
Fixed from next restart.
