### ISSUE TITLE
[Bug]: Not being able to cancel rent on houses 

### ISSUE THREAD

**Issue by Rostance0151** [CMGStudios/issue-tracker#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can not cancel rent when renting a house 

### Expected behaviour

Should be able to cancel the rent 

### Steps to reproduce

Go up to house door and press cancel rent 

### Any Texture Packs? (If so list)

nve 

### CMG User ID

719

**Comment by arthur-rl** [comment]
Not a bug.

**Comment by loganuk** [comment]
POV of this not working would help a lot if you can get that please.

**Comment by Rostance0151** [comment]
Sorry for the late reply
https://youtu.be/C-fUJJ3FDqc

**Comment by arthur-rl** [comment]
Cancelling rent on houses isn't even a feature
