### ISSUE TITLE
Game freezes then goes back to normal then 10 seconds later game crashes.

### ISSUE THREAD

**Issue by Luk3St1rrup** [CMGStudios/issue-tracker#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Literally the exact same as the title. Load into the server, can play alright for a few mins, then the game freezes for a split second then it goes back to normal for about 10 seconds then the game crashes with error ink-dakota-mountain.

### Expected behaviour

...

### Steps to reproduce

Go into CMG
Play
Freeze
Crash

### Any Texture Packs? (If so list)

https://forum.cfx.re/t/release-five-m-visual-pack-update-10-14-20/70752 that one

### CMG User ID

209460

**Comment by loganuk** [comment]
Do you crash all the time or did this just happen once?

Have you tried removing the texture pack bundle?

**Comment by Luk3St1rrup** [comment]
> Do you crash all the time or did this just happen once?
> 
> Have you tried removing the texture pack bundle?

It happens all the time. 
And no I haven't removed the texture back bundle because the crashes started about a month after I installed the texture pack.

**Comment by Luk3St1rrup** [comment]
Ive now deleted the texture pack, will update with any news

**Comment by Luk3St1rrup** [comment]
i deleted my texture pack, it allows me to stay in the game longer but i still crash.

**Comment by Luk3St1rrup** [comment]
![crash](https://user-images.githubusercontent.com/90797980/133890659-c5ad43a8-d41f-4f95-8fbe-98f12efb725f.jpg)

**Comment by Luk3St1rrup** [comment]
[CfxCrashDump_2021_09_18_17_48_57.zip](https://github.com/CMGStudios/issue-tracker/files/7190413/CfxCrashDump_2021_09_18_17_48_57.zip)

**Comment by Luk3St1rrup** [comment]
Still a persistent issue, any fixes?

**Comment by Luk3St1rrup** [comment]
turns out its a problem with fivem itself and not CMG
