### ISSUE TITLE
[Bug]: Cant use = to accept things

### ISSUE THREAD

**Issue by YIN6istheMan** [CMGStudios/issue-tracker#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For a week ive been trying to accept cars and accept people to see my id but it just doesnt work but I can type '=' in game chat and my actual keyboard is 100% fine.

### Expected behaviour

= Works for anything besides accepting things IN CMG.

### Steps to reproduce

Not sure.

### Any Texture Packs? (If so list)

No

### CMG User ID

178827

**Comment by loganuk** [comment]
It is entirely likely you have broken the default binds you have.

Please seek help in #game-support on the CMG Discord for this.
