### ISSUE TITLE
[Bug]: rent expired and i lost the ownership of my house

### ISSUE THREAD

**Issue by BigMoustache1** [CMGStudios/issue-tracker#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi , so before i left cmg i rented my ranch next to casino to el chapo for 3 months since i comeback to cmg i have been surprised that i dont have the owership of my ranch anymore even if the rent expired , This is the first time I have this problem
i guess the rent system got bugget cuz el chapo got banned within this period My perm id : 34042 discord : TheOGMrMoustache#46
![8aaf3673f37bb50c58d84077f1aa1b61ead020d2](https://user-images.githubusercontent.com/61056206/133706208-0f83dd1b-4c7e-4e8f-8926-abdd43a1b52c.jpeg)
66

### Expected behaviour

i want my ranch back Deviation know already about this issue , you can contact the guy i rented to him my ranch thats his discord : ElChapo#7016

### Steps to reproduce

maybe check if there is some issue with renting out houses longer than 30 days or if the rent get bugged when the guy who rent it to him is banned within the rent period

### CMG User ID

34042

**Comment by loganuk** [comment]
You did not search for this issue before - See this one:  https://github.com/CMGStudios/issue-tracker/issues/210

I have manually merged them but I will close this issue - The original issue is marked as high priority so I expect some action on it.

Please don't create duplicate issues as it distracts the developers from prioritising properly :)
