### ISSUE TITLE
[Bug]: Female G4S Character Reset 

### ISSUE THREAD

**Issue by BuzzyBabii1** [CMGStudios/issue-tracker#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i work for G4S in city :) each time i clock in - it changes you into the G4S uniform - when clocking out , it completely resets your character to male and dev clothing / hair / skin etc !! ive tried this a few times to make sure its not just a visual my end - but constantly keeps happening !! 

### Expected behaviour

possible script to make sure it doesnt reset or a closer changing area available to fix issue !!

### Steps to reproduce

clock in - changes character to male [regardless]
clock out - resets ALL personal areas and gender
clothing change / reset - long haul away to reset EACH and every time 

### CMG User ID

226924

**Comment by BuzzyBabii1** [comment]
hi - its default - still finding the same issue unfortunately so have
stopped doing the job until fixed :)

**Comment by alfiellds** [comment]
Hello, thank you for the report. This will be reviewed by the developers shortly.

**Comment by crazychris2404** [comment]
Confirmed Issue 
Thanks for the report.
