### ISSUE TITLE
[Bug]: Cannot fine people as PD because the ipad thing doesn't fit on screen  

### ISSUE THREAD

**Issue by MANN190929** [CMGStudios/issue-tracker#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ive tried changing resolutions and aspect ratios and even the monitor I use aswell as using windowed mode but it never fits.
https://youtu.be/FCS4ban9K9I

### Expected behaviour

The PNC to fit on the screen

### Steps to reproduce

Use `RES HERE` resolution.
Press F7

### Any Texture Packs? (If so list)

No

### CMG User ID

190929

**Comment by arthur-rl** [comment]
What resolution is your monitor?

**Comment by arthur-rl** [comment]
I would also appreciate if you filled in the required fields instead of just putting an `a`

**Comment by MANN190929** [comment]
I apologise about that I didn’t understand it and my monitor is 1680 by 1050

**Comment by zenabzz** [comment]
Anything Below the Res 1600x900 Wont work with the PD PNC

**Comment by alfiellds** [comment]
Hi, I'm aware you have found a solution, however, I'll forward this to be reviewed by the developers. Many thanks.
