### ISSUE TITLE
Y key to take clothes on/off does not work

### ISSUE THREAD

**Issue by akaTimO** [CMGStudios/issue-tracker#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i press my Y key on cmg to open the clothing wheel i can not take it on or off it just simply shows the wheel and lets me do nothing 

### Expected behaviour

when i press my Y key on cmg to open the clothing wheel i can not take it on or off it just simply shows the wheel and lets me do nothing 

### Steps to reproduce

Y key will not let me do shit 

### Any Texture Packs? (If so list)

no

### CMG User ID

223625

**Comment by TheKyle1** [comment]
This issues is still happening with me aswell, I reported this issues over 3 weeks ago. 

Here is a clip of the issues: https://www.youtube.com/watch?v=M-Xp-B6J6h4

**Comment by crazychris2404** [comment]
Closed as linked with another issue which has more detail https://github.com/CMGStudios/issue-tracker/issues/190
