### ISSUE TITLE
[Bug]: headbags from rebel 

### ISSUE THREAD

**Issue by lewisfinlay12** [CMGStudios/issue-tracker#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

head bags don't show on player and cant be removed without using 2nd head bag 

### Expected behaviour

when you head bag someone the bag does not show on there head and you cannot remove it without using another one   

### Steps to reproduce

buy head bag

press alt and b at same time while player has his hands up 

he wont be able to see out of the bag but when looking at the player you cannot see a bag 

### Any Texture Packs? (If so list)

none

### CMG User ID

111

**Comment by alfiellds** [comment]
Hello, thank you for the report. Please could you provide a video of this issue occurring so that I can forward it to the developers to review?

Many thanks.

**Comment by alfiellds** [comment]
Closed due to inactivity.
