### ISSUE TITLE
[Bug]: Cinematic Menu Zoom Weird

### ISSUE THREAD

**Issue by Lynchye** [CMGStudios/issue-tracker#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically the saving of the camera makes it zoom in a lot I have tested it with Realist, it worked fine for him but not for me. Can show if needed.

### Expected behaviour

Shouldn't zoom in as much as does.

### Steps to reproduce

1. Move camera.
2. Choose camera
3. Zooms in more than I chose.

### Any Texture Packs? (If so list)

Private One

### CMG User ID

356

**Comment by alfiellds** [comment]
Hello, thank you for the report. Please can you provide a video of an example of this issue occuring?

Many thanks.

**Comment by Lynchye** [comment]
Hello! 

Sorry for the late reply I hope this clip shows the zooming that I am on about if needs be I can go into discord and show what I mean.

https://youtu.be/jEeK9duyfjI 

Let me know if there is more I can do.

Thanks!

**Comment by crazychris2404** [comment]
I was unable to reproduce this issue myself or with someone else. Do you know if this still occurs?

**Comment by crazychris2404** [comment]
This could be caused by your FOV if still existing please open another issue. After speaking to other staff if you change to around 28-35 you wont have this issue
