### ISSUE TITLE
[Bug]: LFB Station Spawn

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The LFB Spawn Point takes you to the old Fire station, not the one currently in use at East Los santos where the LFB Clock on point is.

### Expected behaviour

Spawn at the East Los santos LFB Station the one with the LFB Clock on Point

### Steps to reproduce

1.Die
2. Respawn LFB Station

### CMG User ID

71613

**Comment by alfiellds** [comment]
Confirmed - this will be reviewed by the developers.
