### ISSUE TITLE
[Bug]: Can't pull my gun out

### ISSUE THREAD

**Issue by wapitie** [CMGStudios/issue-tracker#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when I try to use a weapon( gun or knife) It won't let me pull it out.
Clip: https://youtu.be/ABV-ev-SnnQ

### Expected behaviour

i want to be able to use my gun

### Steps to reproduce

1. buy a gun
2. try to pull it out

### CMG User ID

229569

**Comment by alfiellds** [comment]
Hello, thank you for the report and sorry to hear you are experiencing this issue.

Following making this report, had you tried relogging?

**Comment by wapitie** [comment]
yes, I have tried relogging, storing guns and changing guns

**Comment by rubbertoe98** [comment]
Does this happen all the time? Only sometimes? And does it happen without doing anything when you first spawn in.

**Comment by Anthony1414vg** [comment]
it has happed for the last 4 or 5 days
[14:41]
this happens all the time I've tried relogging/ different guns/ re downloading both gta and fivem.
[14:42]
I've done the bb fix to the usual gun visual glitches
[14:42]
also the guns appear invisible on the weapon wheel i dont know if that could be the cause

**Comment by Anthony1414vg** [comment]
![image](https://user-images.githubusercontent.com/91832155/136035176-a8e28b8e-21cd-47c0-875f-949955e27695.png)

**Comment by Anthony1414vg** [comment]
ive spent nearly 2 million on just trying all the different guns both pistols assault riffles ext. But still no difference

**Comment by Anthony1414vg** [comment]
where will the files be located ?? im not sure

**Comment by arthur-rl** [comment]
> where will the files be located ?? im not sure

`%localappdata%/FiveM/FiveM.app/logs`

**Comment by wapitie** [comment]
> After tomorrow's restart (3pm), please type the command "debugweapons", wait 10 seconds then close the game and send your log file.
> 
> To find your FiveM log files navigate to this directory: %localappdata%/FiveM/FiveM.app/logs

I will try

**Comment by gertio** [comment]
[CitizenFX_log_2021-10-05T173817.log](https://github.com/CMGStudios/issue-tracker/files/7288087/CitizenFX_log_2021-10-05T173817.log)
i have the same issue and here are my logs after the command debugweapons

**Comment by Anthony1414vg** [comment]
where do i write the command at ???

**Comment by rubbertoe98** [comment]
Thank you for the report, this bug has now been fixed from next restart.
