### ISSUE TITLE
[Bug]: Chimp

### ISSUE THREAD

**Issue by HDavid26** [CMGStudios/issue-tracker#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Chimp has 0 HP https://streamable.com/lxdf4f

### Expected behaviour

Chimp dies easily 

### Steps to reproduce

/Pet - Spawn it

### Any Texture Packs? (If so list)

No

### CMG User ID

260

**Comment by Drkiller99** [comment]
Is there an ETA on when this will be fixed? I've been wanting to buy the PET now for a while but there isn't any point in spending money if it's still broken.

**Comment by crazychris2404** [comment]
Confirmed to still be a issue
Moved to low priority developers are now aware of the issue.

**Comment by crazychris2404** [comment]
Unfortunately after speaking to developers this issue can't currently be fixed as it was set to 1000 for testing and the issue would still persist
