### ISSUE TITLE
[Bug]: New hair is not in the barbershop menu

### ISSUE THREAD

**Issue by Tiszr** [CMGStudios/issue-tracker#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The new hair introduced recently is not in the barbershop menu and it's only in the clothing menu.

### Expected behaviour

When going to a barbershop the new hair is not on the menu so you can not apply the hair permanently and need to keep changing your hair in the clothing menu.

### Steps to reproduce

1. Goto barbershop
2. the new hair isn't on the new menu.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

188910

**Comment by crazychris2404** [comment]
Can i get a bit more information on the issue you are facing and what is meant by "new hair" please.

**Comment by crazychris2404** [comment]
Spoke in DM's no longer a problem
