### ISSUE TITLE
[Bug]: game crashes

### ISSUE THREAD

**Issue by wispa5m** [CMGStudios/issue-tracker#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i load into cmg and it kicks me and says timeout server----->client but no one seems to know why
![Desktop Screenshot 2021 10 02 - 14 35 55 09](https://user-images.githubusercontent.com/91843213/135764811-45500116-6293-4b2c-98cd-26a1632b2062.png)
y

### Expected behaviour

i load into cmg and it kicks me and says timeout server----->client but no one seems to know why
![Desktop Screenshot 2021 10 02 - 14 35 55 09](https://user-images.githubusercontent.com/91843213/135764811-45500116-6293-4b2c-98cd-26a1632b2062.png)
y

### Steps to reproduce

![Desktop Screenshot 2021 10 02 - 14 35 55 09](https://user-images.githubusercontent.com/91843213/135764884-be8223ac-a9af-48e2-a075-401ac12f40ec.png)

### Any Texture Packs? (If so list)

reshader

### CMG User ID

184758

**Comment by tom-gun** [comment]
This is an issue isolated to your game or internet connection; as I can see you have successfully connected since I will close the issue.
