### ISSUE TITLE
[Bug]: Weapon Won't take out

### ISSUE THREAD

**Issue by DarkJitsu** [CMGStudios/issue-tracker#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I buy any weapon/item that's in the item wheel and try to equip it, it just does a weird animation (char puts hands behind back) and the weapon isn't taken out
![image](https://user-images.githubusercontent.com/91854373/135773918-9f32b4cc-b8b7-4387-af24-a01f7fac75ba.png)

### Expected behaviour

i expect the weapon to be taken out normally

### Steps to reproduce

1.buy weapon
2.try to take it out

### Any Texture Packs? (If so list)

No

### CMG User ID

229687

**Comment by Berik45** [comment]
I have the same issue

**Comment by Rempa** [comment]
Me and a friend got The same problem

**Comment by wapitie** [comment]
this problem has already been reported

**Comment by DarkJitsu** [comment]
> this problem has already been reported

and?

**Comment by arthur-rl** [comment]
> > this problem has already been reported
> 
> and?

![image](https://user-images.githubusercontent.com/43324346/135900195-1ec8539d-d68f-464f-8980-447cd8a8bc0c.png)

**Comment by arthur-rl** [comment]
Duplicated of #236

**Comment by Anthony1414vg** [comment]
atleast 20 people i have spoken to have this issue and i
t seems like the admins are blind to the issue or don't want to deal with the problem
