### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Deebo1888** [CMGStudios/issue-tracker#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically every time I leave meth processing place my van disappears for some weird reason. Always ends up back at my garage. I have a clip of it happening.

### Expected behaviour

Basically every time I leave meth processing place my van disappears for some weird reason. Always ends up back at my garage. I have clip if proof is needed.

### Steps to reproduce

1. Enter meth processing
2. process your meth till there is none left to do
3. leave and go to your vehicle 

### CMG User ID

214489

**Comment by rubbertoe98** [comment]
Duplicate, closing.
