### ISSUE TITLE
[Bug]: Drone Doesn't Descent

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Using the Drone Pressing Q Allows you to fly Up but when Pressing E the drone doesn't descent, also the controls are pretty uncormfortable:
Recommended controls:
Fly up = E
Fly down=Q
Movement= W,A,S,D
Camera= Arrow Keys
Thermal/Night vision=1/2
as of now Movement and Camera is Inversed
also the Hitbox is tad too big for the drone

### Expected behaviour

Be able to use the Drone Normally with the controls above

### Steps to reproduce

Clock on LFB
/drone
acend with Q
and try to descend 
https://streamable.com/6ubp1p

### CMG User ID

71613

**Comment by alfiellds** [comment]
These are the new drone controls:

Q = up
Z = down
1 = thermal vision
2 = night vision
