### ISSUE TITLE
[Bug]: cant buy a 200 when i dont own it

### ISSUE THREAD

**Issue by cookie744** [CMGStudios/issue-tracker#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i cant buy a kamaz ( 200KG)  as it says i already have it owned when i dont. my perm is 890 but i dont know why i cant buy it

### Expected behaviour

cant buy a kamaz as it says i already own it when i dont

### Steps to reproduce

cant buy it and dont know what to do

### Any Texture Packs? (If so list)

none

### CMG User ID

890

**Comment by crazychris2404** [comment]
Hi sorry for the late response is this issue still ongoing?

**Comment by crazychris2404** [comment]
Also can you confirm which donator rank you have please

**Comment by crazychris2404** [comment]
Solved
