### ISSUE TITLE
Glock Holster and Police menu search for HMP doesn't work

### ISSUE THREAD

**Issue by UncleeAdam** [CMGStudios/issue-tracker#248]
ISSUE 1

I'm a Glock Trained HMP officer, and when i put on "Accessory 162", once i go away from the menu, and i pull out my glock, my "Accessory" switches to number "163" (which is a chain) instead of 161 (which is the holster without the glock in it).

Let me know if a clip is needed to show some better insight to this issue.

ISSUE 2

HMP Guards cant use the "Seize Weapons" & "seize illegals" to take things like kitchen knifes, shanks etc.

**Comment by tom-gun** [comment]
Thanks for the report, the first issue has been fixed and should now equip and remove the gun from the holster as expected. Please place a suggestion with your HQ team for seizing weapons and illegals.
