### ISSUE TITLE
[Bug]: Teamspeak Icons Not Found

### ISSUE THREAD

**Issue by Botxby** [CMGStudios/issue-tracker#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Everytime i log onto CMG Teamspeak there is no icons at all. Not MET PD icons or NHS or even Staff

### Expected behaviour

Everytime i log onto CMG Teamspeak there is no icons at all. Not MET PD icons or NHS or even Staff. I had them on my old pc but not my current one now.

### Steps to reproduce

Load Up TS and You have no Icons. 

If you have icons and fresh install will get rid of them.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

6884

**Comment by crazychris2404** [comment]
There is a fix for this which you can request by messaging me on discord Chris.#2962 I will also update this post with a solution in the morning
