### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Infex1** [CMGStudios/issue-tracker#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Bug]: I have had a shotgun on my back for about a week, I reset my ped, I bought and equipped a shotgun, reset gender, died multiple times, re installed fivem and still hasn’t fixed the problem.

### Expected behaviour

Constantly being initiated on 

### Steps to reproduce

Constant, disappears for about 30 seconds when reset ped.

### Any Texture Packs? (If so list)

No 

### CMG User ID

881

**Comment by tom-gun** [comment]
Thanks for the report, this issue is reported to be fixed.
