### ISSUE TITLE
[Bug]: Poker game glitch

### ISSUE THREAD

**Issue by HPcmg** [CMGStudios/issue-tracker#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Player goes into casino and gambles 10m and looses it to a bug 

Player decided to hit his hand when he had a 10 , he then got 27 after 1 hit which does not make any sense as there is no card higher than 11 

### Expected behaviour

Player goes into casino and gambles 10m and looses it to a bug 

### Steps to reproduce

https://youtu.be/eMgPuz_Zjlk

### Any Texture Packs? (If so list)

NVE 

### CMG User ID

106466

**Comment by alfiellds** [comment]
Thank you for the report - this has been forwarded to the developers and will be looked into shortly.

**Comment by tom-gun** [comment]
Closed, this can not be reproduced and there haven't been any further reports within the past 8 months.
