### ISSUE TITLE
[Bug]: Lockpicking Vehicle Then Stopping and Doing it Again Causes Double Lockpick

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically, this is the same as #216 but for vehicles. 

I have only tested it on a single vehicle instead of two but I'm sure it works (if you do this).

### Expected behaviour

Should cancel respectively.

### Steps to reproduce

1. Buy 2+ lockpicks
2. Lockpick a vehicle
3. Cancel it a bit after
4. Lockpick again before it ends
5. Double lockpicked (2x fail or 1x fail, 1x success etc.)

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by crazychris2404** [comment]
Confirmed
