### ISSUE TITLE
[Bug]: Selling Small Shark Fins (Fish) doesn't work.

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Pretty self explanatory.

You can't sell the small shark fins you get from fishing (illegal).

### Expected behaviour

Selling the Small Shark fins normally.

### Steps to reproduce

1. Get some fish bait and a boat
2. Go to illegal fishing
3. Get a small shark fin
4. Try to sell it when done

### CMG User ID

194575

**Comment by rubbertoe98** [comment]
Fixed.
