### ISSUE TITLE
[Bug]:Bought BF400 Bike, Not in Garage

### ISSUE THREAD

**Issue by Ferg-214153** [CMGStudios/issue-tracker#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Spent 500k on BF400 bike and isn't in garage, relogged and nothing changed

### Expected behaviour

N/A

### Steps to reproduce

https://streamable.com/ly5dov

### CMG User ID

214153

**Comment by tom-gun** [comment]
Thanks for the report, this has been looked at by support and the vehicle should now be in your garage.
