### ISSUE TITLE
[Bug]: Prison Bus Affected by Cleanup

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically, the prison bus gets deleted with vehicle clean up.

Pretty much annoying to either run there or get an admin.
![FiveM_b2189_GTAProcess_YQx8iOpUc0](https://user-images.githubusercontent.com/62995181/138362878-89c2aa26-de4c-40cb-916b-49c104f4fb21.jpg)

### Expected behaviour

Prison bus shouldn't be removed.

### Steps to reproduce

1. Get sent to prison 
2. Hope cleanup appears while in the bus
3. Bus gets deleted

### CMG User ID

194575

**Comment by alfiellds** [comment]
Confirmed - thank you for the report. The developers will look into this shortly.

**Comment by rubbertoe98** [comment]
Fixed.
