### ISSUE TITLE
[Bug]: SoA Towtruck randomly drops cars when towing, if the car has someone in it lots more yikes happense

### ISSUE THREAD

**Issue by Pulsse** [CMGStudios/issue-tracker#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When attaching the hook to a car you can drive around but sometimes it randomly disconnects. When towing a car that has someone in it you can not unhook ( hold H ) and if they drive away it shows ur towing then when your not.

### Expected behaviour

Above

### Steps to reproduce

Above

### Any Texture Packs? (If so list)

None

### CMG User ID

300

**Comment by crazychris2404** [comment]
I have tried this and cannot confirm this bug.
When testing the car only disconnects on sharp turns being what i believe is a GTA Mechanic anyway.
If this issue persists feel free to make another report.
