### ISSUE TITLE
[Bug]: Clocked on As PD going to on car dev universe, backing out and entering a vehicle and fly all over the gaff

### ISSUE THREAD

**Issue by Drillz244** [CMGStudios/issue-tracker#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

How it works is, if you are clocked on PD, proceed to go to your car dev universe whilst you have PD weapons on you, then leave the car dev universe back to the live normal universe and enter a vehicle you fly all over the place 

### Expected behaviour

Weapons remain stuck on you, and additionally, when you enter a vehicle you fly about.

### Steps to reproduce

1. Clock on as PD. 
2. Get weapons on you, Sig MCX etc
3. enter car dev universe
4. Spawn a vehicle on car dev universe [Althought I don't think this matters]
5. DV and go back to the normal universe
6. Enter a car and then you will fly 

### Any Texture Packs? (If so list)

NVE

### CMG User ID

163

**Comment by crazychris2404** [comment]
Issue appears to of been resolved thanks for reporting
