### ISSUE TITLE
Keep on crashing, doesn't matter where i am in city

### ISSUE THREAD

**Issue by Luk3St1rrup** [CMGStudios/issue-tracker#271]
Doesn't matter where i am in the city i always keep on crashing. Always with the same error code ink-dakota-mountain .
Ive literally tried everything on my end to combat the problem, so it is obviously an error on the servers part.

**Comment by alfiellds** [comment]
Hello, are you still experiencing this issue?

**Comment by tom-gun** [comment]
This was an issue isolated to your game; as I can see you have successfully connected since I will close the issue. If this issue persists please verify your game files.
