### ISSUE TITLE
[Bug]: LFB Can't Spawn at fire station

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Clocked on LFB You can't spawn at the Fire station and you also lose your items if you die

### Expected behaviour

Being able to respawn at the LFB Station Like NHS Can in addition to this LFB Should also keep items in their inventory when they die like PD do.

### Steps to reproduce

1. Clock on LFB
2. Die
3. Wait for respawn Menu and LFB Station is not there.

Clip:
https://streamable.com/wmrxe7

### Any Texture Packs? (If so list)

No

### CMG User ID

71613

**Comment by alfiellds** [comment]
Fixed.

**Comment by zenabzz** [comment]
Another Bug report has been opened about this issue #298 it has not been fixed yet. When Clocked on NHS you Can spawn at the fire station but you can't spawn there when you are clocked on LFB.
