### ISSUE TITLE
[Bug]: Fire Hose Shooting Water  infinitely

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Very rarely after using the LFB Fire hose it sometimes keeps on shooting water from your body infinitely Only way to fix it is by relogging.

### Expected behaviour

Fire hose Stops shooting water when you stop pressing Left click.

### Steps to reproduce

 Happens Randomly After using the fire Hose.
 Clip:
 https://clips.twitch.tv/ElegantGracefulBottleFutureMan-M7-ooZoCg--48w-C

### Any Texture Packs? (If so list)

None

### CMG User ID

71613

**Comment by tom-gun** [comment]
Thanks for the report! A fix was pushed for this on the 2nd November and is believed to be fixed. If this is not the case, please reopen the issue and provide a set of steps for us to replicate this issue.
