### ISSUE TITLE
[Bug]: Fire station MLO

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Fire station MLO People and Cars suddenly go invisible also Sometimes you can't see anything and the MLO Doors are buggy they need to be smashed into to open.

### Expected behaviour

For the MLO Doors to work without needing to smash into them, For people and Cars not to disappear and to be able to see normally.

### Steps to reproduce

Happens Randomly, You can park a vehicle and it can disappear someone can walk in the fire station and they can disappear you can carry someone and they might not be able to see, try jumping on a vehicle that is parked inside.

Clip:
https://streamable.com/49w8oy

### Any Texture Packs? (If so list)

NVE

### CMG User ID

71613

**Comment by zenabzz** [comment]
Another Clip
https://streamable.com/p8ahbs

**Comment by alfiellds** [comment]
Hello, thank you for the report. This will be forwarded to the 3D modellers for review.

**Comment by zenabzz** [comment]
Hey any update on this issue?

**Comment by crazychris2404** [comment]
I have spoken to the 3D modellers and it is not currently a possibility to fix this issue and alternative options are being looked into.
