### ISSUE TITLE
[Bug]: craftmoped = craftbmx

### ISSUE THREAD

**Issue by terrorist** [CMGStudios/issue-tracker#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

/craftmoped says 'Can't craft a BMX right now'

### Expected behaviour

Craft a moped not a bmx

### Steps to reproduce

1. /craftmoped

### CMG User ID

11111

**Comment by menstruated** [comment]
Maybe the issue doesn't happen all the time, because now it's working. Got this problem around the road near prison.

**Comment by alfiellds** [comment]
Hello, I can confirm this is not a bug and is simply occurring as you are attempting to craft a moped while in the prison area (in the same way that emotes cannot be used in the prison area).

Thank you for the report.
