### ISSUE TITLE
[Bug]: You can see your Casino Chips in this random place not in casino.

### ISSUE THREAD

**Issue by tyyy04** [CMGStudios/issue-tracker#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I drive down this road, I can see my Casino Chips in the top right. It's nowhere near the casino.

### Expected behaviour

.

### Steps to reproduce

1. Just drive down this road on the right side near the trees.
![image](https://user-images.githubusercontent.com/93607006/139905923-d38c56e0-9f8c-497a-b3d6-5bc1af3f9328.png)

### Any Texture Packs? (If so list)

FPS BOOST PACK#1 : https://drive.google.com/drive/folders/1xYGoHNX6d_XWe1pOHv-hASYK9XGrMQDX?usp=sharing

### CMG User ID

202167

**Comment by tyyy04** [comment]
Hang on Let me highlight the road.

**Comment by JunctionNinja** [comment]
Just to add on to @tyyy04's issue, It may also sometimes shows a random dealer (or 3, like it did to me in the purge).

**Comment by alfiellds** [comment]
Thank you for the report, this will be forwarded to the developers for review.

(was unable to confirm myself)
