### ISSUE TITLE
I cant open any apps on my phone[Bug]: 

### ISSUE THREAD

**Issue by spectre7s** [CMGStudios/issue-tracker#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I press K to open my phone on cmg and when i try to open for example Monzo or Contacts, it wont open. I relog and nothing changes so this means i cant do important things like send money etc

### Expected behaviour

When i open my phone i should be able to open the apps without it doing nothing

### Steps to reproduce

.

### Any Texture Packs? (If so list)

Just a fragging graphics pack

### CMG User ID

7000

**Comment by alfiellds** [comment]
Hello, thank you for the report.

Could you please confirm whether you have rebound any of your keybinds?

**Comment by alfiellds** [comment]
Closed due to inactivity - if the issue persists please reopen the issue or create a new one. Many thanks.
