### ISSUE TITLE
[Bug]: Spawning at Royal london unable to do anything, relogging and dying

### ISSUE THREAD

**Issue by xRhys** [CMGStudios/issue-tracker#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This bug has happened to me on a few occasions now. I spawn at Royal London with no health, unable to type in chat and an invisible ped. I am then forced to relog, upon doing so I am bought underneath the map and am then dead

### Expected behaviour

This bug has happened to me on a few occasions now. I spawn at Royal London with no health, unable to type in chat and an invisible ped. I am then forced to relog, upon doing so I am bought underneath the map and am then dead

### Steps to reproduce

Happens by chance / bad pc maybe

### Any Texture Packs? (If so list)

Reshade (was happening before I installed it)

### CMG User ID

125898

**Comment by alfiellds** [comment]
Hello, are you able to provide a video of this issue occurring?

**Comment by alfiellds** [comment]
Closed due to inactivity.
