### ISSUE TITLE
[Bug]: the dark matter mp5 is not pulling out

### ISSUE THREAD

**Issue by conorzz** [CMGStudios/issue-tracker#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i tryed to pull the mp5 out and its not pulling out heres the clip https://streamable.com/88psv6

### Expected behaviour

mp5 not pulling out https://streamable.com/88psv6

### Steps to reproduce

tryed to pull it out and not doing it 

### Any Texture Packs? (If so list)

dont know y i cant send it lol

### CMG User ID

181502

**Comment by TeaseEU** [comment]
any update on this from admins? ongoing bug

**Comment by crazychris2404** [comment]
https://github.com/CMGStudios/issue-tracker/issues/308

**Comment by crazychris2404** [comment]
Fixed.
Thanks for the report.
