### ISSUE TITLE
[Bug]: Cannot use y menu to take off / put on clothing

### ISSUE THREAD

**Issue by Luk3St1rrup** [CMGStudios/issue-tracker#282]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When ever I press y in game the y menu itself comes up, but i cannot select to change clothing. The menu itself works such as if I do /shirt the shirt icon goes blue, but i can not physically use it and interact with the menu. Ive reset my binds and unbinded y in the f8 menu. I have no clue how to fix this.

### Expected behaviour

Press y, menu comes up, press on any icon, nothing happens

### Steps to reproduce

press y
try and take off clothing
nothing happens

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by alfiellds** [comment]
Hello, thank you for the report. Could you please provide a clip of this issue occurring so that the developers can look into it?

Many thanks.

**Comment by Luk3St1rrup** [comment]
this problem has resolved itself. it was somehow a problem with how the game was installed. GTA was installed on a different hard drive to what fivem was, and that somehow caused the problem because it is now back to normal
