### ISSUE TITLE
[Bug]: pilot job bugged

### ISSUE THREAD

**Issue by kimfake** [CMGStudios/issue-tracker#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have played the pilot job for numerous hours and I have noticed every now then when landing for Heathrow airport I on the odd occasion do not get clearance from atc to land and when I do land there’s no further instructions which means I have to end my shift.This does not happen all the time but since I play a lot it affect my gameplay and experience 

### Expected behaviour

I am unable to do my job as I’m am constantly waiting for instructions to land 

### Steps to reproduce

Fix atc command so it does give me clearance from atc to land

### CMG User ID

231566

**Comment by alfiellds** [comment]
Hello, thank you for the report. Could you please provide a clip of this issue occurring so that the developers can look into it?

Many thanks.

**Comment by crazychris2404** [comment]
Due to no more information being given this issue will be closed. Feel free to create another issue once you can provide more information about the problem.
