### ISSUE TITLE
[Bug]: Cant use f5 menu and i cant leave or join or take gang funds out

### ISSUE THREAD

**Issue by Jameshoward123** [CMGStudios/issue-tracker#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i bought gang license and made my own gang so i could have gang funds - i wanted to take them out but it wont let me even if i go to the bank thing, when i try and leave it wont let me and if i stay in f5 for to long then i can use garages and other items on the floor.

https://streamable.com/tt2j0x

### Expected behaviour

i cant use anything and have to reset the game just to get back to being able to play - i just want gang funds out

### Steps to reproduce

f5 and try and leave

### Any Texture Packs? (If so list)

fps pack

### CMG User ID

212462

**Comment by alfiellds** [comment]
Hello, thank you for the report - this will be reviewed by the development team shortly.

**Comment by Jameshoward123** [comment]
been looked at? i have 100mil sat there doing nothing

**Comment by alfiellds** [comment]
Yes, this is in the process of being reviewed.

**Comment by alfiellds** [comment]
Fixed upon next 3PM restart.

**Comment by Jameshoward123** [comment]
still broken
