### ISSUE TITLE
[Bug]: CPR is broken

### ISSUE THREAD

**Issue by GodlyTed** [CMGStudios/issue-tracker#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CPR no longer works

### Expected behaviour

CPR should perform the animation then give you a prompt saying if the CPR was successful or if you failed to save the person's life. The animation plays but I believe it fails to perform the function that decides if the receive was successful and no result message displays. Meaning CPR has a 0% chance of working :(

### Steps to reproduce

1. CPR a downed person
2. Finish the CPR animation
3. Don't receive any success or failure message

### CMG User ID

7756

**Comment by tom-gun** [comment]
Thanks for the report, the issue has been fixed.
