### ISSUE TITLE
[Bug]: crosshair won't turn off

### ISSUE THREAD

**Issue by terrorist** [CMGStudios/issue-tracker#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Crosshair won't turn off in f2 menu

https://streamable.com/9tieqi

### Expected behaviour

Un tick the box and crosshair turns off

### Steps to reproduce

Turn on crosshair in f2 menu, then attempt to turn off. It won't.

### Any Texture Packs? (If so list)

No Day

### CMG User ID

11111

**Comment by alfiellds** [comment]
Hello, thank you for the report. This will be reviewed by the developers and fixed shortly.

**Comment by menstruated** [comment]
Please get this fixed. Every single time I load in it's there and the first time I go to shoot anyone it puts me off then I have to mess about getting it turned off.

**Comment by alfiellds** [comment]
Thank you for the report, this has now been fixed.
