### ISSUE TITLE
[Bug]: Cannot change hair colour/texture

### ISSUE THREAD

**Issue by Swixx** [CMGStudios/issue-tracker#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i choose a hairstyle, i cannot change the colour and have to use the danny green. I have tried many things to try fix this and none worked. It says 0/63.

### Expected behaviour

When you try to change hair colour by pressing enter the texture does not change.

### Steps to reproduce

1. go to clothing store
2. go down to hair
3. press enter to change colour
4. nothing happens for me

### Any Texture Packs? (If so list)

no

### CMG User ID

2000767

**Comment by tom-gun** [comment]
Thanks for reporting the issue, this is being investigated

**Comment by crazychris2404** [comment]
Hair colour can be changed in the barbers

**Comment by crazychris2404** [comment]
Closed due to no response.
