### ISSUE TITLE
[Bug]: Front of PD desk is invisible 

### ISSUE THREAD

**Issue by CMG-Mac** [CMGStudios/issue-tracker#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

No walls at PD mission row

### Expected behaviour

No walls at PD mission row

### Steps to reproduce

https://cdn.discordapp.com/attachments/508411048596996114/912023021286473728/unknown.png

### Any Texture Packs? (If so list)

German Roads - All Black With Stars

### CMG User ID

741

**Comment by rubbertoe98** [comment]
Fixed.
