### ISSUE TITLE
[Bug]: i lost my money and i want it back i went all in and lost it to a bug

### ISSUE THREAD

**Issue by Markuss18** [CMGStudios/issue-tracker#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i put in money it started and then it never gave my cards and it just took my money 

https://streamable.com/vrtinz

### Expected behaviour

idk

### Steps to reproduce

idk

### Any Texture Packs? (If so list)

x

### CMG User ID

199126

**Comment by crazychris2404** [comment]
This would need more info such as how it can be reproduced please.

**Comment by crazychris2404** [comment]
Also to get your money you would have needed to have made a comp request on the forums.

**Comment by crazychris2404** [comment]
Closed due to no response and being unable to reproduce.
