### ISSUE TITLE
[Bug]: When having a drone out you cannot access your weapons.

### ISSUE THREAD

**Issue by Luk3St1rrup** [CMGStudios/issue-tracker#297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you do the /drone command and press enter to control it, once you back out of the drone screen while the drone is still out you cannot access your weapons. 

### Expected behaviour

To be able to access weapons while having a drone out.

### Steps to reproduce

do /drone 
press enter
press enter again to back out of the drone screen
try and access weapons

### Any Texture Packs? (If so list)

Not really relevant but none

### CMG User ID

209460

**Comment by tom-gun** [comment]
Thanks for the report, the issue has been fixed.
