### ISSUE TITLE
[Bug]:  LFB can't spawn at the fire station after it was fixed

### ISSUE THREAD

**Issue by exmmz** [CMGStudios/issue-tracker#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

LFB can't spawn at their own fire station.

### Expected behaviour

LFB should be able to spawn at their own fire station. NHS can but LFB can't.

### Steps to reproduce

1. Be clocked on LFB
2. Die
3. Wait the respawn time
5. Click E and wait for the spawn menu

CLIP

https://streamable.com/z5vprd

### Any Texture Packs? (If so list)

NVE

### CMG User ID

199923

**Comment by crazychris2404** [comment]
Confirmed Still a issue. 
Only NHS can spawn at the fire station however LFB cannot.
This has been reported to developers and will hopefully be fixed soon.
