### ISSUE TITLE
[Bug]: Car performance bug

### ISSUE THREAD

**Issue by Daulitz** [CMGStudios/issue-tracker#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I drive my lambo (spawncode: certified) it's horrid. barely even hits 250 flat
However when I let other people drive it, the exact same car (me getting out of the car and letting them get in) it drives way better.
Never had a car like this, have spoken to car devs about this and they said its most likely a bug.

Possible issue: For some reason it might be bugged for the OWNER of the car, but not for others driving it (?)

### Expected behaviour

The car is expected to perform the same for me as for everyone else, lmao.

### Steps to reproduce

Spawn the car in as the OWNER of the car, check how it drives. Then let someone else drive the exact same one. 
If you just spawn the car in without actually owning it, it should be fine apparently.

### Any Texture Packs? (If so list)

NVE

### CMG User ID

355

**Comment by Daulitz** [comment]
For some reason, my car is now also CAPPED at 170. As a lamborghini supercar

**Comment by Daulitz** [comment]
Still nothing, huh?...

**Comment by tom-gun** [comment]
Unfortunately this is not the place for car reports, instead you should contact a vehicle developer (Car Developer role on Discord).
