### ISSUE TITLE
[Bug]: Stretcher Sometimes Bugs Out

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically the stretcher won't let me use it at times. It's not like a 100% thing but happens from time to time.

F8:
![image](https://user-images.githubusercontent.com/62995181/143950612-d276bb4a-18e7-4ff8-ae0f-30bbc1fa158a.png)

### Expected behaviour

I should be able to pick it up with **0** problem.

### Steps to reproduce

1. Get a stretcher (reproduced once with the one spawned by NHS)
2. Grab it and drop it (might have to repeat)
3. Should be unable to be picked up now

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by crazychris2404** [comment]
Merged with https://github.com/CMGStudios/issue-tracker/issues/333
