### ISSUE TITLE
[Bug]: Everytime i try to pull a car out its like triple clicking so i can only spawn one car and everytime I die, I respawn invisible and everyone else sees me in danny clothes

### ISSUE THREAD

**Issue by Holmzsy** [CMGStudios/issue-tracker#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://streamable.com/npy6fy This clip shows whats happening

### Expected behaviour

Cant get the car i want out and respawn in danny clothes and I'm instantly respawning with no timer, me and my friend both have this issue

### Steps to reproduce

https://streamable.com/npy6fy

### Any Texture Packs? (If so list)

Ceres Texture pack

### CMG User ID

532

**Comment by maxprich0504** [comment]
Yo Holmzsy I had this issue and I fixed it by changing my version form Canary to Stable in FiveM settings and now works.

**Comment by rubbertoe98** [comment]
Fixed, was a bug on canary.
