### ISSUE TITLE
[Bug]: I keep spawning under the map every time I spawn in.

### ISSUE THREAD

**Issue by maxprich0504** [CMGStudios/issue-tracker#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Spawn under the map instantly after logging in to CMG.

### Expected behaviour

I spawn under the map, and seems like I'm dead but I spawn in the Michael Ped with no Health and CMG Admins cant tp me to legion because I'm not on their member list, seems like a few other people have this issue to.

### Steps to reproduce

https://medal.tv/games/gta-v/clips/73682177/d1337gMbUtTY?invite=cr-MSxVWUEsMjA5NjExNTYs

### Any Texture Packs? (If so list)

Blue Clouds Galaxy pack

### CMG User ID

212628

**Comment by alfiellds** [comment]
Please try changing your game version to stable if you are currently using canary in your FiveM settings.

Let us know if this is useful.

**Comment by maxprich0504** [comment]
Yes Thank You, my game works name!
