### ISSUE TITLE
[Bug]: Anything that requires the text box to pop up to request information.

### ISSUE THREAD

**Issue by Drkiller99** [CMGStudios/issue-tracker#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Explanation of my issue**:
Anything that needs the following box ([click to view image](https://prnt.sc/21ecqpc)) below has a habit of breaking for some reason when you log on randomly and can cause you to need to restart two or three times, I know a lot of people who have this issue and it's now even causing a problem when trying to sell your platinum days. 

**How it broke platinum days**:
I went onto server one for someone who had requested to buy a few days of me from the CMG Auction Room. I logged on there to only experience the glitch where the box never shows up but it's there invisible and you cannot move out of it as if it's trying to show the end-user the text box. To get out of this issue, you'll have to spam your home button a few times so it forcefully cancels it as it will never load.

**How it affects situations when needing staff members**:
When trying to call an admin your expected result is to type */calladmin* and once that has been executed, type a quick message as to why you need assistance to prepare them for your situation. This bug denies you that privilege until you relog, and sometimes it's a constant loop of it not working which means you may be delayed 30 minutes of just logging in to be able to use */calladmin* for assistance. 

**How it affects trading companies**:
When you're a part of a trading company selling illegal items such as guns, drugs, or a part of the legitimate side of things and trying to rent out your trucks... You are unable to because it won't pop up when using the garage menu for "Rent this vehicle" or when trying to use the give nearby players and it brings up this box, it won't work and will delay and could even not work entirely for a reboot and cause that customer to become impatient which isn't what you want at all.

Thank you for reading this report, I know it was a lot longer than you are used to. I just believe that this should be a priority within the bug reports as it causes so many issues and overall affects RP, Sales, and even fragging so much within the CMG Community. 

### Expected behaviour

1. Execute any command that requires the popup text box.
2. It works perfectly fine and allows you to quickly request assistance, give users their LSD, etc.
3. Enjoy the rest of your day.

### Steps to reproduce

[Click here for a video link showing this issue.](https://youtu.be/8i1d2sIw984)

### Any Texture Packs? (If so list)

I don't use any texture packs.

### CMG User ID

850

**Comment by crazychris2404** [comment]
I believe these linked https://github.com/CMGStudios/issue-tracker/issues/243 and does this still occur @Drkiller99 as i personally I don't experience this other than as a result of low specs during gameplay.

**Comment by Drkiller99** [comment]
I’ve never had low specs during gameplay and yes this still occurs for a lot of people, it usually solves itself after re-logging.

**Comment by crazychris2404** [comment]
After speaking to multiple players around CMG general chat. Personally I cannot always reproduce this however others are continuing to have this problem at different times. A developer will need to look into this further

**Comment by crazychris2404** [comment]
Should be fixed after the next restart at midnight. If this issue still persists after this time please respond to this issue.

**Comment by crazychris2404** [comment]
Confirmed still occurring
Usual caused after renting cars/selling cars and other similar menus
Moved to high priority

**Comment by Drkiller99** [comment]
Any update on when this will be fixed? Happened again yesterday.

**Comment by tom-gun** [comment]
Closed - No reports of this occurring recently
