### ISSUE TITLE
[Bug]: scope doesnt stay enabled when it is in the menu

### ISSUE THREAD

**Issue by ghillieee** [CMGStudios/issue-tracker#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I press F2 > Scope Settings > Enabled ✅ and then exit off the menu and its no longer there 
![image](https://user-images.githubusercontent.com/88168239/144516867-d4561f52-ecde-4b3c-8406-e1c21583ad6c.png)

### Expected behaviour

I go on menu, enable it and it should stay enabled

### Steps to reproduce

Go onto the Scope Settings menu press enabled press backspace 

### Any Texture Packs? (If so list)

Realistic pack - https://www.youtube.com/watch?v=Irci1XOG_K8

### CMG User ID

221197

**Comment by rubbertoe98** [comment]
Not a bug, it's only meant to be enabled when using a sniper scope.
