### ISSUE TITLE
[Bug]: Los Santos Police Department sign

### ISSUE THREAD

**Issue by CMG-Mac** [CMGStudios/issue-tracker#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Los Santos Police Department sign 

### Expected behaviour

Los Santos Police Department sign

### Steps to reproduce

https://cdn.discordapp.com/attachments/508411048596996114/916231702433636362/unknown.png

### Any Texture Packs? (If so list)

German Roads - All Black With Stars

### CMG User ID

741

**Comment by rubbertoe98** [comment]
Fixed.
