### ISSUE TITLE
[Bug]: Event Lootdrop - Cayo Island

### ISSUE THREAD

**Issue by Drkiller99** [CMGStudios/issue-tracker#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Issue:**
> The red zone that spawns around the loot drop at the island doesn't work. It's shown in the clip below.
[(Click here to view the clip)
](https://youtu.be/VC7fNmUSZvY)
Would you also be able to make it a smaller red zone so it doesn't affect users who are trying to grind LSD, thank you very much for reading this bug report.

### Expected behaviour

1. Go to the new island to participate in the crate event
2. Enter the red zone and receive a message alerting you that you cannot leave for thirty seconds.
3. After thirty seconds, leave.

### Steps to reproduce

1. Go to the island during the crate event there.
2. Walk into the red zone.
3. Get no message.

### Any Texture Packs? (If so list)

I don't use any texture packs.

### CMG User ID

850

**Comment by crazychris2404** [comment]
Can you confirm if this happens at all crate drops or only this one please @Drkiller99

**Comment by Drkiller99** [comment]
It only happens at that one as far as I’m aware, that’s something that the developers can look into to see if it’s something to do with the new island itself that’s causing the issue. The ones on land that I’ve attended have all had the 30 second combat area.

**Comment by arthur-rl** [comment]
This sounds more like a feature request than a bug report.

**Comment by Drkiller99** [comment]
Some of the event drops that we’ve been too (myself and people I hang out with) have been to some on the mainland that have timers; if that’s not supposed to be the case then the next time I’m at an event drop with a timer I’ll record and submit that as a bug report.
