### ISSUE TITLE
[Bug]: Sentence logs for HMPS

### ISSUE THREAD

**Issue by Drkiller99** [CMGStudios/issue-tracker#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Issue**:
HMPS Jailing system, when we use our jail using the met PD UI, it doesn't actually log when we jail someone. It would be very hard to capture whitelist abuse with this function while it's not working. 

### Expected behaviour

1. You would open the UI and a criminal who's trespassing on the grounds on HMP.
2. Jail them for the correct amount of time.
3. Proceed to check the log at a later date for an admin situation and be able to provide the log. 

### Steps to reproduce

1. Press 'e' on a person.
2. MET PD UI
3. Jail that person.
4. Enter your time.
5. Sentence him to jail
6. Check the sentencing logs.
7. See the person you sentenced whilst on HMPS.

### Any Texture Packs? (If so list)

I don't use any texture packs.

### CMG User ID

850

**Comment by arthur-rl** [comment]
I think this is more of a feature request than a bug. Unless they used to log via the discord?

**Comment by crazychris2404** [comment]
> I think this is more of a feature request than a bug. Unless they used to log via the discord?

use to i believe as hmp logs show pd jail but not hmp jailing

**Comment by Drkiller99** [comment]
Toms already aware of this issue sometimes happening when it comes to the requests sent by discord. Not every log is sent because of something to do with how discord handles the message requests; @crazychris2404 thats why some of the HMP ones in particular don’t send 😇

**Comment by crazychris2404** [comment]
Bug is not reproduceable so probably as mentioned to do with webhooks being sent 
Issue closed.
