### ISSUE TITLE
MP5 Dark Matter Still Not Working

### ISSUE THREAD

**Issue by TeaseEU** [CMGStudios/issue-tracker#308]
https://medal.tv/games/gta-v/clips/74337301/d1337tkYiwAZ?invite=cr-MSx5QXAsMjcyOTI0MjEs

Was claimed the MP5 Dark Matter was fixed, but now doesnt even show up in tab wheel, in a worse state than it was before fix.

**Comment by crazychris2404** [comment]
Is this still a ongoing issue?

**Comment by crazychris2404** [comment]
Merging this issue with previously opened one
