### ISSUE TITLE
[Bug]: Can't Access House Storage

### ISSUE THREAD

**Issue by TeaseEU** [CMGStudios/issue-tracker#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

No matter what I do, I cannot access the storage in my house, this issue has been ongoing for multiple days now. No matter what I do, I am unable to fix this encounter. Relogging, switching servers, nothing has resolved this issue.

This is the bug I am experiencing : https://medal.tv/games/gta-v/clips/74461091/d13375UXNTFi?invite=cr-MSxRamcsMjcyOTI0MjEs
This is what happened when a group tried to bolt cut my house : https://streamable.com/vc6kf0

This is what my house had inside + a draggy sniper rifle : https://cdn.discordapp.com/attachments/880625392212389898/916285943969886249/unknown.png

### Expected behaviour

I should be able to access my house storage, this has stopped me from being able to enjoy my gameplay.

### Steps to reproduce

I am not sure how i encountered this bug, ive just been unable to access my house storage for a couple days.

### Any Texture Packs? (If so list)

none

### CMG User ID

217839

**Comment by TeaseEU** [comment]
Still occuring after another server restart.

**Comment by crazychris2404** [comment]
Does this bug still occur? or has it since been fixed?

**Comment by crazychris2404** [comment]
Still ongoing mentioned via DMS.

**Comment by tom-gun** [comment]
Closed - Author no longer contactable
