### ISSUE TITLE
[Bug]: Bottom of st Thomas 

### ISSUE THREAD

**Issue by Maciscool2007** [CMGStudios/issue-tracker#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

you cant go in there 

### Expected behaviour

you cant go in there

### Steps to reproduce

https://cdn.discordapp.com/attachments/880964002690248755/918021987039850527/unknown.png

### Any Texture Packs? (If so list)

German Roads - All Black With Stars

### CMG User ID

741

**Comment by crazychris2404** [comment]
Issue has since been resolved
