### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by locayte** [CMGStudios/issue-tracker#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

respawn bug, spawns you invis/as a danny.

### Expected behaviour

when i die it automatically sends me to the respawn screen (where you choose a location) without a respawn timer and you spawn in as a danny after you choose the location in which you want to spawn at.

### Steps to reproduce

1. die

### CMG User ID

5475

**Comment by Luk3St1rrup** [comment]
Can confirm this is happening to me aswell. Literally game breaking as it teleports you to royal London hospital.

**Comment by crazychris2404** [comment]
Hello,
Do you have anymore information on this and possibly how it can be reproduced?

**Comment by crazychris2404** [comment]
Close
A fix is being worked on to prevent this occurring or a way for players to deal with this problem.
Reason for closing: No way to 100% reproduce this issue
