### ISSUE TITLE
 spawning under the map 

### ISSUE THREAD

**Issue by havardcmg** [CMGStudios/issue-tracker#312]
I am so tired of spawning under the map. I believe this is the biggest issue within cmg and also why so many people are fed up with cmg. Because they spend half their time online under the map and waiting for admins to take a ticket. Iv had so many people in my comms telling me they are fed up with cmg because of this. Please fix this issue this would make alot of people come back if it gets fixed

**Comment by crazychris2404** [comment]
Developers are currently working on a way to prevent this or allow users to get out from under map easier. Feel free to open another issue if you know any way this problem is reproduced.
