### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Elliot1047** [CMGStudios/issue-tracker#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the CPR is broken for NHS when we try to revive someone it doesnt bleep and let us shock them for atleast 5 mins after and even when it does and they are still moving on the floor it says pulse 0 and we have to just leave them 

### Expected behaviour

the CPR is broken for NHS when we try to revive someone it doesnt bleep and let us shock them for atleast 5 mins after and even when it does and they are still moving on the floor it says pulse 0 and we have to just leave them 

### Steps to reproduce

press e on person 
then CPR
then observations 
then after some time shock patient but they are dead so doesnt work 

### CMG User ID

182296

**Comment by tom-gun** [comment]
Thanks for the report, this issue is reported to be fixed.
