### ISSUE TITLE
[Bug]: Can't get money from Pacific Standard Bank while doing G4S

### ISSUE THREAD

**Issue by ne-x** [CMGStudios/issue-tracker#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While doing G4S job, if you get the money withdrawal from Pacific Standard Bank, you won't be able to withdraw due to the area where the money withdrawal is in, is a part of the bank heist and you can't access it unless you plant thermites.

### Expected behaviour

Can't withdraw my money when completing G4S job.

### Steps to reproduce

1. Run G4S
2. Do jobs until you get Pacific Standard Bank as money withdrawal
3. You won't be able to withdraw since the area is locked up and needs to be blown open with thermites

### Any Texture Packs? (If so list)

Nevek Optimize

### CMG User ID

235511

**Comment by tom-gun** [comment]
Thanks for the report, the issue has been fixed.
