### ISSUE TITLE
[Bug]: cant get the twitter money

### ISSUE THREAD

**Issue by Wberends** [CMGStudios/issue-tracker#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i have tried to get the twitter reward many times tried everything but nothing works.

### Expected behaviour

cannot receive reward

### Steps to reproduce

i have linked it first then i followed the ACC and waited but didn't get anything

### Any Texture Packs? (If so list)

no

### CMG User ID

237749

**Comment by alfiellds** [comment]
Confirmed - there have been issues with twitter rewards for a while now. The development team will look into this issue.

Thank you for the report.
