### ISSUE TITLE
[Bug]: buyed a car from simeons but i cant see the car and they took my money away

### ISSUE THREAD

**Issue by mesiilionel** [CMGStudios/issue-tracker#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i wanna buy a car from simeon so i testet some cars and buyed the tezeract for 2.250.000 and go to garage to spawn it and it wasnt there.
i tried it many times and it doesnt work.
i lost my money now please help me i grinded for that  money.

### Expected behaviour

i expect that you will give me my money back.

### Steps to reproduce

i tried to see if it was standing at a other garage but no

### Any Texture Packs? (If so list)

no

### CMG User ID

238195

**Comment by alfiellds** [comment]
The vehicle you purchased may be in the VIP garage (which you won't be able to see unless you are a donator).

Could you confirm whether you have access to the VIP garage please?
