### ISSUE TITLE
Bug]: No verification code 

### ISSUE THREAD

**Issue by Trillix1534** [CMGStudios/issue-tracker#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the discord says that if you connect to cmg you  get a verification code, but I don't get anything I just get loaded into the server.

### Expected behaviour

Im facing not being able to join the discord server because i have not verified yet.

### Steps to reproduce

No steps.

### Any Texture Packs? (If so list)

No texture packs

### CMG User ID

181020

**Comment by alfiellds** [comment]
Please open a new report and provide a video of this issue occurring in full for the developers to review.
