### ISSUE TITLE
[Bug]: cant get into a seat of vehicle after organ

### ISSUE THREAD

**Issue by Luk3St1rrup** [CMGStudios/issue-tracker#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

after organ heist, if you try to get into the seat of a vehicle when someone else is sitting inside it simply won't allow you to get in, to fix this you both have to relog after organ.

### Expected behaviour

to be able to get into a vehicle if someone else is in after organ

### Steps to reproduce

go to organ 
finish organ
get a vehicle out
try to get someone to get in
they cant get it

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by alfiellds** [comment]
Confirmed - thank you for the report. The development team will look into this shortly.
