### ISSUE TITLE
[Bug]: Audi RS7 Textures constantly bugging

### ISSUE THREAD

**Issue by Abz21Dev** [CMGStudios/issue-tracker#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Audi RS7 Textures constantly bugging 9/10 THERE GLITCHY and not showing the correct look,,,

### Expected behaviour

Audi RS7 Textures constantly bugging 9/10 THERE GLITCHY and not showing the correct look,,,

### Steps to reproduce

Get out garage

### CMG User ID

74370

**Comment by 2140CMG** [comment]
Can you Provide the spawncode for this vehicle? you can find out the spawncode by getting the vehicle out of a garage and pressing F8 and looking for the Vehicle name
this is not a server bug.

**Comment by Abz21Dev** [comment]
> Can you Provide the spawncode for this vehicle? you can find out the spawncode by getting the vehicle out of a garage and pressing F8 and looking for the Vehicle name this is not a server bug.

rs72020

audi rs7 2020

**Comment by alfiellds** [comment]
Not a server bug - please contact a car developer regarding this issue. 

Thank you for the report.
