### ISSUE TITLE
[Bug]: MPX HIP PREVIEW NOT MATCHING

### ISSUE THREAD

**Issue by 15OO** [CMGStudios/issue-tracker#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The MPX from small arms does not match the model that is shown on the side hip when the gun is not in hand

### Expected behaviour

They should be the same on the side and in the hand (the hand shows as a p90

### Steps to reproduce

- buy a mpx
- hold it and then put it away
- you will see they are different

Clip for ease: https://streamable.com/hj9dky

### Any Texture Packs? (If so list)

Ceres Purple Clouds

### CMG User ID

214124

**Comment by crazychris2404** [comment]
Confirmed this is still a problem i will forward to devs to get this fixed.
