### ISSUE TITLE
[Bug]: phone contacts

### ISSUE THREAD

**Issue by Dex4301** [CMGStudios/issue-tracker#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I cant use the contacts in my phone or ring anyone

### Expected behaviour

When I go into the contacts on the phone in game the phone screen goes white and I cant see any contacts and I also cant ring anyone

### Steps to reproduce

1. open phone  2. click on contacts  3. phone screen goes white

### CMG User ID

211949

**Comment by crazychris2404** [comment]
Is this issue still occurring?

**Comment by Drkiller99** [comment]
It’s happened to me a few times when using the mouse mode on the phone, and usually switching to keyboard and then mouse mode fixes it @crazychris2404

**Comment by crazychris2404** [comment]
i have been messaged by @Dex4301 and they were able to use the mouse to access the phone and then fixed by resetting it. Could contacts possibly link to why the phone breaks @arthur-rl

**Comment by crazychris2404** [comment]
This issue was fixed by resetting the phone.
Report has been closed.
If this reoccurs please reopen the issue.
