### ISSUE TITLE
[Bug]: tp back into heist, also can't see bags after heist

### ISSUE THREAD

**Issue by terrorist** [CMGStudios/issue-tracker#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you are in the heist if you start getting money when the gas timer is going, if you cancel the emote to run out of the vault you get teleported back inside and die. 

Also after you do the heist you can no longer see bags. 

### Expected behaviour

You shouldn't get tp'd back into the vault and die. You lose all the money and your guns.

### Steps to reproduce

Do the heist setups, do the heist. Start taking money before the gas runs out. Cancel the emote when the gas is about to run out. Walk out the vault and get tp'd back.

Kill someone after the heist and you can't see the bag.

### CMG User ID

11111

**Comment by tom-gun** [comment]
You should not be able to cancel the looting animation, as this can lead to issues as the one you reported. Please report how you managed to cancel the animation and we can work from that.
