### ISSUE TITLE
Twitter Reward not working.

### ISSUE THREAD

**Issue by a1kho** [CMGStudios/issue-tracker#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Attempted to redeem the reward for following cmg twitter, doesn't work

### Expected behaviour

Can't receive it

### Steps to reproduce

Followed the twitter, couldnt enter my perm id into the website.

### CMG User ID

248395

**Comment by arthur-rl** [comment]
Did you link your Twitter account using the in-game command `/linktwitter`?

**Comment by crazychris2404** [comment]
Closed due to no response if still occurring make another issue
