### ISSUE TITLE
keep spawning with no clothes in the same spot after relogging

### ISSUE THREAD

**Issue by madjacko** [CMGStudios/issue-tracker#33]
**Describe the issue you're facing**
i spawn in the same place every time after relogging without any clothes and i also lose Armor if i previously had it before logging off, inventory stays the same though
**Steps to reproduce**
relogging
**Expected behavior**

**Screenshots/Video**
https://youtu.be/yEYI87fG5O0

**Additional context**

**Perm ID**
409

**Comment by rubbertoe98** [comment]
Have you tried turning off your texture pack?

Please check if your hard disk storage is full?

Are you clearing your cache everytime you restart FiveM?

**Comment by madjacko** [comment]
> Have you tried turning off your texture pack?
> 
> Please check if your hard disk storage is full?
> 
> Are you clearing your cache everytime you restart FiveM?

I've tried taking the texture pack off and it still happens

storage is fine 500gb free

clearing cache also hasn't worked

**Comment by alfiellds** [comment]
Is it just you who cannot see the clothing or can others also not see it?

**Comment by madjacko** [comment]
> Is it just you who cannot see the clothing or can others also not see it?

others cant see it either

**Comment by rubbertoe98** [comment]
This isn't something we can fix then unfortunately, seems to be a rare case of KVP failing which is unrelated to CMG.
