### ISSUE TITLE
[Bug]: Unable to use /cuff when taking a ticket.

### ISSUE THREAD

**Issue by nopuwu** [CMGStudios/issue-tracker#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When taking a ticket, you are unable to use /cuff.
You must return from the ticket and staff on to use /cuff.

### Expected behaviour

When taking a ticket, /cuff should work as you're supposedly staffed on.

### Steps to reproduce

1. Take a staff ticket
2. Use /cuff on a player

### CMG User ID

505

**Comment by Hendreik** [comment]
Fixed
