### ISSUE TITLE
[Bug]: Enable Diagonal Weapons does not persist through relogs.

### ISSUE THREAD

**Issue by nopuwu** [CMGStudios/issue-tracker#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using "Enable Diagonal Weapons" through /settings, this does not persist when rejoining the server and must be disabled & re-enabled when rejoining the server.

### Expected behaviour

Weapons should remain diagonal on back between relogs.

### Steps to reproduce

1. Equip a weapon that shows on back (AK-200 etc.)
2. Enable Diagonal Weapons in /settings
3. Quit and rejoin the server.

### Any Texture Packs? (If so list)

NVE

### CMG User ID

505

**Comment by crazychris2404** [comment]
This is a confirmed bug.
Thanks for reporting.
Moved for developers to fix soon.
