### ISSUE TITLE
[Bug]: Flickering Lights When Looking West

### ISSUE THREAD

**Issue by maxprich0504** [CMGStudios/issue-tracker#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When driving/looking west the in-game lights start to flicker

### Expected behaviour

May be a problem with cmg or my texture pack idk?

### Steps to reproduce

1. Look West While In A Car
2. Lights Start To Flicker

### Any Texture Packs? (If so list)

NVE

### CMG User ID

212628

**Comment by tom-gun** [comment]
Thanks for the report, can you confirm the location this happened at? Report looks similar to #96

**Comment by maxprich0504** [comment]
Yeh, It bugs out towards the area of vinewood especially Triads/G4S mlo

**Comment by crazychris2404** [comment]
https://github.com/CMGStudios/issue-tracker/issues/96 Closing this issue as linked to a pre existing one.
