### ISSUE TITLE
[Bug]: Unable to Move NHS Stretcher

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sometimes when using NHS Stretchers (/stretcher) the option to move around / get on the stretcher disappears and the stretcher becomes an immovable and unusable object.

### Expected behaviour

Always able to use the stretcher wether it is by getting on it or moving it around.

### Steps to reproduce

1. Clock on NHS
2. Spawn Stretcher
3. Use it and Let go of it by pressing Right click or x
4. spawn another stretcher and sometimes it is unusable.

### Any Texture Packs? (If so list)

None

### CMG User ID

71613

**Comment by crazychris2404** [comment]
Could this be linked to https://github.com/CMGStudios/issue-tracker/issues/300 @zenabzz

**Comment by crazychris2404** [comment]
Confirmed issue cannot move stretchers at all currently during my testing once spawned in and previously only able to move when you attempt to interact at a certain angle as well. As a temporary fix try and use only 1 stretcher at a time

**Comment by crazychris2404** [comment]
Fixed
