### ISSUE TITLE
Bug: bmw m4 touring issues 

### ISSUE THREAD

**Issue by Jambo123456** [CMGStudios/issue-tracker#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought the m4 touring and I had upgraded it, I tested it and none of the upgrades appear to be working the car isn’t going any faster than what it should be doing. When I try to re apply the newly bought upgrades it’s saying I can’t afford it even though it is showing I have bought the upgrades 

### Expected behaviour

Vehicle not going as fast as it should especially with upgrades 

### Steps to reproduce

Tried disconnecting, re joining etc etc 

### CMG User ID

249518

**Comment by crazychris2404** [comment]
Regarding this issue you will need to speak to a car developer.
