### ISSUE TITLE
[Bug]: Wont let me load into server!

### ISSUE THREAD

**Issue by justmeturbo** [CMGStudios/issue-tracker#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Loading into cmg everything downloades untill its time to join server. It says "Requestion server info: 1... 2... 3.

Then doesn't connect: https://cdn.discordapp.com/attachments/936460469315719178/936461558962323496/Screenshot_2022-01-28_032324.png

### Expected behaviour

Wont Load into CMG!!!

### Steps to reproduce

Need Help!

### Any Texture Packs? (If so list)

no

### CMG User ID

224372

**Comment by crazychris2404** [comment]
This is usually caused when fivem is down this should now be resolved please try f8 connect s1.cmg.city if it is not resolved you can ask for support in game support on discord

**Comment by justmeturbo** [comment]
still dosent work!
