### ISSUE TITLE
[Bug]: mic lags out and is on constantly after being on push to talk

### ISSUE THREAD

**Issue by Luk3St1rrup** [CMGStudios/issue-tracker#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

sometimes the voice settings bug out and the voice is on constantly despite it being on push to speak. the only way you can fix is to relog and sometimes it just takes the royal piss

### Expected behaviour

being able to actually use your mic without it bugging out

### Steps to reproduce

go into CMG
hope it happens
mic will be on constantly

### Any Texture Packs? (If so list)

Not really relevant but none

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Will need to test this a bit more however I am aware this sometimes occurs when talking and tabbing out

**Comment by crazychris2404** [comment]
Unable to reproduce currently.
Do you know any way this bug is consistent as I have experience myself occasionally however as far as i am aware no way for this to constantly occur or any steps to cause it.

**Comment by Luk3St1rrup** [comment]
Ive been able to reproduce it, i just need to tab out a bunch of time, for example when I'm doing PD trainings and need to tab out constantly to go to the training form

**Comment by crazychris2404** [comment]
> Ive been able to reproduce it, i just need to tab out a bunch of time, for example when I'm doing PD trainings and need to tab out constantly to go to the training form

Are speaking in game whilst tabbing out?

**Comment by Luk3St1rrup** [comment]
not to my knowledge no

**Comment by Luk3St1rrup** [comment]
i might accidentally pressing n when typing or something but idk

**Comment by justmeturbo** [comment]
> i might accidentally pressing n when typing or something but idk

do T /vsync in game to resync

**Comment by Luk3St1rrup** [comment]
> do T /vsync in game to resync

not trying to sound funny but dont you think ive already tried that

**Comment by justmeturbo** [comment]
> > do T /vsync in game to resync
> 
> not trying to sound funny but dont you think ive already tried that

not being funny but then ur mic must be terrible

**Comment by Luk3St1rrup** [comment]
its literally just cmg, if you have no clue what your talking about pipe down and stay out of bug reports

**Comment by crazychris2404** [comment]
After speaking to developers this appears to be more of a FiveM based issue due to how push to talk is handled. This will be further investigated. For now this issue will be closed. Feel free to re-open this issue if you can find a reproduceable method for this bug.
