### ISSUE TITLE
[Bug]: LFB Unable too see Panics

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whilst Clocked on LFB you are unable to see anyone's /panic or even your own /panic.

### Expected behaviour

A panic Box should pop up above the Minimap if anyone Panics and Red GPS Marker will appear.

### Steps to reproduce

1. Clock on LFB
2. /panic
3. You will be unable to see your own panic

### CMG User ID

71613

**Comment by crazychris2404** [comment]
I know this is a issue however I feel for now you need to make sure LFB know just cause it doesn't say they have used the panic button does not mean it hasn't gone through. I will put this forward for "Low Priority" as LFB are not often using their panic and don't have a need to see other panic buttons currently.
