### ISSUE TITLE
[Bug]: NHS Wheelchairs

### ISSUE THREAD

**Issue by GoKartMan** [CMGStudios/issue-tracker#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The wheelchairs are broken, in some peoples eyes they arent there and you cannot move yourself if you are on one

### Expected behaviour

Unable to be seen or move.

### Steps to reproduce

It should work properly

### Any Texture Packs? (If so list)

N/A

### CMG User ID

165954

**Comment by tom-gun** [comment]
Are you spawning these wheelchairs, or are these the ones which exist around the map already?

**Comment by crazychris2404** [comment]
Spawning

> Are you spawning these wheelchairs, or are these the ones which exist around the map already?

**Comment by crazychris2404** [comment]
Does occur at times with naturual

**Comment by Drkiller99** [comment]
It’s only the default spawning ones inside the hospital & also allows you to phase through walls @crazychris2404. It was on my list of bugs to report but due to unforeseen circumstances which you are aware of I’ve not been able to post them. Hoping to go through the list in a few days 🙂

**Comment by crazychris2404** [comment]
Linked with https://github.com/CMGStudios/issue-tracker/issues/333 so closing this issue refer to both issues when resolving
