### ISSUE TITLE
After fingering bum not being able to shoot.

### ISSUE THREAD

**Issue by Prxjecs** [CMGStudios/issue-tracker#34]
**Describe the issue you're facing**
After /fingerbum you can’t shoot and you have to relog
**Steps to reproduce**
Relog
**Expected behavior**
Not having to relog
**Screenshots/Video**
N/A 
**Additional context**
N/A
**Any Texture Packs (if so list)**
N/A
**Perm ID**
611

**Comment by arthur-rl** [comment]
I have pushed a fix for this bug. It will be in at the 3pm restart. Make sure you cancel the emote by doing `/fingerbum` again instead of pressing <kbd>X</kbd>
