### ISSUE TITLE
Long range blips not showing Trident[Bug]: 

### ISSUE THREAD

**Issue by Vizhh** [CMGStudios/issue-tracker#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

All blips are blue on the map meaning you cannot see when an officer is clocked on as trident

### Expected behaviour

All blips are blue on the map meaning you cannot see when an officer is clocked on as trident

### Steps to reproduce

Clock on as PD
Have someone clock on as Trident
Sees the blip is blue

### Any Texture Packs? (If so list)

NVE

### CMG User ID

767

**Comment by tom-gun** [comment]
Closed, this has been fixed for the next scheduled restart.
