### ISSUE TITLE
[Bug]: WHEN YOU DANCE IN ORGAN HEIST YOU CANT STOP DANCING

### ISSUE THREAD

**Issue by ghillieee** [CMGStudios/issue-tracker#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CANT STOP DANCING IN ORGAN HEIST

### Expected behaviour

DO /E C AND IT STOPS

### Steps to reproduce

DANCE
DO /E C
IT DOESNT WORKK

### Any Texture Packs? (If so list)

I CANT REMEBER

### CMG User ID

221197

**Comment by crazychris2404** [comment]
Do you have a clip of this please

**Comment by ghillieee** [comment]
ILL GET ONE NOW

**Comment by ghillieee** [comment]
https://streamable.com/ybpl5z

**Comment by crazychris2404** [comment]
Cannot reproduce this issue
If this occurs again please make another issue
