### ISSUE TITLE
[Bug]: Phone is a white box

### ISSUE THREAD

**Issue by tom-gun** [CMGStudios/issue-tracker#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The phone is a white box when you pull it out: https://i.imgur.com/cAZ0CJW.png

### Expected behaviour

Opening the phone should bring up the home page

### Steps to reproduce

Press K to open the phone

### Any Texture Packs? (If so list)

N/A

### CMG User ID

58

**Comment by crazychris2404** [comment]
Confirmed.
Moved to high priority
