### ISSUE TITLE
[Bug]: Finishing off a downed person no longer stops them from speaking

### ISSUE THREAD

**Issue by GodlyTed** [CMGStudios/issue-tracker#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Previously, when you finished off someone who was killed/downed and in the hurting animation, they would no longer be able to speak. This would shut people up and that's why the phrase 'dead men don't speak' was popular at one point. - However, since the voice upgrades, this no longer works and people can still talk after being finished and shot while downed.

### Expected behaviour

You shouldn't be able to hear people after you finish them while downed/shoot them again after death

### Steps to reproduce

1. Kill someone
2. Loot their bag
3. Hear them talk shit
4. Shoot them again to stop them crying

### CMG User ID

7756

**Comment by crazychris2404** [comment]
Confirmed 
Developers will look into this.

**Comment by tom-gun** [comment]
This has been re-added today and will be in from next restart. Please let us know if there are any issues
