### ISSUE TITLE
[Bug]:can not change color of   Hennessey Camaro

### ISSUE THREAD

**Issue by chasjones1** [CMGStudios/issue-tracker#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i can not change the color of Hennessey Camaro it is white and can only change secondary color which is the interior 

### Expected behaviour

changeable color

### Steps to reproduce

?

### CMG User ID

254747

**Comment by crazychris2404** [comment]
Hi please contact any car developer with the spawn code of this car you can find it by pressing f8 after spawning the car
