### ISSUE TITLE
[Bug]: phone not working for 2 weeks hasnt fixed

### ISSUE THREAD

**Issue by jangolol13** [CMGStudios/issue-tracker#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i can pull out the phone but nothing can be opened on it

### Expected behaviour

1

### Steps to reproduce

press k to open phone
then nothing happens when trying to open apps

### Any Texture Packs? (If so list)

NVE

### CMG User ID

204318

**Comment by crazychris2404** [comment]
Can you attach a video showing this occurring please.

**Comment by crazychris2404** [comment]
Resolved via dms with the user.
Was a issue with key binds being incorrectly set for the phone.
