### ISSUE TITLE
Police remington not showing on back

### ISSUE THREAD

**Issue by Prxjecs** [CMGStudios/issue-tracker#35]
**Describe the issue you're facing**
The police Shotgun does not show on our backs, maybe add weapons on belly instead of back for realism 
**Steps to reproduce**
Nothing it’s bugged
**Expected behavior**
Showing on back
**Screenshots/Video**
N/A
**Additional context**
Iknow it’s a suggestion with the weapons on front but alot of PD want it.
**Any Texture Packs (if so list)**
N/A
**Perm ID**
611

**Comment by alfiellds** [comment]
Not a bug.
