### ISSUE TITLE
[Bug]: Can emote and put your hands up in Organ (leads to /th in Organ causing team sabotage and so on)

### ISSUE THREAD

**Issue by JunctionNinja** [CMGStudios/issue-tracker#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically you can emote and put hands up in organ when not supposed it.

This leads to abuse of /th and sabotage in organ (including /hug, /trophy<>, /ganghug and so on)

### Expected behaviour

Shouldn't be able to emote.

### Steps to reproduce

\*TRY TO PUT YOUR HANDS UP OR /e <emote>, /emotemenu, /dance<num> IN ORGAN BEFORE REPRODUCING*

1. Walk to the ATM in Organ heist (while Organ heist is active - including pre-phase)
2. Walk away from the ATM (don't have to get money out)
3. Now attempt to emote or get your hands up, now you can do it and anyone can you put it in a `/th`.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by arthur-rl** [comment]
Hi, @JunctionNinja thanks for the report. I'll get this added to our todo list and fixed as soon as possible!

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report I have prioritised this for developers to further review
