### ISSUE TITLE
[Bug]: Tow Truck completely broken

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#354]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When trying to Tow Vehicles it is completely broken, sometimes the Vechile instantly detaches, sometimes the Vehicle is being towed on your screen but not on their screen, Sometimes the Hook completely Breaks and is unusable, sometimes the Vehicle disappears.

### Expected behaviour

Pull out a tow truck / flat bed
Be able to drive around with a vehicle on your flat bed / hook.

### Steps to reproduce

1. Clock on AA Mechanic
2. Pull out a Tow Truck
3. Try towing an empty vehicle or try towing a vehicle with a player.

[Clip Here](https://streamable.com/knc1wm)

### Any Texture Packs? (If so list)

NVE

### CMG User ID

71613

**Comment by crazychris2404** [comment]
Issue is confirmed and forwarded to developers.
Thanks for the report
