### ISSUE TITLE
Long delay between being able to Revive people for NHS

### ISSUE THREAD

**Issue by 2140CMG** [CMGStudios/issue-tracker#355]
There is a delay of around 1-2 minutes between being able to revive people using the NHS menu, resulting in NHS members being screamed at to revive people quicker, this delay has only started recently so if a dev could take a look and try to fix or reduce the delay it would be appreciated

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report this is being looked into

**Comment by tom-gun** [comment]
Delay has been reduced to 30 seconds
