### ISSUE TITLE
[Bug]: Chat resets on respawn

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The chat clears once the player respawns.

### Expected behaviour

Chat stays so u can scroll to previous messages prior to dying.

### Steps to reproduce

Die
Respawn
Try scroll up in chat

### CMG User ID

910

**Comment by tom-gun** [comment]
Closed - This is intentional
