### ISSUE TITLE
[Bug]: wont let me access VIP gunstore even though im a VIP

### ISSUE THREAD

**Issue by muntaa** [CMGStudios/issue-tracker#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

been a week or so since i bought cmg supporter and got the VIP role and havent got access to all benefits. i am unable to purchase anything from the gunstore on vip island

### Expected behaviour

been a week or so since i bought cmg supporter and got the VIP role and havent got access to all benefits. i am unable to purchase anything from the gunstore on vip island

### Steps to reproduce

walk up to gunstore
select weapon
confirm purchase
purchase doesnt happen says 'You cant access this store!'

### Any Texture Packs? (If so list)

none

### CMG User ID

243104

**Comment by crazychris2404** [comment]
This can be resolved by donation support. 
https://discord.gg/vnJzCcmKpM
Please make a ticket here and it will be resolved
Any issues when making a ticket please DM me on discord (Chris.#2962) or respond here
