### ISSUE TITLE
Icant join server

### ISSUE THREAD

**Issue by Dlurp** [CMGStudios/issue-tracker#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It tells me:
- Try again at a later time.
- Check your network connection.
- If the issue persists, contact [ Robbster](https://forum.cfx.re/u/Robbster).

Couldn't load resource CMGVeh: Failed to open packfile: ReadBulk of header failed: Failed to fetch: Failed to add entry to local storage (download corrupted?)

### Expected behaviour

Cant join server

### Steps to reproduce

1

### CMG User ID

253538

**Comment by crazychris2404** [comment]
Developers are aware this is a temporary issue 
Closed
