### ISSUE TITLE
[Bug]: Need my discord SumTingWong#8915 linked to my perm id 1006

### ISSUE THREAD

**Issue by SumTingWong1006** [CMGStudios/issue-tracker#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Could somebody help me please my Perm ID 1006 is not linked to my discord SumTingWong#8915 this is due to me being unbanned and I lost access to my original account my discord was linked to  I got it fixed but for some reason it is unlinked could somebody link them both together since this is stopping me from making car reports and admins contacting me on discord.

### Expected behaviour

Could somebody help me please my Perm ID 1006 is not linked to my discord SumTingWong#8915 this is due to me being unbanned and I lost access to my original account my discord was linked to  I got it fixed but for some reason it is unlinked could somebody link them both together since this is stopping me from making car reports and admins contacting me on discord.

### Steps to reproduce

Please just relink my discord SumTingWong#8915 to my Perm ID 1006. 

### Any Texture Packs? (If so list)

None

### CMG User ID

1006

**Comment by crazychris2404** [comment]
Issue has been resolved
