### ISSUE TITLE
Experimental sounds not working 

### ISSUE THREAD

**Issue by Porthos999** [CMGStudios/issue-tracker#36]
**Describe the issue you're facing**
If I shoot someone it does not make a noise even tho I've got experimental features turned on 
**Steps to reproduce**
I've reset it via f2 multiple times and redownloaded fivem 
**Expected behavior**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**
Yes but it was happening before I installed it but no night by neevk 
**Perm ID**
215586

**Comment by arthur-rl** [comment]
Hi @Porthos999, when you shoot somebody does it only make the noise sometimes or does it never make the noise?

**Comment by Porthos999** [comment]
No noise

**Comment by Xotiic1** [comment]
when your on the loading screen try check to see if you have the chromium process is **NOT** muted

**Comment by Porthos999** [comment]
I think it is but I can't check

**Comment by Xotiic1** [comment]
how cant you check?

**Comment by Porthos999** [comment]
Can't get on pc rn

**Comment by loganuk** [comment]
Hello Porthos,

Check your volume mixer when you are next on your PC to see if it is muted - Unmuting it should solve this.

We'll close this issue in 8 hours, Reply before then if that does not solve it.

**Comment by alfiellds** [comment]
Resolved -- spoke to the user on Discord & they confirmed that they had their chromium process muted.
