### ISSUE TITLE
[Bug]: Rebel TP Bug

### ISSUE THREAD

**Issue by FlankzCMG** [CMGStudios/issue-tracker#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I was watching my friends stream in discord, he somehow had a glitch happen where it teleported him while in a red zone putting him down to the docks

### Expected behaviour

When you enter black market, you just stay there

### Steps to reproduce

When you enter, make it not teleport and do this glitch

### Any Texture Packs? (If so list)

None

### CMG User ID

269 - I am banned, I was watching my mate play so this is not his ID

**Comment by FlankzCMG** [comment]
https://www.youtube.com/watch?v=UlNPX8eLwco

**Comment by crazychris2404** [comment]
Thanks for the report I will take a look soon to confirm this 100% reproducable

**Comment by crazychris2404** [comment]
Unable to confirm that you fall through the map however i can confirm that this issue causes your character to keep running as a result of the redzone timer.
