### ISSUE TITLE
[Bug]: LFB Prison Door Perms Broken

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Clocked on as LFB and try to open a locked prison door the animation happens as if you have permissions to open the door
but the door does not lock / unlock.

### Expected behaviour

Be able to Lock / Unlock HMP Prison Doors whilst clocked on LFB.

### Steps to reproduce

1. Clock on LFB
2. Head to the Prison
3. Try unlocking / Locking a door that requires permissions.

### Any Texture Packs? (If so list)

None

### CMG User ID

71613

**Comment by crazychris2404** [comment]
Confirmed 
I have seen this previously
Thanks for the report
