### ISSUE TITLE
[Bug]: Cant put hands up after being searched

### ISSUE THREAD

**Issue by ghillieee** [CMGStudios/issue-tracker#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Just like when you get killed when on your knees, if you get searched while on your knees you cannot run or put your hands up (also i dont have a clip this is 100% reproducible) 

### Expected behaviour

Flex your t/k muscle, get searched, flex X muscle should be able to put hands up, right?

### Steps to reproduce

go on knees, get searched

### Any Texture Packs? (If so list)

I CANT REMEBER

### CMG User ID

221197

**Comment by crazychris2404** [comment]
Confirmed i believe this is caused by the new search animation forcing players to stand up. You can make your player be able to run again by after being searched getting back on your knees and getting up again. 

This will be forwarded to developers.

**Comment by tom-gun** [comment]
Fixed, thanks for the report!
