### ISSUE TITLE
[Bug]: Sandy PD MLO glitched

### ISSUE THREAD

**Issue by Luk3St1rrup** [CMGStudios/issue-tracker#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sandy PD is totally messed up, all of the props e.g. tables and doors are visible but the floors, walls and ceilings are invisible, literally see-through

### Expected behaviour

Being able to see walls.

### Steps to reproduce

Go to Sandy PD, walls are invisible
![unk](https://user-images.githubusercontent.com/90797980/156841019-e57c9778-1639-4765-a979-c97e991ea970.png)

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Confirmed thanks for the report

**Comment by crazychris2404** [comment]
This has since been resolved thanks for the report
