### ISSUE TITLE
[Bug]: NHS New Stretchers ( Summarized list for @Tom )

### ISSUE THREAD

**Issue by JaouadAR** [CMGStudios/issue-tracker#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

@Tom. Can you make the following adjustments to the stretchers:

- Fix the spamming sounds when using it or just remove the sound
- Add the ability to close the back door of the ambulance once you've put the stretcher in (could be some sort of stretcher radius thing where you can open / close the door if a stretcher is nearby
https://www.youtube.com/watch?v=DmHzybySHps
https://streamable.com/bibqjv
https://media.discordapp.net/attachments/752673429408317461/952179312906371082/unknown.png

- You can get into the stretcher while driving
- You can put infinite stretcher in the Back of the ambulance
- Make it so you can't get in vehicles while holding a stretcher / wheelchair
- Stretcher Can't be used with an Ambulance that you don't own 

- Most severe bug -
The Stretcher makes you teleport to a specific location under the map which is not that uncommon by what we've heard from other people within NHS so you might be able to reproduce it pretty easy hopefully.
See clip: https://www.youtube.com/watch?v=xQxVTXrhZi0

- This ticket is meant for @tom-gun 

Thanks in advance for taking your time.

### Expected behaviour

-See list above in description.

### Steps to reproduce

See the clips and pictures provided.

### Any Texture Packs? (If so list)

My own custom pack but this hasn't anything to do with the situation! :)

### CMG User ID

115411

**Comment by zenabzz** [comment]
Any update on this issue?
