### ISSUE TITLE
Missing vehicles 

### ISSUE THREAD

**Issue by Willbs96** [CMGStudios/issue-tracker#37]
**Describe the issue you're facing**
Some vehicles have gone missing from people's garages. I noticed this issue after the server reset on Friday. Personally, I'm missing the 300kg (Vapid Speedo Express) and my friend is missing the Speedo from simeons if this could be looked at the would be great thanks.
**Steps to reproduce**

**Expected behavior**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
452

**Comment by Xotiic1** [comment]
try looking in your VIP vehicles section, last night i was farming and noticed i was missing a 300kg in my folder and i looked in there and found it

**Comment by Willbs96** [comment]
Went through everything and check my rented out vehicles definitely missing. My friend also has the simeons speedo what he stores weapons in and that's also gone I don't know if it's anything to do with vehicles with speedo in the title.

**Comment by rubbertoe98** [comment]
Was this vehicle previously in a custom folder?

**Comment by rubbertoe98** [comment]
This should be resolved from next restart (@3pm), please let me know the issue persists.

**Comment by Willbs96** [comment]
okay thank you
