### ISSUE TITLE
[Bug]: pd dirt bike crashing game

### ISSUE THREAD

**Issue by Coolman1156** [CMGStudios/issue-tracker#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

everytime you get the "pd dirt bike" out of a garage  it crashes the persons game
[CfxCrashDump_2022_03_14_09_24_57.zip](https://github.com/CMGStudios/issue-tracker/files/8243510/CfxCrashDump_2022_03_14_09_24_57.zip)

### Expected behaviour

the dirt bike should just spawn in normally

### Steps to reproduce

1) go to a garage 
2) look at the pd dirt bike and it will crash the game 

### Any Texture Packs? (If so list)

No

### CMG User ID

204336

**Comment by tom-gun** [comment]
Thanks for the report, this has been forwarded to a car developer.

**Comment by tom-gun** [comment]
This has been fixed
