### ISSUE TITLE
[Bug]: Casino clothing 

### ISSUE THREAD

**Issue by BobbyTheBuildery** [CMGStudios/issue-tracker#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When inside the casino, you are unable to take on or off any clothing. when you click shirt nothing happens, if you have no shirt on you can't put it back on and if you have a shirt on you can't take it off. this is the same with all clothing.

### Expected behaviour

Clothing can be taken on and off inside the casino.

### Steps to reproduce

Press Y 
clothing menu comes up
click on shirt or any clothing and it should go blue when being taken off
then it will save

### Any Texture Packs? (If so list)

N/A

### CMG User ID

169174

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by crazychris2404** [comment]
Also to note its not to do with greenzones as works fine in other zones
