### ISSUE TITLE
[Bug]: Cannot Play on The Server, Handshaking with Server...

### ISSUE THREAD

**Issue by WattSkill** [CMGStudios/issue-tracker#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am trying to load on with a new account after getting unbanned by deviation like 2 months ago and it isn't working getting stuck on Handshaking with server, only server this happens on can load onto every other server

(Tom tried helping me from before but couldn't fix this issue)

### Expected behaviour

i cannot load on and it is just saying handshaking with server

### Steps to reproduce

Launch up fivem
Connect to cmg

### CMG User ID

131565 -- Dont have access to this anymore

**Comment by crazychris2404** [comment]
Is this still a issue?

**Comment by crazychris2404** [comment]
Closed due to no response

**Comment by postsmoke** [comment]
yea my friend had the same problem for a couple of days.
Tried deleting cache etc.  Nothing worked so far.
