### ISSUE TITLE
[Bug]: Fivem comuputer blackscreening 

### ISSUE THREAD

**Issue by Wolfzyyy** [CMGStudios/issue-tracker#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My Fivem every time i start loading into a server both of my screens go black it has been happening for 3 days, i have been trying multiple things but i have no idea what to do to fix it. Do you reckon you could help me?

### Expected behaviour

My Fivem every time i start loading into a server both of my screens go black it has been happening for 3 days, i have been trying multiple things but i have no idea what to do to fix it. Do you reckon you could help me?

### Steps to reproduce

Open Fivem
launch cmg
loading cmg 
then both screens blackscreen

### Any Texture Packs? (If so list)

i am using this texture pack https://www.youtube.com/watch?v=e73o62r9iVY&t=93s

### CMG User ID

243425

**Comment by tom-gun** [comment]
Hey Wolfzyyy, I have taken this discussion to #game-support where you posted your original query
