### ISSUE TITLE
Car extras issue

### ISSUE THREAD

**Issue by ghost** [CMGStudios/issue-tracker#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My corvette zr1 is always spawning without a rooftop and a spoiler when I go to the extras menu under /cmgclub when I enable them they don’t come on

### Expected behaviour

When I turn them on they are meant to turn on but they don’t 

### Steps to reproduce

/cmgclub -> manage privileges -> extras -> extra 1-4 

### CMG User ID

261797

**Comment by crazychris2404** [comment]
Please speak to a car developer to resolve this issue.
