### ISSUE TITLE
[Bug]: Renting bug

### ISSUE THREAD

**Issue by JoeBiden4** [CMGStudios/issue-tracker#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When renting out a truck the owner of the truck can then own another truck of the same type, when this happens the rent will run out and the person renting the truck will have the truck for along as the truck is being held by the original owner. this allows for people to buy and own the same vehicles multiple times over. since being discovered a few people have taken to using this to collect most of the custom import trucks, this then allows them to control the market and create a monopoly

### Expected behaviour

When a truck is rented out the owner should not be able to buy the vehicle, this would fix the problem

### Steps to reproduce

1. Rent out car
2. buy or rent out same car from someone else
3. wait for timer to run out 

### Any Texture Packs? (If so list)

no

### CMG User ID

1447

**Comment by crazychris2404** [comment]
Thanks for the report this is confirmed a bug and will be moved to high priority

**Comment by crazychris2404** [comment]
Intended features
