### ISSUE TITLE
Bug Report - Line 

### ISSUE THREAD

**Issue by exmmz** [CMGStudios/issue-tracker#38]
**Describe the issue you're facing**
A line across my screen which follows where I move or look,

**Steps to reproduce**
unknown

**Expected behavior**

**Screenshots/Video**
https://www.youtube.com/watch?v=YtPJkQJZ4JY

**Additional context**

**Any Texture Packs (if so list)**
no

**Perm ID**
199923

**Comment by arthur-rl** [comment]
This seems to be happening to a minority of people. You can fix this by relogging and the line should be gone. If after 3 or 4 attempts the line has not gone. Please re open this issue.

**Comment by rubbertoe98** [comment]
This is a known FiveM issue with build b2189, not something we can fix unfortunately.
