### ISSUE TITLE
[Bug]: will not let me sell my plat even tho i have 89 days

### ISSUE THREAD

**Issue by McGee2511** [CMGStudios/issue-tracker#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i try to sell my plat nothing happens and my blue tab box does not appear

### Expected behaviour

i cannot sell the plat that i have purchased of the store

### Steps to reproduce

https://medal.tv/games/gta-v/clips/hJ0VAkpCbmAxi/d1337ms1ISRg?invite=cr-MSw0bHosNTExODk4MzUs

### Any Texture Packs? (If so list)

yes i do im using citezen

### CMG User ID

250392

**Comment by crazychris2404** [comment]
In your fivem settings on the main menu please enable the fix ui lag option and tell me if this still occurs

**Comment by crazychris2404** [comment]
Closed due to no response
