### ISSUE TITLE
[Bug]: not able to purchase from the vip gun store (but have the subscription)

### ISSUE THREAD

**Issue by smaleszy** [CMGStudios/issue-tracker#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I purchased the basic supporter button and still cant access the vip gun store but received everything else that came with it.

### Expected behaviour

I purchased the basic supporter button and still cant access the vip gun store but received everything else that came with it.

### Steps to reproduce

.

### CMG User ID

265143

**Comment by crazychris2404** [comment]
Is this still occuring?

**Comment by crazychris2404** [comment]
Closed due to no response
