### ISSUE TITLE
[Bug]: i cannot pull a gun or knife or anything like that out.. admin could not help either

### ISSUE THREAD

**Issue by joeyonfivem** [CMGStudios/issue-tracker#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

cant pull a knife or gun out

### Expected behaviour

be able to use what i bought

### Steps to reproduce

https://medal.tv/games/gta-v/clips/hYB4Uo_mc-Zf6/d1337zAyaeyD?invite=cr-MSx0ZzEsNDQ2NDc1NzQs

### CMG User ID

267971

**Comment by ghillieee** [comment]
From the clip nothing is wrong + you didn’t show at least 1 second after pulling the knife out. (bind store all weapons it makes it easier)

**Comment by crazychris2404** [comment]
Did relogging resolve this issue? I cannot currently reproduce this

**Comment by crazychris2404** [comment]
Closed due to no response
