### ISSUE TITLE
[Bug]: Bus Job

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

At the end of the Bus job ( last stop ), the bus disappears instead of returning to the bus depot, also the job has low pay, the bus drivers get shit from people they should get payed more.

### Expected behaviour

Return to the bus depot after last stop instead of bus despawning

### Steps to reproduce

1. Clock on bus driver (city hall)
2. Complete the routes
3. The bus disappears at last stop

### CMG User ID

71613

**Comment by crazychris2404** [comment]
Thanks for the report
I will list this as low priority.

**Comment by tom-gun** [comment]
Closed - The last bus route will take you back to the depot
