### ISSUE TITLE
[Bug]:  not being able to buy amour at vip when i have gang license rebel license and plat please fix 

### ISSUE THREAD

**Issue by kickbacks** [CMGStudios/issue-tracker#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 not being able to buy amour at vip when i have gang license rebel license and plat please fix  ive tried relogging admins dont know what to do please fix this 

### Expected behaviour

 not being able to buy amour at vip when i have gang license rebel license and plat please fix  ive tried relogging admins dont know what to do please fix this 

### Steps to reproduce

![unknown](https://user-images.githubusercontent.com/103856488/163690320-305c7e22-f066-4fdb-a15b-22e8aa988287.png)

### Any Texture Packs? (If so list)

fps pack

### CMG User ID

259350

**Comment by crazychris2404** [comment]
This is the following information i have been given can you confirm whether you meet these requirements
He needs Supporter+ to access the VIP Gunstore.
- He needs gang license + plat to buy up to level 2 armour
- He needs rebel + plat to buy up to level 4 armour.

**Comment by crazychris2404** [comment]
Closed due to no response
