### ISSUE TITLE
[Bug]: Can't take off anti-lag on a car

### ISSUE THREAD

**Issue by bobbsteruwu** [CMGStudios/issue-tracker#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi you can't take off the anti-lag on a vehicle. If you try it will say not enough money.
The issue is absolutely not in the money.

### Expected behaviour

I expect to be abel to take it off

### Steps to reproduce

1. Put anti-lag on
2. Try to take off anti-lag
3. Results

### Any Texture Packs? (If so list)

no

### CMG User ID

1234

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report moved to high priority

**Comment by tom-gun** [comment]
Closed - This has been fixed
