### ISSUE TITLE
[Bug]: Can't pull out weapons in Organ (PD side)

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue has been ongoing for ages but somehow went unreported.

Basically, there is a bug that puts you in a "handcuffed state" (observed by falling and putting you in a cuffed animation on way up). This causes you to not pull out guns after you put one away, it can also impact when you come out causing you to not be able to shoot or get out guns until you get cuffed/uncuffed (or relog). However, this is impossible while in Organ and basically causes you to do nothing.

It's usually random whenever you press `Alt` (usually while aiming or tabbing out) and doesn't happen 100% of the time.

I've tried a lot of things in attempt to fix the issue, was unsuccessful in all of them:

- `Did /finger(2)`, `/ma` and `/bong`
- Getting out a shield with /shield
- Falling over (which will show you in a cuffed animation) and begging to be cuffed/uncuffed.
- Testing out /uncuffme for no reason at all.
- Searched someone
- Got someone to search me
- Did a `/nearby` emote
- Called someone on the phone
- Buying a new gun to see if this mitigates the issue
- Storing all guns and equipping again
- Whistled a couple times.
- Trashed an item
- Given an item to someone else

### Expected behaviour

Should be able to pull out guns no matter what, even after you press `Alt` and get yourself out of the radio state.

### Steps to reproduce

1. Enter Organ clocked on as PD
2. Hold or aim a gun and press `Alt` (may take a couple tries in some cases (could try tabbing out))

**THIS SHOULD PUT YOU IN A STATE WHERE YOU CANNOT SHOOT**

3. Whistle or do `/finger` or `/finger2`
4. Put your gun away
5. Observe how it is now impossible to get another weapon out

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by crazychris2404** [comment]
Thanks for the report.
This has been moved to low priority due to not always being able to reproduce.

**Comment by tom-gun** [comment]
Closed - This has been fixed
