### ISSUE TITLE
Ladders in LSD redzone not working

### ISSUE THREAD

**Issue by DAVEcmg** [CMGStudios/issue-tracker#39]
**Describe the issue you're facing**
Ladders on roof of lsd north side dont work you cant climb
**Steps to reproduce**
go to the screenshot 
**Expected behavior**
should work
**Screenshots/Video**
https://cdn.discordapp.com/attachments/406898780789800972/861218831073542144/unknown.png
**Additional context**
could be due to mlo as they used to work when the mlo wasnt there
**Any Texture Packs (if so list)**
n/a
**Perm ID**
156

**Comment by rubbertoe98** [comment]
Thank you for the report, will be fixed.

**Comment by MrLexo** [comment]
Pretty sure I looked into this locally and fixed this so will check and push a fix.

**Comment by MrLexo** [comment]
I have rectified this issue and also fixed some other problems that I found while testing the area. This has been pushed to @rubbertoe98 for testing and adding to the live server. Thanks for your bug report @DAVEcmg!

**Comment by rubbertoe98** [comment]
Fixed by @MrLexo
