### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by MegaMining** [CMGStudios/issue-tracker#390]
[CfxCrashDump_2022_04_25_18_41_53.zip](https://github.com/CMGStudios/issue-tracker/files/8557136/CfxCrashDump_2022_04_25_18_41_53.zip)

**Comment by crazychris2404** [comment]
Put this in crash zips channel on discord

**Comment by MegaMining** [comment]
I can't. It wont let me verify

James

**Comment by crazychris2404** [comment]
What is your ID?

**Comment by MegaMining** [comment]
Mr. Mega#3784

**Comment by crazychris2404** [comment]
Try now
