### ISSUE TITLE
[Bug]: Can’t push cars

### ISSUE THREAD

**Issue by Jake-Fivem** [CMGStudios/issue-tracker#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I can’t push any vehicle using the key bindings shown (SHIFT + E)

### Expected behaviour

I can’t push the cars when they’re broken down or anything it’s really frustrating.

### Steps to reproduce

Not sure how to reproduce this as it’s not happening to my friend or a few admins I’ve had look at the issue.

### Any Texture Packs? (If so list)

None

### CMG User ID

269480

**Comment by crazychris2404** [comment]
Please can you check your keybinds and let me know which keys you have bound to sprint and pick-up please

**Comment by Jake-Fivem** [comment]
I have sprint as “R” and I have pick up items as “E”.

**Comment by ghillieee** [comment]
You might have to bind sprint to left shift for it to work, not sure though

**Comment by crazychris2404** [comment]
This will be why it does not work for you.
For you pushing vehicles will be r and e

**Comment by tom-gun** [comment]
Confirmed that R + E works for the user, closing
