### ISSUE TITLE
[Bug]: PD PNC not working

### ISSUE THREAD

**Issue by Luk3St1rrup** [CMGStudios/issue-tracker#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The PD PNC "f7" is not working, you can press f7 and it comes up but you cannot press on person search, there is just a blue screen.

### Expected behaviour

for the PNC to actually work and be able to fine people

### Steps to reproduce

Ask for someones ID
Press f7
Press person search
nothing happens

### Any Texture Packs? (If so list)

I have an FPS booster pack but another person has the same bug so it isnt related to texture pack

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Confirmed Thanks for the report
Moved to high priority

**Comment by tom-gun** [comment]
Thanks for the report, this has been fixed.
