### ISSUE TITLE
[Bug]: Last Figurine is Bugged Location not viewable

### ISSUE THREAD

**Issue by Crzy-Amar** [CMGStudios/issue-tracker#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have searched for the last figurine over 3 weeks, checked all locations checked the maps the video still cant be found.

### Expected behaviour

For last 3 weeks I have searched for the last figurine Iv had admins help me, iv checked every location 5 times Iv also had other players take me to every location and Its still not viewable. I have contacted admins they had told me to re check which I have done multiple times and told me if it still cant be found request a bug report. 

### Steps to reproduce

I have literally had everyone help me.

### CMG User ID

246025

**Comment by LuciddDEVV** [comment]
There's a few which are within redzones , I have a figurines map which I can send you on discord to see if you have missed any out .

**Comment by Crzy-Amar** [comment]
hi pal i have maps, pictures and video links rebel red zone found h redzone found iv literally been every where iv been so many places i can literally take u to all the spots without a map thats how many times iv been

**Comment by crazychris2404** [comment]
Thanks for your discussions within the community about this issue I will list this as a trivial issue and forward to developers where they can look further into problem

**Comment by CapJohnny077** [comment]
bro i still have this problem, its so annoying

**Comment by crazychris2404** [comment]
Can you do the /collectiblesremaing

**Comment by CapJohnny077** [comment]
> Can you do the /collectiblesremaing

i know it says 1 is left and i know wich one it is but i cant pick it up

**Comment by crazychris2404** [comment]
Closed
A developer will contact you privately to discuss this as it seems to be a issue specific to you
