### ISSUE TITLE
[Bug]: vehicle garage

### ISSUE THREAD

**Issue by CannibalRyan** [CMGStudios/issue-tracker#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My burrito van has disappeared from my garage

### Expected behaviour

Bought the van last night, logged on this morning it was there, re logged and its vanished..

### Steps to reproduce

.

### Any Texture Packs? (If so list)

Ni

### CMG User ID

269095

**Comment by crazychris2404** [comment]
This should now be fixed

**Comment by CannibalRyan** [comment]
It has not re appeared

**Comment by crazychris2404** [comment]
Please try relog and it should be there

**Comment by CannibalRyan** [comment]
I have re logged, its still not there.

**Comment by crazychris2404** [comment]
Try once more please should be done

**Comment by CannibalRyan** [comment]
Its there! Thank you
