### ISSUE TITLE
[Bug]: Fix the rig ladders through the floor at rig ASAP

### ISSUE THREAD

**Issue by x2Adz** [CMGStudios/issue-tracker#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i got throught the ladder then my frind carries me out then we die like fucks sake fix it

### Expected behaviour

Its causing me to lose guns everytime

### Steps to reproduce

?

### CMG User ID

221997

**Comment by ghillieee** [comment]
your id is 800 after my one my one is 221197

**Comment by crazychris2404** [comment]
Can you please attach a video of this occuring so i can forward this to developers

**Comment by crazychris2404** [comment]
Closed due to no response
