### ISSUE TITLE
[Bug]: spawning under map

### ISSUE THREAD

**Issue by GavLive1** [CMGStudios/issue-tracker#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My friend keeps spawning under map when server resets or when he dies keeps having to reset his fit i think its a bug with spawn manager or one of them scripts

### Expected behaviour

spawn undering map on server restart with default clothes and having to change everytime

### Steps to reproduce

tried changing char spoke to couple admins change fix reinstalled game to

### Any Texture Packs? (If so list)

no

### CMG User ID

250391 thats his id

**Comment by crazychris2404** [comment]
Developers are looking into this 
Thanks for the report

**Comment by tom-gun** [comment]
This has been fixed for the next scheduled restart
