### ISSUE TITLE
[Bug]: Changing Peds kicks you out of Organ Heist

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically, changing your ped (incl. equipping a horse and changing gender) kicks you out of Organ.

Found this while also finding out it's a potential (tested only twice) fix (other than likely forcing SetEnableHandcuffs to false) to the bug where you can't shoot if you tab out while aiming (#389).

[Clip of this happening](https://streamable.com/g2tq39)

### Expected behaviour

Should keep me in organ normally when changing ped.

### Steps to reproduce

1. Go in Organ
2. Change ped via clothes menu (or do /policehorse)
3. Observe how you get absolutely stuck

### CMG User ID

194575

**Comment by crazychris2404** [comment]
Thanks for the report moved for developers

**Comment by tom-gun** [comment]
Closed, this has been fixed for the next scheduled restart.
