### ISSUE TITLE
I was dead and there was explosions happening and i was getting kills when i was dead [Bug]: 

### ISSUE THREAD

**Issue by Markuss18** [CMGStudios/issue-tracker#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i dead and few second later i hear explosions and then i started to get kills 

### Expected behaviour

https://www.youtube.com/watch?v=IMyEVdEHUpk 
Go To 8:30min

### Steps to reproduce

idk have a clue game just bugged out

### Any Texture Packs? (If so list)

nope

### CMG User ID

199126

**Comment by tom-gun** [comment]
Not a bug, please contact the admin that banned you.

**Comment by Markuss18** [comment]
it was a bug 
https://youtu.be/IMyEVdEHUpk
