### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RonnieBiggz** [CMGStudios/issue-tracker#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm not receiving a code when connecting to the GTA server.. I need the code to verify on discord. Please help. My discord is Ronnie#6505

### Expected behaviour

I am failing to connect to the server as it just says attempting to connect 1, 2, 3...
 

### Steps to reproduce

1. Join server.
2. Not being able to connect.

### CMG User ID

Dontknow

**Comment by crazychris2404** [comment]
Does this still occur?

**Comment by crazychris2404** [comment]
Closed due to no response
