### ISSUE TITLE
[Bug]: /me command

### ISSUE THREAD

**Issue by JorPet1** [CMGStudios/issue-tracker#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you to a /me command in chat, and start with a number, the first number doesnt pop up over the character.

### Expected behaviour

Wont show up over character

### Steps to reproduce

1. Open chat
2. Write f.eks: /me 250 bullets
3. Press enter
4. Over you character, it will just show 50 bullets

### Any Texture Packs? (If so list)

none

### CMG User ID

605

**Comment by crazychris2404** [comment]
Thanks for the report
This is confirmed thanks for the report

**Comment by tom-gun** [comment]
Closed - This has been fixed and colours will work again
