### ISSUE TITLE
Collectibles Not Working

### ISSUE THREAD

**Issue by Frostt2t** [CMGStudios/issue-tracker#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

collected all 50 toys, but fell from a height whilst getting the one at airport. went back to it and could still see it. re logged and it disappeared so now im stuck with one collectible left despite already collecting it. my friend lukey ID 167390 was there with me the entier time collection the toys and he got issued to reward whereas i did not. anyway i can get the 7 days plat seeming as i collected all and did not receive the reward.

### Expected behaviour

I expected it to give me the reward however, im stuck on 49 collected despite my friend getting the reward. (he was there for every one we collected together)

### Steps to reproduce

1. collect all collectibles
2. one at airport -fall off the top whilst collecting
3. should say collected but not actually count.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

272052

**Comment by crazychris2404** [comment]
After speaking to a developer it would mean you still have 1 to collect.

**Comment by Frostt2t** [comment]
> After speaking to a developer it would mean you still have 1 to collect.

i went round each 50 again with somebody else, they got the reward and i could not see any of them indicating ive collected them all. a few people have told me its happened to them too

**Comment by alfiellds** [comment]
Try /collectiblesremaining
