### ISSUE TITLE
[Bug]: Horse Bug leads to Type #45 AC Ban

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically the horse will drop a ped (if you taze the ped **on** the horse and immediately get off it.

In some cases (don't know an exact cause of it dropping a gun), this'll drop a **stock GTA** Pistol and you end up getting banned for picking it up.

### Expected behaviour

Shouldn't drop a gun and also shouldn't type (#)45 you.

### Steps to reproduce

1. Get a police horse out (somehow)
2. Get someone to taze the ped on the horse
3. Get rid of the horse with space.
4. Observe how the ped falls
5. Kill the ped
6. Notice how a gun may drop in some cases and you get type 45'd for picking it up.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by crazychris2404** [comment]
Confirmed
https://canary.discord.com/channels/458382797103693867/745625690308870154/977571542709964800

**Comment by tom-gun** [comment]
Thanks for the report, this has been fixed.
