### ISSUE TITLE
[Bug]: scuberdiving 

### ISSUE THREAD

**Issue by Joflin** [CMGStudios/issue-tracker#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I get a pop up saying “ your boat has been destroyed ” wich doesnt happen and also didnt pay me 6 times for my runs

### Expected behaviour

Well its supposed to pay me and i didnt get paid 6 times 5 times yesterday and once today when it said my boat was destroyed

### Steps to reproduce

1. Start job
2. Collect everything 
3. Get back in boat
4. Drive back to hq
5. Get paid

### CMG User ID

275113

**Comment by crazychris2404** [comment]
Closed
This is already reported
