### ISSUE TITLE
Falling through beds at NHS

### ISSUE THREAD

**Issue by alfiellds** [CMGStudios/issue-tracker#41]
**Describe the issue you're facing**
When using a pre-spawned bed at St Thomas Hospital, you are in the bed visibly fine for yourself, however for others you are falling constantly under the map - this is quite bad for RP as it also affects voice chat. 

**Steps to reproduce**
Use any pre-spawned bed at St Thomas. 

**Expected behaviour**
You will fall under the map visually for others.

**Screenshots/Video**
https://streamable.com/q59bdj

**Additional context**
This issue does not occur for any stretchers spawned by players with /stretcher.

**Any Texture Packs (if so list)**
N/A

**Perm ID**
71413

**Comment by rubbertoe98** [comment]
Fixed.
