### ISSUE TITLE
[Bug]: All 50 Little characters to collect for cmg 7 days plat, only appears as 49/50.

### ISSUE THREAD

**Issue by PropaWrongun** [CMGStudios/issue-tracker#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

50 Characters when collected only pop up that 49 have been collected, so u cannot collect plat. Once all 50 locations have been done, for some ppl like me, the fraction of the ones completed is 49/50 even though all 50 locations have been met.

### Expected behaviour

Dont have an answer for this box.

### Steps to reproduce

Try collect all 50 characters and for some players this may only say 49/50

### CMG User ID

222030

**Comment by crazychris2404** [comment]
After speaking to developers 
This is not a bug and you are missing 1 collectible please keep searching
