### ISSUE TITLE
[Bug]: Shank Shop “ammunition”

### ISSUE THREAD

**Issue by EuIen** [CMGStudios/issue-tracker#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the shank shop if buying a melee weapon, there is an option to “refill ammo” but a melee doesn’t have ammo and when double clicking it takes a % of your money from you.

### Expected behaviour

Once bought should not be able to buy until you have stored it in your inventory.

### Steps to reproduce

1 • walk into shank shop
2 • go to the blip to buy a shank
3 • purchase a shank and click it twice 
4 • you will see it takes a % of the money from your cash

### Any Texture Packs? (If so list)

Ceres 

### CMG User ID

214124

**Comment by crazychris2404** [comment]
Confirmed

**Comment by tom-gun** [comment]
Closed, this has been fixed for the next scheduled restart.
