### ISSUE TITLE
[Bug]: Cant take things out of a boot in a 300kg vehicle . 

### ISSUE THREAD

**Issue by FocusZK** [CMGStudios/issue-tracker#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

You cant get things out your boot in a 300kg vehicle 

### Expected behaviour

i try to take things out my 300kg boot and it just doesn’t let me, like it accepts it but doesn’t go into my inventory 

### Steps to reproduce

…

### CMG User ID

45

**Comment by tom-gun** [comment]
Thanks for the report @FocusZK. Can you please provide the vehicle name and a screenshot of the items in the vehicle

**Comment by tom-gun** [comment]
Closed - Not enough information to act on and OP is no longer contactable through GitHub or Discord.
