### ISSUE TITLE
[Bug]: hmp seizing

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you seize illegals as hmp it doesnt seize prison items that you can pick up from the ground

### Expected behaviour

When seizing illegals it should take contraband

### Steps to reproduce

cuff a prisoner
Seize illegals
poof nothing

### Any Texture Packs? (If so list)

nothing

### CMG User ID

14009

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by liltoby** [comment]
Surely it should not remove picked up items as they are part of the RP? If you start removing picked up items on search it will make it impossible to make shank or wire cutters?

**Comment by Olz7** [comment]
No you can only remove items if the prisoner does not have a valid reason to why they have it, if a prisoner had a blade and they said they were using it to shave their facial hair that’s a valid reason same goes for all other items in the prison

**Comment by tom-gun** [comment]
There can be legitimate use cases for having these items so wouldn't make sense to have them as seizable.

**Comment by wooffighter** [comment]
there should be some other method to take off these items then as we tell the inmates to hand it to us or we must use the rob function, not an easy method
