### ISSUE TITLE
[Bug]: Boot full of prison items was randomly empty when i opened it.

### ISSUE THREAD

**Issue by liltoby** [CMGStudios/issue-tracker#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have spent the last week collecting all the items from prison as I wanted to create a prison riot with multiply people with shanks. I go into prison collect all the picks ups then leave. I get my 20kg out of the garage in front of the prison for about 10 seconds while I fill it with the new prison item. It has never been out of the garage for more than 30 seconds so it doesn't make sense that somebody would have been able to pick it up. There were also around 60 items in there so 60kg, If somebody was to pick it they would have had to pick it in under 30 seconds, and also had a bag in order to completely clear it out. This doesn't seem viable considering I am in it or next to it as it only comes out for me to put stuff in.

### Expected behaviour

For inventory that I spent days putting together to not vanish.

### Steps to reproduce

I do not know how you would reproduce as I do know how all my stuff vanished.

I can see there was a ticket raised regarding prison items before this one. Would have had anything to do with all my items vanishing. I have a screenshot of my boot at 11am 04/06/2211 a
![Prison Items](https://user-images.githubusercontent.com/100544552/172045293-9b5d0a24-5789-4a55-924d-bc0be20eed88.png)
m

### Any Texture Packs? (If so list)

NO

### CMG User ID

647

**Comment by tom-gun** [comment]
Closed - No actionable information to work off and there haven't been other reports of boots vanishing. Multiple vehicles you owned that night got searched, and it's possible it got lockpicked at some point.
