### ISSUE TITLE
[Bug]: No easy way to re verify on cmg

### ISSUE THREAD

**Issue by jettersafc** [CMGStudios/issue-tracker#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am having a issue when trying to do my NHS training. Long story short when I verified on cmg it was on my old discord which was deleted and now cause of whitelist issues it is not detecting that I have been whitelisted on the NHS bot so I cannot clock on.
I am trying to re verify when loading into cmg but it will not appear.

### Expected behaviour

N/A

### Steps to reproduce

N/A

### Any Texture Packs? (If so list)

No

### CMG User ID

219425

**Comment by crazychris2404** [comment]
This is resolved by contacting staff and they can get your discord reverified.
Ways around this are being looked into
