### ISSUE TITLE
[Bug]: Cant see discord code

### ISSUE THREAD

**Issue by smw2701** [CMGStudios/issue-tracker#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I cant find my code to verify my discod, where to find it?

### Expected behaviour

It to show on start up

### Steps to reproduce

none

### CMG User ID

271777

**Comment by Trapstar-UK** [comment]
This is no bug.

The reason why you can´t find the verification role is because you already were verified before, you most likely left the discord and re-joined here recently.

I would suggest getting in contact with a staff member in-game and ask for the verified role in the discord.

**Comment by Pugles-Beancat** [comment]
Hi,

As of 12/06/2022, If you face this issue all you need to do to resolve it providing you are using the Discord account you originally verified with when playing is to just Re-Join the server.

Additionally if you have lost any donation roles such as supporter, baller etc. You can regain them doing the !getroles command in discord.
