### ISSUE TITLE
Rappelling from NPAS helicopters

### ISSUE THREAD

**Issue by PapiPhoenix1** [CMGStudios/issue-tracker#42]
**Describe the issue you're facing**
Whenever rappelling from helicopters, you will always fall over and never stay standing. is very annoying during situations
**Steps to reproduce**
N/A
**Expected behavior**
You will fall over and not be able to stand up for up to 10 seconds
**Screenshots/Video**
N/A
**Additional context**
N/A
**Any Texture Packs (if so list)**
N/A
**Perm ID**
178513

**Comment by alfiellds** [comment]
Thank you for the report, the developers will look into this shortly.

Note for developers -- this issue does not always occur.

**Comment by rubbertoe98** [comment]
Fixed from next restart.

**Comment by rubbertoe98** [comment]
Wrong issue, woops.

**Comment by rubbertoe98** [comment]
Fixed from next restart.
