### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wispa5m** [CMGStudios/issue-tracker#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i keep getting this error message after i get kicked out of the game and its been over 6 months and no one has still helped me, it only happens on cmg

### Expected behaviour

.

### Steps to reproduce

![Desktop Screenshot 2022 06 17 - 12 05 47 43](https://user-images.githubusercontent.com/91843213/174435369-f3d2e1b1-811a-4bab-b34e-c7f455f00b71.png)

### Any Texture Packs? (If so list)

none

### CMG User ID

i dont know because i get kicked from the game

**Comment by crazychris2404** [comment]
After speaking to developers this will be a result of a poor internet connection
This is not a issue directly related to CMG

**Comment by wispa5m** [comment]
thats weird because when i load on im on 20ms and it only happens on cmg

**Comment by wispa5m** [comment]
and i can play cmg minigames but not cmg
