### ISSUE TITLE
PROBLEM - BALLER LOCK CAR

### ISSUE THREAD

**Issue by Slippy12** [CMGStudios/issue-tracker#422]
JAGUAR F-Type L3D EDDITION - ftypel3d - I cannot save my secondary colour on my car or neon Kits as when I get a new car out of the garage it resets back to default. happening to both me and my friend as we both own the same car. please can you have a look at it

**Comment by crazychris2404** [comment]
Please make a car report in the discord or DM a car developer to resolve this issue
