### ISSUE TITLE
[Bug]: Los Santos mods for Bmw i8 not working

### ISSUE THREAD

**Issue by RialeFPS** [CMGStudios/issue-tracker#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The mods I buy from Los Santos for my car (BMW I8) are not working.

I know you have to buy them, then press equip. This is where it bugs and says its not purchased but it is.

### Expected behaviour

Car mods not working on BMW i8

### Steps to reproduce

Purchase Supreme Rank
Select BMW 18 as VIP car
Go to Garage in game
Take out BMW i8 and bring to Los Santos Customs
Try to purchase mods

### CMG User ID

281690

**Comment by crazychris2404** [comment]
This is a issue for car developers
Please DM a car dev on discord with the spawn code of the car and details about the problem
You can find the spawn code of the car by getting the vehicle out of a garage and pressing F8
