### ISSUE TITLE
Fuel state saving issues

### ISSUE THREAD

**Issue by Xotiic1** [CMGStudios/issue-tracker#43]
**Describe the issue you're facing**
when I log in and pull the Vapid speedo express out it has fuel but when I put it away and bring it out again it looses the fuel it has 

**Steps to reproduce**
relogging 

**Expected behavior**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
90861

**Comment by Xotiic1** [comment]
also happening to "superkart"

**Comment by arthur-rl** [comment]
How long do you wait before storing your vehicle after refuelling?

**Comment by Xotiic1** [comment]
i stored it after fueling it up with a jerry can

**Comment by rubbertoe98** [comment]
Will be fixed.

**Comment by Xotiic1** [comment]
cheeres

**Comment by alfiellds** [comment]
As a temporary solution, try waiting around 45 seconds to a minute before storing your vehicle after filling it up.

**Comment by loganuk** [comment]
Hello @Xotiic1 

I think a dev patch was made recently in updates regarding fuel. Can you test to see if this is fixed?

**Comment by Xotiic1** [comment]
fixed now
