### ISSUE TITLE
[Bug]: Long range blips missing

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

HMP and LFB are missing from the long range blips

### Expected behaviour

HMP and LFB should be able to see long range blips and be seen on them

### Steps to reproduce

When HMP or LFB clocked on
Someone on PD/NHS check long range blips
They cant be seen on long range

### CMG User ID

910

**Comment by tom-gun** [comment]
Closed - This is intentional
