### ISSUE TITLE
[Bug]: Got sold a vip veichle when im not vip and i lost all my money!

### ISSUE THREAD

**Issue by Wwaeee** [CMGStudios/issue-tracker#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

So my friend, DJSmilez sold me a VIP veichle when im not vip and now i cant acess it, we both agree that i can get my money back and he can get the car back, i would like help with this issue considering ive lost 750k for nothing!

### Expected behaviour

I'm facing an issue then where ive lost 750k cus i got sold a vip veichle by accident from my friend and we are trying to solve this so he gets the car back and i get the money back!

### Steps to reproduce

1. The vip car seller  requests to sell to me
2. i accept it
3. i lose 750k and have no access to the vip garage

### Any Texture Packs? (If so list)

no

### CMG User ID

285450

**Comment by crazychris2404** [comment]
This is something you need to be cautious of. There is annoyingly nothing that can be done however i will forward a suggestion to make it so VIP cars cant be sold to non VIP players
