### ISSUE TITLE
[Bug]: WRONG DİSCROD VERİFİED HELP PLS

### ISSUE THREAD

**Issue by tagoo0** [CMGStudios/issue-tracker#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

can u help me rly quick pls i verify my fivem acc to other discord acc and that discord acc i verified banned for spam and this is my new acc and i cant verify this discord so i cant see the other channels other acc is ekmekarasıekmek#4084  and admins are not responding my dm's and now its stuck on connecting server screen if i reinstall fivem i cant log back my acc and i paid the acc

### Expected behaviour

idk

### Steps to reproduce

idk help

### CMG User ID

281928

**Comment by crazychris2404** [comment]
This is not a issue for a bug report
please DM a staff member about this problem
