### ISSUE TITLE
[Bug]:  teleporter

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

go to a teleporter then go where every and then your ui is broken and the in game custom crosshair is not in the middle of you screen the only way you can fix this is by going back to where the teleporter is   clip https://youtu.be/ndgzfQLkj3M

### Expected behaviour

should not break  your ui or crosshair  

### Steps to reproduce

1. go to a teleporter
2. teleporter to where every 
3. then your ui and custom crosshair is broken 

### CMG User ID

68457

**Comment by crazychris2404** [comment]
Confirmed
More info can be found [here ](https://canary.discord.com/channels/458382797103693867/860642278610829342/1001506607445856286)
