### ISSUE TITLE
[Bug]: Bobcat Breaks Pet Shop Preview

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically, the bobcat breaks the entire pet shop preview (nothing much to say exactly).

This also includes any messages and the animal itself. Only the menu will show and will remain broken until you relog.

### Expected behaviour

Should be able to freely scroll without error.

### Steps to reproduce

1. Go to pet shop
2. Scroll down to the bobcat
3. Observe how you won't be able to see any info ("This pet cannot attack", "You viewing the xyz" and no preview) about any other pets after scrolling  over it.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Closing, this appears to be fixed
![image](https://user-images.githubusercontent.com/97990837/190603041-4d4a3ebf-e196-43ab-bdeb-74f1ee6c4fba.png)
