### ISSUE TITLE
[Bug]: Stat menu keeps appearing when keybind isn't pressed

### ISSUE THREAD

**Issue by maxreid250** [CMGStudios/issue-tracker#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Stat menu keeps appearing on my screen without anything being pressed

### Expected behaviour

The Statistics menu keeps appearing on my screen when keybind isn't being pressed 

### Steps to reproduce

1. F9 which is the stat menu
2. When it disappears it comes back occasionally up to 30 seconds later
3. Press F9 to get rid of it but it repeats itself usually occurs when I tab back in

### Any Texture Packs? (If so list)

N/A

### CMG User ID

204066

**Comment by crazychris2404** [comment]
This is not reproduceable please remake a issue once you experience this consistently
