### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by Lxdzn** [CMGStudios/issue-tracker#45]
Im getting so much FPS drops in certain areas of the city this was not happening before an update

**Comment by alfiellds** [comment]
Please can you provide more detail and fill out the report in the following format:

```
Describe the issue you're facing

Steps to reproduce

Expected behavior

Screenshots/Video

Additional context

```
Any Texture Packs (if so list)

Perm ID

**Comment by Lxdzn** [comment]
My FPS drops so much during driving around some areas of the city and this was not the case a few weeks back and IDK whats happened.

I have lowered some settings however these seemed to not make it any better.


I have a no sky texture pack
211410

**Comment by alfiellds** [comment]
You still haven't filled out a report following the format. Please make a new report following the format.
