### ISSUE TITLE
[Bug]: Car Boot

### ISSUE THREAD

**Issue by SpoTIsLegend** [CMGStudios/issue-tracker#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello i have  a issue with my car boot. its been not working for 1 year or more. whene i press e on my car and open boot it says i dont have keys. its my car i bought it but it says i dont have keys. and whene i press lockpick it says owner is not online.
and i have another glitch. every time i spawn in city my clothes reset and i spawn in the same location everytime, legion garage!
thanks for reading! bye.

### Expected behaviour

Im expecting a fix because its pretty serious bugs i listed.

### Steps to reproduce

idk what this is?

### CMG User ID

71423

**Comment by crazychris2404** [comment]
Hi after speaking to developers I have the following way to hopefully resolve this for you 

you will need to reinstall fivem and delete your kvs file located here `%appdata%\Roaming\CitizenFX\kvs` 

if you still experience this issue please reopen this

**Comment by SpoTIsLegend** [comment]
IT HELPED 4 bugs thanks bro much love
