### ISSUE TITLE
[Bug]: Phone Number

### ISSUE THREAD

**Issue by RKZ1CO** [CMGStudios/issue-tracker#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I go on settings, and then go on to phone number its just hashtags, and no numbers there as if I havent got one and just started, not sure what this is.

### Expected behaviour

Not having a phone number.

### Steps to reproduce

Open Phone
Go to settings
Look at phone number

### CMG User ID

295663

**Comment by crazychris2404** [comment]
Are you still experiencing this problem ?

**Comment by kdsmokingog** [comment]
@crazychris2404 my boyfriend and i always have this problem and have to quit the server multiple times until it fixes itself. it's very annoying. resetting the phone also doesn't help.

**Comment by packfile** [comment]
@RKZ1CO Your in game phone number is 07067190189. Could you provide a screenshot of what you see? Same for @kdsmokingog

**Comment by kdsmokingog** [comment]
![FiveM® by Cfx re -  UK_EU  CMG #1 ___ British Themed ___ Economy ___ Arma 3 Vibe ___ discord gg_cmg 2022_09_20 18_23_56](https://user-images.githubusercontent.com/113561770/191313246-d5f016a1-3065-4360-9f43-fdf6846890f3.png)
Here you go, it happens at very random times. I've heard a few people in game also have had the same issue.

**Comment by crazychris2404** [comment]
Closed
Please DM me on discord Chris.#2962 and i can further assist as currently this is a personal issue and not affecting the majority of the server
