### ISSUE TITLE
[Bug]: Unable to pull out car after DV'ing or storing

### ISSUE THREAD

**Issue by Pugles-Beancat** [CMGStudios/issue-tracker#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Occasionally a vehicle will not be able to be pulled out of a garage even though it is stored

### Expected behaviour

Unable to pull out vehicles that have been stored

https://medal.tv/games/gta-v/clips/xefH0LmunLQtA/d1337e7DJjZN?invite=cr-MSxkRnksMzgyMzE3MTgs

### Steps to reproduce

1. Get out a car
2. Store it
3. Try to pull it out

### Any Texture Packs? (If so list)

N/A

### CMG User ID

836

**Comment by crazychris2404** [comment]
Personally I have only experienced this when deleting a car and then getting it straight away but if you wait a few seconds it shouldn’t occur. I will ask around and see if anyone has still experienced a major issue with this as we had previous reports of which no issues were found

**Comment by crazychris2404** [comment]
Spoken to developers if you wait a short time you can pull cars out
