### ISSUE TITLE
Plat/plus 

### ISSUE THREAD

**Issue by Chazinho97** [CMGStudios/issue-tracker#456]
Paid for plat of the store and won 336 hours of plus off the drops currently being given out, claimed my kit from plus (pistol smg morphine taco's and armour) But now i can't sell my remaining 7 days of plat and i haven't had a kit from it also.

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by AlexGonzales2** [comment]
I'm also expirinceing this issue, luckily there's a reset coming up, so I'll see if this fixes it.

**Comment by crazychris2404** [comment]
Closed
This is no longer relevant and was only a problem during the drops for 300k users
