### ISSUE TITLE
[Bug]: Driving Test Not Completing 

### ISSUE THREAD

**Issue by Hazzenator** [CMGStudios/issue-tracker#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have attempted to complete my driving test on 2 occasions now (totalling £40,000 spent) and both times the test has frozen and not gone any further when parking in the final bay. I am left on a screen with the prompt to 'Park Up Safely' in the marked bay but upon parking, nothing further happens. This issue happened both times when attempting my driving test.

### Expected behaviour

The test completes as expected and I am awarded the full Driving Licence.

### Steps to reproduce

1. Start the test
2. Complete all steps as required
3. Park in the bay on the final part - Test should progress no further from here

### Any Texture Packs? (If so list)

NVE

### CMG User ID

89665

**Comment by crazychris2404** [comment]
Hi
Do you have a clip of this occurring please

**Comment by packfile** [comment]
Closing, no response to request for more information
