### ISSUE TITLE
airdrop redzone bugged

### ISSUE THREAD

**Issue by ynzkdc** [CMGStudios/issue-tracker#46]
Oke so basically whenever you go to the drop the airdrop doesnt show, this isnt only a problem for me but its a bug in general. On the place from the drop there is a bunker platform which possibly makes it glitch, whenever you put a car on the bunker platform it phases thrue the platfrom

![Desktop Screenshot 2021 07 04 - 23 22 17 69](https://user-images.githubusercontent.com/44806827/124399877-b62b9900-dd1e-11eb-8c59-4882f67ad6c4.png)

https://drive.google.com/file/d/1vI4fEtDqBfk7mpv9GDGtgH2qbt4yXx-H/view (my texture pack)

287

**Comment by alfiellds** [comment]
Thank you for the report, however, there is a reason for a format being there when you open a report - this is to provide the developers with the information they need in order to fix the bug.

Please can you provide a video that demonstrates the issue?

Many thanks.

**Comment by ynzkdc** [comment]
> Thank you for the report, however, there is a reason for a format being there when you open a report - this is to provide the developers with the information they need in order to fix the bug.
> 
> Please can you provide a video that demonstrates the issue?
> 
> Many thanks.

No i dont have a clip i can show to explain the issue more, but its simply just that the drop doesnt spawn/show at that particular redzone

**Comment by alfiellds** [comment]
Alright, I will pass this onto the developers, however, they may require more information in the future, so please keep an eye on the report.

**Comment by rubbertoe98** [comment]
Fixed from next restart.
