### ISSUE TITLE
[Bug]: Frontend Sounds Not Playing Upon Leaving Casino

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A small number of times, frontend sounds (such as UI and bag opening) don't play at all due to being somewhat muted.

I've never 100% found a cause for this but it is 100% caused by the casino. I believe this happens after leaving a blackjack table but I am unsure due to how little I have tested this.

### Expected behaviour

Should play **all** sounds.

### Steps to reproduce

1. Enter casino
2. I guess mess around a bit (sit at tables and whatever)
3. Exit casino
4. Observe how sounds don't play at all (FIXED BY RELOGGING)

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by packfile** [comment]
Thanks for the report, this behaviour is also observed in #444
