### ISSUE TITLE
[Bug]: Heist Setups making you pay and redo after it says it is completed

### ISSUE THREAD

**Issue by Parmahh** [CMGStudios/issue-tracker#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I completed the first 2 setups of the bank heist by paying the 500,000 and then the 1,000,000 for the second setup. After i completed the second setup, it said it was completed on the heist screen yet i couldnt move onto the next setup or whatever and it wanted me to pay the 1 million again and redo the setup. You can see in the image that is says its completed but i cant move onto the next one and it makes me pay and do the setup again
![image_2022-09-03_213600774](https://user-images.githubusercontent.com/112781124/188286949-1f6008c8-261c-4e18-a071-af79a99daca5.png)

### Expected behaviour

It made me basically waste 1million on nothing and I called an admin but they couldn't do anything about it, but what can I do?

### Steps to reproduce

1. Complete the first two setups
2. See if it completes it but doesnt allow you to progress

### CMG User ID

299909

**Comment by packfile** [comment]
Thanks for the report, after each setup you will be provided with an item in your inventory. Once you have completed the two setups, you can then head to the bank of England and start the heist by the gated door. I understand this isn't entirely clear, so I've made a note to add further guidance
