### ISSUE TITLE
[Bug]: Weird streaming issue with mission row stairs

### ISSUE THREAD

**Issue by Pugles-Beancat** [CMGStudios/issue-tracker#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am unsure whether this is completley clientsided or not. But it appears the stairs on the outside of mission row do not stream correctly. I have re-installed FiveM due to this issue to try and resolve this as it was happening frequently for myself. I had re-installed FiveM an when I had first spawned in at mission row they were streaming completley fine but as soon as I go around legion and come back. It's like its refusing to change from its low to high lod.

[pic1](https://media.discordapp.net/attachments/745116598376988795/1015896178870734878/unknown.png?width=1194&height=671)
[pic2](https://cdn.discordapp.com/attachments/745116598376988795/1015897303514628156/unknown.png)

[my citizen log for the session](https://mega.nz/file/naR21LxK#UDCXcFPXo6wLp8oSLP_22u-CTj8vEr5tNxn7wFnUWKY)

### Expected behaviour

.

### Steps to reproduce

Simply exist at mission row

### Any Texture Packs? (If so list)

N/A

### CMG User ID

836

**Comment by crazychris2404** [comment]
I will leave this as trivial for developers as I have also experienced this but when I upgraded my graphics card the issue stopped

**Comment by packfile** [comment]
Might have improved with recent optimisations. If not, then please screenshot the windows that open when running `strmem 1` and `strdbg 1` in F8 so there is further info to diagnose.
