### ISSUE TITLE
[Bug]: pink textures 

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

there is some pink textures around Vespucci  
https://media.discordapp.net/attachments/913896366944690176/1017837630769090611/pd_pink.PNG
https://media.discordapp.net/attachments/913896366944690176/1017837833580466258/pink_v2.PNG

### Expected behaviour

pink textures should not be there 

### Steps to reproduce

go to Vespucci pd and you will see it 

### CMG User ID

68457

**Comment by crazychris2404** [comment]
Confirmed
I have seen this around a few areas including vespucci and also the wall behind the pub opposite casino
I will put this in low priority for developers

**Comment by packfile** [comment]
Thanks for the report, you should see this fixed for Monday 19th.
