### ISSUE TITLE
[Bug]: panic photo 

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

panic should display a photo as the player who panics but instead it show photo as yourself every time    

### Expected behaviour

should show photo of the player who panic but don't 

### Steps to reproduce

get someone to panic 
then it shows photo of yourself  

### CMG User ID

68457

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the repoort

**Comment by packfile** [comment]
This should work for players within ~300m, anyone out of the range it will display yourself. For optimisation reasons, players outside of that range are not 'rendered' and therefore don't have a head to display. 

I will close this for now as it is not a priority, and can be looked at once the backlog is cleared.
