### ISSUE TITLE
[Bug]: twitter reward

### ISSUE THREAD

**Issue by Fredd0e** [CMGStudios/issue-tracker#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i followed the twitter and the reward says i still need to follow the twitter

### Expected behaviour

![2022-09-10 (8)](https://user-images.githubusercontent.com/113265796/189503203-ab9e01b4-daf2-470e-a700-3b3f105bd2a9.png)

### Steps to reproduce

![2022-09-10 (8)](https://user-images.githubusercontent.com/113265796/189503177-be4e3341-43e0-4d02-97ad-c2f03ca2008d.png)

### Any Texture Packs? (If so list)

no

### CMG User ID

270658

**Comment by crazychris2404** [comment]
There is not a bug with this you just need to complete the following steps.

Do /linktwitter ingame 
And wait for 5 or so minutes 
Then do /twitterreward 
And ensure your following twitter
