### ISSUE TITLE
Didn't get paid for my scuba diving job 

### ISSUE THREAD

**Issue by wanweer** [CMGStudios/issue-tracker#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I returned to the hq after collecting all of the "treasure" and when I got there I clicked "Claim Reward" and afterwards it apparently paid me but I wasn't paid and then I tried to do the job another time and it said(refer to the attachment below) and I'm frustrated cause it takes time to find the "treasure" so I'm a little sad.

![image](https://user-images.githubusercontent.com/113588037/190353336-be555a75-49c6-485e-981f-f34fcf47a7b1.png)

### Expected behaviour

I returned to the hq after collecting all of the "treasure" and when I got there I clicked "Claim Reward" and afterwards it apparently paid me but I wasn't paid and then I tried to do the job another time and it said(refer to the attachment below) and I'm frustrated cause it takes time to find the "treasure" so I'm a little sad.

![image](https://user-images.githubusercontent.com/113588037/190353336-be555a75-49c6-485e-981f-f34fcf47a7b1.png)

### Steps to reproduce

Not sure

### Any Texture Packs? (If so list)

-

### CMG User ID

306145

**Comment by packfile** [comment]
Thanks for the report

When you mentioned `it apparently paid me`, what makes you say that? Did you get a notification saying `Scuba Diving paycheck received`?

**Comment by wanweer** [comment]
> 

Alright so I didn't get the Scuba Diving Paycheck but it didn't let me do another job again cause I had an ongoing job apparently also I never got paid so idk ig

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for next restart.
