### ISSUE TITLE
[Bug]: anpr error

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you do /flagr and put reason
and when you go near it in a pd car it shows an error  
https://media.discordapp.net/attachments/913896366944690176/1020422500863197234/flagr.PNG

### Expected behaviour

should display the reason you flag it for 

### Steps to reproduce

/flagr
and then reason 
and then it show an error on anpr 

### CMG User ID

68457

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
