### ISSUE TITLE
[Bug]: Map doesn't render around places and people invisible

### ISSUE THREAD

**Issue by JimmaJamzz** [CMGStudios/issue-tracker#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I spawn in around st thomas hospital, I drive around the map and fall through the map and still get issues. 

I have purchased alot of stuff from your server and feel disappointed i cannot play the game correctly

Specs i9 10900k
Ram 32GB 
GPU 3080ti
m.2 2tb Nvme 
![cmg](https://user-images.githubusercontent.com/110597740/190986757-dbc7726c-9ee8-459d-9192-cd7aa43d40de.PNG)

### Expected behaviour

map doesnt render, could be sat there and the map just disappears. My mate got stuck up yesterday and i couldnt help due to people being invisible 

### Steps to reproduce

Just driving around mainly around JD, ST thomas Hospital and places to buy guns. Just awful!

### Any Texture Packs? (If so list)

NVE and without 

### CMG User ID

199336

**Comment by packfile** [comment]
In settings, under `Graphics`, turn up your `Extended Texture Budget` to around 30-40%.
