### ISSUE TITLE
vip perks not working + vip cars folder gone

### ISSUE THREAD

**Issue by ayotyoudidthis** [CMGStudios/issue-tracker#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically i bought the cheapest rank on the server, Everything wokred fine. I bought 3 Import cars and had fun with it. After 1 week i thought abt buying the King ping Rank. Every since i bought the rank, non of my vip perks works. My ingame name is Red cuz of the rank, but my perks are gone. Cant use a vip garage + my vip car folder is gone. So i spent 80bucks and cant do nun with it. What i also realized is that all my licences were gone too. I had gold licens + weed licens. I bought them all again. I alrdy txted the support ticket and its not looking good. Been waiting for 1 week now and im always getting dry awnsers wich are saying literly nothing. idk what to do no more i dont get any help. Loosing all my fun on this server right now.

### Expected behaviour

Non workable vip garage
Vipcarfolder is gone
Licens are gone

### Steps to reproduce

.

### CMG User ID

305754

**Comment by crazychris2404** [comment]
Try contact donation support who can forward to the relevant people who can resolve this
Make a ticket here https://discord.gg/b9wQUEjz
