### ISSUE TITLE
[Bug]: Vip Garages not appearing / disappearance of licenses

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I and some other players are having this issue and we were told it would be fixed today, and it has not been fixed since the restart this morning, i started having this problem about a day after i purchased some money bags, ranks and some custom imports. This has been a problem for about 3 days now and leaves the server unplayable for those who have this problem. 

### Expected behaviour

Vip garages and licenses disappearing 
https://prnt.sc/uuZK3to3JpBY 

### Steps to reproduce

N/A

### Any Texture Packs? (If so list)

N/A

### CMG User ID

197081

**Comment by crazychris2404** [comment]
You will need to contact donation support to resolve this
