### ISSUE TITLE
crashing[Bug]: 

### ISSUE THREAD

**Issue by Scriptvre** [CMGStudios/issue-tracker#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i am just playing and randomly crashing, heres the code it says
{
    "crash_hash": "fivem.exe+1663A4E",
    "crash_hash_id": 1878152500,
    "crash_hash_key": "don-golf-west",
    "crashometry_crashometry_has_mod_data": "yes",
    "crashometry_crashometry_has_package_data": "yes",
    "crashometry_did_render_backbuf": "true",
    "crashometry_gpu_id": "10de:2414",
    "crashometry_gpu_name": "NVIDIA GeForce RTX 3060 Ti",
    "crashometry_hs_state": "HS_HOSTED",
    "crashometry_last_server": "136.175.222.3:30120",
    "crashometry_last_server_url": "http://136.175.222.3:30120/",
    "crashometry_last_server_ver": "master v1.0.0.5681",
    "crashometry_load_game_first_launch": "true",
    "crashometry_mod_package_count": "1",
    "crashometry_onesync_big": "true",
    "crashometry_onesync_enabled": "true"
}

### Expected behaviour

random crashing 

### Steps to reproduce

not sure what this means tbh

### CMG User ID

298874

**Comment by packfile** [comment]
No actionable information, if you know a set of steps to cause this crash then please reopen.
