### ISSUE TITLE
[Bug]: Weapons not buyable in organ heist

### ISSUE THREAD

**Issue by maxreid250** [CMGStudios/issue-tracker#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

You can't buy guns in organ as it says "Not in correct session"

### Expected behaviour

Not being able to buy guns in organ heist as not in correct session

### Steps to reproduce

1. Enter Organ
2. Buy a weapon

### Any Texture Packs? (If so list)

N/A

### CMG User ID

204066

**Comment by crazychris2404** [comment]
Thanks for the report
This is confirmed for PD involved Unsure about CIV currently
I will move this to high priority

**Comment by packfile** [comment]
Thanks for the report, this will be fixed from next restart
