### ISSUE TITLE
[Bug]: communicate with flight tower (pilot job)

### ISSUE THREAD

**Issue by Juliius420** [CMGStudios/issue-tracker#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Before landing you have to communicate with the flight tower sometimes it doesnt appear for you to accept. That means you can't drop off or pick up passenger's 

### Expected behaviour

Have to restart the job then it works but after 4th or 5th job the flight tower will not communicate with you 

### Steps to reproduce

Could happen after 4th job
Try starting the pilot job and get to destination before landing it will want you to accept the communication between you and the flight tower.  

### CMG User ID

255345

**Comment by crazychris2404** [comment]
Can you provide a clip of this occuring please

**Comment by crazychris2404** [comment]
Closed linked with https://github.com/CMGStudios/issue-tracker/issues/397 please direct further discussion there
