### ISSUE TITLE
[Bug]: Cannot sell plat

### ISSUE THREAD

**Issue by AlexGonzales2** [CMGStudios/issue-tracker#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have this glitch which doesn't allow me to sell Platinum subscriptions. When I open the /cmgclub menu, I can see the menu showing me the amount of platinum I have and but when I walk over to a person to try and sell it, it doesn't work. The blue box menu doesn't come up.

I've tried multiple things like deleting cache and temp, I've removed and reinstalled GTA and FiveM, and it's still not good.

Before the problem happened, it did let me do it. The problem happened when I got into the menu and started to type the person's details, then he fell through the ground, which then closed my menu and after that, I couldn't access it.

Other action that requires the little blue menu do work, such as renting vehicles to other players and selling vehicles work but not the plat selling menu.

### Steps to reproduce

/cmgclub
sell platinum days
no blue box appears

### Any Texture Packs? (If so list)

N/A

### CMG User ID

301583

**Comment by crazychris2404** [comment]
Can you provide a clip of this occuring please

**Comment by AlexGonzales2** [comment]
https://youtu.be/Olb7IsQYtfk

**Comment by crazychris2404** [comment]
Thanks, have you claimed your kit from the subscription?

**Comment by AlexGonzales2** [comment]
I haven't, I had only 4.5 days of plat, I tried buying plat from someone and tried to sell that but nothing

**Comment by AlexGonzales2** [comment]
Update: The monthly boot wipe has fixed this so i guess that is that 

The only possible fix i see is a restart of the server, i think this is a server problem.

**Comment by crazychris2404** [comment]
Will close this as no longer a problem and no way to reproduce the issue
