### ISSUE TITLE
[Bug]: Cash Briefcase 4 - Diamonds emote breaks the menus

### ISSUE THREAD

**Issue by maxreid250** [CMGStudios/issue-tracker#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cash Briefcase 4 - Diamonds emote breaks the menus 

### Expected behaviour

Once the emote is selected you can't open the emote or F2 menu thing as the emote breaks it

### Steps to reproduce

1. F3
2. Custom Emotes
3. Cash Briefcase 4 - Diamonds

### Any Texture Packs? (If so list)

N/A

### CMG User ID

204066

**Comment by crazychris2404** [comment]
Can i get a clip of this occuring please

**Comment by maxreid250** [comment]
https://streamable.com/l01swe

**Comment by crazychris2404** [comment]
Confirmed thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
