### ISSUE TITLE
Not letting me sell fish 

### ISSUE THREAD

**Issue by HenchmanHarry** [CMGStudios/issue-tracker#48]
**Describe the issue you're facing**
The fish seller is not letting me sell my small shark fins. I had mediums that it let me sell but the smells just won’t sell.

**Steps to reproduce**
To try fix I tried relaunching my game but it didn’t work so I returned the next day to only find the same problem occurring.
**Expected behavior**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
217854

**Comment by loganuk** [comment]
Hello Harry - Can you record a video of you attempting to do this please?

**Comment by loganuk** [comment]
Please provide footage or this will be closed within the next 12 hours. - Thank you.

**Comment by HenchmanHarry** [comment]
im trying to send you a clip of me going there on via this email but it says the file is to big what should i use to forward this to you 

    On Thursday, 8 July 2021, 13:53:02 BST, Andrew Logan ***@***.***> wrote:  
 
 


Please provide footage or this will be closed within the next 12 hours. - Thank you.

**Comment by loganuk** [comment]
Upload to YouTube or Streamable
