### ISSUE TITLE
SCUBA MISSION NOT GIVING MONEY[Bug]: 

### ISSUE THREAD

**Issue by XOTIICMATT** [CMGStudios/issue-tracker#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i completed the scuba mission and i got all 5 crates i then went back to sell them and when i did it never gave me the money i then went to try and start again but it said job in progress it also did this to another person that was also trying to sell the crates.

### Expected behaviour

im supposed to get the money after completing the mission 

### Steps to reproduce

do the scuba mission 

### CMG User ID

309750

**Comment by packfile** [comment]
Can you provide your log file for when this happened, to find your FiveM log files navigate to this directory: `%localappdata%/FiveM/FiveM.app/logs`.
Additionally, did you use the boat you was given to go back to the start?

**Comment by packfile** [comment]
Closing - No actionable information provided. It's likely you returned back to the start without boarding your original boat at the end of collecting the crates.
