### ISSUE TITLE
[Bug]: Home Menu Broken

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As of recent, the home menu bugs out. The only way I've found to get around it is by relogging.

In the clip below, I spam Home (to try and close it) while also attempting to scroll through and pressing Tab, none of which were successful in closing the player list.

https://streamable.com/d8n6wf

### Expected behaviour

Home menu should close as expected and without error.

### Steps to reproduce

1. Go about CMG Normally
2. Open Home Menu (then try to close)
3. Go from There

### Any Texture Packs? (If so list)

N/A

### CMG User ID

194575

**Comment by packfile** [comment]
Thanks for the report, this is being investigated

**Comment by ItsJunction** [comment]
Would like to add on that a scuffed workaround (without relogging) of this is by holding `Home` for around two seconds. 

However, doing this leads to some weird behaviour with other NUI such as opening the Pause Menu if you writing a ticket with the letter "P" in it or getting out a weapon if you are typing in the PNC.

**Comment by packfile** [comment]
Yes, the requirement for this to happen is to open and close the PNC, after which point the UI will be broken. This has been fixed internally and will be on the main server in the next few days
