### ISSUE TITLE
[Bug]: police remington 870 flashlight 

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you have a another gun in your hand and press e it tunes on and off the flashlight on the shotgun when its on your back     https://streamable.com/q4m5x6

### Expected behaviour

should not tune flashlight on and off when on back 

### Steps to reproduce

get the shotgun
and pull out glock and press e 

### CMG User ID

68457

**Comment by packfile** [comment]
Huh, that's interesting game behaviour :P

**Comment by crazychris2404** [comment]
As tom said interesting bug
Moved to low priority

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
