### ISSUE TITLE
[Bug]: If toys for  7 days free plat are collected on different computers you are unable to collect all 

### ISSUE THREAD

**Issue by Theovega69** [CMGStudios/issue-tracker#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the toys for 7 days of free plat are collected on different computers but on the same device you are unable to collect the ones u have already collected on the other device. The collected ityems for one device do not count towards the collected items on the other. This makes it impossible to collect all of them if any where collected on anoither device.

### Expected behaviour

It states i have collcted half the otys on both pc and i cannot see the rest.

### Steps to reproduce

1. collect a toy on 1 device 
2. log into same account on seperate device
3. collect a toy on seperate device
4. go to previouse toy location for step 1

### Any Texture Packs? (If so list)

no

### CMG User ID

111037

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report 
As this could be affecting a wider range of users i will move this to high priority

**Comment by terrorist** [comment]
It's because of storing in kvp dawg

**Comment by terrorist** [comment]
plz dont delete dawg im trying to help
![image](https://user-images.githubusercontent.com/34693611/195853142-84abf7f2-8fe6-4ed0-a3c0-b2dadb0e84f8.png)
