### ISSUE TITLE
[Bug]: admin feedback screen 

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you get the feedback screen if you tab out and tab back in you have no cursor

### Expected behaviour

you should be able to tab out with out losing the cursor when you tab in 

### Steps to reproduce

/calladmin
then get admin to take ticket
the get admin to return
then you get feedback screen 
then tab out 
then tab back in 
and you have no cursor  

### CMG User ID

68457

**Comment by crazychris2404** [comment]
Hi @stony5 thanks for the report!
Please can i have a clip of this occurring because after testing with multiple people we are unable to reproduce this issue.

**Comment by stony5** [comment]
i think this has been fixed
