### ISSUE TITLE
Car crashes my game and people around, only recently started doing it

### ISSUE THREAD

**Issue by scouserstano** [CMGStudios/issue-tracker#49]
**My PD baller lock keeps crashing my game everytime i spawn it and all the people around me, never use to do this just recently started, the person who owns the other one dosent happen for him**

**Unmarked BMW 33oi MSport, Spawn code g20pd**

**NVE**

**344**

**Comment by arthur-rl** [comment]
Hi @scouserstano do you have any upgrades on the car? Ones that the other owner doesn’t.

**Comment by scouserstano** [comment]
No mate both got all the same upgrades, everything on it apart from anti lag

Sent from my iPhone

On 6 Jul 2021, at 15:52, Arthur ***@***.***> wrote:

﻿

Hi @scouserstano<https://github.com/scouserstano> do you have any upgrades on the car? Ones that the other owner doesn’t.

**Comment by arthur-rl** [comment]
@scouserstano If you log back into game you should be able to spawn in the vehicle without it crashing now. 

Please let me know if this is fixed.

**Comment by scouserstano** [comment]
Will do I rented it to someone too see if it happened to them so as soon as it’s off rent I’ll check and if it’s still doing it I’ll message back here

Sent from my iPhone

On 6 Jul 2021, at 17:46, Arthur ***@***.***> wrote:

﻿

@scouserstano<https://github.com/scouserstano> If you log back into game you should be able to spawn in the vehicle without it crashing now.

Please let me know if this is fixed.

**Comment by scouserstano** [comment]
Works now mate, thanks a lot for your help

Sent from my iPhone

On 6 Jul 2021, at 17:46, Arthur ***@***.***> wrote:

﻿

@scouserstano<https://github.com/scouserstano> If you log back into game you should be able to spawn in the vehicle without it crashing now.

Please let me know if this is fixed.
