### ISSUE TITLE
[Bug]: Molotov

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When throwing a Molotov at someone it doesn’t doesn’t kill them, only knocks them out. Realistically if you get torched your going to do.

### Expected behaviour

Should kill the player.

### Steps to reproduce

1. Get Molotov 
2. Throw it at player
3. It only knocks them out instead of killing

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for next restart
