### ISSUE TITLE
[Bug]: Able to walk through windows in HMP

### ISSUE THREAD

**Issue by JackooCmg** [CMGStudios/issue-tracker#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Opposite the main Cell block in HMP you can walk straight through the glass without the doors unlocked 

### Expected behaviour

The windows should be solid and not able to walk straight into 

### Steps to reproduce

Go to prison grounds and walk into to the window next to the double doors opposite the main cell block.

### CMG User ID

193089

**Comment by crazychris2404** [comment]
There are certain places this does occur around the prison @tom-gun i will privately attach you a image of the area when you look into this just contact me

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for next restart
