### ISSUE TITLE
After being revived you cannot put your hands up

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After being revived by NHS, you cannot put your hands up for a solid 10 seconds. As a result of this, if PD want to arrest you or some civs want to take you hostage you cannot comply as a result of the bug.

### Expected behaviour

Get revived
Try and put your hands up
You cannot

### Steps to reproduce

Die
Get revived by NHS or by hand so you get the blurry screen effect
You cannot put hands up 

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report whilst you have the blurry effect you cannot raise your hands

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for next restart
