### ISSUE TITLE
[Bug]: Zombies

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I killed a zombie,  The bags dropped  they disappeard straight away   I try to find the disappearing bags and get killed by the dead zombie

### Expected behaviour

I expected the bags to drop so i can loot them and i died 

### Steps to reproduce

I dont know 

### Any Texture Packs? (If so list)

None

### CMG User ID

867

**Comment by crazychris2404** [comment]
Confirmed
here is the clip of this issue
https://streamable.com/bww3ya

I will move this to high priority due to being a limited time event

**Comment by packfile** [comment]
Thanks for the report. This has been fixed for the next event

**Comment by ItsJunction** [comment]
It still seems to persist. The client console/logs didn't show anything - all 3 clips are from today:

12:06 - 2 bags drop, 0 despawn (loaded on when the server came back up): https://streamable.com/av00yl
12:27 - 2 bags drop, 1 despawns (^): https://streamable.com/soemu1
13:51 - 4 bags drop, 4 despawn (loaded on from 13:49): https://streamable.com/h79w9f
