### ISSUE TITLE
[Bug]: Can't use in-game twitter on phone.

### ISSUE THREAD

**Issue by TotalXanarchy** [CMGStudios/issue-tracker#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open the twitter app and i try to send a tweet I get this error message in the chat
![image](https://user-images.githubusercontent.com/36505312/197522461-b0937eb7-7dec-4e14-8749-98bc9bacfade.png)

### Expected behaviour

The tweet should send? I think?

### Steps to reproduce

Open twitter on phone
Go to tweet tab
Type anything
Press enter or click the send button
Chat in top left will say "Invalid account / passwords"

### Any Texture Packs? (If so list)

no

### CMG User ID

313151

**Comment by packfile** [comment]
Thanks for the report, is this your first time using Twitter on the phone?

**Comment by TotalXanarchy** [comment]
> Thanks for the report, is this your first time using Twitter on the phone?

No, I've used it a few times over the last couple of days but always had this error. Didn't know it was a bug until I asked about it in discord.

**Comment by packfile** [comment]
This has been fixed for the user
