### ISSUE TITLE
[Bug]: AFK Mode not able to come out of it

### ISSUE THREAD

**Issue by maxreid250** [CMGStudios/issue-tracker#497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not too sure if it's been patched or not, but when you go into AFK mode and come back out of it; it still doesn't give you money when you are meant to receive the paycheck

### Expected behaviour

AFK mode not coming out after going into it, re-logging will make it work again though

### Steps to reproduce

1. Go into AFK Mode
2. Move again
3. Wait until the next paycheck 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

204066

**Comment by crazychris2404** [comment]
@tom-gun after this was mentioned you said it was being looked into was it resolved ?

**Comment by packfile** [comment]
Not yet, though a fix is underway

**Comment by crazychris2404** [comment]
Thanks this is now confirmed

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from next restart
