### ISSUE TITLE
[Bug]: Ammo Not In Bags

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When looting bags it become apparent that many of them will not contain ammo, I was in lsd and this happened 3/4 times in a row. I have also discussed this with other people and they said they are having the same issue. I don’t have a clip to reproduce but it is an issue.
I have seen it happen with:
• ump
• mosin
• WL SMG

### Expected behaviour

The bag should drop ammo in the bag when the player dies (possible issue with the ammo storing???)

### Steps to reproduce

1. Kill someone
2. Loot their bag
3. It will likely not contain ammo

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from next restart
