### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chardyz** [CMGStudios/issue-tracker#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some of the cars that you purchase from the standard dealership can not be modified properly, now i dont know if this is because you need a certain rank to apply the mods onto cars, but if that is the case the option to purchase the mods for the car in LS customs should be disabled for new players like me so we dont waste our ingame money.

I purchased the neon light kit and tinted windows for my audi rs3
The game took my money but did not apply the mods i paid for onto my car, i have tried re logging and respawning the car and making sure im equipping the mod i paid for but still I dont receive anything.

### Expected behaviour

When you have purchased a mod, it should apply on to the car and be able to be seen in LS Customs

### Steps to reproduce

Go to the modification
Purchase it
It should apply but doesn't

### Any Texture Packs? (If so list)

none

### CMG User ID

277433

**Comment by crazychris2404** [comment]
Can you provide a clip of this occuring please @chardyz also which specific car this happened with the spawncode can be found by taking the car out your garage and pressing f8 and it should say there

**Comment by chardyz** [comment]
> Can you provide a clip of this occuring please @chardyz also which specific car this happened with the spawncode can be found by taking the car out your garage and pressing f8 and it should say there

Yeah no worries i should be able to get on in the next couple of hours and show a demonstration

**Comment by packfile** [comment]
Hey @chardyz, have you managed to locate the request info?
