### ISSUE TITLE
Drones

### ISSUE THREAD

**Issue by alfiellds** [CMGStudios/issue-tracker#50]
**Describe the issue you're facing**
You can control drones as helicopters by approaching them and pressing F.

**Steps to reproduce**
Approach a drone placed with /drone and press F.

**Expected behavior**
You will pull an invisible ped out of the drone and then control it as a helicopter. It also explodes if you go too near to other objects.

**Screenshots/Video**
https://i.imgur.com/1VhsBP1.png

**Any Texture Packs (if so list)**
N/A

**Perm ID**
71413

**Comment by rubbertoe98** [comment]
Fixed from next restart.
