### ISSUE TITLE
[Bug]: killfeed

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

killfeed is not working 

### Expected behaviour

should see killfeed 

### Steps to reproduce

kill someone 
then it don't show in killfeed  

### CMG User ID

68457

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
Developers are looking into a cause of this

**Comment by packfile** [comment]
Thanks for the report, this appears to have resolved itself as the killfeed is working fine in both the main & dev server.
