### ISSUE TITLE
[Bug]: Statistics menu

### ISSUE THREAD

**Issue by HypeFUT** [CMGStudios/issue-tracker#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Statistics menu keeps on coming up when i load in and i cant fix it

### Expected behaviour

Everytime, i load into CMG i get the stats menu opened i have unbinded the key before so i cant change it because when the menu comes up i cant do anything call admin or even going into the settings and if i click F9 again it doesnt do anything i have tried everything and nothing has happened i have talked to a admin and said he doesnt know what to do either! 

### Steps to reproduce

1. Load on game
2. Try and play the game 
3. 30 seconds later stats menu opens!

### Any Texture Packs? (If so list)

None

### CMG User ID

273451

**Comment by crazychris2404** [comment]
I am unable to reproduce this but have seen this issue occur specifically for this player.

**Comment by packfile** [comment]
Thanks for the report, do you get a `Downloading statistics...` text at the bottom of your screen before this happens?

**Comment by HypeFUT** [comment]
Yea but it has stopped happening now!

- [ ]

**Comment by packfile** [comment]
Closed, this has been resolved
