### ISSUE TITLE
[Bug]: Weight Spamming HMP Gym

### ISSUE THREAD

**Issue by JackooCmg** [CMGStudios/issue-tracker#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Someone starts working out in the gym and when moving over to the bar they can keep pressing it. 

### Expected behaviour

should only be able to lift 1 bar at a time while working out 

### Steps to reproduce

workout in the gym as a prisoner, starting with pull ups then move over to the Bar and spam X while lifting 

### CMG User ID

193089

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from next restart
