### ISSUE TITLE
[Bug]: Phone White screen

### ISSUE THREAD

**Issue by Horowitz06** [CMGStudios/issue-tracker#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When my phone is opened everything loads i can message people out of my contacts and send people money except when i go to my phone book it is a white screen and when i go my contacts where you add new people i cannot see anyone and neither the button for adding contacts its a completely white screen i have gone through 2 server restarts and restarted my game mutiple times and no fix yet

### Expected behaviour

no contacts appearing and no phone book appearing just a complete white screen 

### Steps to reproduce

press k
go to contacts
nothing is there

### Any Texture Packs? (If so list)

none

### CMG User ID

85123

**Comment by packfile** [comment]
Thanks for the report. Can you reconnect and see if the issue still occurs?

**Comment by packfile** [comment]
This should be fixed for your account. Please reopen if this is not the case
