### ISSUE TITLE
[Bug]: Pets

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I spawn my pet in, It gets killed but then doesnt let me respawn it at all so i have to completely relog

### Expected behaviour

I spawn my pet it,  It gets killed and then i have to wait 5 minutes to respawn it

### Steps to reproduce

Spawn Pet In
Kill It
Try to respawn it 5 minutes later

### Any Texture Packs? (If so list)

No

### CMG User ID

867

**Comment by packfile** [comment]
Thanks for the report. During this 5 minute waiting period, are you spawning a different pet?

**Comment by Declare5M** [comment]
At the time i only owned the chimp but recently purchased a dog too  Which it lets me spawn every 5 minutes but when i only owned the chimp,  Even after about 30 minutes  I tried to respawn it and wouldnt work so i was forced to relog

**Comment by packfile** [comment]
This should be fixed from next restart

**Comment by Declare5M** [comment]
Thank You
