### ISSUE TITLE
[Bug]: Storing Weapon No Ammo

### ISSUE THREAD

**Issue by Lucid-FiveM** [CMGStudios/issue-tracker#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have been getting no ammo when I store a weapon with ammo it’s frustrating 

### Expected behaviour

To have ammo

### Steps to reproduce

/storeallweapon

### Any Texture Packs? (If so list)

No

### CMG User ID

309513

**Comment by packfile** [comment]
Thanks for the report. I noticed you haven't played on the server since the 31st of October; this is believed to be fixed as of the latest restart, can you connect again and let us know if this still occurs? Ref #498.

**Comment by Lucid-FiveM** [comment]
Okay thanks
