### ISSUE TITLE
[Bug]: New Stancer Update

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought the Stancer stuff and messed around with it for a bit   Reset it back to default and now   Every time i spawn my car It changes the width and camber without me doing anything 

### Expected behaviour

Expecting my car to spawn with default camber and default width

### Steps to reproduce

Buy the 4 stancer upgrades 
Mess around with it
Set it back to the default (0)
Respawn your car
Completely different camer and width

### Any Texture Packs? (If so list)

None

### CMG User ID

867

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from next restart.
