### ISSUE TITLE
[Bug]: my 'tsgr20' liveries are fucked

### ISSUE THREAD

**Issue by xRhys** [CMGStudios/issue-tracker#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my liveries are not mapped onto the car correctly (possibly due to Tom's texture optimisation adventures)

https://media.discordapp.net/attachments/850761595902492682/1038074637025804338/image.png

spawncode is 'tsgr20'

(muted in cord so cant let you know via the cord init)

### Expected behaviour

https://media.discordapp.net/attachments/850761595902492682/1038074637025804338/image.png

Livery not mapped properly

### Steps to reproduce

Go to LS customs and check the liveries

### Any Texture Packs? (If so list)

No

### CMG User ID

2804

**Comment by crazychris2404** [comment]
Fixing this for next restart
