### ISSUE TITLE
[Bug]: Biometric Lock for Helicopters

### ISSUE THREAD

**Issue by RealistSaid** [CMGStudios/issue-tracker#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Bought the Biometric Lock for my helicopter and others can still fly it.

### Expected behaviour

It tells them they cant drive vehicle due to biometric lock but still lets them fly it.

### Steps to reproduce

1. Buy Biometric lock on a helicopter
2. Let someone else fly it.

### CMG User ID

808

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
