### ISSUE TITLE
[Bug]: T/setuparch Audio Issues

### ISSUE THREAD

**Issue by JackooCmg** [CMGStudios/issue-tracker#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you setup the Metal arch while clocked on HMP/PD after removing it the audio is not removed from the machine but the machine is gone. what happens then is that the alarm still triggers every time someone walks through the area it was placed.

### Expected behaviour

should have no audio for alarms when the arch has been removed 

### Steps to reproduce

clock on HMP
T/ Setuparch
walk through it beeps 
T/ Removearch
walk through and it still makes noise

### CMG User ID

193089

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
