### ISSUE TITLE
car de-spawning randomly 

### ISSUE THREAD

**Issue by YoFlqme** [CMGStudios/issue-tracker#51]
**Describe the issue you're facing**
Every time i go to the shack thing at frog legs my car will de-spawn within every 10 mins or so
**Steps to reproduce**

**Expected behavior**

**Screenshots/Video**
https://gyazo.com/6370173a0e84d4095c475b9746e872f0
**Additional context**
N/A
**Any Texture Packs (if so list)**
Always day
**Perm ID**
550

**Comment by loganuk** [comment]
Can you get a video clip of this happening?

Are you sure there were no vehicle clean-ups? Did you forget to lock your truck?

**Comment by loganuk** [comment]
Please provide footage or this will be closed within the next 12 hours. - Thank you.
