### ISSUE TITLE
[Bug]: Deposit All gang funds

### ISSUE THREAD

**Issue by maxreid250** [CMGStudios/issue-tracker#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Deposit all in gang funds is not working

### Expected behaviour

https://streamable.com/42pl31

### Steps to reproduce

1. Withdraw Money
2. Deposit All

### Any Texture Packs? (If so list)

N/A

### CMG User ID

204066

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this is fixed from the next scheduled restart
