### ISSUE TITLE
[Bug]: scuba diving 

### ISSUE THREAD

**Issue by Fynp151** [CMGStudios/issue-tracker#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Every time I jump out of the boat I either freeze in the water or I can walk on the water .

### Expected behaviour

Freezing and walking on water when diving out of scuba boat .

### Steps to reproduce

No steps yet 

### CMG User ID

/getmyid

**Comment by crazychris2404** [comment]
Hi @Fynp151 
Thanks for the report
Do you have a clip of this occurring please

**Comment by crazychris2404** [comment]
Closed due to no response
