### ISSUE TITLE
[Bug]: Voicechat

### ISSUE THREAD

**Issue by JorPet1** [CMGStudios/issue-tracker#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When youre outside burger shot, example doing negotiations, you cannot hear the people inside the burger shot, not at all, even if the door is open.

### Expected behaviour

not being able to talk through doors at burger shot

### Steps to reproduce

1. be 2 people
2. one inside and one outside
3. try talk
4. (it doesnt work lmao)

### CMG User ID

605

**Comment by crazychris2404** [comment]
Confirmed I had mentioned this to @tom-gun

**Comment by crazychris2404** [comment]
For now this is not something that can be fixed so the issue will be closed and in future a feature is planned to be added as a way to avoid this problem for now there are work around for this issue
