### ISSUE TITLE
[Bug]: When you have a weapon equiped in your weapon wheel it brings it into your hand if in cuffs

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically as the title says, if you get put in cuffs, if you have any weapons in your weapon wheel it put them into your hand when put in cuffs

### Expected behaviour

Having a gun out when being cuffed even when not equiping it into your hands

### Steps to reproduce

Have a gun in your weapon wheel
get cuffed
have it in your hands

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next restart
