### ISSUE TITLE
[Bug]: r150r textures aren't looking too good brev

### ISSUE THREAD

**Issue by xRhys** [CMGStudios/issue-tracker#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I assume that the Texture optimisation has caused my 'r150r' carbon textures to be altered - they're green/purple now

### Expected behaviour

green/purple carbon textures

### Steps to reproduce

spawn car in - r150r
find carbon skirt/widebody mod

### Any Texture Packs? (If so list)

No

### CMG User ID

2804

**Comment by crazychris2404** [comment]
Thanks for the report 
I will resolve this issue for next restart

**Comment by crazychris2404** [comment]
Turns out I fixed this on the 7/11/22 if still occurring please reply here

**Comment by xRhys** [comment]
Yh the carbon texture on the widebody are green
