### ISSUE TITLE
[Bug]: not letting me put any money into gang funds and its been like this for days 

### ISSUE THREAD

**Issue by sizi90** [CMGStudios/issue-tracker#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 not letting me put any money into gang funds and its been like this for days 

### Expected behaviour

 not letting me put any money into gang funds and its been like this for days 

### Steps to reproduce

![images](https://user-images.githubusercontent.com/117852484/200898895-be2dacf1-6d05-4bb0-9a25-be11c7576d08.jpg)

### CMG User ID

214494

**Comment by packfile** [comment]
Duplicate of #511
