### ISSUE TITLE
[Bug]: White screen phone bug 

### ISSUE THREAD

**Issue by 08Beno** [CMGStudios/issue-tracker#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i open my contacts on my phone there is a white screen and when i open my messages there is a white screen. i have restarted my game multiple times and it still doesnt work

### Expected behaviour

When opening my contacts it should bring up my contacts and when i open my messages there should be my messages but there is a white screen

### Steps to reproduce

Press k to open phone

Go on contacts 

and see the contacts 

### Any Texture Packs? (If so list)

no

### CMG User ID

294570

**Comment by crazychris2404** [comment]
@tom-gun will need to resolve this for you as it’s user specific 
Did you do anything before this bug occurred ?

**Comment by packfile** [comment]
Hello @08Beno, can you please load in game and confirm if this is fixed?

**Comment by crazychris2404** [comment]
Closed due to no response
