### ISSUE TITLE
[Bug]: Ingame ui not updating in real time

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

All of a sudden my ui has stopped updating in real time (balance / chat / voice activity / car speed), i've tried clearing my game cache and some other stuff and it's not fixed it, i have to tab to my other monitor and back to my main monitor for my games ui to update

### Expected behaviour

Ui not updating in real time

### Steps to reproduce

I don't think there is any physical way to reproduce it, it randomly just starting happening

https://user-images.githubusercontent.com/114100126/201545137-35b844f9-7c27-4437-9f71-ab82b76710ed.mp4

### Any Texture Packs? (If so list)

N/A

### CMG User ID

197081

**Comment by crazychris2404** [comment]
Can you try "disble UI lag" in fivem settings please

**Comment by PIKAlmao** [comment]
Oh hello yes, tom already helped me with this but i forgot to close the ticket apologies , and thank you chris
