### ISSUE TITLE
[Bug]: Headlight colour change

### ISSUE THREAD

**Issue by gadgetboy2003** [CMGStudios/issue-tracker#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I change the colour of my cars headlight only happening for one car it doesn't change colour even if it is selected.

I have a clip but the clip file is too big to submit, if you would like to see the clip message my discord - gadget✓ᵛᵉʳᶦᶠᶦᵉᵈ#2635 

### Expected behaviour

It should change the colour of the headlights but it won't

### Steps to reproduce

Select headlights using sheepy racing R8

### CMG User ID

259068

**Comment by packfile** [comment]
Thanks for the report - Can you confirm you have the Xenon Lights purchased & applied too? This is requirement for coloured lights to work

**Comment by gadgetboy2003** [comment]
> Thanks for the report - Can you confirm you have the Xenon Lights purchased & applied too? This is requirement for coloured lights to work

I will double check that for you now

**Comment by gadgetboy2003** [comment]
Its working now
