### ISSUE TITLE
SCUBA DIVING JOB IS BUGGED

### ISSUE THREAD

**Issue by Eluzify** [CMGStudios/issue-tracker#52]
**Describe the issue you're facing**

mission failed multiple times not even due to entity cleanup its just bugged and needs to be fixed asap lost out on so much money and time 

**Perm ID**

218508

**Comment by loganuk** [comment]
Hello,

Can you get a video recording of this happening so we can see?

**Comment by loganuk** [comment]
Please provide footage or this will be closed within the next 12 hours. - Thank you.
