### ISSUE TITLE
[Bug]: Cant access whitelisted garages

### ISSUE THREAD

**Issue by TheRealWicks** [CMGStudios/issue-tracker#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I cant access my whitelisted garage such as my 400kg for cmg trader and my casino cars, i still have the whitelist but i cant tackle but i still get pay checks aswell as.

### Expected behaviour

Be able to access  my 400kg, and tackle

### Steps to reproduce

try to open my garage to access 400kg and tackle

### Any Texture Packs? (If so list)

no

### CMG User ID

387

**Comment by packfile** [comment]
Thanks for the report, this is intentional. If you wish to get these permissions back you should get in contact with the gang owners
