### ISSUE TITLE
[Bug]: HMP Guard PA still announces if you put nothing in the box. 

### ISSUE THREAD

**Issue by Jamie1253** [CMGStudios/issue-tracker#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When clocked onto HMP and you use GuardPA if you don't put anything in the announcement a blank announcement still pops up. 

### Expected behaviour

If nothing is put in the announcement box, the announcement does not pop up.

### Steps to reproduce

1. Do /guardpa
2. Don't put anything in the box
3. Press Tab to close it

### CMG User ID

309666

**Comment by crazychris2404** [comment]
Confirmed 
This is the same with most boxes requiring input. Another example of this bug is /announcemenu

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next restart
