### ISSUE TITLE
[Bug]: Falling through roof of HMP Armory and Medical Building

### ISSUE THREAD

**Issue by Jamie1253** [CMGStudios/issue-tracker#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There have been multiple times where people have climbed onto the Prison Armory and Medical Building and fallen through the roof when then de-syncs you to the point where you either need to re-log or get tazed. 

![Prison](https://user-images.githubusercontent.com/79331351/202842935-fd2c6fb0-61fe-428c-932c-115b81b4ec6e.png)

### Expected behaviour

To not fall through the roof of the building into the armoury or medical part.

### Steps to reproduce

1. Climb onto the armoury building 
2. Jump when on the building

### CMG User ID

309666

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next restart
