### ISSUE TITLE
[Bug]: I’m stuck on a boat 

### ISSUE THREAD

**Issue by AEowen** [CMGStudios/issue-tracker#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I’m stuck on my boat doing the scuba diving job at the crashed boat site. None of my buttons are working and I can’t move at all. And if I restart my game I will spawn back in in the middle of the ocean.

### Expected behaviour

To be able to do my scuba diving job without getting stuck on a boat

### Steps to reproduce

I tried to do the scuba mission whilst it was snowing and I pressed E to dive into the water but it tried to pick snowballs up off the boat instead and now I can’t move 

### CMG User ID

I can’t get it because I can’t press T

**Comment by crazychris2404** [comment]
Thanks for the report
The issue with this was the picking up snowballs animation cancelling other actions and this can occur in multiple situations

**Comment by packfile** [comment]
Thanks for the report, being able to pick up snowballs on a boat has been fixed from the next restart
