### ISSUE TITLE
[Bug]: When selling something from the in-game store menu, the confirmation message shows the senders name, not receiver.

### ISSUE THREAD

**Issue by TotalXanarchy** [CMGStudios/issue-tracker#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I sold something from /store to somebody else and it showed my name in the confirmation instead of theirs.

![image](https://user-images.githubusercontent.com/36505312/203617606-7a8d8a34-755c-4bd2-baee-aba9ef77f1a4.png)

### Expected behaviour

It should have their name

### Steps to reproduce

Sell something from the store to somebody
See the name in the confirmation

### Any Texture Packs? (If so list)

no

### CMG User ID

313151

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next restart
