### ISSUE TITLE
[Bug]: Flashlight costing 2k in the PD armory when it should be free

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically the same as the title, in the PD armory the flashlight costs 2k when it should be free. 
![image](https://user-images.githubusercontent.com/90797980/204084382-76af6f1d-fdcf-433f-894c-26f2a184853c.png)

### Expected behaviour

Flashlight cost 2k in armory

### Steps to reproduce

Go to the PD armory
buy a flashlight
it costs 2k

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next restart
