### ISSUE TITLE
[Bug]: car completely fucked

### ISSUE THREAD

**Issue by bighlattgang** [CMGStudios/issue-tracker#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my car will not spawn and it also does not show the spawncode of the car so cant make a car report ( lambo liberty walk wb 1/1 baller )

### Expected behaviour

https://www.youtube.com/watch?v=zqM_ir3pvOs&ab_channel=afroman

### Steps to reproduce

not sure what im meant to put here so ill just say idk

### CMG User ID

184974

**Comment by bighlattgang** [comment]
if this is not where i should have posted this can someone tell me bc ive never done anything like this before

**Comment by crazychris2404** [comment]
I will look into this today for you

**Comment by bighlattgang** [comment]
did you manage to find the problem, i think it is because the car has been deleted from the servers files where all of the cars are stored

**Comment by crazychris2404** [comment]
I need a actual spawncode for the car please

**Comment by bighlattgang** [comment]
i cant get the spawncode as it says in my post

**Comment by bighlattgang** [comment]
i can screenshare on discord if you need proof

**Comment by bighlattgang** [comment]
any updates?

**Comment by crazychris2404** [comment]
Fixed for next restart
