### ISSUE TITLE
[Bug]: cant change propeller colour on culinal heli 

### ISSUE THREAD

**Issue by spencmg** [CMGStudios/issue-tracker#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

been to the los santos customs at airport and there is no option to change wheel colour 

### Expected behaviour

wheel colour is option meaning i can change colour of my propellers 
car spawn code = Cullinanheli

### Steps to reproduce

1 go to los santos 
2 scroll through the menus
3 come to the conclusion their is no wheel colour option 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

184171

**Comment by crazychris2404** [comment]
This is not something we can resolve.
