### ISSUE TITLE
[Bug]: LS Customs 

### ISSUE THREAD

**Issue by BobbyTheBuildery** [CMGStudios/issue-tracker#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When selecting neon colour the camera moves to under the map a long way from LS Customs
Picture of the camera not being with the car when under neon colour https://i.imgur.com/qAgpa7T.png

### Expected behaviour

When selecting neon colour the camera shouldn't move and still be in front of the car showing the colour as you pick them.

### Steps to reproduce

1. go to any LS customs
2. select lights > neon kits > neon colour
3. the camera will move to a specific place on the map

### Any Texture Packs? (If so list)

N/A

### CMG User ID

169174

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, what car was you trying this on?

**Comment by crazychris2404** [comment]
This happens on all cars

**Comment by packfile** [comment]
> This happens on all cars

Just tested on the Alfa Romeo Giulia and Mitsubishi EVO X, camera displays fine

**Comment by crazychris2404** [comment]
Weird I had a few cars experiencing this issue and so did @BobbyTheBuildery so assumed it was all cars will wait for him to confirm car this was on

**Comment by BobbyTheBuildery** [comment]
The car that I used was the nhs mustang mach-e spawncode is 22mac.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next restart
