### ISSUE TITLE
[Bug]: Flashbangs and Smoke grenades

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When PD purchase smokes or flashbangs they are given in quantities of 1 instead of the 25 that was before

### Expected behaviour

Gives full 25

### Steps to reproduce

Purchase smokes or flashbangs on PD

### CMG User ID

910

**Comment by packfile** [comment]
This is intentional, makes it easier to buy an amount which you can afford or have space to store
