### ISSUE TITLE
SOME CARS ARE FASTER THAN SUPERBIKES

### ISSUE THREAD

**Issue by Denzzzz** [CMGStudios/issue-tracker#53]
**Describe the issue you're facing**
I have a 4 door custom import Mercedes it goes 230 flat but have a maxed out custom import race bike that only goes 200flat with and with out nos
**Steps to reproduce**

**Expected behavior**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**
N/A
**Perm ID**
177964

**Comment by alfiellds** [comment]
Hello, thanks for bringing this to our attention, however, this is not a bug. Please request a car developer to review your vehicle if you feel that it is not performing as it should.

Many thanks.
