### ISSUE TITLE
[Bug]: Voice chat

### ISSUE THREAD

**Issue by criss6s** [CMGStudios/issue-tracker#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you press 'PG up' or 'PG down' it shuffles through 'whisper' and 'Talking' only and doesn't go through to shouting this is occurring mainly when someone first logs onto the city and it happens all around the map and doesn't get solved until you spam it or wait some time.

### Expected behaviour

the expected behaviour of this task is that it is supposed to shuffle through whisper talking and shouting however it is only processing two of them.

### Steps to reproduce

when you first log on press PG up or PG down and you will see it only manages to shuffle through wisper mode and talking mode.

### Any Texture Packs? (If so list)

no

### CMG User ID

219070

**Comment by crazychris2404** [comment]
Can i get a clip of this occuring please
