### ISSUE TITLE
[Bug]: Radio menu whilst driving

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The /radios menu does not open on the wheel whilst driving

### Expected behaviour

Can use /radios whilst driving

### Steps to reproduce

drive
use /radios
see the wheel
annoyingly have to get out car to change radio

### CMG User ID

910

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next restart
