### ISSUE TITLE
[Bug]: ELS Not functioning as should

### ISSUE THREAD

**Issue by l3x04** [CMGStudios/issue-tracker#532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Lots of ELS vehicles are bugging out. sirens are staying on for some people and staying off for some. Doesn't seem to be any correlation between vehicles/people, just seems to be random and very common recently. ELS could possibly do with an update/rework?

### Expected behaviour

ELS synchronises between game clients as it should.

### Steps to reproduce

1) Go in the city
2) Interact with PD
3) Wait till someone asks for sirens to be turned off when you cannot hear any

### CMG User ID

45

**Comment by crazychris2404** [comment]
This is a issue that is randomly occurring and no set way to reproduce it i can leave this open for @tom-gun to give any suggestions for reproducing this issue

**Comment by packfile** [comment]
@VladDoesCars When this occurs, does turning the siren on and off fix the issue for the clients that have it stuck on?
