### ISSUE TITLE
[Bug]: MPD Doors being wierd.

### ISSUE THREAD

**Issue by l3x04** [CMGStudios/issue-tracker#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Doors in MPD/Vespucci are behaving weirdly when multiple people are near them.

### Expected behaviour

Doors open and close with one press of "E".

### Steps to reproduce

1) Go to MPD/Vesp
2) Open/Close doors

### CMG User ID

45

**Comment by crazychris2404** [comment]
I did experience this around mission row but was unable to get a clip of it occurring please can you attach a clip to show the exact issue

**Comment by packfile** [comment]
This is intentional (see dev-updates https://discord.com/channels/458382797103693867/598108077786529812/1052550556092223530). If this occurs when there is not a player around, or you have a suggestion on how this could be made more user-friendly around multiple players please lmk!
