### ISSUE TITLE
[Bug]: Vehicle Lock/Unlocking glitching

### ISSUE THREAD

**Issue by l3x04** [CMGStudios/issue-tracker#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sometimes when locking/unlocking a vehicle, the notification comes up with the status such as "Vehicle Unlocked", however when then attempting to enter the vehicle, you are unable to do so. To fix this pressing E on the vehicle to lock/unlock it through the radial menu helps.

### Expected behaviour

Vehicle locks behave as expected.

### Steps to reproduce

1) Get a car out
2) Lock/Unlock it and try to enter it when you unlock it.
3) This doesn't seem to have anything specific involved in producing the bug, but is more random. Has been an issue for years now.

### CMG User ID

45

**Comment by crazychris2404** [comment]
This is still a issue but as mentioned not reproducible commonly is caused when going far from the vehicle and having the blip disappear

**Comment by packfile** [comment]
No actionable information in report. There was a fix a couple months back that reduced the frequency of this happening. We'd need a series of steps to reproduce the behaviour you're describing in order to fix.
