### ISSUE TITLE
[Bug]: St Thomas Hospital

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

At at Thomas hospital there are sections of the road outside both above and below the building that are not solid objects and you fall right through them both on foot and in a car.

### Expected behaviour

You should be able to walk/drive over it.

### Steps to reproduce

1. All info above (currently I don’t have a clip, but it’s an issue for everyone not just one sided)

### Any Texture Packs? (If so list)

No

### CMG User ID

214124

**Comment by crazychris2404** [comment]
Thanks for the report this is something I have already mentioned to @tom-gun

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart.
