### ISSUE TITLE
[Bug]: Heist Set Up Keeps Replaying

### ISSUE THREAD

**Issue by Tomfuze** [CMGStudios/issue-tracker#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Evetime I finish the set up it wants me to do it again and pay another 500.000. I have done this twice already and have lost 1.000.000 so far. So id like a refund

### Expected behaviour

Complete the set up and continue?

### Steps to reproduce

Start the setup
Finish the set up
Start the set up again

### Any Texture Packs? (If so list)

N/A

### CMG User ID

317885

**Comment by packfile** [comment]
You can complete a setup as many times as you'd like. When you finish it should give you an item in your inventory (Scrambler Device). If you use your arrow keys you can switch between the setups
