### ISSUE TITLE
[Bug]: Gun still holstered after the battlegrounds event.

### ISSUE THREAD

**Issue by TotalXanarchy** [CMGStudios/issue-tracker#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After dying and leaving the battlegrounds event, although the weapons obviously aren't in my inventory, the assault rifle still displays on my character.
![image](https://user-images.githubusercontent.com/36505312/209348933-8295988d-f919-4f7d-82e1-4716f978e49a.png)

### Expected behaviour

There shouldn't be an assault rifle that I don't own strapped to my chest.

### Steps to reproduce

Join battlegrounds event

Get a weapon that holsters on your body

Die

Respawn at the airport with the gun holstered on your body still

### Any Texture Packs? (If so list)

Nope

### CMG User ID

313151

**Comment by TotalXanarchy** [comment]
After logging out and logging in later today, it put the gun from the event into my inventory without ammo so it just gave me the AR for free...?

**Comment by crazychris2404** [comment]
Confirmed

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next events test
