### ISSUE TITLE
[Bug]: my car is bugged

### ISSUE THREAD

**Issue by optixvi** [CMGStudios/issue-tracker#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

most times when i spawn my car in it is a different colour or has no windows. spawn code is 21ramtrx 

### Expected behaviour

most times when i spawn my car in it is a different colour or has no windows.

### Steps to reproduce

spawn the car in and it will be a different colour most of the time and have no windows. the car is meant to be black spawns in white most times. https://medal.tv/games/gta-v/clips/NYKZgOSM-AM4K/d1337ds6wGwJ?invite=cr-MSw3UjgsODgxMTUzOTks

### Any Texture Packs? (If so list)

no

### CMG User ID

218087

**Comment by crazychris2404** [comment]
This is not something we can fix the reason for it sometimes appearing white is due to the car having multiple liverys if you press insert you will have the ability to change this.
