### ISSUE TITLE
[Bug]: when im on my phone and go to a app i cant enter to go onto the app i need

### ISSUE THREAD

**Issue by callum1234567** [CMGStudios/issue-tracker#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when im on my phone and go to a app i cant enter to go onto the app i need

### Expected behaviour

when im on my phone and go to a app i cant enter to go onto the app i need

### Steps to reproduce

when im on my phone and go to a app i cant enter to go onto the app i need

### Any Texture Packs? (If so list)

no

### CMG User ID

287929

**Comment by crazychris2404** [comment]
Could I please get a clip of this occurring as I cannot reproduce this bug

**Comment by packfile** [comment]
No reproducible steps provided, once you have the requested clip ready please reopen the issue.
