### ISSUE TITLE
[Bug]: Dragging and pressing alt + E put in vehicle on PD

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you press alt and e when you are dragging someone and then put them in the vehicle, when you get them out of the vehicle they teleport to the person who dragged the originally. Basically allows you to crossmap drag someone. has happened to me when i put someone in another pds vehicle and when they got them out of the vehicle they teleported to me when i was in legion and they were at Mission Row

### Expected behaviour

Drag someone using alt D
Press alt e to open the wheel when youre dragging them
put them in vehicle
get them out of the vehicle (can be you or someone else)
they teleport drag to the person who put them into the vehicle when they dragged them

### Steps to reproduce

drag someone using alt d 
put them in the vehicle whilst dragging them using alt e
get them out the vehicle using alt f
they teleport to the person who put them into the vehicle when dragging them

### Any Texture Packs? (If so list)

None,

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Thanks for the report @004Luke 
Do you have a clip of this occurring please?

**Comment by 004Luke** [comment]
https://youtu.be/97oL8kBxx-I 
@crazychris2404 there you go

**Comment by crazychris2404** [comment]
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
