### ISSUE TITLE
[Bug]: safe sound effect  

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

after cracking the safe open you hear the safe open sound effect every 5 minutes

### Expected behaviour

you should only hear the sound effect when you open the safe  

### Steps to reproduce

crack the safe open
then you hear the sound effect every 5 minutes 

### CMG User ID

68457

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next restart
