### ISSUE TITLE
[Bug]: CMGstore purchases

### ISSUE THREAD

**Issue by Farrrrrrrr** [CMGStudios/issue-tracker#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

purchasing on the website, tried paypal and my personal card info it just says payment declined even though the bank has said its not a problem on their side i cannot purchase anything has been happening for awhile now

### Expected behaviour

cannot purchase anything off the CMG store when i click paypal doesn't come up with the "sign into paypal"

### Steps to reproduce

..

### CMG User ID

261446

**Comment by crazychris2404** [comment]
This is not something within the servers control unfortunately
