### ISSUE TITLE
[Bug]: Cars capped to 99 / 249

### ISSUE THREAD

**Issue by TheRealWicks** [CMGStudios/issue-tracker#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Car is capped to 249 and 99 in the city im assuming something wrong with the abusive flags thing yesterday

### Expected behaviour

100mph/250 flat

### Steps to reproduce

drive car

### Any Texture Packs? (If so list)

no

### CMG User ID

387

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
This is a visual bug (due to a rounding error), the cars are still driving at 100MPH/250MPH. It has been fixed from the next scheduled restart and is unrelated to the 'abusive flags' you're referring to
