### ISSUE TITLE
[Bug]: There is no timer when mining LSD/Diamond or anything 

### ISSUE THREAD

**Issue by yhcriss** [CMGStudios/issue-tracker#546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you go to gather process or do anything the timer at the bottom of your screen doesn't come up.

### Expected behaviour

Timer should come up at the bottom of your screen.

### Steps to reproduce

.

### Any Texture Packs? (If so list)

no

### CMG User ID

988

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
