### ISSUE TITLE
[Bug]: Long range blips lfb

### ISSUE THREAD

**Issue by BobbyTheBuildery** [CMGStudios/issue-tracker#547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When clocking on lfb long range blips don't work, normally they would display without doing /blipson however no blips are displayed, after doing /blipson they are only local blips compared to long range blips.

### Expected behaviour

clock on lfb 
long range blips display or /blips on and long range blips show not local ones

### Steps to reproduce

1. clock on lfb
2. long range blips should be displayed 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

169174

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
