### ISSUE TITLE
[Bug] : Game Crash

### ISSUE THREAD

**Issue by uhJux** [CMGStudios/issue-tracker#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i’m playing CMG my game randomly crashes no error message it’s like I’m F8 quitting but I’m not.

### Expected behaviour

An error message to appear 

### Steps to reproduce

.

### Any Texture Packs? (If so list)

None

### CMG User ID

154968

**Comment by crazychris2404** [comment]
This needs to be posted in discord under crash-zips instead of here please
