### ISSUE TITLE
[Bug]: UI bug

### ISSUE THREAD

**Issue by BobbyTheBuildery** [CMGStudios/issue-tracker#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

there is a bug which I'm unsure if it's reproducible, whenever I have loaded in for the first time into cmg I have a weird ui bug.
https://i.imgur.com/j3ZBdsg.png 
this only happens the first time I load in, I then have to relog and it's fine again. I have only had the issue yesterday and today. 

### Expected behaviour

load into cmg, ui loads normal you don't have to relog.

### Steps to reproduce

1. load into cmg
2. ui will look weird
3. f8 > quit
4. reload into cmg
5. ui is fine 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

169174

**Comment by crazychris2404** [comment]
Thanks for the report
Heard a few people mention this
There are some workarounds and not sure if this is reproducible so will move to trivial 

workarounds are as follows
Change your talking mode to shouting or whisper to update UI

OR

Take £1 from a ATM

**Comment by packfile** [comment]
Is this issue still happening @BobbyTheBuildery?

**Comment by crazychris2404** [comment]
This occurred to me last night aswell but was sadly not reproducible

**Comment by BobbyTheBuildery** [comment]
> Is this issue still happening @BobbyTheBuildery?

It's still happening to me

**Comment by packfile** [comment]
@BobbyTheBuildery What is your % CPU utilisation in the last 10 seconds before the loading screen disappears?

**Comment by BobbyTheBuildery** [comment]
The highest % was 45% in the last 10 seconds @tom-gun

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
