### ISSUE TITLE
Cocaine Strip Club MLO crashing game.

### ISSUE THREAD

**Issue by Grxpz** [CMGStudios/issue-tracker#55]
**Describe the issue you're facing** - Alot of crashing around the new Strip Club Mlo in the cocaine trader zone. Was with 3 friends at the time, we all crashed when driving in the facing direction of the entrance to the zone coming from the fuel station...Didnt crash when we entered the MLO from the other side, but the pathway leading to the gas station side is where we all crashed, I personally had a second crash whilst merely driving past, not looking at the MLO....perhaps unlucky but I said I'd report it.

**Steps to reproduce** Move in the direction of the new Strip Club MLO, when rendering the MLO it crashes your game it seems, only occured from the one side, described above.

**Expected behavior** Game will crash upon the attempt at rendering the MLO.

**Screenshots/Video** N/A

**Additional context** N/A

**Any Texture Packs (if so list)** New Vision Evolved | I believe the 3 parties involved all use NVE, however Im only certain of 2, myself included.

**Perm ID** 191307

**Comment by loganuk** [comment]
Can you give a screenshot of the exact location where this happens so I can test?

**Comment by loganuk** [comment]
Confirmed bug.

Causes crashes in the vicinity.
Really poor performance, even outside it.
No NPC to sell coke at position.
Back door of strip club broken.

MLO seems very borked beyond belief.

**Comment by rubbertoe98** [comment]
Fixed, MLO has been removed.
