### ISSUE TITLE
[Bug]: Radios menu shooting gun

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the /radios menu if you have a gun in hand it will shoot 

### Expected behaviour

Gun does not fire when using menu and should ignore the click when you are using the radios menu

### Steps to reproduce

Hold a gun
Use /radios
Select a option
Gun will fire

### CMG User ID

910

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
