### ISSUE TITLE
[Bug]: Broken textures in paleto

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When going towards the sand in paleto behind diner textures are very glitched
![image](https://user-images.githubusercontent.com/36340714/211854714-812975ca-8afe-4590-aa69-2055bbe1c0dd.png)

### Expected behaviour

To not have glitched textures

### Steps to reproduce

Drive to this location and see the glitched textures 
![image](https://user-images.githubusercontent.com/36340714/211854608-74af6559-0b54-4a24-9eb3-acd1876a41b0.png)

### CMG User ID

910

**Comment by packfile** [comment]
This does not reproduce locally, however I suspect this _could_ be one of the following:
1. Extended texture budget is too low
2. Extended distance scaling is too high
