### ISSUE TITLE
[Bug]: Unable to remove lfb equipment

### ISSUE THREAD

**Issue by BobbyTheBuildery** [CMGStudios/issue-tracker#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when placing down any lfb equipment in the lfb menu you will be unable to remove it most of the time, sometimes you are able to remove it but 90% of the time you can't. 
When it's used in a big situation it won't be removable. Staff are unable to remove it using the delgun.

### Expected behaviour

open lfb menu place down equipment such as water monitors and supply lines etc. when finished at active situation go back into the menu and remove the equipment using the remove buttons in the menu equipment should remove.

### Steps to reproduce

1. clock on lfb 
2. get fire truck out
3. go to active situation
4. open lfb menu 
5. place down equipment (supply lines, water monitors etc.)
6. put out fire
7. try and remove the lfb equipment (you can't remove the equipment)

### Any Texture Packs? (If so list)

N/A

### CMG User ID

169174

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
I can't reproduce this with the steps provided (objects delete fine), I suspect there is another condition involved here. Could you please confirm the following (by testing again in game):
a) You are able to delete objects created by other player(s)
b) Does the `Supply line removed` (or similar) notification appear when it fails to delete

**Comment by BobbyTheBuildery** [comment]
> I can't reproduce this with the steps provided (objects delete fine), I suspect there is another condition involved here. Could you please confirm the following (by testing again in game): a) You are able to delete objects created by other player(s) b) Does the `Supply line removed` (or similar) notification appear when it fails to delete

The supply line issue is mostly due to people getting in the vehicle whilst the hose is still connected this then prevents the hose being removed.
The other objects such as water monitors this can occur when placing more than one in a given area as far as I know.

**Comment by crazychris2404** [comment]
This I can confirm does not happen 100% of the time but enough that it should be investigated to find a cause of it

**Comment by tom-gun** [comment]
> The supply line issue is mostly due to people getting in the vehicle whilst the hose is still connected this then prevents the hose being removed.

Doesn't reproduce. Testing with 2 people, I had one drive the truck with the supply line still connected to the other side of the map & back, and it still deleted.
