### ISSUE TITLE
Faction Radios

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After pressing the Mute button in any faction radio, other people can still hear you if you press your radio button to speak

### Expected behaviour

Being able to mute radio and press the talk button without being heard

### Steps to reproduce

1. Join any faction radio
2. Press mute through settings
3. Press the radio talk button
4. Your name is shown as talking and you can also be heard

### CMG User ID

71613

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
