### ISSUE TITLE
[Bug]: looting bags in organ

### ISSUE THREAD

**Issue by maxreid250** [CMGStudios/issue-tracker#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you loot a bag in organ it'll put you in a freeze position

### Expected behaviour

above^ https://streamable.com/1tgg8g

### Steps to reproduce

1. Loot a bag in organ heist

### Any Texture Packs? (If so list)

N/A

### CMG User ID

204066

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
