### ISSUE TITLE
[Bug]: tutorial

### ISSUE THREAD

**Issue by DJW999999** [CMGStudios/issue-tracker#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am unable to pull out weapons or do a variety of things in game it says I must complete the tutorial first however /tutorial doesn’t work 

### Expected behaviour

/tutorial to work
Being able to pull out weapons and play properly

### Steps to reproduce

Load up the game
/tutorial
Nothing happens 

### Any Texture Packs? (If so list)

NA

### CMG User ID

329802

**Comment by crazychris2404** [comment]
Hi
This is expected as the /tutourial command will only work at a certain area within the airport
Please use /calladmin and request staff to take you there
