### ISSUE TITLE
[Bug]: LFB breathing aparatice bug 

### ISSUE THREAD

**Issue by jxckrundle** [CMGStudios/issue-tracker#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

on LFB u can put BA up and BA down when u do ba up it takes the full ba of you witch is not ment to happen it is ment to just take it of ur face

### Expected behaviour

it is ment to just take it of ur face

### Steps to reproduce

press u do ba up then ba down then it disappears 

### Any Texture Packs? (If so list)

no

### CMG User ID

201150

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
