### ISSUE TITLE
Open way under the map

### ISSUE THREAD

**Issue by SpeedyNN** [CMGStudios/issue-tracker#56]
**Describe the issue you're facing** Possible to jump under the map in cocaine turf

**Steps to reproduce** Log in and go to cocaine turf and go into the doorway at the back of the strip club

**Expected behavior** You fall for a bit and then spawn at the front of cocaine

**Screenshots/Video** 
![image](https://user-images.githubusercontent.com/87138573/124946370-a6120300-e017-11eb-8b7a-fae117b7c03b.png)

**Additional context** This started when the strip club mlo got added

**Perm ID** 200198

**Comment by MrLexo** [comment]
Interesting, Ill take a look at the new MLO added and see what the problem is.

**Comment by alfiellds** [comment]
Hello, this MLO will be removed at today's 3 PM restart. This should fix any crashing issues you may be experiencing.

Many thanks for bringing this to our attention.
