### ISSUE TITLE
[Bug]: Radial menu not working

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to open my boot to grind LSD and the radial menu doesnt work 

### Expected behaviour

I press E on my vehicle 
The radial menu should work

### Steps to reproduce

Pull a vehicle out 
Press E
Try to open boot

### Any Texture Packs? (If so list)

N/A

### CMG User ID

867

**Comment by crazychris2404** [comment]
Thanks for the report this is currently being resolved
