### ISSUE TITLE
[Bug]: Battlegrounds Event

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the battle grounds event there is a way to become invisible and unable to take damage meaning a win Everytime 

(Last bug report got deleted so gonna make this since no response was given at all)

### Expected behaviour

You should just get kicked from the event if you don’t jump from the bus in the designated area or if you don’t press the red button to drop.

### Steps to reproduce

1 • Press f5 when on the plane and your mouse will disappear

2 • Wait on plane and don’t jump until your out of the red circle and you don’t use mouse you just press “F”.

3 • When you land you can just loot crates as normal and equip them to use.

4 • To become visible again just press f5 your mouse will appear and click the deploy button and you will just appear on the spot

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
