### ISSUE TITLE
[Bug]: server timeout every time I try to rejoin

### ISSUE THREAD

**Issue by DJW999999** [CMGStudios/issue-tracker#562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I changed my death sound in game to roblox and it instantly kicked me now I get an error every time I rejoin
![image](https://user-images.githubusercontent.com/122706475/213067980-b3937bbe-d4ce-4ec9-b9e5-c12cbf570a73.jpg)

### Expected behaviour

Should let me join the server

### Steps to reproduce

Change death sound to roblox 

### CMG User ID

91042

**Comment by crazychris2404** [comment]
Is this still occuring @DJW999999 ?
