### ISSUE TITLE
[Bug]: Faction Contacts

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When sending a message to a Faction through the Contacts app on the Phone, that specific faction does not receive the call inside the call manager

### Expected behaviour

Send message to Faction
Message shows up as a call in Call Manager

### Steps to reproduce

1. Clock on LFB / NHS
2. Open Phone
3. Go to contacts
4. Select LFB / NHS
5. Enter message and press send
6. Open Call manager and the call is not found

### CMG User ID

71613

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
