### ISSUE TITLE
[Bug]: LFB Duty Menu

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When opening the LFB Duty Menu you can see every Clock on rank without having the required Discord Roles

### Expected behaviour

Open LFB Duty Menu and only be able to see the Ranks that are linked to Discord Roles

### Steps to reproduce

1. Get LFB Whitelist
2. Open LFB Duty Menu

### CMG User ID

71613

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
