### ISSUE TITLE
[Bug]: LFB Paycheck Multiplier

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Paycheck notification has incorrect spelling
Not receiving a multiplied paycheck even though I have the Firefighter of the Week Role on Discord
![image](https://user-images.githubusercontent.com/88695973/213302403-610100be-5dff-40c1-9991-4704fb3ef819.png)
![image](https://user-images.githubusercontent.com/88695973/213302437-14e9d54e-8726-4ef5-99f7-3e942cee1c22.png)

### Expected behaviour

Paycheck notification to have correct spelling
Receive a multiplied paycheck when I have the `Firefighter of the Week` Discord Role

### Steps to reproduce

1. Add `Firefighter of the Week` Discord Role
2. Clock on LFB
3. Wait for Paycheck

### CMG User ID

71613

**Comment by crazychris2404** [comment]
The spelling is correct?
Also this is not a bug report but something to be requested in the liasion channel
