### ISSUE TITLE
[Bug]: When you CPR you fall through the ground

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

with the new CPR update, when you finish CPR, you go about 2 foot below the ground and if you do CPR 2-3 times you eventually go through the floor and fall through the map.

### Expected behaviour

CPR someone 2-3 times without moving and you fall through the floor

### Steps to reproduce

Do CPR on an injured person
Dont move
Do CPR 2 more times
Fall through the ground

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
This does not happen 100% of time but can cause some issues

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
