### ISSUE TITLE
[Bug]: Fires in mid air from cars.

### ISSUE THREAD

**Issue by ghost** [CMGStudios/issue-tracker#569]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When cars go on fire, and they are flying, they tend to sometimes have fire in the air after they roll down to the ground.

### Expected behaviour

Cars should only be on fire when they are on the ground.

### Steps to reproduce

**1). Get a car
2). Vroom Vroom into the air till you can go on fire
3). Clock on as LFB
4). Try put the fire out**
5). Cry because the fire won't go out

### Any Texture Packs? (If so list)

N/A

### CMG User ID

328441

**Comment by crazychris2404** [comment]
Confirmed 
This is caused by fire not being removed save time as vehicle

**Comment by elfbars** [comment]
join discord.gg/cmgfrags :)

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
