### ISSUE TITLE
No clipping when dragging someone on PD

### ISSUE THREAD

**Issue by RazzaWelshy** [CMGStudios/issue-tracker#57]
**Describe the issue you're facing**
When arresting someone and pressing ALT + D I get thrown back and I go through walls and like there is nothing there and I can fly like im No Clipping and can go backwards

**Steps to reproduce** Im not sure but its up by sandy PD walking in press alt + d and get thrown and dragged backwards

**Expected behavior** No clipping through what you want

**Screenshots/Video** Dont have one as it happened when my clips was off

**Additional context**

**Any Texture Packs (if so list)**None

**Perm ID** 117744

**Comment by BigBoyReece** [comment]
Hey, is this happening multiple times to you? 

Or just this one occasion?

**Comment by BigBoyReece** [comment]
I have attempted to reproduce the issue, but do not get the same outcome.

Please upload video of this happening.

Thank you.
