### ISSUE TITLE
[Bug]: Some doors not lockable in the prison

### ISSUE THREAD

**Issue by Jamie1253** [CMGStudios/issue-tracker#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are multiple doors that are unable to be locked on the prison which allows for bad RP and trolling to take place. These doors are the boiler room in the cell block and the watch towers.

Prisoners troll prison guards and failrp in the boiler room by blocking the door as it is not lockable and then report said guard when they try and stop them.

When people breaking into the prison (Usually by GTA Driving) instead of being caught they will just run up the tower because the doors are not lockable and threaten to jump off which is just awful RP for the prison guards.

### Expected behaviour

The boiler room door and watch tower doors are able to be locked.

### Steps to reproduce

1. Go to a watch tower door and see you are unable to lock/unlock the door.
2. Go to the boiler room door and see you are unable to lock/unlock the door.

### CMG User ID

309666

**Comment by packfile** [comment]
Please make a feature request through your HQ team
