### ISSUE TITLE
[Bug]: Organ not opening at 18:50

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Same as the title. Organ heist is not opening at 18:50 and instead is opening after 7pm

### Expected behaviour

Same as above

### Steps to reproduce

Go to organ
it doesnt open at 18:50

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Thanks 
This is confirmed

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
