### ISSUE TITLE
[Bug]: If you are on the second page of your boot and store your car you are unable to loot bags 

### ISSUE THREAD

**Issue by Olddevaccount-RT** [CMGStudios/issue-tracker#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you leave your car boot on the second page and attempt to loot a bag you are unable to see or loot the contents

### Expected behaviour

Unable to loot bags

### Steps to reproduce

Open boot , go to second page , try loot a bag 

### CMG User ID

107980

**Comment by crazychris2404** [comment]
Hi @Olddevaccount-RT 
Thanks for the report
Do you have a clip of this occuring please

**Comment by Olddevaccount-RT** [comment]
Not currently , however a potential fix may be to set the users boot to page 1 after they close it

**Comment by crazychris2404** [comment]
Confirmed Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
