### ISSUE TITLE
[Bug]: Getting stuck on bags after you loot them 

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you loot bags on the floor. Not all the time but sometimes you get stuck on the bag after looting them. When you are stuck you cannot move until someone carries you and puts you back down on the floor. 

### Expected behaviour

Same as above. When you loot a bag you can't move until someone carries you and puts you back down. 

### Steps to reproduce

Loot bag
Can press X to cancel animation if you want but it doesn't matter 
Exit inventory screen
Can't move

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Thanks for the report @004Luke do you have a clip of this occuring?

**Comment by packfile** [comment]
No actionable information.
