### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Septic0x** [CMGStudios/issue-tracker#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Lights flickering on and off in organ heist

### Expected behaviour

The lights to just stay lit and not flicker on and off

### Steps to reproduce

1. Go in organ heist and looks at the lights 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

210593

**Comment by packfile** [comment]
Do you have a video of this occurring? The lights do not flicker when I go through any section of the silo

**Comment by kajblm** [comment]
I’m having the same issue as this user, it’s all the lamps that are in the cave area. I can provide a clip for this when I get home later.

**Comment by Septic0x** [comment]
https://medal.tv/games/gta-v/clips/T2LpxK10y_iJI/d13375HrNK8K?invite=cr-MSxrVEQsMjU3MDExNTcs 

Above is a clip of the lights flickering in organ

**Comment by crazychris2404** [comment]
Thanks for the report
I will leave this as trivial for further investigation

**Comment by ItsJunction** [comment]
If **Shadow Quality** is Off in settings then the lights tend to flicker - this isn't (directly) a CMG issue as it does the same on a vanilla server.

As a workaround, I would recommend setting Shadow Quality (Settings -> Graphics -> Shadow Quality) to Normal (or above).

https://streamable.com/cljnwn (tested on "all" low)

**Comment by crazychris2404** [comment]
Thanks for the info this is now confirmed

**Comment by packfile** [comment]
Solution has been provided above, as aforementioned the issue lies outside of CMG
