### ISSUE TITLE
[Bug]: cant get all 50 toys

### ISSUE THREAD

**Issue by SpooderModz** [CMGStudios/issue-tracker#576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,
Yesterday I was collecting all the toys and encountered the same problem as a lot of people and that I am stuck on 49/50 and I want the 7 days of plat and the 500k.

### Expected behaviour

The YouTube had put a video for the 50th toy but all comments are the same as me 49/50

### Steps to reproduce

I went to all locations again but still nothing

### CMG User ID

334804

**Comment by packfile** [comment]
Please verify all 50 locations again (and wait for ~5 seconds at that location for it to appear), you are likely missing one.
