### ISSUE TITLE
[Bug]: Custom Folders

### ISSUE THREAD

**Issue by NBKdev** [CMGStudios/issue-tracker#577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically everytime I log off my vehicles disappear from my custom folder garage and I have to reput them in and it's really annoying

### Expected behaviour

What I said above

### Steps to reproduce

F8 Quit
Relog
Connect to cmg go to pd garage and it shows 0

### CMG User ID

22

**Comment by crazychris2404** [comment]
Personally i have not experienced this i will see if anyone else has

**Comment by packfile** [comment]
@NBKdev Can you please confirm if this is still happening since the latest restart

**Comment by NBKdev** [comment]
@tom-gun yes it's just happened now when i brought plat

**Comment by NBKdev** [comment]
A few other civs were complaining about it

**Comment by crazychris2404** [comment]
Is this linked to https://github.com/CMGStudios/issue-tracker/issues/579

**Comment by crazychris2404** [comment]
Fixed from next restart
