### ISSUE TITLE
[Bug]: HMP Range Rover missing from garage 

### ISSUE THREAD

**Issue by Jamie1253** [CMGStudios/issue-tracker#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Logged onto the server to find that my HMP Range Rover is missing from my garage. I got multiple others to try and spawn them too from garage but they are also missing the range rover.

### Expected behaviour

Range Rover able to be spawned from garage. 

### Steps to reproduce

1. Go to garage
2. HMP Vehicles Folder

### CMG User ID

309666

**Comment by crazychris2404** [comment]
Fixed for next restart
