### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MoTioNzHD** [CMGStudios/issue-tracker#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Vehicles are wiped from custom folders and even after making new folders and putting back in they wipe again 

### Expected behaviour

Vehicles are wiped from custom folders and even after making new folders and putting back in they wipe again 

### Steps to reproduce

1.add vehicles to custom folder
2. Go back into custom folders
3. No cars in custom folders

### Any Texture Packs? (If so list)

No

### CMG User ID

912

**Comment by crazychris2404** [comment]
Fixed from next restart
