### ISSUE TITLE
Spawning under the floor

### ISSUE THREAD

**Issue by RazzaWelshy** [CMGStudios/issue-tracker#58]
**Describe the issue you're facing**When loading in I keep spawning under the floor and get stuck underneath the floor and my clothes reset

**Steps to reproduce** Load in

**Expected behavior** Spawn under the floor

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**None

**Perm ID**117744

**Comment by alfiellds** [comment]
Hello Razza, thank you for the report. This will be forwarded to the developers for them to review.

**Comment by rubbertoe98** [comment]
Cannot reproduce, how often does this happen? Can you post a video? And please post your PC specs too.

**Comment by Xotiic1** [comment]
This used to happen to me before I stopped using steam

**Comment by rubbertoe98** [comment]
Closing due to being unable to reproduce & no reply after asking for further evidence.
