### ISSUE TITLE
[Bug]: DJ Menu inside casino nightclub

### ISSUE THREAD

**Issue by Septic0x** [CMGStudios/issue-tracker#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the DJ menu in the nightclub, you are frozen mid-air after using the menu.

### Expected behaviour

Use the DJ menu without being frozen

### Steps to reproduce

1. Go to the Casino nightclub
2. Use the DJ menu inside 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

210593

**Comment by crazychris2404** [comment]
hi @Septic0x Thanks for the report
Do you have a clip of this occuring?

**Comment by tom-gun** [comment]
We're unable to reproduce this bug; I've seen this used recently too, and there wasn't any apparent issues. Once you have the requested video please reopen the report
