### ISSUE TITLE
[Bug]: Duplicate Vehicle in Garages

### ISSUE THREAD

**Issue by MarvyMarvz** [CMGStudios/issue-tracker#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the Custom Folder bug, we've seen duplicate vehicles in the garages. The vehicles in custom folders also show up in the VIP Garages.

Please note: I have 'Hide customs folder vehicles' enabled. (So it should work)

### Expected behaviour

If I put a vehicle in custom folder, I shouldn't be able to see it in the VIP Garage.

### Steps to reproduce

1. Create a Custom Folder
2. Go to VIP Garages and Add a Vehicle to the Custom Folder
3. Check Custom Folder

### CMG User ID

382

**Comment by crazychris2404** [comment]
Confirmed
This is also a problem when cars are rented or sold they show within custom folders/garages until relogging
