### ISSUE TITLE
[Bug]: PD cant cuff after coming out of organ

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After organ heist finished, you cannot cuff civs after you tackle or taze them or even have hands up

### Expected behaviour

Look above

### Steps to reproduce

go to organ
finish it
cant cuff

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Can i see a clip of this occuring please @004Luke

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
