### ISSUE TITLE
[Bug]: custom folders

### ISSUE THREAD

**Issue by MoTioNzHD** [CMGStudios/issue-tracker#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Custom folders not refreshing straight away wen I remove vehicles from custom folders but does wen I add ,as wen I try remove vehicle again it says vehicle ain’t in custom folder but it’s still in folder

### Expected behaviour

Custom folders not working 

### Steps to reproduce

1.remove car from custom folder
2.still there and try to remove again
3.says car ain’t in custom folder but shows in there 

### CMG User ID

912

**Comment by crazychris2404** [comment]
Linked with https://github.com/CMGStudios/issue-tracker/issues/581#issuecomment-1424745146

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
