### ISSUE TITLE
[Bug]: Plat Menu Broken

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have 20 days of plat remaining but im unable to sell any to my friends

### Expected behaviour

I expect to be able to sell play to my friends without having any struggle

### Steps to reproduce

1. Do /cmgclub
2. Click on manage subscription
3. Click "Sell Platinum Subscription Days"
4. Nothing Happens

### Any Texture Packs? (If so list)

N/A

### CMG User ID

867

**Comment by crazychris2404** [comment]
This should be fixed now @Declare5M if this is still occuring feel free to reopen this issue
