### ISSUE TITLE
[Bug]: can't fuel up my car

### ISSUE THREAD

**Issue by eraywm** [CMGStudios/issue-tracker#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I can't fuel up my car, I tried going to a gastation and buying a jerrycan. Both options didn't work to fuel it up. Spawncode of the car is (biggestbird). You can only fuel it up with platinum subscription.

### Expected behaviour

the car should be able to fuel up

### Steps to reproduce

1) go to a gasstation
2) fuel up your car or buy a jerrycan

### CMG User ID

878

**Comment by crazychris2404** [comment]
Forwarded to @tom-gun

**Comment by tom-gun** [comment]
Thanks for the report, this will be fixed in the next few days

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
