### ISSUE TITLE
[Bug]: Whitelist Weapons Menu Bug?

### ISSUE THREAD

**Issue by MarvyMarvz** [CMGStudios/issue-tracker#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can't see my weapons in the Custom Weapons Owned Menu ![image](https://user-images.githubusercontent.com/115298470/218324671-8bee4aed-dad6-4285-b8a9-2ac3a4ae37c6.png)

### Expected behaviour

I should be able to see all my weapons that are whitelist owned.

### Steps to reproduce

1. Click F2
2. Click WhiteList Weapons

### CMG User ID

382

**Comment by crazychris2404** [comment]
![image](https://user-images.githubusercontent.com/36340714/218329486-c42d7b76-aff2-4898-9df2-ddbeb77940ef.png)
Personally i do not have this issue maybe @tom-gun knows more about this

**Comment by crazychris2404** [comment]
Please can you include which weapon this concerns

**Comment by crazychris2404** [comment]
@MarvyMarvz As it states create a weapon ticket in the donation support discord
