### ISSUE TITLE
[Bug]:  carbon bug

### ISSUE THREAD

**Issue by ghost** [CMGStudios/issue-tracker#588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the carbon textures on my car keeps on bugging out and its gone green and black where its meant to be carbon black 

### Expected behaviour

the carbon textures on my car keeps on bugging out and its gone green and black where its meant to be carbon black 

### Steps to reproduce

-

### Any Texture Packs? (If so list)

no

### CMG User ID

252820

**Comment by crazychris2404** [comment]
This is a issue with the model of the car if you DM me on discord Chris.#2962 i will attempt to resolve this ASAP
