### ISSUE TITLE
ELS/Siren's BUG

### ISSUE THREAD

**Issue by 2140CMG** [CMGStudios/issue-tracker#589]
Siren's are staying on after being turned off or when lights are not turned on, Bug happens on NHS vehicles, spawncode "rs6amboels" and "defenderambo" issue has been happening for a while with the driver usually not able to hear the sirens but others can , Evidence https://streamable.com/ycknj2 - Bug happening with me still hearing the sirens after being turned off
https://medal.tv/games/gta-v/clips/UuFjzDGKei5oC/d1337b3YEZW2?invite=cr-MSwzU1EsMTQ1NDg1NjY0LA - others hearing sirens after lights off.
https://clips.twitch.tv/ConfidentCarelessMacaroniHassaanChop-DAUFw440etYHZewy

**Comment by packfile** [comment]
Thanks for the report, perhaps this is related to having custom engine audio? Could you (or @crazychris2404 when back) please try and see if this is the case and let me know

**Comment by crazychris2404** [comment]
Tested and was still not reproducible @tom-gun
