### ISSUE TITLE
[NHS] Wheelchairs hard to get hold of with E

### ISSUE THREAD

**Issue by JaouadAR** [CMGStudios/issue-tracker#59]
**Describe the issue you're facing**
When getting out the /wheelchair to sit or grab a hold of it using E it is really hard at the moment, hopefully this can be fixed.

**Steps to reproduce**
Get out /wheelchair
Spam E to get a hold of it real quick.

**Expected behavior**
The E should be stuck on one place and we only should press E once to sit or get a hold of it.
**Screenshots/Video**
N/A but i'm pretty sure it might have been known to you already.
**Additional context**
-
**Any Texture Packs (if so list)**
It didn't work before already but i made a custom one for myself with a lot of different components.
**Perm ID**
115411

**Comment by alfiellds** [comment]
Thanks for the report, this will be forwarded to the developers.

**Comment by rubbertoe98** [comment]
Fixed from next restart.
