### ISSUE TITLE
[Bug]: radio 

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you die you cant talk on the radio for 10 seconds 

### Expected behaviour

you should be able to talk on radio unless your been finished of 

### Steps to reproduce

die 
then try to talk on the radio 

### CMG User ID

68457

**Comment by tom-gun** [comment]
> when you die you cant talk
