### ISSUE TITLE
[Bug]: Mission Row MLO Bugged and Call Manager

### ISSUE THREAD

**Issue by Macccc1** [CMGStudios/issue-tracker#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The front desk at mission row is broken again and the call manager is bugged every time you try to deny a all it doesn't deny it u have to click on it one by one and deny it

### Expected behaviour

The front desk at mission row is broken again and the call manager is bugged every time you try to deny a all it doesn't deny it u have to click on it one by one and deny it

### Steps to reproduce

https://cdn.discordapp.com/attachments/880964002690248755/1076299623825686529/image.png

https://cdn.discordapp.com/attachments/880964002690248755/1076299739408117780/image.png

### Any Texture Packs? (If so list)

No

### CMG User ID

741

**Comment by crazychris2404** [comment]
The call manager is not a bug 
Front desk is fixed
