### ISSUE TITLE
[Bug]: Extreme lag in Mission Row PD and surrounding areas

### ISSUE THREAD

**Issue by ghost** [CMGStudios/issue-tracker#592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In mission row and the surrounding areas some lower end PCs tend to lag and have severe FPS drops. This affects transports and other MET activities. 

### Expected behaviour

Not be so laggy at mission row and surrounding areas. 

### Steps to reproduce

1. Go to mission row
2. Enjoy the lagfest

### CMG User ID

328441

**Comment by crazychris2404** [comment]
Hi could this be down to your pc specs? 
I was playing this morning with 0 issues?

**Comment by ghost** [comment]
Nope, it’s fine everywhere else in the map. Just around that area I get massive fps drops.
