### ISSUE TITLE
[Bug]: looting bag puts u in the floor

### ISSUE THREAD

**Issue by TheRealWicks** [CMGStudios/issue-tracker#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you are looting a bag and u cancel it or just sometimes normally u bug in the ground and u cant move its very annoying and you need someone to /carry u out or craftmoped

### Expected behaviour

not be stuck like step sis

### Steps to reproduce

loot a bag i think its when u pers x to cancel animation

### Any Texture Packs? (If so list)

no

### CMG User ID

387

**Comment by packfile** [comment]
@TheRealWicks Can you please provide a video of this occurring

**Comment by TheRealWicks** [comment]
https://streamable.com/is7gv9

**Comment by TheRealWicks** [comment]
Why is this low priority we are litterally losing fights and guns because we are stuck in one place pls fix

**Comment by crazychris2404** [comment]
Placed in wrong folder fixed

**Comment by 004Luke** [comment]
Don't know if this helps but if you get searched or carried, it fixes itself. 
May I also add that this also happens sometimes with cpr.

**Comment by packfile** [comment]
Thanks for the report, this should no longer happen from the next scheduled restart
