### ISSUE TITLE
[Bug]: Call manager

### ISSUE THREAD

**Issue by NBKdev** [CMGStudios/issue-tracker#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can't delete pd calls you have to click on the call then press -  as before you could simply press - / + 

### Expected behaviour

Can't delete pd calls you have to click on the call then press -  as before you could simply press - / + 

### Steps to reproduce

Press ` 
Click on a call 
Then press - 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

22

**Comment by crazychris2404** [comment]
I believe this is a feature where you now need to select a call to deny
 @tom-gun can you confirm?

**Comment by packfile** [comment]
Correct, but this original behaviour shouldn't have been changed either. Will take a look later this week

**Comment by elfbars** [comment]
meow

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
