### ISSUE TITLE
[Bug]: combat timer when clocking off

### ISSUE THREAD

**Issue by BobbyTheBuildery** [CMGStudios/issue-tracker#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when clock off nhs you gain a combat timer which makes you slam the wall for a solid minute

https://i.imgur.com/0quwPPs.png 
### Expected behaviour

clock on nhs
take calls 
clock off nhs no combat timer and able to freely walk around and do other stuff.

### Steps to reproduce

1. clock on nhs 
2. take calls
3. go to clock off 
4. gain a combat timer for 60 seconds

### Any Texture Packs? (If so list)

N/A

### CMG User ID

169174

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report
This occurs with all factions

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
