### ISSUE TITLE
[Bug]: bought 2m money bag it’s been 40 mins hasn’t came

### ISSUE THREAD

**Issue by Jmezza1** [CMGStudios/issue-tracker#596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

bought 2m money bag it’s been 40 mins hasn’t came

### Expected behaviour

No

### Steps to reproduce

Idk 

### Any Texture Packs? (If so list)

No

### CMG User ID

273840

**Comment by crazychris2404** [comment]
Hi if you do /store it should appear there if not reopen the issue
