### ISSUE TITLE
[Bug]: mclaran

### ISSUE THREAD

**Issue by billy32349** [CMGStudios/issue-tracker#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought a McLaren for 1.65 million at simians on the super section and it took my money but didn't give me the car.

### Expected behaviour

I should have had a car in my garage.

### Steps to reproduce

1.go to simians.
2.go to the super class.
3.buy the mclaran720s for £1,650,000.
4.check your garage.

### Any Texture Packs? (If so list)

vanilla.

### CMG User ID

340514

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
