### ISSUE TITLE
[Bug]: pd smoke grenades

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you aim your gun and press g it throws the can but the smoke never shows 

### Expected behaviour

should aim your gun press g and should throw smoke grenade and you should smoke 

### Steps to reproduce

aim gun 
press g

### CMG User ID

68457

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report
Note:
This only occurs when using g to throw whilst aiming

**Comment by packfile** [comment]
This is intentional for now
