### ISSUE TITLE
prison bug

### ISSUE THREAD

**Issue by S0baa** [CMGStudios/issue-tracker#60]
whenever i get sent to jail i get let out immediately and it says i have to relog and that im in the wrong game file, then when i restart im in jail but dead and it says i have committed suicide 
this is really annoying because i dont like restarting my game and having to relaunch and then have to wait in jail while dead, i would appreciate it if you could look into this and find a way to resolve it or if its on my end help me resolve it .

**Comment by alfiellds** [comment]
Hello, thank you for the report. It would've been extremely useful if you could've followed the template provided in order to provide the developers with the information they need in order to fix this issue. 

Are you able to provide a video of this occurring?

**Comment by S0baa** [comment]
no i cant and i dont know how i would follow the template because i have no clue how u would get a texture pack for it

**Comment by alfiellds** [comment]
You do not need a texture pack. If you do not have one just put N/A.

If you could try and reproduce the issue and provide us with a video of it occurring then the developers can make an attempt to fix it.

Many thanks.

**Comment by alfiellds** [comment]
Closing this due to no response. If the issue occurs again please save a video and make a new bug report.

Many thanks.
