### ISSUE TITLE
[Bug]: Balance in Monzo app does not update

### ISSUE THREAD

**Issue by TomDotBat** [CMGStudios/issue-tracker#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The balance presented in the Monzo app does not update with your bank balance. It will only display the amount you had at the first time you opened it during a session.

### Expected behaviour

The balance should have the same value as what is shown on your HUD.

### Steps to reproduce

1. Open the app
2. Profit (literally)
3. Open the app and find your cashflow sucks

### Any Texture Packs? (If so list)

N/A

### CMG User ID

338708

**Comment by crazychris2404** [comment]
Thanks for the report 
Confirmed 
Low priority bug

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
