### ISSUE TITLE
[Bug]: /p chat no longer works due to recent addition of pava spray.

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The /p chat for police no longer no works because of the addition of pava spray. You cannot chat, nor can you do anything with  /p. 

### Expected behaviour

/p chat not working

### Steps to reproduce

Do /p
Doesn't work

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
This has already been mentioned but will be moved to high priority

**Comment by packfile** [comment]
Thanks for the report, PAVA has now been changed to a weapon which can be bought in the armoury
