### ISSUE TITLE
[Bug]: Oil RIG MLO not moved

### ISSUE THREAD

**Issue by MostlyCloud** [CMGStudios/issue-tracker#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

tom said he moved the new MLO to the old location biut it hasnt moved only the crate has and it spawns mid air

### Expected behaviour

cant loot crate as its mid air

### Steps to reproduce

wait for rig to pop 

### Any Texture Packs? (If so list)

No

### CMG User ID

977

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next restart
