### ISSUE TITLE
Fortune Club Bugs and Errors

### ISSUE THREAD

**Issue by joshuaarodgerss** [CMGStudios/issue-tracker#603]
Hi there, Mr. Glittering's here. There are a few bugs within the Fortune Nightclub MLO that I would hopefully like to have fixed, below I have attached a YouTube video with the bugs and errors I'd like fixed. Thankings!

https://youtu.be/GeepgDUZQxw

**Comment by packfile** [comment]
Thanks for the report, closed as this issue is not game breaking. If this building is used for your notable gang, please get in contact with me directly
