### ISSUE TITLE
[Bug]: Galaxy Nightclub MLO

### ISSUE THREAD

**Issue by joshuaarodgerss** [CMGStudios/issue-tracker#604]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

The issues that we are facing with the Galaxy Nightclub MLO as are follows:

- People may need to relog when arriving at the club as the MLO hasn't loaded in.
  Video Link showing this bug: https://youtu.be/jbbe6L-skD0

- The garage doors in the garage of the MLO do not open.
   Video Link showing this bug: https://youtu.be/fsRl7CvjHuc

- You cannot get to the ticket booth as there is no door that leads to it, this was pointed out to me by an Admin.
   Image showing the room in question: https://imgur.com/a/fcG7a55

- The DJ booth faces your character the wrong way whilst you're using it
   Image showing this bug: https://imgur.com/a/gJz62tv

### Expected behaviour

The MLO should correctly load upon first arrival. The doors to the garage should open, as there is a CMG car spawner in the garage. You should be able to get to the ticket booth. The DJ booth should face the character the correct way whilst it's in use.

### Steps to reproduce

MLO Not Loading
1. Drive to the MLO

Garage Doors do not open
1. Drive up to the garage doors.

Ticket Booth
1. N/A

DJ Booth
1. Go to use the DJ booth, and you won't be facing the correct way.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

213879

**Comment by crazychris2404** [comment]
MLO not loading:
Did not experience but have seen before so may be something not seen 100% of the time

Garage doors not opening:
This is correct however feel they were not planned to open originally. As there is no exit on other side of garage door

Ticket office:
Correct however there was never a door here so would be a case of not being inside original MLO more than being a bug

DJ Booth:
Confirmed character position is incorrect

**Comment by joshuaarodgerss** [comment]
Is there any way we could get the MLO updated with the new files, as I believe this could reduce the amount of bugs that Galaxy currently contains.

**Comment by joshuaarodgerss** [comment]
Didn’t mean to close it, oops!

**Comment by crazychris2404** [comment]
They are not bugs as it is just features that were not implemented originally with the MLO so i will leave for @tom-gun to decide alongside management if this can be updated.

There is only one thing listed which was a bug that one being textures not loading.

**Comment by joshuaarodgerss** [comment]
The DJ also facing the incorrect way is a bug too, but thanks for all your help.

**Comment by crazychris2404** [comment]
My bad that aswell

**Comment by packfile** [comment]
MLO not loading can not be reproduced (and there was also a fix for this around a month ago). For the Garage doors not opening/Ticket office, as Chris mentioned, this is how it was originally imported. The DJ character position has been fixed for next restart
