### ISSUE TITLE
Looting back freezes you on the spot (random) civ/pd matter

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#605]
when looting bags sometimes you get randomly frozen on the spot, and the only way to get out of this position is via another player doing t/th, t/carry and searching you otherwise you have to have an admin come carry you. 
https://youtu.be/IbQ0X6CzcdE

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
This is believe to be fixed from the next scheduled restart. If not then please reopen the issue
