### ISSUE TITLE
[Bug]: In game faction radios

### ISSUE THREAD

**Issue by Macccc1** [CMGStudios/issue-tracker#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When ever you f8 quit your name will still be on the radio. this has happened before like 5 months ago

### Expected behaviour

When ever you f8 quit your name will still be on the radio. this has happened before like 5 months ago

### Steps to reproduce

https://cdn.discordapp.com/attachments/1053845892299509862/1082099087517692004/image.png

### Any Texture Packs? (If so list)

No

### CMG User ID

741

**Comment by crazychris2404** [comment]
I believe this may now be fixed
If not this would be linked to the recent gangs update
If this still occurs please reopne this report
