### ISSUE TITLE
[Bug]: whitelisted faction radios

### ISSUE THREAD

**Issue by Macccc1** [CMGStudios/issue-tracker#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When ever you f8 quit your still on the radio. this has happened before like 5 months ago. I believe this has happened because of the new gang radios that has currently been implemented

### Expected behaviour

When ever you f8 quit your still on the radio. this has happened before like 5 months ago. I believe this has happened because of the new gang radios that has currently been implemented

### Steps to reproduce

https://cdn.discordapp.com/attachments/824010561657503744/1082777440033706175/image.png

### Any Texture Packs? (If so list)

No

### CMG User ID

741

**Comment by crazychris2404** [comment]
This has since been fixed
