### ISSUE TITLE
[Bug]: not able to rebind crouch button anymore

### ISSUE THREAD

**Issue by JDove11** [CMGStudios/issue-tracker#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the update that added the option to prone I have not been able to crouch using the button that I bind it to. For example, if I bound 'stealth mode' to a side mouse button it would not work using the side mouse button and would only work using the default left control button.

### Expected behaviour

Should be able to crouch or go into 'stealth mode' using the key that you bind it to in the settings rather than only being able to use the left control button.

### Steps to reproduce

Rebind 'stealth mode' in the settings to a new keybind and try to use that key to crouch.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

863

**Comment by crazychris2404** [comment]
Can you try go to settings -> key binding -> cmg and rebind crouch there please

**Comment by crazychris2404** [comment]
Closed due to no response
