### ISSUE TITLE
[Bug]: You can relog and get a car out the garage to prevent lockpicking

### ISSUE THREAD

**Issue by FinJ23** [CMGStudios/issue-tracker#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you re-log and respawn the same car, the person lockpicking will only get a "Vehicle unlocked" pop-up in the lower left of their screen. 

### Expected behaviour

Should be able to just lockpick normally

### Steps to reproduce

.

### Any Texture Packs? (If so list)

.

### CMG User ID

93969

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this was fixed last week
