### ISSUE TITLE
Staff cant open settings menu

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#61]
**Describe the issue you're facing**
Staff cannot open the settings menu on F2

**Steps to reproduce**
Press F2 as staff then go to settings and it will not open the menu.

**Expected behavior**
Should open menu to toggle rendering and weapons etc

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
168906

**Comment by arthur-rl** [comment]
Have you tried using `/settings`?

**Comment by crazychris2404** [comment]
Using /settings works however the option on admin menu does not

**Comment by rubbertoe98** [comment]
Already fixed for next restart.

**Comment by crazychris2404** [comment]
Issue still occuring
