### ISSUE TITLE
[Bug]: voice chat - Pgup

### ISSUE THREAD

**Issue by Macccc1** [CMGStudios/issue-tracker#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In order to go on shouting you have to press Pgdn 2 times before this bug happened you were able to press Pgup 2 times and you would be on shouting

### Expected behaviour

In order to go on shouting you have to press Pgdn 2 times before this bug happened you were able to press Pgup 2 times and you would be on shouting

### Steps to reproduce

Fix it so you can Pgup 2 times to go from whisper - talking to shouting

### Any Texture Packs? (If so list)

No

### CMG User ID

741

**Comment by crazychris2404** [comment]
I havent experienced this maybe someone else has?
