### ISSUE TITLE
[Bug]: AA Job not picking up cars with it's hook  

### ISSUE THREAD

**Issue by Gooobie** [CMGStudios/issue-tracker#612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When clocked on as the AA job you are given the option between 3 AA cars one of the cars is the Tow truck, and the hook only attaches to a small number of cars.

### Expected behaviour

The AA truck should be able to pick everything up with its hook.

### Steps to reproduce

Get in the AA truck and put the hook against any car sometimes it works and sometimes it doesn't.

### Any Texture Packs? (If so list)

NVE

### CMG User ID

168410

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report 
https://canary.discord.com/channels/458382797103693867/892435088430727198/1086257184381349898

**Comment by packfile** [comment]
Thanks for the report, there will be an update shortly to resolve this.
