### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Houchkin** [CMGStudios/issue-tracker#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When looting bags, you can quiet often get stuck, it requires a carry / piggyback to fix and its really annoying and can get you killed.

### Expected behaviour

When looting a bag, after you loot you cannot move, you just run on the spot

### Steps to reproduce

Loot a bag and sometimes you get stuck

### CMG User ID

12345

**Comment by crazychris2404** [comment]
Confirmed this does happen occasionally when doing cpr or looting a bag

**Comment by crazychris2404** [comment]
Linked with a pre-existing report 
https://github.com/CMGStudios/issue-tracker/issues/605
