### ISSUE TITLE
[Bug]: Cant access figure in redzone

### ISSUE THREAD

**Issue by papasauce101** [CMGStudios/issue-tracker#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cant access figure in redzone as usdate has put a house there apparently? maybe inside the house? all the others are good

### Expected behaviour

maybe move figure next to house or move house out the way maybe

### Steps to reproduce

.

### CMG User ID

306089

**Comment by crazychris2404** [comment]
This is already planned to be fixed over next couple of days thanks for the report
