### ISSUE TITLE
[Bug]: 111/999 Invisibility

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you do /111 or /999 in a car the texting animation caused you to become invisible until you step out of the car.

https://streamable.com/uubve5

### Expected behaviour

Shouldnt happen

### Steps to reproduce

1. Sit in car
2. Do /111 /999
3. It will animate and then ur invisible

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by kajblm** [comment]
* can also be used to alter location so if you drive away it will say you where you began

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
