### ISSUE TITLE
[Bug]: Track width

### ISSUE THREAD

**Issue by Boddy12** [CMGStudios/issue-tracker#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When changing the track width on my import S15 the wheel has bugged into the car. Cant reset it and adjusting the width doesnt work at all.

### Expected behaviour

When applying the Front track width it has bugged my wheels and they are inside the car

### Steps to reproduce

1.) own import s15.
2.) apply front track width mod.
3.) see the wheel has bugged into the vehicle.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

212275

**Comment by crazychris2404** [comment]
Can you provide a clip of ls customs settings please

**Comment by Boddy12** [comment]
> Can you provide a clip of ls customs settings please

could you come discord and i can show you my clippign software is broken, trying to sort it now but unsure wether itll work.

**Comment by Boddy12** [comment]
think its sorted one second

**Comment by Boddy12** [comment]
cant clip it, discord?

**Comment by Boddy12** [comment]
![image](https://user-images.githubusercontent.com/128744342/227343358-46ccf001-fdc2-445b-8991-a4d4384caa52.png)
![image](https://user-images.githubusercontent.com/128744342/227343396-483423e1-0489-43c3-9929-57b39d6afc56.png)
![image](https://user-images.githubusercontent.com/128744342/227343422-470285ee-e249-4265-ab89-04de7a858c60.png)
![image](https://user-images.githubusercontent.com/128744342/227343442-e86eba07-deb6-4338-9c77-856eed3ad605.png)
![image](https://user-images.githubusercontent.com/128744342/227343471-fab640a8-4c8c-4c4c-a899-72aa9ef8f06c.png)
This is a few different settings, seems like the whole thing is off line the one on the right is not even with the left one.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart. Make sure the front/rear width is set to 0.0 and then spawn the car from the garage again
