### ISSUE TITLE
[Bug]: Midnight club MLO

### ISSUE THREAD

**Issue by CMGJ4mes** [CMGStudios/issue-tracker#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MLO has an invisible wall

### Expected behaviour https://medal.tv/games/gta-v/clips/10ZDdf9lXVggmZ/d1337o2EXBBQ?invite=cr-MSx2ck8sNzIwNTY0MzMs

MLO has an invisible wall

### Any Texture Packs? (If so list)

nope

### CMG User ID

274129

**Comment by crazychris2404** [comment]
Which MLO ?

**Comment by CMGJ4mes** [comment]
Midnight garage by mission row

**Comment by crazychris2404** [comment]
Confirmed Thanks for the report

**Comment by CMGJ4mes** [comment]
Any update on this ?

**Comment by crazychris2404** [comment]
Just need to wait for the bug to be fixed by a developer

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
