### ISSUE TITLE
[Bug]: Trouser bug

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Purple trousers (165) are appearing to be black for people with no graphics pack.
When I went on CMG with NVE on yesterday it showed them as purple for me and maybe it is regular GTA / FiveM that is where the issue is.

### Expected behaviour

Trousers to be purple

### Steps to reproduce

Put on 165 trousers and load on CMG with no graphics pack.
Load on with NVE and you see them as purple.

### Any Texture Packs? (If so list)

No

### CMG User ID

205070

**Comment by packfile** [comment]
This is an issue with FiveM and is being fixed by them.
