### ISSUE TITLE
Incorrect stats about clocked on showing on home menu for HMP

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#62]
**Describe the issue you're facing**
Says a different number to amount clocked on under HMPS on home menu

**Steps to reproduce**

**Expected behavior**
Shows correct amount clocked on

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/36340714/125166290-d8943b00-e192-11eb-94a7-6f0fb7ce133b.png)

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
168906

**Comment by alfiellds** [comment]
Hello, thank you for the report. I believe the developers are currently looking to get this resolved.

**Comment by alfiellds** [comment]
Hello Chris, I can confirm this has been fixed by the developers and changes should be live now following today's 3PM restart.

Many thanks for the report.
