### ISSUE TITLE
[Bug]: Banned from discord

### ISSUE THREAD

**Issue by TB420** [CMGStudios/issue-tracker#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am currently banned from discord.gg/cmg. this is saddening to hear and is affecting my mental health as a result. I would love to hear as to why i was banned. 

### Expected behaviour

Unbanned

### Steps to reproduce

discord.gg/cmg --> unable to accept invite

### CMG User ID

202724

**Comment by crazychris2404** [comment]
Appeal on forums not here
