### ISSUE TITLE
[Bug]: my gangs are glitched 

### ISSUE THREAD

**Issue by Eugene091025** [CMGStudios/issue-tracker#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when people invite me to a gang it says i am in one when im not 

### Expected behaviour

.

### Steps to reproduce

.

### Any Texture Packs? (If so list)

.

### CMG User ID

327297

**Comment by crazychris2404** [comment]
Leaving for @tom-gun to look into as it is stated you are not in a gang
Please test this after server restart and let me know if a persistent issue please

**Comment by Eugene091025** [comment]
@crazychris2404 this issue is still present because it says to the person that is trying to invite me that I I'm in another gang already.

**Comment by packfile** [comment]
@triipodd Can you confirm the date you was last in a gang and how you left it
