### ISSUE TITLE
Character cant pull out weapons

### ISSUE THREAD

**Issue by B0PPIE** [CMGStudios/issue-tracker#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i been playing on the server for years for some reason i cant pull any weapons out tried with different weapons. tried restarting game,clearing fivem cache, tried everything pls help.

ID 170052

### Expected behaviour

Pull weapon out

### Steps to reproduce

N/A

### Any Texture Packs? (If so list)

NO

### CMG User ID

170052

**Comment by crazychris2404** [comment]
Can you provide a clip please @B0PPIE

**Comment by B0PPIE** [comment]
Hi Chris, here is the clip @crazychris2404 
https://www.youtube.com/watch?v=vD3-ZrpWOpk

**Comment by crazychris2404** [comment]
@tom-gun Any info on this?

**Comment by B0PPIE** [comment]
My speed is also capped at 125 for some reason aswell its not a speed limiter or anything

**Comment by packfile** [comment]
You're clocked on the AA job. If you go unemployed the speed & weapon restriction will disappear
