### ISSUE TITLE
[Bug]: Midnight Club

### ISSUE THREAD

**Issue by CanucklePuckette** [CMGStudios/issue-tracker#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello!
My MidnightClub MLO randomly has an invisible wall in the entrance. This was never an issue and has been about 5 days now. Another thing with the MLO is that the storage and clothing menu don't always pop up. 

### Expected behaviour

I can not enter my MLO to access it. ENTER HOUSE is inside. Also when going up to the clothing and storage Icon it not always opens up menu.

### Steps to reproduce

N/A

### Any Texture Packs? (If so list)

no

### CMG User ID

986

**Comment by crazychris2404** [comment]
Closed linked with (https://github.com/CMGStudios/issue-tracker/issues/618)
