### ISSUE TITLE
[Bug My folders are still bugged 

### ISSUE THREAD

**Issue by CanucklePuckette** [CMGStudios/issue-tracker#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My folders are still bugged. Making duplicates and when I make a folder some I cant delete. I was wondering if it can be reset for me at all?

### Expected behaviour

I have multiple trucks listed at times and I cant delete some folders. All cars stay in VIP section as well.

### Steps to reproduce

n/a

### Any Texture Packs? (If so list)

no

### CMG User ID

986

**Comment by crazychris2404** [comment]
Confirmed
When renting a truck it does not disappear from garages

**Comment by crazychris2404** [comment]
However cannot be used/rented/sold during this period

**Comment by packfile** [comment]
Thanks for the report, these have been fixed from the next scheduled restart
