### ISSUE TITLE
[Bug]: Melee Weapon Whitelists

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have added someone to my Melee Weapon Whitelist and they have used the slot and code i gave them, But there name isnt showing on the whitelist 

### Expected behaviour

Give someone the code
They get on the whitelist
Look at weapon whitelist on f2 menu
Go to the specified weapon 
Their name and ID should show 

### Steps to reproduce

1. Press F2
2. Go to Weapon Whitelist
3. Go to your Melee Whitelist
4. View Whitelisted Users
5. There isnt any names

### Any Texture Packs? (If so list)

N/A

### CMG User ID

867

**Comment by packfile** [comment]
Thanks for the report, do you have the User ID of the person that you gave the code to? Has the user confirmed it does not appear in the shank shop for them?

**Comment by Declare5M** [comment]
ID 31 and they haven't checked yet but it said they have access to the whitelist but its not showing in my F2 menu

**Comment by packfile** [comment]
Thanks, what was the name of the melee they got access to?

**Comment by Declare5M** [comment]
Baby Mike

**Comment by packfile** [comment]
The whitelisted users page only updates once per restart, so from next restart you'll see him on there. This is just a visual thing, and I verified he does have access to 'Bike Mike' in game as of now
