### ISSUE TITLE
[Bug]: Game crash while previewing the BMW i8 in the claim supporter menu

### ISSUE THREAD

**Issue by Vortex-647** [CMGStudios/issue-tracker#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Game crash while previewing the BMW i8 in the claim supporter menu in the vip parking at the diamond casino. Err mess:

[Window Title]
Error GTA5_b2545.exe!sub_140EF8918 (0x0)

[Main Instruction]
GTA5_b2545.exe!sub_140EF8918 (0x0)

[Content]
An error at GTA5_b2545.exe!sub_140EF8918 (0x0) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: rugby-may-sierra
Stack trace:
  GTA5_b2545.exe!sub_140EF8918 (0x0)
  GTA5_b2545.exe!sub_140F251B8 (0x82)
  GTA5_b2545.exe!sub_140F25094 (0xe8)
  GTA5_b2545.exe!sub_140878D74 (0x5c)
  GTA5_b2545.exe!sub_14088D814 (0xec)
  GTA5_b2545.exe!sub_141604E2C (0x45)
  GTA5_b2545.exe!sub_1416052DC (0x80)

[^] Hide details  [Save information] [Close]

[Expanded Information]
Crash signature: GTA5_b2545.exe+EF8918
Report ID: si-9923ef50af554adfbdbc7053ad83a10c
You can press Ctrl-C to copy this message and paste it elsewhere.
 

### Expected behaviour

Preview vehicle.

### Steps to reproduce

Have no claimed support packages
Leave casino
Have job scuba diver
Have scuba diver suit and flip flops but to oxygen gear
Be at Diamond Casino
Enter "/shop" in chat
Start to claim vehicles
Preview BMW i8
Crash after a few seconds

### Any Texture Packs? (If so list)

N/A

### CMG User ID

348256

**Comment by packfile** [comment]
Thanks for the report! Does this crash occur every time you try to preview the BMW i8 following these steps or did it only happen once?

**Comment by packfile** [comment]
No further information provided, closing.
