### ISSUE TITLE
[Bug]: Message mention highlights are triggered by player names

### ISSUE THREAD

**Issue by TomDotBat** [CMGStudios/issue-tracker#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a player talks in chat whose name includes your own as a substring, the message will be highlighted even if they don't explicitly mention you.

### Expected behaviour

Only the top message seen in the screenshot should be highlighted.
![image](https://user-images.githubusercontent.com/11298466/228646557-3e00fd85-6ac6-4f67-b5f9-2523e6752293.png)

### Steps to reproduce

Should be fairly self explanatory.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

338708

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
This is believed to be fixed since Friday
