### ISSUE TITLE
[Bug]: cmgtrader cant buy gun 

### ISSUE THREAD

**Issue by TheRealWicks** [CMGStudios/issue-tracker#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cant buy a gun at the cmg trader docks whitelist just nicks ur money got scammed 1.5m

### Expected behaviour

cant buy gun at cmg trader docks

### Steps to reproduce

try to buy a gun at cmg trader docks

### Any Texture Packs? (If so list)

no

### CMG User ID

387

**Comment by crazychris2404** [comment]
Thanks for the report
There is a active donation support ticket about this issue
