### ISSUE TITLE
[Bug]: Atm’s

### ISSUE THREAD

**Issue by Helme96** [CMGStudios/issue-tracker#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you go to rob some
ATMs before you’ve even started cutting the wires , the animation pops up and suddenly says you have failed to cut the wires and the animation proceeds to stay on your screen for a period of time even though you haven’t attempted to click the spacebar to cut them. 

### Expected behaviour

The atms fail when you haven’t started to cut the wires. 

### Steps to reproduce

Attack the atm
Then it’s changed you to the wires
Then it will just stop you for no reason 
Telling you you have failed to cut wires
When you haven’t clicked anything

### Any Texture Packs? (If so list)

NA

### CMG User ID

190368

**Comment by packfile** [comment]
Can't reproduce this with the steps provided.
