### ISSUE TITLE
my phone [Bug]: 

### ISSUE THREAD

**Issue by tyler0321** [CMGStudios/issue-tracker#631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

so i press k to open my phone and nothing opens when i press enter or right mouse click 

### Expected behaviour

o i press k to open my phone and nothing opens when i press enter or right mouse click 

### Steps to reproduce

iidk

### Any Texture Packs? (If so list)

no

### CMG User ID

252371

**Comment by crazychris2404** [comment]
Hi @tyler0321 
Thanks for the report
do you have a clip of this occurring please ?

**Comment by tyler0321** [comment]
I can get one

**Comment by packfile** [comment]
Please reopen the issue once reproduction steps or a video has been provided.
