### ISSUE TITLE
Recent AA changes / fixes

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#632]
**Regarding the recent AA changes/fixes:**

 **When using the flat-bed truck**, sometimes you have to "tow" a vehicle twice as the first time it doesn't appear on your bed, Some cars also float inside the bed {collision issues ?}. (Random occurrence) 
 **https://prnt.sc/U_l03AhfPEU_** **https://youtu.be/j59sPObiDO0**
 
 **When using the "tow-truck"** , Sometimes when you tow a car with the tow-truck you get ragged around the place shown in **Video 1 tow truck** (Random occurrence), Also when driving the "tow-truck" around your game audio cuts out and you can only hear the tow hook on the rear dragging, you physically can't lift up the hook any more via using "shift / ctrl" to raise and lower, shown in "Video 2 tow truck", Another thing is, when you turn on the beacons for the "tow-truck" the numberplate on the rear starts flickering to the beacons" the lights are also not physically emitting from the beacon location.
{ Vid 1 **https://youtu.be/REZY77Q2GM0** } { Vid 2 **https://youtu.be/NMLBUionDCY** }

**Comment by PIKAlmao** [comment]
Just another clip i forgot to add
https://youtu.be/9-kG8zpLFTs

**Comment by packfile** [comment]
Thanks for the report, the aforementioned issues have been fixed! Note for the tow truck, before attaching the rope you have to get in and out the driver seat of the vehicle you want to tow first to prevent you getting 'ragged around' once attached.
