### ISSUE TITLE
[Bug]: AA Job

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the AA, the tow truck barely works for any cars once you attach you can’t drive anywhere.

Also the flat-bed is really restricted for some reason, if I attempt to attach a van or something like a large off-roader it doesn’t give the option.

### Expected behaviour

Tow truck should work for everything

Flat bed should work for everything

### Steps to reproduce

1. For flatbed attempt to attach a van or a larger car and it won’t give the option.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by packfile** [comment]
There is a size limit to the vehicles you can attach, this is around 10 meters in diagonal length.
For the tow truck, you should only tow vehicles which have a lower mass than the tow truck. I'd also recommend getting in and out the driver seat of the vehicle you're going to tow before the rope is attached.
