### ISSUE TITLE
[Bug]: Gangs are glitched, cannot leave or do anything. Stuck.

### ISSUE THREAD

**Issue by ghost** [CMGStudios/issue-tracker#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was apart of a gang with a friend called infex. He got com banned and he was lead, I was recruit. Now I'm apart of a gang as a recruit, that cannot withdraw, invite or disband. When I leave the gang I get presented the normal picture or joining a new gang however my mouse cursor isn't available and when I press esc it puts me back into the gang and says, cannot disband gang as I'm the only one in it. I've accidently deposited $1million. I've also just bought gang license and it didn't change anything. Cant withdraw, cant leave. Need help. Possible fix - Force kick me and comp 1 million i.e delete and add or move or whatever :)

### Expected behaviour

Cant leave gang. Stuck as recruit, cant promote myself or do anything. Maybe my friends account being deleted has caused this to me.

### Steps to reproduce

1. Attempt to leave
2. Shows the tab/picture that I have left
3. Nothing works, no cursor
4. Press esc or anything
5. Back into gang
6. Message saying I cannot disband
7. Stuck
8. Cry

### Any Texture Packs? (If so list)

nonne

### CMG User ID

186624

**Comment by tom-gun** [comment]
You've mentioned your 'friend' here 3 times, yet have failed to provide his perm id so this can be investigated... Also accounts don't get 'deleted' and it would be useful if you mentioned when he left the gang so we know if this is pre or post gang v2 update.
