### ISSUE TITLE
gang name not changing after paying to change

### ISSUE THREAD

**Issue by TheRealWicks** [CMGStudios/issue-tracker#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

gang name not changing after paying to change

### Expected behaviour

gang name not changing after paying to change

### Steps to reproduce

gang name not changing after paying to change

### CMG User ID

387

**Comment by tom-gun** [comment]
You've failed to provide any meaningful information... i.e. what you gang name is, what you tried changing it to, etc.
