### ISSUE TITLE
[Bug]: Custom Folders Broken.... Again

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

All my custom folders have been deleted and all vehicles have been put back into VIP Cars

### Expected behaviour

I expect to see my custom folders but theyre not there
![Broken Folders AGAIN](https://user-images.githubusercontent.com/109679930/230337511-9aefbf29-b1b0-405f-ac0a-c366a87787b9.png)

### Steps to reproduce

1. Go to a garage
2. Go to Custom Folders
3. No Custom Folders there

### Any Texture Packs? (If so list)

N/A

### CMG User ID

867

**Comment by packfile** [comment]
You'll have to recreate the folders in this instance.
