### ISSUE TITLE
[Bug]: Emergency Radio does not work on HMP

### ISSUE THREAD

**Issue by Jamie1253** [CMGStudios/issue-tracker#637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Lost radio on HMP - Went to get an emergency radio and it appears that it is not working, I click use on the radio when I get it and nothing.

### Expected behaviour

Be able to use radio on HMP with the emergency radio.

### Steps to reproduce

1. Have radio taken from you
2. Get emergency radio
3. Click 'Use' on the Emergency Radio in inventory
4. Nothing happens

### CMG User ID

309666

**Comment by packfile** [comment]
Use the /radios command to join back
