### ISSUE TITLE
[Bug]: Cannot Leave Gang.

### ISSUE THREAD

**Issue by ghost** [CMGStudios/issue-tracker#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

More extensive overview, apologies.

Hi, can I get some help please. I cant leave my gang. I'm stuck as a recruit and it wont let me leave. My IGID is: 186624. Owner of Gangs ID: 881.
Brief background knowledge:
1. Friend [ID: 881] had a gang alone [leader] > invited me [recruit]; only us two in this gang, all was working fine.
2. Friend [ID: 881] gets perm banned. No longer in gang; I'm sole member in gang [recruit].
3. I now attempt to leave the gang; doesn't work.

3.1 (doesn't work? wdym?)
3.1.1: Can you deposit funds as a recruit: yes, [and I have accidentally].
3.1.2: Can you disband as you are alone? [no 'you cannot leave the gang if you are the only member'].
3.1.3: Can you leave the gang? Yes/No. > When I write 'yes' to leave, I am then presented with the join gang/invites tab, however there is no cursor and it seems bugged. I then press back i.e escape and I am back in the gang hence, I never really left. 
3.1.4: Can you invite someone else and try leave? No, I am recruit.

Was this pre or post v2 update. 
This occurred post gang v2 update. Before the leader [881] got permed, all was fine, this was around 2 weeks ago.

I don't know what to do.

### Expected behaviour

Unable to leave gang, powers restricted to that of 'recruit'.

### Steps to reproduce

1. F5 
2. Leave Gang > Yes
3. Presented with message > 'you cannot leave the gang if you are the only member'.

### Any Texture Packs? (If so list)

Default

### CMG User ID

186624

**Comment by crazychris2404** [comment]
This should now be fixed if not please reopen this issue

**Comment by ghost** [comment]
Still in the gang, no updates... nothing fixed.
