### ISSUE TITLE
[Bug]: cannot create a gang after licence is bought 

### ISSUE THREAD

**Issue by HaydeenyJT** [CMGStudios/issue-tracker#639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought the gang licence but when I open the menu to create it I type the name of the gang press enter and nothing happens the menu just closes 

### Expected behaviour

Gang not being created 

### Steps to reproduce

Open gang menu and create gang 

### CMG User ID

201900

**Comment by crazychris2404** [comment]
This should now be fixed if not please reopen this issue
