### ISSUE TITLE
Freeze in place when scuba diving 

### ISSUE THREAD

**Issue by Kyrotm** [CMGStudios/issue-tracker#64]
**Describe the issue you're facing**
Being froze in place

**Steps to reproduce**
1.turn computer on
2.open five m
3.locate server
4.join server
5.become scuba diver
6.start job
7.spawn boat
8.drive to location
9.get muted
10.start diving
11.You are now froze in place 

**Expected behavior**
First of all its behaviour not behavior
You will freeze in place and wont be able to move until an admin unfreezes you 

**Screenshots/Video**
don't have one but its pretty obvious what you would see
**Additional context**

**Any Texture Packs (if so list)**
No. this ain't minecraft

**Perm ID**
219695

to the admin that tped to me - thanks for not unfreezing me very helpful xo

**Comment by arthur-rl** [comment]
> First of all its behaviour not behavior

Blame GitHub for that!

> No. this ain't minecraft

You can have texture packs in FiveM. For example Natural Vision Evolved.

> 9.get muted
Can you explain what you mean by this please?

**Comment by JamieGarner** [comment]
He got muted in the in-game text chat.

**Comment by arthur-rl** [comment]
I have tried to reproduce the issue based on the steps you've given us & I cannot reproduce the issue.

Since you were muted you were probably frozen by an a member of the staff team. 

If you can get me a clip of you reproducing the issue in game within 12 hours I'll be happy to look into this further.

**Comment by Kyrotm** [comment]
Right so. i was chat muted and froze by an admin and when i was unfroze it has just kept happening over and over since.

**Comment by alfiellds** [comment]
Please try doing the scuba diving job following today's 3PM restart and let me know if any of your issues have been resolved.
