### ISSUE TITLE
[Bug]: Not being able to shoot sniper in first person

### ISSUE THREAD

**Issue by qwazixRAWR** [CMGStudios/issue-tracker#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not being able to shoot while using a sniper in first person. Something that needs fixing as many ppl tend to go first person for this ;)

### Expected behaviour

Works sometimes, sometimes doesnt. Does not reload nor shoot, you are able to aim in tho.

### Steps to reproduce

1. go first person
2. Try shoot when aimed in

### CMG User ID

241

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
