### ISSUE TITLE
[Bug]: Can /suicide in greenzones

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Exactly as what the title is, if you have a pistol equipped, you can /suicide in greenzones. This can result in people taken into Vespucci PD committing suicide if you haven't taken their pistol off of them. This shouldnt occur as you cannot normally draw guns out in greenzones. It can also happen when you're in cuffs.

### Expected behaviour

Self-explanatory

### Steps to reproduce

go into greenzones with pistol equipped
do /suicide
you die

### Any Texture Packs? (If so list)

None

### CMG User ID

209460

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been ammended.
