### ISSUE TITLE
[Bug]: Can’t claim weekly kit

### ISSUE THREAD

**Issue by NoChill5K** [CMGStudios/issue-tracker#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I claimed my weekly kit last Sunday 08/04 and it has not reset for me this Sunday. When I attempt to claim my weekly kit it says I have already used my kit and it will reset on Sunday at 3pm. I have over 300 days and have tried multiple time since Sunday.

### Expected behaviour

Not able to claim weekly plat kit.

### Steps to reproduce

/cmgclub - manage perks - claim weekly kit

### CMG User ID

965

**Comment by crazychris2404** [comment]
Confirmed 
This is happening for multiple users
Thanks for the report

**Comment by packfile** [comment]
This has been resolved for next week
