### ISSUE TITLE
Helicopter crashing and not being able to spawn it for more than 1 hour

### ISSUE THREAD

**Issue by Poseidon122** [CMGStudios/issue-tracker#644]
I had a helicopter spawn out, and I parked it somewhere. Someone else jacked it, crashed it, and jumped out right before it, killing himself. This has caused my helicopter to not spawn for more than an hour.

**Comment by crazychris2404** [comment]
Confirmed 
When helicopters exploded it is still classed as a vehicle being out

**Comment by packfile** [comment]
Thanks for the report, this was changed a few days ago.
