### ISSUE TITLE
[Bug]: Cannot leave old gang

### ISSUE THREAD

**Issue by HaydeenyJT** [CMGStudios/issue-tracker#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2023-04-11 224246](https://user-images.githubusercontent.com/130112982/231294652-cd788061-afb1-4d10-8a50-fd8f12f72a7f.png)
will not let me create a new gang after old founder got permed still says im in a gang when im not

### Expected behaviour

i press F5 and it will not let me create a gang cause I'm apparently in a gang already even though I'm not its glitched out since the founder got permed 

### Steps to reproduce

1: F5
3: Create Gang
4: Enter name
5: the menu just closes and doesn't create a gang 

i tried it with my mate and he said i was in another gang so he couldn't invite me 

### Any Texture Packs? (If so list)

No

### CMG User ID

201900

**Comment by crazychris2404** [comment]
After restart this should work
