### ISSUE TITLE
[Bug]: Vehicles rented out never return to garage.

### ISSUE THREAD

**Issue by qwazixRAWR** [CMGStudios/issue-tracker#647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Vehicles that have shoudl've been returned waaay long ago is not showing up.

Never had this problem after the newly fix on custom garages. Might be that the Vehicles are assigned to a folder that is non existent as they got deleted in the last previous update.

Maybe they have it assigned to a Custom Folder aswell?

### Expected behaviour

After they dissapear from the "rented out" tab, they are no where to be found. When u relog, they come back into the "rented out" tab where it says 1 hour remaining. This has happend all day for me. No idea if this is on a player wide bases. In my personal garage it is the following vehicles that won't return;

- Childish Icecream Van - rented to DanG (1hr left for the past 12hrs)
- Renault Kangoo - rented to MWGaming02 (1hr left for the past 12hrs)
- Transvan2 - rented to MWGaming02 (1hr left for the past 12hrs)
Volkswagen Crafter - rented to MWGaming02 (1hr left for the past 12hrs)

### Steps to reproduce

1. Rent vehicle out to a player
2. Wait for the period to be over
3. Watch if it goes in your garage or not (try relogging)
4. Doesn't return to your custom folder u assigned it to in the first place, not VIP garage either.

### CMG User ID

241

**Comment by packfile** [comment]
Please reopen your ticket in the support Discord for this to be resolved.
