### ISSUE TITLE
[Bug]: wont let me sell plat when i have 149 days 

### ISSUE THREAD

**Issue by jordgti** [CMGStudios/issue-tracker#648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

wont let me sell plat when i have 149 days dont come up the the bit when you type in days id ect 

### Expected behaviour

wont let me sell plat when i have 149 days dont come up the the bit when you type in days id ect 
https://medal.tv/games/gta-v/clips/14v0YfMNAYeteQ/d1337OXauxtb?invite=cr-MSxRRFYsMTY4MzQzNjM4LA

### Steps to reproduce

t/cmgclub
manage subscription 
sell platinum subscription days 
then nothing happens 

### CMG User ID

469

**Comment by crazychris2404** [comment]
Do you happen to still have this issue when players are nearby as it seems to be a isolated bug

**Comment by packfile** [comment]
No response from author, please reopen if it is still occurring
