### ISSUE TITLE
[Bug]: orange plastic fence

### ISSUE THREAD

**Issue by Macccc1** [CMGStudios/issue-tracker#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when ever you place down a plastic fence instead of it being the orange plastic one it will turn into a white wooden one from GTAV

I will provide a screenshot below
https://cdn.discordapp.com/attachments/880964002690248755/1096212246876663839/image.png

### Expected behaviour

when ever you place down a plastic fence instead of it being the orange plastic one it will turn into a white wooden one from GTAV

I will provide a screenshot below
https://cdn.discordapp.com/attachments/880964002690248755/1096212246876663839/image.png

### Steps to reproduce

change the fence back to the orange one

### Any Texture Packs? (If so list)

No

### CMG User ID

741

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
