### ISSUE TITLE
[Bug]: the vehicle with the spawn code ‘’ demonrs6pd ‘’ has no ANPR attached to it as it is a pd car it should have the ARPN

### ISSUE THREAD

**Issue by Solo-ghost** [CMGStudios/issue-tracker#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The RS6 PD has no ANPR

### Expected behaviour

No visual ANPR

### Steps to reproduce

Spawn car in 

### Any Texture Packs? (If so list)

No

### CMG User ID

286583

**Comment by crazychris2404** [comment]
Fixed for next restart
