### ISSUE TITLE
[Bug]: Police long shield

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When equipping the police-issued long shield and bumping into a vehicle, the shield becomes useless and you can get shot through it. Other "players" can see that the shield is "bugged" but the person holding it cannot

### Expected behaviour

The shield should keep you protected even do you bump into a vehicle. 

### Steps to reproduce

clock on pd
/shield
equip long shield 
bump into a vehicle
get someone to shoot at you 

### CMG User ID

9975

**Comment by packfile** [comment]
Unsure what 'bumping into a vehicle' means in this case, but the following scenarios have been tested and produce valid results when having the long shield out:
- Player runs into a stationary vehicle (player remains in the shield animation).
- Player gets knocked over by a moving vehicle (players gets up and returns to shield animation).
- Player runs towards a slow moving vehicle heading towards them (player remains in shield animation).

Note: These were tested with 2 players and appeared the same on each screen.
