### ISSUE TITLE
[Bug]: vehicle disappearing 

### ISSUE THREAD

**Issue by Toxiccmg** [CMGStudios/issue-tracker#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I am doing meth processing I go in and my truck is outside but when I come out it isn't there anymore even if vehicle cleanup didn't happen.

### Expected behaviour

https://streamable.com/xhqpp5

### Steps to reproduce

https://streamable.com/xhqpp5

### Any Texture Packs? (If so list)

no

### CMG User ID

258150

**Comment by crazychris2404** [comment]
Please can you resubmit the video of this occuring

**Comment by crazychris2404** [comment]
No response
CLOSED
