### ISSUE TITLE
[Bug]: Been unbanned but still get the ban pop-up it's the 2nd time

### ISSUE THREAD

**Issue by Bloempot2060** [CMGStudios/issue-tracker#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

firtst i was unbanned then i tried to search the old account and i think that caused the popup to come the first time but then admin supreme took care of it by sending management and they removed it i played before the restart and everything went fine but now after the restart i get the ban evading message again while i'm unbanned.
![image (2)](https://user-images.githubusercontent.com/132268047/235446931-0a480bff-b230-4dce-8657-2b012db39f72.png)

### Expected behaviour

i would like to play again because i already been unbanned and still see the popup

### Steps to reproduce

i don't get the question just want to play. Thanks in advance 

### CMG User ID

247696

**Comment by packfile** [comment]
Please get in contact with a member of management.
