### ISSUE TITLE
Platnum bug

### ISSUE THREAD

**Issue by DCamp20-03** [CMGStudios/issue-tracker#656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i had 50 days play when i claimed my weakly kidt its been 3 days so i should be able to sell every day but 4 days i have 7.4 days and says i cant sell it and i dont want to buy more just incase it keeps doing it

### Expected behaviour

hope it gets sorted

### Steps to reproduce

none

### Any Texture Packs? (If so list)

none

### CMG User ID

339935

**Comment by crazychris2404** [comment]
Is this still occuring @DCamp20-03 ?
