### ISSUE TITLE
[Bug]: Casino BJ: 2 aces being soft 12 and getting 10 gives you 22

### ISSUE THREAD

**Issue by NoChill5K** [CMGStudios/issue-tracker#658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When getting 2 aces in the casino this is a soft 12 meaning if a 10 is hit it will still be 12. This is not the case in cmg casino I have lost a fair amount of money from hitting on 2 aces and getting a 10 to make 22 when it should still be 12.

### Expected behaviour

Not getting the correct count in casino

### Steps to reproduce

Hit 2 aces in casino.
Hit a ten.
Bust on 22.

### CMG User ID

965

**Comment by crazychris2404** [comment]
Believe this is just how CMG casino was made feel free to make a suggestion for change in CMG discord
