### ISSUE TITLE
Phone update:

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#659]
Regarding the most recent update with the phones, If you use any form of camera on the phone and then try using a gun afterwards your ads will be bugged instant ads (camera fov), or when running and ads' your gun will aim at random directions (seems to be following the trajectory of if you were using the camera on a phone) movement + ads. 

https://youtu.be/s3ARK3NlP-Y

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by crazychris2404** [comment]
Closed
Thanks for the report however this is not currently something developers can fix
