### ISSUE TITLE
Phone update #2

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#660]
Regarding the most recent update with the phones, If you attempt to use the volume slider on the apple music app it shuts down your phone and does not allow you to pull it out again or use it unless you relog. These are the only two bugs i'm currently personally aware of.

https://youtu.be/2GVk_5VQvKE

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by crazychris2404** [comment]
Closed
Thanks for the report however this is not currently something developers can fix
