### ISSUE TITLE
[Bug]: AA Job since new phone update

### ISSUE THREAD

**Issue by FallenPikachuu** [CMGStudios/issue-tracker#661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

before the update you used to be able to press ` to see what jobs there are, but since the update you get called constantly and you have no information to go on to find them.

### Expected behaviour

not able to get the location of the vehicles that needing to be fixed

### Steps to reproduce

unknown

### CMG User ID

356800

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by crazychris2404** [comment]
Closed
Thanks for the report however this is not currently something developers can fix
