### ISSUE TITLE
[Bug]: Cant call 2 digit phone numbers

### ISSUE THREAD

**Issue by Pluggyy** [CMGStudios/issue-tracker#662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to call 2 digit phone numbers it doesn't allow you to press call but works with 3 digit phone numbers

### Expected behaviour

It should allow you to call 1/2/3 digit numbers

### Steps to reproduce

call a 2 digit phone number

### Any Texture Packs? (If so list)

no

### CMG User ID

339293

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by crazychris2404** [comment]
Closed
Thanks for the report however this is not currently something developers can fix
