### ISSUE TITLE
[Bug]: Using phone it bugs out your microphone and make you go quiet 

### ISSUE THREAD

**Issue by NBKdev** [CMGStudios/issue-tracker#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically when u facetime someone and do other things that requires the microphone once you stop using ur phone you will either have to do /vsync or change your microphone setting volume as many people say that I'm quiet or not talking which can effect rp situations. sometimes when you are bugged you can hear people's phone conversations 

### Expected behaviour

Explained above even in radio's people go very quiet due to this issue 

### Steps to reproduce

1. use phone with microphone features
2. hang-up 
3. speak with people if that doesn't work keep using your phone till the person can't hear you.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

22

**Comment by crazychris2404** [comment]
Closed
Thanks for the report however this is not currently something developers can fix
