### ISSUE TITLE
[Bug]: Long range blip not working

### ISSUE THREAD

**Issue by AnonymousCMG** [CMGStudios/issue-tracker#664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have got long range blips. All my f5 settings are correct I have a gang radio yet my long range blips do not work.I am a guest on the f5

### Expected behaviour

Would be able to see blips on the other side of the map

### Steps to reproduce

1. Buy long range blips
2. Make sure all f5 settings are on
3. have a gang radio

### Any Texture Packs? (If so list)

no

### CMG User ID

896

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for a restart later this week.
