### ISSUE TITLE
[Bug]: MLO render issues

### ISSUE THREAD

**Issue by dannydodar** [CMGStudios/issue-tracker#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When accessing the MLO through various means, rendering the MLO becomes an issue.
https://medal.tv/games/gta-v/clips/18W8mIeVm3lZqa/d1337UfxlzON?invite=cr-MSxwaXUsMTc3NzcwODk0LA

### Expected behaviour

FUll render of inside, INCLUDING additional props placed in the placement menu.

### Steps to reproduce

Enter MLO using doorbell or property menu at front door to enter.

### CMG User ID

229138

**Comment by crazychris2404** [comment]
Confirmed thanks for the report 
Please leave listed here the House name

**Comment by packfile** [comment]
This does not occur locally following the steps provided.
