### ISSUE TITLE
[Bug]: teleporting after scuba diving into the water

### ISSUE THREAD

**Issue by Bombushka17** [CMGStudios/issue-tracker#667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

teleporting to random place after scuba diving

### Expected behaviour

https://medal.tv/games/gta-v/clips/19hYu6bN2jqwlY/d1337fsAbYc8?invite=cr-MSw3QXMsODE2NDg4MDAs
teleporting after scuba diving

### Steps to reproduce

just scuba dive idfk

### Any Texture Packs? (If so list)

no

### CMG User ID

357219

**Comment by crazychris2404** [comment]
Confirmed
This is randomly occurring 
Any idea how to reproduce ?

**Comment by packfile** [comment]
No reproduction steps provided

**Comment by PIKAlmao** [comment]
> No reproduction steps provided #667


Hello, after a few tests i have found this occurs when pressing f (to exit your boat) and almost instantly pressing g (to start diving) it stands you up then teleports you underneath the map whilst starting the dive animation, which then teleports you into or underneath the main city area. The timing is a bit iffy to reproduce it but i've managed to do it a couple of times.

**Comment by crazychris2404** [comment]
Thanks for the info

**Comment by PIKAlmao** [comment]
> Thanks for the info

Video  https://youtu.be/HvqePbLpdaU

**Comment by packfile** [comment]
Thank you for the reproduction steps @PIKAlmao, this will be looked into soon

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
