### ISSUE TITLE
[Bug]: Prisoners are able to glitch out of segregation

### ISSUE THREAD

**Issue by Jamie1253** [CMGStudios/issue-tracker#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Prisoners are able to glitch out of segregation cells. 
https://medal.tv/games/gta-v/clips/19CkS1csaZV6ZN/d1337SRMFvM5?invite=cr-MSxqVkksMTM5Mjg0ODMwLA

### Expected behaviour

Not being able to get out

### Steps to reproduce

1. Go to Seg Cell 2
2. Jump in the corner
3. Get TPd outside

### Any Texture Packs? (If so list)

n/a

### CMG User ID

309666

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by Jamie1253** [comment]
Just had an update, 
this is all segregation cells, not just Seg Cell 2
https://youtu.be/PzReiDYisZU?t=509

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
