### ISSUE TITLE
[Bug]: headlight colour won’t change on vehicle

### ISSUE THREAD

**Issue by G3NKk** [CMGStudios/issue-tracker#669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I change the colour of my headlights in the mod shop it doesn’t work 

### Expected behaviour

Headlight colour isn’t changing when paid for in garage 

### Steps to reproduce

Take car into mod shop
Go into the lights sections 
Select Xeon lights and choose colour 
Colour shows up but dissapears when leaving the lights section

### CMG User ID

259720

**Comment by PIKAlmao** [comment]
After changing a cars Lights colour (underglow inc) then store your car in a garage and then pull it out again and it should be perfectly fine. @G3NKk

**Comment by G3NKk** [comment]
I have tried this and it still doesn’t change the headlight to the colour I selected I don’t seem to have a problem with the under glow just the headlight

**Comment by G3NKk** [comment]
It says I must have purchased xenon lights to apply but I don’t think it’s giving me an option or buy them

**Comment by PIKAlmao** [comment]
> It says I must have purchased xenon lights to apply but I don’t think it’s giving me an option or buy them

Just came on and purchased xenon lights on multiple cars, simeons and ballers (VIP), and it is having the same issue, and i have tried helping another player ingame with it and he has the same issue aswell, it only seems to be with **xenon headlights** and underglow is perfectly fine, we've also tried storing the car after equipping the new coloured xenon headlights but they instantly dequip right after buying them.

**Comment by crazychris2404** [comment]
This could potentially be a model based issue as it does not occur on all cars will leave for @tom-gun to review

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
