### ISSUE TITLE
upgrades such as respray wont work on car

### ISSUE THREAD

**Issue by Hxmza72s** [CMGStudios/issue-tracker#67]
just bought my first car and the respray and stuff is not working i spoke to admin and was told to report it here

i tried buying neon on lights and also tried respraying the car did not work idk if there is any more upgrades that didnt work too the car is a mclarren 650s  SPAWNCODE: 650S1W
perm id :219320

**Comment by alfiellds** [comment]
Hello, thank you for the report. Unfortunately, the CMG bug tracker is not the place to raise concerns regarding vehicles mis-functioning. Instead you should contact one of CMG's Car Developers who can be identified with the Car Developer tag, and they will be able to help you resolve this issue.

Many thanks.
