### ISSUE TITLE
[Bug]: 200KG showing same weight on vehicle menu

### ISSUE THREAD

**Issue by Septic0x** [CMGStudios/issue-tracker#670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when on the vehicle menu it displays the weight of the 200kg, but when owning 2 of the same 200kg it displays the weight of one 200kg for both when the 2nd one it empty.

BELOW IS A CLIP SHOWING THIS BUG:
https://medal.tv/games/gta-v/clips/19X6SSW5DAbjvy/d1337TkEbRRs?invite=cr-MSxDRGQsMjU3MDExNTcs

### Expected behaviour

weight of the 200kgs to be separate

### Steps to reproduce

1. go onto the vehicle menu
2. look at the weight of one 200kg
3. pull out the 2nd 200kg and it will be empty but still showing that it has something inside of the 200kg

### Any Texture Packs? (If so list)

N/A

### CMG User ID

210593

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
