### ISSUE TITLE
[Bug]: Prisoners unable to heal in infirmary with new sitting system

### ISSUE THREAD

**Issue by Jamie1253** [CMGStudios/issue-tracker#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Prisoners are unable to heal in the infirmary beds now the new chair system has been added. When going to the bed now, you have the option to Lie Down or Sit. This does not work with the healing system that was added for prisoners. Prisoners are now unable to heal. 

### Expected behaviour

Prisoners are able to lie on the bed and get healed.

### Steps to reproduce

1. Go to prison infirmary
2. Go to the infirmary bed
3. Press E

### Any Texture Packs? (If so list)

N/A

### CMG User ID

309666

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
