### ISSUE TITLE
[Bug]: i just got my baller ID and my custom number and everything on my phone is gone

### ISSUE THREAD

**Issue by Jayret02** [CMGStudios/issue-tracker#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i got my baller id, now the phone is wiped name is completley diff, ive lost my custom phone umber too 

### Expected behaviour

id like my number all my photos and everything on my phone returned

### Steps to reproduce

i just got my baller id changed

### CMG User ID

1037

**Comment by crazychris2404** [comment]
Ask about this in your baller ticket
