### ISSUE TITLE
[Bug]: Cant rappel out of helicopters

### ISSUE THREAD

**Issue by oVexo123** [CMGStudios/issue-tracker#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 When using an nhs or civillian helicopter when in the rear seats of the helicopter when (x) is pressed there is no rappel takes place.

### Expected behaviour

X is pressed
rappel rope drops out of helicopter
player slides down rope

### Steps to reproduce

Get into a helicopter with the rappel function
press x when in a rear seat
No rappel happens

### Any Texture Packs? (If so list)

no

### CMG User ID

238154

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Fixed
