### ISSUE TITLE
[Bug]: speedgun not working

### ISSUE THREAD

**Issue by maxreid250** [CMGStudios/issue-tracker#675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

for some reason, the speed gun has broken and will not fine anyone,

### Expected behaviour

for some reason, the speed gun has broken and will not fine anyone,

### Steps to reproduce

1. Bring out the speed gun
2. Point it at a car

### Any Texture Packs? (If so list)

N/A

### CMG User ID

204066

**Comment by maxreid250** [comment]
After using speed gun you cannot any guns

**Comment by maxreid250** [comment]
cannot shoot*

**Comment by crazychris2404** [comment]
Confirmed
Cars speed is not tracked by speed gun
Once the above occurs guns cannot be shot
Thanks for supporting CMG by reporting these bugs

**Comment by packfile** [comment]
Fixed
