### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Muja12** [CMGStudios/issue-tracker#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought a gang licence couple weeks ago and tried to make a gang and it’s not working been trying everyday for the past weeks

### Expected behaviour

Not able to put my money in gang funds 

### Steps to reproduce

1. Press f5
2. Create gang 
3. Put name in

### Any Texture Packs? (If so list)

NO

### CMG User ID

318684

**Comment by crazychris2404** [comment]
This is something unique to you, create a "game support" ticket in the dono support discord and someone will assist you
