### ISSUE TITLE
[Bug]: Prison Catwalk causing you to fall over or even die

### ISSUE THREAD

**Issue by Jamie1253** [CMGStudios/issue-tracker#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The prison catwork and stairs right behind the cell block when going towards the HMP Garage is causing you to fall over when running. This has happened multiple times while chasing people which causes them to get away. 

It was also reported that someone died when they fell over with full health and Armor. 

https://medal.tv/games/gta-v/clips/1bMuzwXYpNiXas/d13374urdbd7?invite=cr-MSxTWVcsMTM5Mjg0ODMwLA

Not sure if its related but its right next to Seg where the other bug was just fixed.

### Expected behaviour

Not falling over on catwalk

### Steps to reproduce

1. Go to catwalk stairs behind cell block towards garage
2. Run up the stairs and around the catwalk

### CMG User ID

309666

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
