### ISSUE TITLE
[Bug]: Mini-Events not working

### ISSUE THREAD

**Issue by TIPlays** [CMGStudios/issue-tracker#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the mini events where the first person to type something up, is broken.

### Expected behaviour

it doesnt let anyone win

### Steps to reproduce

try to win the event it doesnt work for anyone

### Any Texture Packs? (If so list)

nah

### CMG User ID

6430

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by tom-gun** [comment]
This does not reproduce, I saw a few mini events happen yesterday and they worked fine for other players

**Comment by packfile** [comment]
This has been fixed for a scheduled restart later this week
