### ISSUE TITLE
[Bug]: jewellery setup not working  

### ISSUE THREAD

**Issue by cHOCCYMILK888** [CMGStudios/issue-tracker#679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

for the past 3 weeks the jewellery setup not working for me and all my friends it just said its not ready and its happened every time we have done it and some times we have waited for up to 30 minutes  

### Expected behaviour

for the past 3 weeks the jewellery setup not working for me and all my friends it just said its not ready and its happened every time we have done it and some times we have waited for up to 30 minutes  

### Steps to reproduce

walk up to the door 
press E 
it wont woek 

### Any Texture Packs? (If so list)

NA

### CMG User ID

347694

**Comment by PIKAlmao** [comment]
I've tried entering the jewelry store for over an hour now, still nothing, no one else has entered or left since my time being here. I'll have another try after the daily restart tomorrow aswell.  https://prnt.sc/v2XoTyCoiGn4

**Comment by PIKAlmao** [comment]
Update, seems to be working fine now @cHOCCYMILK888

**Comment by crazychris2404** [comment]
Closed
This is randomly occuring and not reproducible
