### ISSUE TITLE
Staff cant carry people in prison

### ISSUE THREAD

**Issue by ducky-allen724** [CMGStudios/issue-tracker#68]
**Describe the issue you're facing**
Staff members cant carry when in prison which proves to be annoying when kids are beefing and you need to separate them.

**Steps to reproduce**
Step 1: Make you war to the prison
Step 2:Be a staff member
Step 3; Try carry someone
**Expected behaviour**
Should be able to carry them
**Screenshots/Video**
effort
**Additional context**
N/A
**Any Texture Packs (if so list)**
effort
**Perm ID**
33763

**Comment by arthur-rl** [comment]
Please can you confirm whether you have any texture packs or not.
