### ISSUE TITLE
[Bug]: Phone bind

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you load onto the server for the first time (as a fresh player) the phone keybind is set to f1 this collides with the rules menu so they both open at the same time. (Could be a challenge for many new players if they don’t know how to change it)

### Expected behaviour

Keybind should be set to (K) upon joining the server.

### Steps to reproduce

1. Join server as new player or someone who hasn’t changed the bind themselves
2. Press f1 and it will open both your phone and the f1 rules menu

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
The default bind is set to `K`, however if you've set up the phone previously in another city it will be set to that instead. This is an implementation detail by FiveM and can't be resolved by us

**Comment by kajblm** [comment]
so for everyone who joins new to the server that has played any sort of server which has that phone (which is likely a long list) has this problem wouldnt it be an idea to get a different phone/revert to the old one cuz regardless of that sending money to a 10 didget number isnt much help.
