### ISSUE TITLE
Logged in and lost Tec-9 from inventory

### ISSUE THREAD

**Issue by Metalmadness402** [CMGStudios/issue-tracker#681]
I logged off at 3:30am, I was in the scuba diving mission area, had a Tec-9 in my inventory weapon wheel.

Logged back in I was in the exact same spot but my inventory and weapon wheel was empty.

**Comment by packfile** [comment]
Hey @Metalmadness402, can you please provide your perm id

**Comment by PIKAlmao** [comment]
> 

Talked to him in game support on the discord, turns out he shot his gun before logging off with a combat timer, so he died with it.

**Comment by packfile** [comment]
> Talked to him in game support on the discord, turns out he shot his gun before logging off with a combat timer, so he died with it.

Great, thanks for checking
