### ISSUE TITLE
[Bug]: LS Customs

### ISSUE THREAD

**Issue by JorPet1** [CMGStudios/issue-tracker#682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When in any mod shop, go over to Wheels > Stancer, and when you hit backspace to leave stancer you got all the way out of the mod shop, instead of back to the menus

### Expected behaviour

^

### Steps to reproduce

Go Mod shop
Scroll down to wheels
Enter stancer options
Hit backspace
Youll go out of the whole mod shop, bare annoying

### CMG User ID

605

**Comment by PIKAlmao** [comment]
Tested and can confirm this does happen, with backing out of the stancer menu only in specific

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
