### ISSUE TITLE
New players coming out of the tutorial

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#683]
Whilst a new player is doing the tutorial they are in a different bucket and then to finish off the tutorial they drive to city hall leave their car outside of city hall, which then sets them back into bucket 0 the default, which then causes the problem of a new players only car being stuck in a different bucket which makes it physically un-retrievable unless there's a vehicle clean up that they have to wait for. 
This results in new players always questioning where their car's gone within the discord all the time.

**Comment by packfile** [comment]
Thanks for the report, this has been changed for the next scheduled restart
