### ISSUE TITLE
[Bug]: Clothing Reset

### ISSUE THREAD

**Issue by Azonq** [CMGStudios/issue-tracker#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when using the Y menu to take off ur cloths pressing the reset button bottom right does not reset ur cloths 

### Expected behaviour

Y menu reset button not working

### Steps to reproduce

hold Y
Take off all ur cloths and accessories 
press the reset button bottom right of the wheel

### Any Texture Packs? (If so list)

no

### CMG User ID

1069

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
