### ISSUE TITLE
[Bug]: When speaking in game your mic volume goes lower 

### ISSUE THREAD

**Issue by NBKdev** [CMGStudios/issue-tracker#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Basically when u use radio's and in game voice chat for a x amount of time your mic volume will slowly go down and you have to keep going in sound control panel to turn up ur mic volume 

### Expected behaviour

explained above

### Steps to reproduce

I believe it's a pd issue not civ issue much
Speak in game a bit and use radios 
then people won't be able to hear u
/vsync doesn't do much
then go on sound control panel to recordings
select the mic and turn it up again

### Any Texture Packs? (If so list)

NA

### CMG User ID

22

**Comment by packfile** [comment]
Thanks for the report! This should be resolved from the latest restart, please reopen if you still experience this issue
