### ISSUE TITLE
PD Sirens

### ISSUE THREAD

**Issue by NBKdev** [CMGStudios/issue-tracker#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

PD siren bug basically when the officer has his sirens on and exit the vehicle some cars will have their sirens on still when the user has left the vehicle 

### Expected behaviour

explained above

### Steps to reproduce

Use sirens
Then hop out of car 
ask an officer is they can hear the sirens 
if they hear sirens they can't turn them of but on ur client side they are off so 
only way is to dv the vehicle to prevent it from happening

### CMG User ID

22

**Comment by crazychris2404** [comment]
I have experienced this myself and understand it’s frustrating however due to no steps to reproduce there is nothing that can be done currently

if you find a way to reproduce this please add onto the report
