### ISSUE TITLE
[Bug]: Hairdressers Resetting appearance

### ISSUE THREAD

**Issue by Azonq** [CMGStudios/issue-tracker#688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you go into the hairdressers and change something it resets you whole character face 

### Expected behaviour

hairdressers resets characters appearance 

### Steps to reproduce

go into hairdressers 
change something on your face

### CMG User ID

1069

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
