### ISSUE TITLE
[Bug]: K9 dogs missing its vest

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you spawn a K9 as HMP its missing its vest, rest works fine

### Expected behaviour

When you spawn it for the dogs to have its vest

### Steps to reproduce

1. t/k9
2. Spawn K9
3. No vest

### CMG User ID

14009

**Comment by crazychris2404** [comment]
Confirmed
This is throughout every faction that has access to /k9 and the vest is missing

**Comment by packfile** [comment]
This has been fixed for the next scheduled restart. Thanks for the report!
