### ISSUE TITLE
Store weapons in Vehicle

### ISSUE THREAD

**Issue by Kemalism** [CMGStudios/issue-tracker#69]
Guys,

Am I doing something wrong or is this the way it is. I cannot store more weapons in my trunk of my bus with 200KGS.
It will only fit 6 sometimes 7 weapons. How come ?

It happens on more vehicles.
With 200KGS i would expect it would store more.

Please help!

**Comment by alfiellds** [comment]
Hello, is this issue still occuring? This is a strange issue as I have been unable to reproduce it myself and we have received no other reports of issues with storing this amount of weapons in a 200kg.

Could you also provide your perm ID please?

Many thanks.

**Comment by Kemalism** [comment]
Hi,

This issue is still occuring. If i want to store more type of weapons in a 200KG it is not possible.
It looks like you can only store 2 type of weapons, when you try the 3th one it is not accessible.

Perm ID: 147382
________________________________
Van: AlfieLLDS ***@***.***>
Verzonden: zondag 18 juli 2021 21:24
Aan: CMGStudios/issue-tracker ***@***.***>
CC: Kemalism ***@***.***>; Author ***@***.***>
Onderwerp: Re: [CMGStudios/issue-tracker] Store weapons in Vehicle (#69)


Hello, is this issue still occuring? This is a strange issue as I have been unable to reproduce it myself and we have received no other reports of issues with storing this amount of weapons in a 200kg.

Could you also provide your perm ID please?

Many thanks.

**Comment by arthur-rl** [comment]
This is an intended feature. You can only store 2 weapons in the boot at once.
