### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Muja12** [CMGStudios/issue-tracker#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought the f5 gang license a couple weeks ago. And every day since then I’ve been trying to create a gang. And it’s not working 

### Expected behaviour

Loosing loads of money on tax on my vehicles 

### Steps to reproduce

1. Press F5
2. Press Create Gang
3. Type in the name
4. Press enter 

### Any Texture Packs? (If so list)

no

### CMG User ID

318684

**Comment by crazychris2404** [comment]
This has since been fixed
If you have any steps to reproduce what had caused this issue please add on to this report @Muja12
