### ISSUE TITLE
[Bug]: Invisible Clothing

### ISSUE THREAD

**Issue by yowild** [CMGStudios/issue-tracker#692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

clothing issue some players r invisible for me and my shirts and jackets r 519 i cant get into the same cloths to frag with my mates

### Expected behaviour

sdd

### Steps to reproduce

dsds

### Any Texture Packs? (If so list)

dsds

### CMG User ID

177106

**Comment by crazychris2404** [comment]
Do you have a clip of this or any way to reproduce?

**Comment by packfile** [comment]
No information provided, please reopen once you have reproduction steps. You should verify your texture budget is around 20%-30% (or higher), and verify your game files.

**Comment by yowild** [comment]
https://medal.tv/games/gta-v/clips/1dpGdBK144KR9-/d1337N8vVDgL?invite=cr-MSxxVEwsMTQ2NzY1ODgs

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
