### ISSUE TITLE
Pilot job only gives half xp

### ISSUE THREAD

**Issue by Jswp462** [CMGStudios/issue-tracker#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

-When dropping off people you get rewarded xp
-When collecting people for the second time you dont get xp

### Expected behaviour

-When dropping off people you get rewarded xp
-When collecting people for the second time you should get xp

### Steps to reproduce

Become pilot 
do one run of pilot job
Collect people for 2nd time

### Any Texture Packs? (If so list)

N/a

### CMG User ID

286583

**Comment by crazychris2404** [comment]
I haven’t experienced this when testing the job nor has others when I spoke to them about this if you have a clip of this to highlight the issue please reopen this issue
