### ISSUE TITLE
[Bug]: 49/50 Platinum Toys

### ISSUE THREAD

**Issue by ZXFIVEM** [CMGStudios/issue-tracker#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The issue, i am currently having is claiming the platinum toy 

I am currently aware that the platinum toy is in the rebel house but you cant access it unless you can noclip into the house and claim it 

The reason you cant get it from the rebel house is cause there is no MLO for the house or u cant enter it cause someone owns the house.

### Expected behaviour

It would be much appreciated if you can move the plat toy out of the house and change it to a new place just so people can access the toy

it is also not just me who is having this glitch it is everyone who is in the city trying to claim the platinum 

I have only just found out this, bug so i hope you can get back to me ASAP 

Thanks.

### Steps to reproduce

1. Go into rebel go to the house
2. No house so you cant enter it 
3. all i ask is you move the toy from that location

### Any Texture Packs? (If so list)

None

### CMG User ID

932

**Comment by crazychris2404** [comment]
Believe this was already fixed by @tom-gun when did you last try this ?

**Comment by ZXFIVEM** [comment]
I Tried this the other day (3 days ago to be exact)

**Comment by crazychris2404** [comment]
After discussing with multiple other people i cannot find anyone else experiencing this issue `/questsremaining`
