### ISSUE TITLE
[Bug]: Sandy PD MLO

### ISSUE THREAD

**Issue by Macccc1** [CMGStudios/issue-tracker#696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MLO is invisible when u go down stairs

### Expected behaviour

MLO is invisible when u go down stairs

### Steps to reproduce

delete the files and then re-ensure them

### Any Texture Packs? (If so list)

No

### CMG User ID

741

**Comment by crazychris2404** [comment]
Not 100% reproducible until we have known settings to cause this issue we cant do anything
