### ISSUE TITLE
[Bug]: discord verification

### ISSUE THREAD

**Issue by harrydbartram** [CMGStudios/issue-tracker#699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my account has already been verified on discord with another discord account it was my previous one although it has been banned... ive tried to contact the owner although he wont accept my request 

### Expected behaviour

 i dont get a new code when i join the game so can 

### Steps to reproduce

idk what this means

### Any Texture Packs? (If so list)

no

### CMG User ID

295127

**Comment by maxreid250** [comment]
This isn't a bug. Have you gone to your F2 menu and gone to the "Changed Linked Discord" in-game? This should solve the issue if you haven't tried it. If it doesn't work after then make a support ticket.

**Comment by crazychris2404** [comment]
Correct steps have been listed by max feel free to contact me on discord for more info 

> `chris._._.`
