### ISSUE TITLE
[Bug]: Home app saying "this is not available right now" 

### ISSUE THREAD

**Issue by itjustz** [CMGStudios/issue-tracker#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

any time i try to do anything in the home app it says "this is not available right now" even for houses im not renting and i own so i cant give access to any of my friends because of this bug

### Expected behaviour

So you open your phone go onto the home app then press a house you own then one of the options and it says "this is not available right now" when i should be able to give the keys to my friends
![image](https://github.com/CMGStudios/issue-tracker/assets/136995952/b4265c21-950f-4230-8398-ef67bc176eed)

### Steps to reproduce

1. open your phone and open the app called "home"
2. click one of your houses then any of the options like "lock doors" or "give key"
3. the notification "this is not available right now"

### CMG User ID

317145

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
During multiple tests features regarding houses do not work and display the message listed in this report

**Comment by packfile** [comment]
This is intentional behaviour at the moment. This may be something we choose to implement in the future :)
