### ISSUE TITLE
[Bug]: Casino staff clothing

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="648" alt="image" src="https://github.com/CMGStudios/issue-tracker/assets/38780460/81ad79a3-db19-49c0-97f0-e2ae5ad97264">
I don't think I need to say more

### Expected behaviour

They dont look like a weird danny?

### Steps to reproduce

1.Go to casino
2.Cry your eyes out

### CMG User ID

14009

**Comment by crazychris2404** [comment]
Confirmed 
This occurs to multiple dealers around the casino

**Comment by packfile** [comment]
Thanks for the report, this is fixed from the latest restart
