### ISSUE TITLE
Selling Whitelist

### ISSUE THREAD

**Issue by Spino001** [CMGStudios/issue-tracker#702]
I just spent 40 pound on the game so I can get an smg whitelist and sell it however when I tried to sell it.
Standing right next to the player who I was selling it to it said "there are no nearby players" I have tried restarting my game deleting cache files and spoke to an admin who sent me here what can I do?

**Comment by crazychris2404** [comment]
Unfortunately without any information as to what could of caused this nothing we can do

**Comment by Spino001** [comment]
Well can you try look into it please

**Comment by crazychris2404** [comment]
Cannot be looked into without actionable information
