### ISSUE TITLE
[Bug]: Bullets disappear when storing weapons in a vehicle

### ISSUE THREAD

**Issue by maxreid250** [CMGStudios/issue-tracker#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I can get a clip if requested but when I stored a gun sat in my car all the bullets disappear.

### Expected behaviour

Bullets disappeared when storing my weapon

### Steps to reproduce

1. Sit in a car
2. Storeallweapons

### CMG User ID

204066

**Comment by crazychris2404** [comment]
This isn't occurring for me please can you attach a clip to show more details of how it can be reproduced?
