### ISSUE TITLE
[Bug]: character freezes when clocking off NHS/PD and click "t" to open chat

### ISSUE THREAD

**Issue by cookieforpres** [CMGStudios/issue-tracker#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i go from NHS to Unemployed via the red circle at St. Thomas, i click "t" to open the chat and mu character freezes, i've tried /reset but it doesn't work.

### Expected behaviour

Open the chat 

### Steps to reproduce

1. Clock off NHS
2. Click "t" to open the chat

### CMG User ID

360789

**Comment by crazychris2404** [comment]
This is not happening for me if you can get a clip of this occurring please press f8 and include that in the clip when reopening this issue
