### ISSUE TITLE
[Bug]: Advanced gang 

### ISSUE THREAD

**Issue by Tayserr** [CMGStudios/issue-tracker#705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my mate just bhought advanced gang license,i joined his gang as a member we enabled everything but somehow we cant see any blips,health or names,and the leader himself cant withdraw money,hope it gets fixed asap(btw he bhought it from the gang menu itself not the license store)

### Expected behaviour

advanced gang license

### Steps to reproduce

.

### Any Texture Packs? (If so list)

no just reshade

### CMG User ID

309840

**Comment by PIKAlmao** [comment]
Hello @Tayserr the blips/health/names is not a bug as far as i'm aware, if you go into the members list, there will be a pin icon next to the users name, if you press that they should appear on your minimap/map and have names above their heads assuming you've enabled everything else within the advanced gang license settings. The not being able to withdraw money from the gang may be though so keep this report open and someone can look into that side of it.

**Comment by crazychris2404** [comment]
Sorted by server staff already
