### ISSUE TITLE
[Bug]: Race Events

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Race events around the map do not work and cannot be started/triggered

### Expected behaviour

Head to event location for example sandy airfield race in a car and try start event
Should work

### Steps to reproduce

Head to event location for example sandy airfield race in a car and try start event
Nothing comes up

### CMG User ID

910

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the latest restart
