### ISSUE TITLE
[Bug]: Opening chat causes game to freeze

### ISSUE THREAD

**Issue by Benunzeee** [CMGStudios/issue-tracker#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When opening chat, most commonly in a greenzone or after leaving an event, or during an event, your character freezes and the only way to fix it is by relogging. I did see another issue about this but it has since been closed, I opened this issue as seeing that one made me see it is not only me this is happening to and I can provide more evidence.

![image](https://github.com/CMGStudios/issue-tracker/assets/138224462/5f11c202-a7dc-4d0b-aa6c-68acaab4da7b)

### Expected behaviour

Once pressing T to open the chat you get an error in F8 and can no longer move or do anything until you relog.

### Steps to reproduce

- Leave an event, be in an event or stand in St Thomas Hospital and open chat.

- You can no longer move and the error above is in the f8 console.

- This may take a few attempts as it doesn't happen every single time.

### CMG User ID

331658

**Comment by crazychris2404** [comment]
Does this occur with any specific event?

**Comment by crazychris2404** [comment]
Based on the causes you have listed i am unable to have this bug occur myself

**Comment by Benunzeee** [comment]
I'm not 100% on this but you may have to be clocked on PD or NHS for it to occur as I am most of the time, you could try that.

**Comment by Benunzeee** [comment]
and any event at all, can't open the chat to leave the event most cases.

**Comment by crazychris2404** [comment]
I have tried whilst clocked on I am still not experiencing this

**Comment by Benunzeee** [comment]
I'm not sure, this is happening for lots of people in pd, sometimes it can even happen as soon as I join the server. When I join the server usually the chat is only displaying twitter messages until I press T and then it shows all the OOC chats aswell, could be related.

**Comment by crazychris2404** [comment]
Confirmed
When clocked off a faction 
Try clock on and it will occur

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
