### ISSUE TITLE
[Bug]: It will not let me leave the gang im in.

### ISSUE THREAD

**Issue by Tomnate2** [CMGStudios/issue-tracker#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i first started this server one of my friends started a gang and me and my friends joined it. after I took a break from the game i was the only one left in the gang. so i tried to leave and was left with the message that i cannot leave as im the only person left in the gang. so i tried to disband the gang yet it says that i do not have permission to disband the gang. so i thought maybe if i bought my own gang license it would kick me but it has not and im still stuck in the gang 1.5 million down. can you pls help me.

### Expected behaviour

I described my problem in the description

### Steps to reproduce

.

### Any Texture Packs? (If so list)

no

### CMG User ID

251046

**Comment by crazychris2404** [comment]
Can you please provide screenshots or a video showing this issue please

**Comment by Tomnate2** [comment]
yes here is a clip of it. as u can see it will not let me leave or disband the gang and i cannot withdraw the money i deposited https://youtu.be/jc3Bu-YkS1w

**Comment by crazychris2404** [comment]
Thanks for this report can you please leave a message here in the following format
Gang Name:
Perm ID:

**Comment by Tomnate2** [comment]
Gang name: Get Rich Or Die Tryin
Perm ID:251046

**Comment by Tomnate2** [comment]
gang name : Get rich or Die tryin
perm id: 251046

**Comment by crazychris2404** [comment]
Thanks i will forward this and close this report should hopefully be fixed soon

**Comment by Tomnate2** [comment]
it still hasnt been fixed
