### ISSUE TITLE
[Bug]: when your clocked off casino, speed cap is still on 

### ISSUE THREAD

**Issue by MrVortex122** [CMGStudios/issue-tracker#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After the new rule of speed cap whilst clocked on casino has been added, I’ve noticed that’s when you clock off your postion, the speed limit remains, someone else also dm asking about it so it’s several people having this issue

### Expected behaviour

-

### Steps to reproduce

Clock of, speed limit is still on

### Any Texture Packs? (If so list)

No

### CMG User ID

1070

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the response

**Comment by TheRealWicks** [comment]
I cant catch people on the higway going 150mph, fix this quick pls

**Comment by MrVortex122** [comment]
> I cant catch people on the higway going 150mph, fix this quick pls

I think you mean 125

**Comment by packfile** [comment]
This was fixed earlier this week, thanks for the report.
