### ISSUE TITLE
NHS Rappel Heli Bug

### ISSUE THREAD

**Issue by bethbtw** [CMGStudios/issue-tracker#71]
**Describe the issue you're facing**
When you are flying an NHS helicopter that has a rappel feature or are the co-pilot of the Heli, if you press "X" it begins the falling animation whilst keeping you in the seat. This ultimately makes you lose control of the helicopter until you land or crash. 
**Steps to reproduce**
Take either the NHS Big Heli or the NHS HEMS Air-1 out of a garage. Sit in either the pilot or co-pilot seat and press "X".
**Expected behaviour**
To maintain full control of the heli at all times and to have no falling animation.
**Screenshots/Video**
![HeliGlitch](https://user-images.githubusercontent.com/87390299/125523035-28a669ca-9ace-4b45-945c-c71666ea3797.png)

**Additional context**
N/A
**Any Texture Packs (if so list)**
N/A
**Perm ID**
182742

**Comment by alfiellds** [comment]
Hello Bethany, thank you for the report. I have tested and confirmed this issue occurs with most PD, NHS & Civilian helicopters and will now forward this to the developers.

Many thanks.

**Comment by rubbertoe98** [comment]
Fixed from next restart.
