### ISSUE TITLE
[Bug]: texture index menu broken

### ISSUE THREAD

**Issue by ChippyWonk** [CMGStudios/issue-tracker#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

New update broke the texture menu on some faction clothing I believe. Essentially its hard to flick through certain textures or some are outright removed; a good example is the HMP vest (99), wherein only the riot unit index is available. 

### Expected behaviour

Basically just put it above; essentially usually you'd be able to flick through no problem. For me this impacts both NHS shirt (427), NHS bulletproof vest (89), and HMP vest (99).

### Steps to reproduce

1. Clock onto HMP
2. Select vest (99)
3. Attempt to change index

### CMG User ID

363029

**Comment by crazychris2404** [comment]
Believe this is now fixed
