### ISSUE TITLE
[Bug]: big thing on the roof of my jeep trackhawk that was imported

### ISSUE THREAD

**Issue by st4cktill4pf** [CMGStudios/issue-tracker#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

hi there, i purchased a jeep trackhawk thru vehicle imports. for some reason it has a big thing on the roof of the car and i want it removed as it was not advertised like that on the import page. it never use to appear but now it does. ive tried to go to the repair shop to remove it but its not giving me an option

### Expected behaviour

hi there, i purchased a jeep trackhawk thru vehicle imports. for some reason it has a big thing on the roof of the car and i want it removed as it was not advertised like that on the import page. it never use to appear but now it does. ive tried to go to the repair shop to remove it but its not giving me an option

### Steps to reproduce

any way to pressa key to remove this thing on it?

### CMG User ID

367906

**Comment by PIKAlmao** [comment]
Hello, is it this one you chose ? if so contact me on discord by either PIKA or td5. 
https://prnt.sc/mXWsSmoCUJvW

**Comment by crazychris2404** [comment]
This is something with the car and not something we can resolve here
