### ISSUE TITLE
[Bug]: House gate  doesnt open 

### ISSUE THREAD

**Issue by NovaOnTop21** [CMGStudios/issue-tracker#712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

in my house the garage dont open

### Expected behaviour

i want my garage to open please itll help alot

### Steps to reproduce

![Screenshot 2023-07-05 171312](https://github.com/CMGStudios/issue-tracker/assets/138704320/da7d6fc3-6ab5-4736-933e-32c7e466a3ca)
This is where my house is

### Any Texture Packs? (If so list)

No

### CMG User ID

299781

**Comment by PIKAlmao** [comment]
👍 Pretty much every house on the road or in the area all have working gates, just seems to be this one in particular that doesn't work. 
![screenieeeeeeeee](https://github.com/CMGStudios/issue-tracker/assets/114100126/b80672b8-8123-4c5f-a9ad-b5666f81c9bf)

**Comment by crazychris2404** [comment]
Confirmed
The house named "Mega Luxury n03" does not have a working gate whereas others do

**Comment by packfile** [comment]
![image](https://github.com/CMGStudios/issue-tracker/assets/97990837/6c976b5c-73be-4a39-935b-42e2023d3b1f)
This gate appears to be non functional in the base game too
