### ISSUE TITLE
[Bug]: Organ Heist Floodlights

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In organ the lights are constantly flickering

### Expected behaviour

They should work like normal lights and not make me have an epileptic fit 

### Steps to reproduce

https://www.youtube.com/watch?v=rJHpyC0_t_0

### Any Texture Packs? (If so list)

No

### CMG User ID

867

**Comment by PIKAlmao** [comment]
Not too sure if this is correct, but i think i remember seeing something regarding the graphics menu in your f2 menu, if you turn them to the lowest or off or whatever should fix it. Should be fixed eitherway for all settings

**Comment by Declare5M** [comment]
Ill have to check in the next organ

**Comment by PIKAlmao** [comment]
👍

**Comment by crazychris2404** [comment]
I haven’t experienced this before or heard about this so try what @PIKAlmao has suggested and feel free to reopen this issue if you find steps to reproduce

**Comment by crazychris2404** [comment]
Closed info listed here thanks junction for spotting this https://github.com/CMGStudios/issue-tracker/issues/575
