### ISSUE TITLE
[Bug]: Enter custom shop with other people’s car

### ISSUE THREAD

**Issue by Azonq** [CMGStudios/issue-tracker#714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

some times i can enter the car custom shop with other peoples cars 

### Expected behaviour

some times it works and you can customise a car u don’t own

### Steps to reproduce

take a car u don’t own
drive custom shop
press enter (9/10 times it works)

### Any Texture Packs? (If so list)

no

### CMG User ID

1069

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart. Note: This was only a visual bug, and changes would not persist.
