### ISSUE TITLE
[Bug]: If you enter water while speaking on a radio you die

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

What it is in the title. If you enter water while speaking on a radio you die. It doesn't happen 100% of the time but it happens often enough that it is a problem.

### Expected behaviour

Read above

### Steps to reproduce

Speak on radio
enter water
die

### Any Texture Packs? (If so list)

None

### CMG User ID

1220

**Comment by crazychris2404** [comment]
Thanks for the report
This is reproducible

**Comment by packfile** [comment]
Thanks for the report, this is fixed from the latest restart
