### ISSUE TITLE
[Bug]: SOA vest not in clothes shop 

### ISSUE THREAD

**Issue by lildickie27** [CMGStudios/issue-tracker#717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The SOA vest has now disappeared out of the clothing shop. It used to be option 86 in vests but is no longer there and not under any other number.

### Expected behaviour

the SOA vest to be in the vest option.

### Steps to reproduce

1. go to clothes shop
2. go to vests
3. try to find SOA vest 
4. its not there

### Any Texture Packs? (If so list)

no

### CMG User ID

1027

**Comment by Simonstv** [comment]
Confirmed
Thanks for the report.
