### ISSUE TITLE
[Bug]: Emergency Radio blips are fucked

### ISSUE THREAD

**Issue by 004Luke** [CMGStudios/issue-tracker#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

PD, NHS, LFB, HMP emergency radios blips are all messed, when people join the game and still have an emergency radio on them their blip sometimes doesn't automatically appear.
this is usually fixed by either getting an emergency radio given to you or you just pick one up from the store. miraculously, you can also trash your existing radio in your inventory and restore your blip

### Expected behaviour

When a person joins the server clocked onto a faction with an emergency radio, their blips doesn't show

### Steps to reproduce

join the server already clocked onto a faction with an emergency radio
you won't have a blip

### Any Texture Packs? (If so list)

None

### CMG User ID

1220

**Comment by crazychris2404** [comment]
Any steps to reproduce ?

**Comment by 004Luke** [comment]
> Any steps to reproduce ?

Not really, people just relog and sometimes they don't have a blip. It got fixed before but now it's come back and its worse as half of the people clocked onto a faction don't have a blip.

**Comment by crazychris2404** [comment]
I am experiencing this alot currently so will leave as trivial whilst we wait to find any reproduction steps to this

**Comment by packfile** [comment]
Thanks for the report. A potential fix has been put in from the next scheduled restart. If this still occurs then please reopen the issue

**Comment by DjDoon** [comment]
This issue does still occur, if you have multiple radios on you and trash on it fixes itself also got an issue where you can see the blips on long-range but when you get closer they disappear

**Comment by crazychris2404** [comment]
Great thanks for the info will reopen
