### ISSUE TITLE
[Bug]:  Mirror Park House 10 Interior

### ISSUE THREAD

**Issue by Street1112** [CMGStudios/issue-tracker#719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Interior of Mirror Park House 10 still needs fixing

### Expected behaviour

https://medal.tv/games/gta-v/clips/1bTGW6FfWApyPz/d1337lFpJNPL?invite=cr-MSwzbEcsMTU3MDE1NzI4LA

### Steps to reproduce

https://medal.tv/games/gta-v/clips/1bTGW6FfWApyPz/d1337lFpJNPL?invite=cr-MSwzbEcsMTU3MDE1NzI4LA

### CMG User ID

958

**Comment by Simonstv** [comment]
https://github.com/CMGStudios/issue-tracker/issues/657#issuecomment-1569753459 
This is the original issue, this has still been resolved sorry for the delay, this will be forwarded to the dev team.

**Comment by packfile** [comment]
Please refer to the comment on #685
