### ISSUE TITLE
New Stretcher Bug

### ISSUE THREAD

**Issue by Grxpz** [CMGStudios/issue-tracker#72]
**Describe the issue you're facing**
With the newly fixed NHS stretchers, whilst you can now be visible when lying in them, it would appear asthough theres a chance you will now be frozen upon attempting to leave/get up of the stretcher. I have witnessed it 4 or 5 times now after admin tickets have been called for people to be unfrozen. Not entirely sure if its 100% of the time, but Its clear that there is some sort of interference occuring.

**Steps to reproduce**
1. Get into an NHS stretcher
2. Attempt to leave said stretcher
3. You will be frozen in mid-air, with no way to move.

**Expected behaviour**
You will become frozen above the stretcher.
As previously mentioned, not entirely sure the % chance of this occuring, could be very high or low, however I have witnessed it multiple times within the last 24 hours, hence the bug report.

**Screenshots/Video**
https://youtu.be/9dTY0awAGiU
https://youtu.be/4qkvOjtEHmY

**Additional context**
The beds were just recently adjusted, so I'd imagine theres some sort of interference in the new code causing this issue for some people.

**Any Texture Packs (if so list)**
New Vision Evolved.

**Perm ID**
191307

**Comment by MrLexo** [comment]
I have also experienced this and it appears the only way to get someone unfroze is by using another stretcher and getting them to get on and off which is weird making the bug 50/50 or a staff member to freeze/unfreeze.

**Comment by Grxpz** [comment]
I am currently rendering more evidence.

**Comment by alfiellds** [comment]
Hello Grxpz, thank you for the report. This report will be moved to high priority as it is causing gameplay issues and requires a staff member in order to be resolved.

A developer will hopefully look at this shortly.

**Comment by rubbertoe98** [comment]
Fixed from next restart.
