### ISSUE TITLE
[Bug]: Trucking job trailer going side to side whilst at higher speeds and it detaches

### ISSUE THREAD

**Issue by KC0161** [CMGStudios/issue-tracker#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

due to the weight of the cargo that you are carrying on the trailer during a truck job the trailer goes side to side and you lose traction and the trailer detaches and makes you unable to finish the trucking job and basically cant do anything to fix it

### Expected behaviour

trucking job is undoable if you have a locked truck that goes faster than normal speed and the cargo will cause the trailer to detach

### Steps to reproduce

truck job
get trailer (heavier loads)
get a locked truck
hook it and try to drive it fast

### CMG User ID

508

**Comment by Simonstv** [comment]
Thank you for your report, i can confirm this is a bug and will pass it on to the developers
Extra information from it can be found from this clip https://streamable.com/v0xdx6

**Comment by packfile** [comment]
This is believe to have been fixed as of yesterday, please let us know if it still occurring from today.
