### ISSUE TITLE
[Bug]: instagram live audio overlapping when phone is closed

### ISSUE THREAD

**Issue by Yiqqa** [CMGStudios/issue-tracker#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i open the instagram app inside of CMG and i go onto someones live sometimes i am able to hear the audio of that live stream even when i am not on the app anymore or even when i close my phone.

### Expected behaviour

the expected behaviour of this issue is for the audio to overlap without being on the phone / app

### Steps to reproduce

1. open the instagram app inside of CMG
2. go onto someone's live stream
3. watch it for about 2 minutes
4. close your phone
5. you still should hear the livestream audio

### CMG User ID

354742

**Comment by Keegasity** [comment]
Good evening,

I cannot seem to replicate the issue with the steps provided. Please can you provide some more information or a video of the bug?

Thanks

**Comment by Yiqqa** [comment]
here is me doing it myself. i forgot to mention that you press k when you are on the live

https://clipchamp.com/watch/7aVA9kLDYOw

**Comment by Skilly1x** [comment]
This isn’t just with instagram lives it’s any audio on the phone but when it’s a live you can hear others comms even after they end

**Comment by packfile** [comment]
This may be fixed in a future phone update, in the meantime keep an eye on dev updates for it.
