### ISSUE TITLE
[Bug]: Taser reload

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

You can do the tazer reload infinite even do you have a full "mag"infinitely

### Expected behaviour

Can only get the reload emote when you can reload the tazer

### Steps to reproduce

Go on PD 
Grab a tazer
press  R

### Any Texture Packs? (If so list)

N/A

### CMG User ID

9975

**Comment by DjDoon** [comment]
Clip of issue - https://medal.tv/games/gta-v/clips/1kt5cbFLIyuEAe/d1337jZLmkFI?invite=cr-MSw4ODQsNDE3Mzg1MDgs

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report, this bug has now been fixed.
