### ISSUE TITLE
[Bug]: Weapon options on F2 menu directing to the wrong menu

### ISSUE THREAD

**Issue by tomp1118** [CMGStudios/issue-tracker#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When going into the F2 menu and selecting "Weapon Options" it takes you to the "Gang Options" menu.

### Expected behaviour

When going into the F2 menu and selecting "Weapon Options" it should take you to the "Weapon Options" menu instead of "Gang Options"

### Steps to reproduce

1. Press F2
2. Select "Weapon Options"

### CMG User ID

257819

**Comment by PIKAlmao** [comment]
Can confirm this is true,  Shows "gang options" settings within the weapon options tab.

https://github.com/CMGStudios/issue-tracker/assets/114100126/03bf0d4d-3158-44fc-82b1-a0a45adffa05

**Comment by Keegasity** [comment]
As mentioned above by PIKA.

- Upon clicking on "Weapon Options" this takes you to "Gang Options" 

- The "Gang Options" tab is working correctly and does take you to "Gang Options"

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
