### ISSUE TITLE
[Bug]: respawning with combat timer

### ISSUE THREAD

**Issue by Azonq** [CMGStudios/issue-tracker#725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

dying in red made me swapn with combat timer

### Expected behaviour

i dont know how to repeat this and whether it a 1 time thing or not

### Steps to reproduce

1.die in red zone
2.respawn

### Any Texture Packs? (If so list)

no

### CMG User ID

1069

**Comment by Azonq** [comment]
https://medal.tv/games/gta-v/clips/1kuDKWZy4mlFZL/d1337sXfzmb3?invite=cr-MSw1cmMsMTY5OTQ2NTU3LA

**Comment by PIKAlmao** [comment]
Tried this twice and couldn't get the same out come, seems to be a random occurrence.

**Comment by packfile** [comment]
Thanks for the report, this edge case should be fixed from the latest restart
