### ISSUE TITLE
[Bug]: AA mechanics cant read messages sent through the services app

### ISSUE THREAD

**Issue by HapiSpeed** [CMGStudios/issue-tracker#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When clients try to send locations to us through the app we get a notification saying that they sent us a location but we cant accually access the message to see the location. 

### Expected behaviour

can you please just take away the message feature or fix it so we can accually see the messages they send us.

### Steps to reproduce

Have someone registered as a AA mechanic, then the other guy sends his location through the services app and the AA mechanic should recieve the pop up notification but he cant accually go into the services app and see where the locatioon is.

### CMG User ID

372479

**Comment by Keegasity** [comment]
Confirmed, Thank you for the report.

Steps to reproduce this.

- Open up your phone and go to "Services"
- Click the message icon on the far right of "AA Mechanic" 
- In the bottom left click the "Location" icon and click "Send"
- This should send your location to the AA and appear in "Job Messages"

What actually happens?

- AA receives a message notification that you cannot click on or see within the "Job Messages"

**Comment by HapiSpeed** [comment]
Yup thats the problem

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
