### ISSUE TITLE
[Bug]: not a bug but something that should be changed none the less and that is auto helmets on bikes for civs

### ISSUE THREAD

**Issue by KC0161** [CMGStudios/issue-tracker#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

please disable auto helmets for helicopters and bikes it is so annoying and theres no need for it at all apart from it removing your hat and having to go to a clothes store every 10 min

### Expected behaviour

everytime you get on a bike or some helicopters a helmet gets put on you and you cant stop it please remove this feature for civs

### Steps to reproduce

1. get on bike or heli
2. boom helmet gets put on
3. now your hat or whatever you had on disappeared

### CMG User ID

508

**Comment by crazychris2404** [comment]
Good morning
Thanks for the report 
Unfortunately this isn’t a bug but is something development team is 100% interested in doing please can you make a suggestion in the cmg discord
