### ISSUE TITLE
[Bug]: Firefighting hose unusable in greenzones

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we have a fire in a greenzone, at organ for example it makes it quite hard for us to fight these because we are unable to equip our hose within a greenzone

### Expected behaviour

To be able to equip a firehose in a greenzone

### Steps to reproduce

1. clock on
2. fight a fire in a greenzone

### Any Texture Packs? (If so list)

no

### CMG User ID

14009

**Comment by crazychris2404** [comment]
This is confirmed to be a issue 
Best solution would be removing the fire from that location due to the greenzone I will move for developers to investigate

**Comment by packfile** [comment]
Thanks for the report. Fires should not be created in greenzones, so I have tasked this internally to be fixed
