### ISSUE TITLE
[Bug]: AA Ford Transit not spawnable

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The new AA Ford Transit vehicle can't be spawned at any garage but can be purchased

### Expected behaviour

Be able to spawn the vehicle

### Steps to reproduce

1. Clock on AA
2. Purchase the Transit vehicle
3. Try spawning it

### CMG User ID

71613

**Comment by Keegasity** [comment]
Confirmed. Developers are aware of this.

Thank you for the report

**Comment by crazychris2404** [comment]
Fixed
