### ISSUE TITLE
[Bug]:Pet Coyote is broken

### ISSUE THREAD

**Issue by MrVortexCmG** [CMGStudios/issue-tracker#730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you press attack on someone, the pet Coyote will just run the opposite way and not stop ever again.

### Expected behaviour

Expected behaviour would be to attack the person you press attack on lmao

### Steps to reproduce

Spawn coyote
Aim gun at someone and press attack
He runs away 

### Any Texture Packs? (If so list)

No

### CMG User ID

1070

**Comment by packfile** [comment]
This does not reproduce locally, please note that inside or near custom buildings this may not work.
