### ISSUE TITLE
[Bug]: When entering house car locks even if left unlocked before entering house 

### ISSUE THREAD

**Issue by nicsarr** [CMGStudios/issue-tracker#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Before entering your house  you would lock your car and enter your house but when entering your house and coming back out of it you wont be able to get in your car by trying to unlock it because it locks it for some reason even if left unlocked. Therefore not allowing you to get in your car if parked close to your house when entering.

### Expected behaviour

You should be able to get back into your car after leaving your house.

### Steps to reproduce

1. Park your car near your house and enter it 
2. Leave the house and try get in your car 
3. You should not be able to get into it 

### Any Texture Packs? (If so list)

No

### CMG User ID

235907

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
(You loose the blip for the car meaning a few issues occur and you are required to press e to unlock the car)

**Comment by packfile** [comment]
This does not reproduce locally with two players. Please use the aforementioned workaround when this does happen.
