### ISSUE TITLE
[/drone not working for nhs ]: 

### ISSUE THREAD

**Issue by Gooobie** [CMGStudios/issue-tracker#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The /drone command doesn't seem to be working it has been tested by a few others but nothing seems to happen 

### Expected behaviour

when you do /drone a little drone appears 

### Steps to reproduce

/drone 

### Any Texture Packs? (If so list)

NVE (others without packs have the same outcome)

### CMG User ID

168410

**Comment by Keegasity** [comment]
Confirmed, Thank you for the report.

/drone only works for MET PD.

NHS, LFB, HMP have no access to this.

**Comment by packfile** [comment]
This has been fixed, thanks for the report
