### ISSUE TITLE
[Bug]: Pilot job, consistently stuck everytime i start a job and exit the start vehicle

### ISSUE THREAD

**Issue by shalom54321** [CMGStudios/issue-tracker#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Pilot job, consistently stuck everytime i start a job and exit the start vehicle.
https://www.youtube.com/watch?v=ILhviK87_Lg
### Expected behaviour
https://www.youtube.com/watch?v=ILhviK87_Lg
i have not been able to enter my aircraft yet, i have reconnected 5 times and it happends every time, i got a friend with the exact same problem when he exits his runway vehicle

### Steps to reproduce
https://www.youtube.com/watch?v=ILhviK87_Lg
start job
drive to plane
exit runway vehicle
get stuck
plane despawn
disconnect 
repeat

### CMG User ID

371925

**Comment by shalom54321** [comment]
here is visual representation of the bug
https://www.youtube.com/watch?v=ILhviK87_Lg

**Comment by Simonstv** [comment]
Thank you for your report, i can confirm this is a bug, and will pass it on the Developer Team.

**Comment by packfile** [comment]
This has been fixed, thanks for the report
