### ISSUE TITLE
[Bug]: Trucking Pickup spot glitch

### ISSUE THREAD

**Issue by qwakeuk** [CMGStudios/issue-tracker#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

trucking bug where it takes you to a location but there is no trailer pickup, I have gone unemployed and logged off neither reset it. When I log back in and go to the Ilegal trucking job place and accept a job it leads me straight back to the glitched spot.

https://imgur.com/XLND9Lv  / <- the location of the glitch spot

Hope this helps as It's very annoying

### Expected behaviour

Cant do anymore trucking as it always says you have a Job already active

### Steps to reproduce

I was just trucking perfectly fine and it just told me to go here

### CMG User ID

373241

**Comment by Keegasity** [comment]
After testing, I cannot see to replicate this issue. Please can you provide a video of this.

**Comment by crazychris2404** [comment]
Closed due to no response
