### ISSUE TITLE
[Bug]: failed to call inflate mpbiker_male

### ISSUE THREAD

**Issue by bluebandit13** [CMGStudios/issue-tracker#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Game crashes and this box appears

### Expected behaviour

game crashes, I am new to fivem, tried uninstalling/reinstalling etc

### Steps to reproduce

game crashes, no reasdon

### Any Texture Packs? (If so list)

no

### CMG User ID

n/a cant open game

**Comment by Keegasity** [comment]
Good Evening,

Please can you contact myself via discord (Keegan - Moderator) 

I will help you rectify this issue.
