### ISSUE TITLE
When your job is "Truck Driver" cars speed is capped at 150mph

### ISSUE THREAD

**Issue by FrankLadd** [CMGStudios/issue-tracker#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you go become a truck driver. Your cars will no longer go faster than 150mph until you change your job again.

### Expected behaviour

Personally owned vehicles will not go over 150mph

### Steps to reproduce

Go become a truck driver and then drive any car you own

### Any Texture Packs? (If so list)

No

### CMG User ID

208345

**Comment by crazychris2404** [comment]
Thanks for the report however this is intentional

**Comment by LiamTownsley2** [comment]
> Thanks for the report however this is intentional

Just wondering why? Was about to report this but just seen this issue.
Me & my friend were confused on why we couldn't go past 150 haha

**Comment by crazychris2404** [comment]
It’s a limit set to make it a fair way of making money

**Comment by LiamTownsley2** [comment]
> It’s a limit set to make it a fair way of making money

The issue was referring to regular cars, my personal car (Audi) is restricted to 150mph, the same as my Truck when I am on the Trucker job

**Comment by crazychris2404** [comment]
It’s just the way devs decided to do this if you would like to put a recommendation for change please post in the suggestions channel in discord as this thread is for bugs only
