### ISSUE TITLE
[Bug]: fishing

### ISSUE THREAD

**Issue by Azonq** [CMGStudios/issue-tracker#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when fishing pressing spacebar on the green doesn't actually count 

### Expected behaviour

i could just be really bad at fishing

### Steps to reproduce

1.start fishing
2.fish at location (i fished illegally)
3.press space bar (on the green) when slider comes up 
 

### Any Texture Packs? (If so list)

no

### CMG User ID

1069

**Comment by packfile** [comment]
This does not reproduce locally, please can you get a video of this issue occurring and then reopen this
