### ISSUE TITLE
[Bug]: !verify code not working

### ISSUE THREAD

**Issue by Gleedy0** [CMGStudios/issue-tracker#739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi I'm trying to join this server and every time I put my code in it give me from FiveM it says code not found. Hope I can find a fix so I can play.

### Expected behaviour

Hi I'm trying to join this server and every time I put my code in it give me from FiveM it says code not found. Hope I can find a fix so I can play.

### Steps to reproduce

im not sure if its just me. i signed up for FiveM only 3 days ago.

### CMG User ID

/getmyid

**Comment by PIKAlmao** [comment]
What's your discord ?

**Comment by Keegasity** [comment]
Please drop myself a message on discord (Keegan - Moderator) and we will get this resolved. 

This is not a bug

**Comment by Gleedy0** [comment]
still doesnt work
