### ISSUE TITLE
Issue with 21:9 resolution

### ISSUE THREAD

**Issue by samwht** [CMGStudios/issue-tracker#74]
On 21:9 resolution on a ultrawide monitor, menus are half off the screen and the money and map stuff overlaps on my screen.

**Steps to reproduce** 
Use 21:9 Aspect Ratio

**Expected behaviour**

**Screenshots/Video**
[
![219](https://user-images.githubusercontent.com/87452062/125703900-2de4e443-d2ee-4a81-a9dc-2c8816ab3f6c.PNG)
](url)
**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
542

**Comment by rubbertoe98** [comment]
Fixed from next restart
