### ISSUE TITLE
[Bug]: Mercedes Vito

### ISSUE THREAD

**Issue by E12217** [CMGStudios/issue-tracker#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fix the Mercedes Vito 300kg van. The whole van is basically a ghost peak and overall just broken.

### Expected behaviour

half the van is basically non-existent making it difficult to flip with other cars, and sometimes it's impossible to open the boot because half of the van is not even there.

### Steps to reproduce

I'm unsure if its like this all the time, but the majority of the time the van is broken and half of it is basically non-existent. 

### CMG User ID

231560

**Comment by Keegasity** [comment]
Thank you for the report.

Unfortunately this is a car development issue. However, I will pass this onto the correct team.
