### ISSUE TITLE
[Bug]: Scuba Diving Pay out 

### ISSUE THREAD

**Issue by notpph0enix** [CMGStudios/issue-tracker#741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

just done scuba diving job and went to the place to get my money got all 6 from the boat and received no money
some other people I was talking to recently had the same issue
in game

### Expected behaviour

just done scuba diving job and went to the place to get my money got all 6 from the boat and received no money
some other people I was talking to recently had the same issue
in game

### Steps to reproduce

Did the scuba diving took the boat to a near garage drove car to place and complete job 

### Any Texture Packs? (If so list)

Not using any 

### CMG User ID

233618

**Comment by PIKAlmao** [comment]
I will join and compensate you for this loss. Direct message me if you're on.

**Comment by Keegasity** [comment]
Good Evening,

I cannot seem to replicate this issue. Please can you provide a video of this bug.

**Comment by packfile** [comment]
No actionable information to work off, closed. Please reopen once you have reproduction steps
