### ISSUE TITLE
[Bug]: weapons not in my cars

### ISSUE THREAD

**Issue by gazaboss1941** [CMGStudios/issue-tracker#742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

all my weapons have gone out of my cars

### Expected behaviour

i have no weapons in my cars

### Steps to reproduce

tried restarting the game

### Any Texture Packs? (If so list)

none

### CMG User ID

gazaboss1941

**Comment by crazychris2404** [comment]
This is not a bug boots are wiped once a month

**Comment by gazaboss1941** [comment]
Will my house get wiped too

**Comment by crazychris2404** [comment]
Yes

**Comment by gazaboss1941** [comment]
Where will they be safe the sorry for all the question new to all this

**Comment by PIKAlmao** [comment]
Check #game-support on the discord i'll explain to you how it all works since this has been closed now.
