### ISSUE TITLE
[Bug]: Cant use alt + D to drag a cuffed person

### ISSUE THREAD

**Issue by lildickie27** [CMGStudios/issue-tracker#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am clocked on as Casino security helping test but for some reason i am unable to use alt + D to drag a person i have tackled and cuffed. I cant find a way to change the keybind anywhere. This was an issue when i was going through PD training and that and is still a problem now.

### Expected behaviour

Expect it to drag the cuffed person when i use ALT + D

### Steps to reproduce

Press shift+g to tackle someone
cuff the person
press ALT+D to drag
Doesn't drag them no matter how many times i try

### Any Texture Packs? (If so list)

no

### CMG User ID

1027

**Comment by crazychris2404** [comment]
Make sure your radio PTT keybind is set to alt in your settings

**Comment by lildickie27** [comment]
So it is set to left alt for radio PTT. I changed the bind incase it was that to see if it would work and it still didnt i changed it back and it still wasnt working.

**Comment by packfile** [comment]
Error with user configuration, closed
