### ISSUE TITLE
[Bug] advanced gang licence 

### ISSUE THREAD

**Issue by Azonq** [CMGStudios/issue-tracker#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

names do not appear when set as active  

### Expected behaviour

please fix

### Steps to reproduce

press f5 
set gang as active
pin multiple people 
![image]   https://github.com/CMGStudios/issue-tracker/assets/135645251/2b60a32e-d9ed-4bec-8143-c557b4ce7960

### Any Texture Packs? (If so list)

no

### CMG User ID

1069

**Comment by packfile** [comment]
This was fixed as of a couple days ago, thanks for the report
