### ISSUE TITLE
[Bug]: Taco Seller Clock on

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you clock on as a Taco Seller in City Hall you instantly die

### Expected behaviour

Able to clock on without dying

### Steps to reproduce

1. Go to CIty Hall
2. Open Job Menu
3. Clock on as Taco Seller

### CMG User ID

71613

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report!

**Comment by packfile** [comment]
Fixed, thanks for the report
