### ISSUE TITLE
[Bug]: Lag issue with new farming job

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Where the farming job is on cayo perico, it is really laggy and causing everyone to drop FPS in that area.
It was fine before the update so it must be linked to it.

### Expected behaviour

Not to lag.

### Steps to reproduce

Go to cayo perico and visit the area where farming / lsd is.

### Any Texture Packs? (If so list)

-

### CMG User ID

205070

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report 
A fix is currently being worked on

**Comment by packfile** [comment]
Thanks for the report, this was fixed the day after
