### ISSUE TITLE
[Bug]: interior 

### ISSUE THREAD

**Issue by Azonq** [CMGStudios/issue-tracker#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

inside this building is bugged

### Expected behaviour

also the atm is floating in the air

### Steps to reproduce

go inside this garage door
https://github.com/CMGStudios/issue-tracker/assets/135645251/a68a1540-f5fa-4c20-9ed6-251252841e8e

the map location 
https://github.com/CMGStudios/issue-tracker/assets/135645251/975d5817-d0fa-4f44-9e93-1fe196ef2b33

### Any Texture Packs? (If so list)

no

### CMG User ID

1069

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report. The interior of the building is non-existent.

However, you can still use the garage and the LS customs.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
