### ISSUE TITLE
New ui (not necessarily a bug) 

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#748]
When opening your phone and pressing ESCAPE to close your phone which many do believe it or not, it opens the new ui. So whether it can be changed to not open the menu whilst upon the exiting of your phone i'm sure it would be much appreciated.

**Comment by PIKAlmao** [comment]
This is the same with exiting vehicle boots, player inventory's, house inventory's,

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
