### ISSUE TITLE
[Bug]: New UI

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you have been killed / full dead and you press ESC, THe respawn screen disappears
![image](https://github.com/CMGStudios/issue-tracker/assets/109679930/a82659e0-d5a7-4fe7-bea4-e2fab59ec629)

### Expected behaviour

After closing the new UI, The respawn screen should still be there

### Steps to reproduce

Have someone full kill you 
Press ESC
Respawn screen is gone

### Any Texture Packs? (If so list)

N/A

### CMG User ID

867

**Comment by PIKAlmao** [comment]
https://streamable.com/z3iio3

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for next restart
