### ISSUE TITLE
Koenigsegg Jesko 2020 Passenger Seat

### ISSUE THREAD

**Issue by TeaseEU** [CMGStudios/issue-tracker#75]
**Describe the issue you're facing**
My Koenigsegg Jesko 2020, the passenger rarely works, meaning that i can only have myself in the car majority of the time, it makes RP hard as i cannot have a passenger in my car.
**Steps to reproduce**
I dont really know, majority of the time when i am driving around, the bug happens and i have to get a different car out.
**Expected behaviour**
The passenger seat should work, as it is a 2 seater and works sometimes. 
**Screenshots/Video**
---
**Additional context**
Not much to say, its a simple bug that influences my ability to RP.
**Any Texture Packs (if so list)**
No textures
**Perm ID**
217839

**Comment by arthur-rl** [comment]
Please feel free to make a car report in our discord. If you cannot please comment the spawn code of the vehicle and I'll forward this to the car team.

**Comment by alfiellds** [comment]
As stated above, please contact a member of the Car Development team if you feel there is an issue with your vehicle. They can be found in the CMG Discord with the [Car Developer] tag.
