### ISSUE TITLE
[Bug]: New menu ui bug with chat

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you /hidechat then visit the new menu ui and then exit the menu it then turns chat back on.

### Expected behaviour

Shouldn't show the chat again unless you do /showchat

### Steps to reproduce

1. type /hidechat
2. enter new menu ui
3. it shows chat again and requires /hidechat again.

### Any Texture Packs? (If so list)

-

### CMG User ID

205070

**Comment by PIKAlmao** [comment]
Also if you use the tabbing through the chat mode features to hide chat, you can't use commands . (not 100% whether this has been fixed yet)

**Comment by Simonstv** [comment]
Thank you for your report, i can confirm this does happen, however thec chat box does disappear if its not active until someone types again.
This be passed on to the developers to be looked at.

**Comment by packfile** [comment]
`/hidechat` and the alike commands do not retain user preference, they are one time and are not guaranteed to be persistent. Please use the options in Settings -> UI Visibility if you wish to have absolute control and prevent code such as pause menu changing your preference
