### ISSUE TITLE
[Bug]: Chat bug

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Long time bug - since the new chat update was released.
When you are on hidden mode, you can't use any commands or do anything. It is really annoying.

### Expected behaviour

Allow commands at the very minimum

### Steps to reproduce

1. Go to hidden chat
2. Try anything with that chat and it will fail

### Any Texture Packs? (If so list)

-

### CMG User ID

205070

**Comment by packfile** [comment]
Please make a suggestion on the Discord, as this is an intentional design choice for the chat resource
