### ISSUE TITLE
[Bug]: the kill feed in organ heist is not working 

### ISSUE THREAD

**Issue by stony5** [CMGStudios/issue-tracker#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the kill feed in organ heist is not working 

### Expected behaviour

.

### Steps to reproduce

.

### CMG User ID

68457

**Comment by Simonstv** [comment]
Thank you for your report, 
I will check this myself this evening, then forward it to the developers to have a look at it once confirmed.
