### ISSUE TITLE
[Bug]: Pulling out a car

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you pull out a car it has a short period where your can get damaged or hit before it does the usual bit where you can't get hit or damaged for x amount of time. Bit of an inconvenience when you can get damaged during that short period of time.

### Expected behaviour

Shouldn't be able to get damaged till the time expires and spawns normally.

### Steps to reproduce

Pull out any car. And get someone to hit it immediately. 

### Any Texture Packs? (If so list)

-

### CMG User ID

205070

**Comment by Simonstv** [comment]
After Attempting the above, do you have any more info as i've created about 5 times and can't seem to get my car damage as you've said so if you have a clip of it happening or can reproduce on your end that would be helpful.

**Comment by ThroughAGame** [comment]
Ok I will get a clip but this has been closed for some reason?
