### ISSUE TITLE
[Bug]: Menu/Phone bug

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you press the home button (at the bottom of the phone) on the phone it now opens the new menu UI - also shows chat again (see other bug report).
Makes it hard to use the phone. 

### Expected behaviour

Press home button on the phone and do the regular phone stuff and not open the new menu ui.

### Steps to reproduce

Open the phone and press the home button.

### Any Texture Packs? (If so list)

-

### CMG User ID

205070

**Comment by Simonstv** [comment]
Thank you for your report,
I can confirm this is a valid report and will pass it on to the developers
