### ISSUE TITLE
[Bug]: Polito bay didnt render in on time and i crashed into the ocean waiting as i was running out of fuel. 

### ISSUE THREAD

**Issue by ottermad1** [CMGStudios/issue-tracker#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the airport in the middle of the ocean didnt render in on time and i crashed into the ocean waiting as i was running out of fuel. 

### Expected behaviour

should always be there and visable to land

### Steps to reproduce

simply fly over there and youll see/. 

### Any Texture Packs? (If so list)

no

### CMG User ID

378660

**Comment by 004Luke** [comment]
I believe this just an issue with your PC. When you next load in turn up your extended texture budget to possibly avoid this in the future.

**Comment by packfile** [comment]
As mentioned above, please confirm your graphics settings. Additionally, if it was your first time to the airport, it loading in would be dependent on your download speed
