### ISSUE TITLE
[Bug]: cant open map on controller

### ISSUE THREAD

**Issue by zahiirr** [CMGStudios/issue-tracker#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

since yesterday i am unable to open my map or settings on controller and a few other controller players had the same issue

### Expected behaviour

map should open from pressing start but instead nothing happens

### Steps to reproduce

press start on controller

### Any Texture Packs? (If so list)

no

### CMG User ID

213844

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, controller support will be added to the UI within the upcoming week. Please keep an eye on dev updates!
