### ISSUE TITLE
No cocaine dealer

### ISSUE THREAD

**Issue by Zedeu** [CMGStudios/issue-tracker#76]
Went to try and sell cocaine but when I got there, there was no place to sell it. Sorry if this has already been reported

**Comment by MrLexo** [comment]
This has now been fixed in the recent update: cf9d9a9 fix(trader): cocaine trader - rubbertoe98

@rubbertoe98 or @arthur-rl can now close this.

**Comment by alfiellds** [comment]
As stated above, this has been fixed in the recent commit. If this issue persists please open another bug report.

Many thanks.
