### ISSUE TITLE
[Bug]: Headbags being taken off requires another headbag

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When removing a headbag from a player you shouldnt need another headbag to do so

### Expected behaviour

Able to remove headbag without needing to have one already in inventory

### Steps to reproduce

Find a player with a headbag
Try and remove it
Requires another headbag to remove

### CMG User ID

910

**Comment by packfile** [comment]
When a player has a bag on their head, please us the radial menu:
![image](https://github.com/CMGStudios/issue-tracker/assets/97990837/c6e101ec-e325-4cf9-aa76-09981ed886eb)
