### ISSUE TITLE
[Bug]: Racing events leaving checkpoint blips

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When taking part in the races around the map such as the one at airport, when the race is finished checkpoint blips will remain on minimap until you relog

### Expected behaviour

Checkpoint blips not to show after race has finished

### Steps to reproduce

Go to a race start location
Complete race
See blips for checkpoints still on map

### CMG User ID

910

**Comment by packfile** [comment]
I completed the airport race and the blips no longer existed on the map:
![image](https://github.com/CMGStudios/issue-tracker/assets/97990837/a2b4db14-d0df-478d-9f35-c5fd8e1e487e)
Please let us know if you have any further information to add.
