### ISSUE TITLE
[Bug]: flipcar command doesnt work for trucks

### ISSUE THREAD

**Issue by zahiirr** [CMGStudios/issue-tracker#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

whenever you use the flipcar command nothing happens for trucks and it stays upside down or sidewards

### Expected behaviour

should flip

### Steps to reproduce

open chat then /flipcar

### CMG User ID

213844

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
