### ISSUE TITLE
[Bug]: LFB TOOLS ISSUES

### ISSUE THREAD

**Issue by MrMikeyTV** [CMGStudios/issue-tracker#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Tools need fixing:
Decontamination Tent - You have to spam E to turn them on. Audio of some water stays on for other people.
Rescue Cushion - It does work but people fall through the middle of it
Spreaders - Audio remains a few times after use. It's very temperamental with which doors it wants to chop off etc.
Extractor Fans - Audio is really loud when they do work, but we couldn't get it to work in-game. We had one placed at the border, it stayed there really loud until restart the other day
Fireaxe - doesn't actually break any doors

### Expected behaviour

The tools should all work and be able to be removed easily afterwards

### Steps to reproduce

Clock on LFB
Click /LFB
Go to Tools
Try to use them

### Any Texture Packs? (If so list)

NVE (they don't work on normal GTA graphics too)

### CMG User ID

604

**Comment by crazychris2404** [comment]
Confirmed thanks for the reports

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
