### ISSUE TITLE
[Bug] Farmer Job: 

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I tried to do the farmer job and requested the equipment it just flickers the icons on the map and doesnt spawn any vehicles

### Expected behaviour

When you press request equipment for it to actually spawn

### Steps to reproduce

1. Clock on famer
2. Request equipment
3. Suffer

### Any Texture Packs? (If so list)

None

### CMG User ID

14009

**Comment by packfile** [comment]
Thanks for the report, this was fixed as of the latest restart
