### ISSUE TITLE
[Bug]: Paleto bay airport not spawning

### ISSUE THREAD

**Issue by DingleWarrior** [CMGStudios/issue-tracker#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I've seen a similar report to this with a response claiming it's the user's graphic issues, I can confirm it's not. I currently use a 1080ti and all my settings are maxed out and yet I still have the issue where either the island doesn't spawn in OR the island does spawn but the plane goes straight through the ground and lands into the sea underneath killing you. I believe this issue is only rising up now as more people have decided to take on the pilot job compared to the past few years and this is why this issue has been relatively unnoticed. My suggested fix (which is also in suggestions) is to simply get rid of the island whose only sole use is the pilot job and nothing else (wasted land) and to simply replace it with the Cayo airstrip. On top of this if what your claiming the problem is the user's GPU then surely Cayo would be a better option for this issue also as personally that looks like you're saying you cant do the pilot job unless you have a high-tier GPU which let's face it probably a decent 75% of the server does not have where as cayo loads in much better regardless of GPU settings.

### Expected behaviour

The island should spawn flawlessly without falling through upon landing

### Steps to reproduce

fly to island max settings

### Any Texture Packs? (If so list)

n/a

### CMG User ID

208

**Comment by packfile** [comment]
Thanks for the report, this airport has since been removed
