### ISSUE TITLE
[Bug]After i brought advanced gang licence, i can pull out money from my gang funds, when im the owner : 

### ISSUE THREAD

**Issue by MrNewton5785** [CMGStudios/issue-tracker#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

hen i brought advanced gang licence it doesn't let me pull out money from my gang funds and tells me ''this amount exceeds the maximum daily withdrawal amount from your account'' and doesn't even let me take out any money at all, i have all of the security settings set to ''No'' which i have been told by admins and other people with the licence to do,

here is a clip https://youtu.be/h3fuK5PclTA

### Expected behaviour

not being able to take any money from my gang funds

### Steps to reproduce

1. click F5
2. press gang funds
3. try and withdraw any amount 

### CMG User ID

973

**Comment by packfile** [comment]
Please increase the "Maximum withdraw amount per member" field to be greater than £0
