### ISSUE TITLE
[Bug]: CMG Statistic Menu

### ISSUE THREAD

**Issue by Macccc1** [CMGStudios/issue-tracker#768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The whole menu is bugged every time i click on "Civilian" the menu disappears and there is 1 of the same player on every page you also cant change for "This Month" to "All Time".

### Expected behaviour

The whole menu is bugged every time i click on "Civilian" the menu disappears and there is 1 of the same player on every page you also cant change for "This Month" to "All Time".

### Steps to reproduce

https://www.youtube.com/watch?v=aPjwI-T3r-M

### Any Texture Packs? (If so list)

Reshade and NVE Files

### CMG User ID

741

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report.

Steps To Reproduce:

1. Press F9 to pull up the CMG Statistics menu
2. Click onto Civillian
3. This page will not load and you will not be able to reopen the CMG Statistics unless you relog.

Other Issues:

1. Trader Page: Displays £NaN on all sections other than "Rank" and "Name"
2. Police Page: Displays false "Arrests" and "Searches"
3. NHS Page: Displays that everyone has done "10 Revives" and "100 Bodybagged"
4. Button to change between "This Month" and "All Time" does not change the results

**Comment by packfile** [comment]
I believe this has been fixed since the latest restart, if not please reopen.
