### ISSUE TITLE
[Bug]: My player is not visible and other players aint aswell also cant load in cars 

### ISSUE THREAD

**Issue by FC19051** [CMGStudios/issue-tracker#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My player wont load in other players wont aswell cant spawn in cars and i fall through the map aswell

### Expected behaviour

My player wont load in other players wont aswell cant spawn in cars and i fall through the map aswell

### Steps to reproduce

n/a

### Any Texture Packs? (If so list)

none

### CMG User ID

330295

**Comment by PIKAlmao** [comment]
This is not a bug, this happens client sided depending on your pc specs, to fix falling through the map i suggest doing this.

turn all of your settings to the lowest, or off. Then have extended texture budget up 50-70% or as much as you need to till your game renders correctly
(if you're stuck under the map at this current time, do /unstuck or /reset, if neither work do /calladmin and wait)

And with your character being invisible, do /calladmin, ask then to pick you up then drop you again.

**Comment by Simonstv** [comment]
This ticket will be closed due to it being a user setting error rather than bug
