### ISSUE TITLE
Fines

### ISSUE THREAD

**Issue by c-yber** [CMGStudios/issue-tracker#77]
The bug is when I'm driving my bike and going towards paleto atm I sometimes get fined 12k or 30k but my mate screenshared and that never happened to him no matter what he drove
![image](https://user-images.githubusercontent.com/87503886/125868349-e44b3a92-5a94-4955-9b2d-75469aada248.png)

perm id is 1098

**Comment by arthur-rl** [comment]
Intended feature. Not a bug.
