### ISSUE TITLE
300kg boat boot not acessible 

### ISSUE THREAD

**Issue by jake896896** [CMGStudios/issue-tracker#771]
i bought the 300kg boat from the boat shop, it will not let get into the boot i have had admins look at the issue and they said to make a bug report about it and it will get fixed. please could you fix it

**Comment by packfile** [comment]
Could you please confirm what boat you are referring to, and/or provide your Perm ID so we can find it for you?

**Comment by jake896896** [comment]
Now then mate the name of the boat is the; Tug
And my id is; 375729

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jake896896** [comment]
Also Tom I don’t no if you do anything for jobs in the game but I like to fish on it and I have been doing it a couple of days now and I never caught shark even using the best bait. I was wondering if it could be changed to a levelling system like trucking or the odds of catching stuff be changed. If not no worries just thought I would ask. Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jake896896** [comment]
boat name tug
id; 375729

**Comment by crazychris2404** [comment]
Forwarded to car devs

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
