### ISSUE TITLE
[Bug]: logging off in clothes and when re logging im in a different outfit that i wore a couple of weeks ago this has been happening for a couple weeks now

### ISSUE THREAD

**Issue by roryyyyyyy** [CMGStudios/issue-tracker#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i log off in an outfit then log on the next day and im in a different fit i logged off in sometimes i log off in an npc outfit and instantly die 

### Expected behaviour

able to log off and log on in the same clothes 

### Steps to reproduce

?

### Any Texture Packs? (If so list)

no

### CMG User ID

242599

**Comment by packfile** [comment]
Can you delete the `kvs` folder @ `C:\Users\[USERNAME]\AppData\Roaming\CitizenFX\kvs` aka `%appdata%/CitizenFX/kvs` and see if this resolves the issue?

**Comment by roryyyyyyy** [comment]
> Can you delete the `kvs` folder @ `C:\Users\[USERNAME]\AppData\Roaming\CitizenFX\kvs` aka `%appdata%/CitizenFX/kvs` and see if this resolves the issue?

didnt work spawning in full dead as a janitor with a 5 minute timer
