### ISSUE TITLE
[Bug]: bug pd job

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When switching rank on pd to another division(NPAS) from your normal rank, it acts as you clocked off but you are still clocked on in "home" menu

### Expected behaviour

You should be able to switch ranks without going unemployed, was like this before 

### Steps to reproduce

https://medal.tv/games/gta-v/clips/1qRLDBYzCSZX-V/d133705nFLo5?invite=cr-MSxMaHcsNDE3Mzg1MDgs 

### CMG User ID

9975

**Comment by packfile** [comment]
Ah, thanks, this will be fixed soon

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
