### ISSUE TITLE
[Bug]: Pilot job where fuel is too quick and marcus's voice is really annoying

### ISSUE THREAD

**Issue by NBKdev** [CMGStudios/issue-tracker#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

You cannot repair you plane when u go to the repair marker. 
fuel goes too quick which you have to fuel up every 2/3 runs 
pressing enter so many times which is pretty annoying

### Expected behaviour

Above

### Steps to reproduce

a command to disable marcus's voice
Add a longer or a better fuel system or able to buy jerry can and exit the plane to fill up (but increase the seconds when leaving the plane)
Pressing enter should be a tutorial to new players up to level 5 so we don't need to press enter every 10 times per a run 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

22

**Comment by packfile** [comment]
GitHub is for actionable issues, this is a feature request, so please put it through on Discord.
Side note: I believe the voice is Deviations, not Marcus
