### ISSUE TITLE
[Bug]: Sandy PD MLO Invisible 

### ISSUE THREAD

**Issue by Macccc1** [CMGStudios/issue-tracker#775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Every time you go down the the holing cells in sandy PD the whole MLO goes invisible no matter what if you try and /reset its still invisible

### Expected behaviour

Every time you go down the the holing cells in sandy PD the whole MLO goes invisible no matter what if you try and /reset its still invisible

### Steps to reproduce

https://cdn.discordapp.com/attachments/880964002690248755/1145189035665531052/image.png

### Any Texture Packs? (If so list)

Reshade and NVE Files

### CMG User ID

741

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
(This is downstairs only and based on camera position)

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
