### ISSUE TITLE
[Bug]: Ammo/Weapons in organ

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I came into organ with a NATO ar and a double barrel shotgun, I have stored all weapons but havent received the 12 gauge pellets back

### Expected behaviour

I receive all my ammo back when doing /storeallweapons

### Steps to reproduce

Go into organ with 2 or more weapons with full ammo
Store the pistol to start
equip all weapons
do /storeallweapons again
Was missing all the 12 gauge pellets

(Dont have proof because my clips died)

### Any Texture Packs? (If so list)

N/A

### CMG User ID

867

**Comment by Simonstv** [comment]
More information gathered on this https://www.youtube.com/watch?v=ALzVkJbRXAw this will be passed onto the dev team.

**Comment by packfile** [comment]
Thanks for the report! This has been fixed for the next scheduled restart
