### ISSUE TITLE
[Bug]: House not working Interior is bad

### ISSUE THREAD

**Issue by StuartStuartt** [CMGStudios/issue-tracker#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have just bought this house and the interior doest work. I cant walk anywhere inside the property Mirror Park house 10

### Expected behaviour

Being able to walk around in my house I bought

### Steps to reproduce

Walk into the house and you'll see you cant get inside

### Any Texture Packs? (If so list)

N/A

### CMG User ID

309346

**Comment by packfile** [comment]
Please refer to the previous issues at #719, #685 and #657
