### ISSUE TITLE
HMP Roof

### ISSUE THREAD

**Issue by Keegasity** [CMGStudios/issue-tracker#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you go to the roof of HMP directly above the main entrance into the cells, you will be able to walk through the roof and fall into the cells 

Reported Internally By Trauma

https://www.youtube.com/watch?v=cA9nuXcjVgg&ab_channel=SyFenn - 50 Seconds onwards

### Expected behaviour

Fall through the roof of HMP into the cells below

### Steps to reproduce

1. Land on the roof or find your way to the roof of HMP
2. Head to the main entrance of HMP on the roof
3. Where the roof goes higher, walk directly into this point
4. You will fall into the cells directly below

### CMG User ID

116867

**Comment by Keegasity** [comment]
Confirmed.

Thank you for the report!

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
