### ISSUE TITLE
[Bug]: Dispute Menu

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was in LSD South earlier and died to someone who broke a rule, After I respawned I attempted to contact him with the dispute menu. However, the person who killed me wasn't popping up on the dispute menu. It doesn't happen 100% of the time  Just happens every now and then

### Expected behaviour

The people who damage you to pop up on the dispute menu

### Steps to reproduce

Die to someone
Check the dispute menu
Name of the person who damaged you may not be there
(not 100% chance)

### Any Texture Packs? (If so list)

N/A

### CMG User ID

867

**Comment by crazychris2404** [comment]
This usually occurs if the other player isn’t registered for killing you will leave here for further investigation

**Comment by packfile** [comment]
Given this is fairly infrequent and can't be reproduced the issue will be closed for now
