### ISSUE TITLE
Sport wheels 140 crash game

### ISSUE THREAD

**Issue by JohnnyMush** [CMGStudios/issue-tracker#78]
**Describe the issue you're facing**

When I go over sport wheels 140 in LSC my game crashes.

**Steps to reproduce**

Go into any LSC
Go to the sports wheels
Go to wheels 140
Game crashes

**Expected behaviour**

Game stutters and then crashes like 10 seconds later.

**Screenshots/Video**

https://streamable.com/qmvcmf
https://media.discordapp.net/attachments/696045038106312832/865638902139715614/unknown.png

**Additional context**

**Any Texture Packs (if so list)**

NVE

**Perm ID**

279

**Comment by arthur-rl** [comment]
What's the spawn code of the vehicle you tried this with?

**Comment by JohnnyMush** [comment]
> What's the spawn code of the vehicle you tried this with?

It happens with every car in my garage.

**Comment by arthur-rl** [comment]
Can you try without NVE on? Sport wheels 140 work for me without crashing. 

![img](https://thenames.bond/p8tnbjLw)

**Comment by alfiellds** [comment]
Please reply with the information requested above so that the developers can look into this issue further - @JohnnyMush.

**Comment by alfiellds** [comment]
Hello, I will be closing this issue due to being unable to be reproduced by developers and no response within 96 hours. If the issue persists please open another bug report.

Many thanks.
