### ISSUE TITLE
[Bug]: Accessing Vehicle Menu Whilst Cuffed

### ISSUE THREAD

**Issue by Keegasity** [CMGStudios/issue-tracker#780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Following the reason change to the vehicle menu, you can now press M and switch to the driver seat whilst cuffed.

https://youtu.be/zs6FgyhXoZw

Reported internally by Jay

### Expected behaviour

Press M and change to the drivers seat whilst cuffed, this allows you to drive away from the scene

### Steps to reproduce

1. Get handcuffed and put in the back of a vehicle
2. Wait for the Officer to jump out of the driver seat
3. Press M and switch to the driver seat

### CMG User ID

116867

**Comment by Keegasity** [comment]
Confirmed.

**Comment by packfile** [comment]
Thanks, this has been fixed
