### ISSUE TITLE
[Bug]: NHS/HEMS Clock on bug

### ISSUE THREAD

**Issue by JakeBrown03** [CMGStudios/issue-tracker#781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when switching from any NHS rank to HEMS or vies versa you lose access to the call manager and can no longer use the NHS menu to revive someone as it just does the normal CPR action.

### Expected behaviour

to be able to CPR and use call manager

### Steps to reproduce

Be clocked on as any NHS Rank then switch to HEMS
Then try access the call manager or CPR someone

### Any Texture Packs? (If so list)

no

### CMG User ID

289670

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
