### ISSUE TITLE
[Bug]: woke up today and cant join the server says "failed to handshake to server"

### ISSUE THREAD

**Issue by omar8228** [CMGStudios/issue-tracker#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/CMGStudios/issue-tracker/assets/140748157/73e43a3e-0ee6-43d9-8a71-b00ec58ed2e7)

### Expected behaviour

cant join the server check the image

### Steps to reproduce

i just cant join the server

### CMG User ID

dont remember

**Comment by PIKAlmao** [comment]
This is not a bug. This is most likely a client sided issue due to a poor internet connection, i may be wrong though. (Definitely not a bug though)

**Comment by omar8228** [comment]
> This is not a bug. This is most likely a client sided issue due to a poor internet connection, i may be wrong though. (Definitely not a bug though)

so its my internet?

**Comment by PIKAlmao** [comment]
I would like to think so, only person who i've seen complain about it today.

**Comment by omar8228** [comment]
> I would like to think so, only person who i've seen complain about it today.

what do you reccomend me to do then wait till my internet is good or can i do something about it or do i just wait it out?

**Comment by PIKAlmao** [comment]
Try reset your internet, and see if that does anything. If you have a dynamic ip then force change it. (Dm me on discord so we're not flooding the #bug-tracker channel on the discord) **PIKA / Td5.**
