### ISSUE TITLE
[Bug]: F9 menu not working

### ISSUE THREAD

**Issue by rashh1** [CMGStudios/issue-tracker#784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i press f9 to bring up the stats and the row at the top takes up the whole area when on the monthly section (image attatched)
![Screenshot 2023-09-02 000609](https://github.com/CMGStudios/issue-tracker/assets/143850658/7b5cb0a6-928e-494c-b2d6-710e38cb5f75)

### Expected behaviour

^

### Steps to reproduce

press f9 
make sure youre on monthly

### Any Texture Packs? (If so list)

NVE but tried without

### CMG User ID

1301

**Comment by Keegasity** [comment]
This bug has now be resolved.
