### ISSUE TITLE
[Bug]: DJ MENU 

### ISSUE THREAD

**Issue by M9RGYT** [CMGStudios/issue-tracker#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

cuts first like 20 seconds off all songs 

### Expected behaviour

DJ MENU BROKEN 

### Steps to reproduce

T/DJMENU
SELECT SONG
SONG BROKEN CAUSE DJ MENU BROKEN

### CMG User ID

220815

**Comment by Keegasity** [comment]
Cannot replicate this, please can you provide a clip of this happening.

**Comment by packfile** [comment]
As above, this can't be reproduced. Please provide steps to cause this issue to happen
