### ISSUE TITLE
[Bug]: Pet Spawning

### ISSUE THREAD

**Issue by Keegasity** [CMGStudios/issue-tracker#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to spawn a pet purchased from the pet shop, it does not spawn in. This happens with the following pets:

- Westie
- Duck
- Greyhound
- Husky

I believe this will occur with all pets.

Video - https://youtu.be/g9pXiumAg_o

### Expected behaviour

Spawn a pet and it will disappear, teleport a pet and it will not arrive

### Steps to reproduce

1. Purchase a pet
2. Try to spawn the pet
3. Try to teleport the pet to yourself
4. No pet will arrive

### Any Texture Packs? (If so list)

NVE

### CMG User ID

116867

**Comment by Simonstv** [comment]
Confirmed Issue, Animals seem to be disappearing when you "Spawn Name" in.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
