### ISSUE TITLE
[Bug]: Weapon Doesn't spawn when buying (Tom Issue)

### ISSUE THREAD

**Issue by NBKdev** [CMGStudios/issue-tracker#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Going to large arms 
select HK417
when i buy it nothing on wheel or back or storeallweapons etc

I have clip if needed

### Expected behaviour

Going to large arms 
select HK417
when i buy it nothing on wheel or back or storeallweapons etc

I have clip if needed

### Steps to reproduce

Gotta find my guns somewhere in the files 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

22

**Comment by packfile** [comment]
Confirmed, this will be fixed in the next pass of reports.

**Comment by packfile** [comment]
This has been fixed, though it may take a week or two to come in. Please keep an eye on dev updates as it will be posted in there when in
