### ISSUE TITLE
[Bug]: Can't Repair Plane for pilot job

### ISSUE THREAD

**Issue by NBKdev** [CMGStudios/issue-tracker#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Go to marker press E and wait a min or 2 till it's ready and it doesn't actually repair 

### Expected behaviour

Go to marker press E and wait a min or 2 till it's ready and it doesn't actually repair 

### Steps to reproduce

Make it repair 

### CMG User ID

22

**Comment by Simonstv** [comment]
Confirmed Issue.
Relating to this Issue when you drive into the Repair Area, and press Repair
Steps should be plane is fixed and flyable / workable
However Attempting this i was still missing half a wing, and could not fly so it is reproducible.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
