### ISSUE TITLE
[Bug]: House Sharing 

### ISSUE THREAD

**Issue by Hiitmon** [CMGStudios/issue-tracker#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My friend just bought a house (Sea View 1), he's shared the keys out to our friends and me using the correct ID's and they can all get in the house fine no issues. 

However I can't get access, the same building for me is listed as Sea View 5, I try ringing the bell to enter but it says the owner is not online despite him being next to me. An admin confirmed that for him the property also has a different name. 

We waited for a restart in case it was just a bug but we're still having the issue. We've triple checked that they've put the correct ID for me. 

Cheers.

### Expected behaviour

To be able to enter the house and that it's the same address.

### Steps to reproduce

1. Walk up to door with green arrow, it'll either say Sea View 1 or Sea View 5.
2. See that when you ring the bell the owner is offline when he's next to me 

### CMG User ID

376651

**Comment by packfile** [comment]
It seems these houses were (mistakenly) added on top of each other. They've now been separated, and Sea View 5 is moved to a vacant house down the road
