### ISSUE TITLE
brabus in coupes is glitched and charges you money but doesnt go to your garage

### ISSUE THREAD

**Issue by ch4z4s** [CMGStudios/issue-tracker#79]
**Describe the issue you're facing**

**Steps to reproduce**

**Expected behaviour**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**

**Comment by ch4z4s** [comment]
its in my garage in the command of !getcars with my permid but it cost me 90k and it hasnt actually showed up

**Comment by alfiellds** [comment]
Hello, can you please provide your perm ID and confirm whether you have the "Premium" rank from https://store.cmgforums.com/category/ranks?

**Comment by alfiellds** [comment]
Hello, this will be closed due to a lack of response. Please open another report if the issue persists.

Many thanks.
