### ISSUE TITLE
[Tattoo shop isn't working]: 

### ISSUE THREAD

**Issue by Gooobie** [CMGStudios/issue-tracker#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, the tattoo shop isn't working When you go to buy tattoos you need to have the money in cash, and when you spend the money on tattoos it just doesn't work and resets it when you leave

### Expected behaviour

when you buy a tattoo it stays on you're body 

### Steps to reproduce

Go to the tattoo parlor 
buy a tattoo 
Leave with bought tattoo 
then it removes the tattoo once stepping out of the shop

### Any Texture Packs? (If so list)

no

### CMG User ID

168410

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
