### ISSUE TITLE
[Bug]: NHS Bodybag bug

### ISSUE THREAD

**Issue by Plextay** [CMGStudios/issue-tracker#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sometimes when you die and get bodybagged you can't respawn and there's  nothing you can do apart from relog and then you have to wait for the respawn again, and hope it doesn't happen again

### Expected behaviour

Sometimes when you die and get bodybagged you can't respawn and there's  nothing you can do apart from relog and then you have to wait for the respawn again, and hope it doesn't happen again

### Steps to reproduce

Be bodybagged and try to respawn

### CMG User ID

12855

**Comment by packfile** [comment]
Can you elaborate on what you mean by "can't respawn"? i.e.
- Death screen UI doesn't show
- Pressing E doesn't do anything
- Pressing spawn button doesn't do anything
- etc.

**Comment by Plextay** [comment]
the death screen ui shows up, and then when the timer goes to zero, you press E, and then the death screen disappears, and then nothing happens, there's no UI and you can just see where you died

**Comment by packfile** [comment]
Our bug managers have investigated this report, and can't reproduce it locally; there is no connection between being body bagged and respawning either, so this is likely the result of something else. Please reopen if you able to find steps that reliably cause this to happen!
