### ISSUE TITLE
AA tow truck hook does more damage then good

### ISSUE THREAD

**Issue by FIoofBoi** [CMGStudios/issue-tracker#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

So the tow vehicle feature on AA trucks is no good, the hook is to close to the truck and makes both the truck the the towed vehicle freak out and push the truck forward, flipping it, crashing it into things, overall causes more damage then to simply move a broken vehicle 

### Expected behaviour

The hook should grab the desired vehicle and attach to the front or back depending on which half of the vehicle it was placed on, and allow the AA member to move it safely somewhere else like the vanilla gta tow truck does

### Steps to reproduce

Tow a vehicle with the aa towtruck and try to drive with it

### CMG User ID

384099

**Comment by packfile** [comment]
Closing the issue for now, I believe this vehicle is going to be replaced soon with a more realistic counterpart (another flatbed). Thank you for the report!
