### ISSUE TITLE
[Bug]: Pilot job xp visual glitch 

### ISSUE THREAD

**Issue by NBKdev** [CMGStudios/issue-tracker#793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When landing and gathering xp u get a bunch of numbers
![image](https://github.com/CMGStudios/issue-tracker/assets/75136375/c7f1728f-477b-4fcb-8d34-ccb13bea58e2)

### Expected behaviour

When landing and gathering xp u get a bunch of numbers
![image](https://github.com/CMGStudios/issue-tracker/assets/75136375/c7f1728f-477b-4fcb-8d34-ccb13bea58e2)

### Steps to reproduce

use to show like 23000/ 40000xp 

now it's like 100000000/40000xp

### CMG User ID

22

**Comment by NBKdev** [comment]
Further note you can't level up

**Comment by packfile** [comment]
Thanks, this has been fixed since the latest restart
