### ISSUE TITLE
[Bug]: Link Twitter 500k reward

### ISSUE THREAD

**Issue by Dawoud-18022640** [CMGStudios/issue-tracker#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Twitter link follow is not working as the Twitter page isn’t loading when the command is triggered. The help page also indicates it isn’t working 

### Expected behaviour

Open Twitter link but it fails to load 

### Steps to reproduce

https://wiki.cmgstudios.net/start-here/linking-your-twitter

### CMG User ID

N/A

**Comment by crazychris2404** [comment]
This is a ongoing issue due to twitter api being rate limited please just try early in the day as there is nothing we are able to do
