### ISSUE TITLE
[Bug]: Trucking XP Level Bugged

### ISSUE THREAD

**Issue by Simonstv** [CMGStudios/issue-tracker#795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the XP display for trucking at the top of your screen it is saying an overall number which is related to the level xp you should be getting or lower.

for example it is saying 118271375/30500 and the bar is all blue as well

### Expected behaviour

Expected is to say say 11500/30500
With the XP Bar gain a blue percentage

### Steps to reproduce

Clocking on Trucking
Start Job
Deliver Trailer 
Get XP / Money

https://cdn.discordapp.com/attachments/892435088430727198/1149306442449432656/image.png

### Any Texture Packs? (If so list)

Nope

### CMG User ID

1193

**Comment by packfile** [comment]
Thanks, this has been fixed since the latest restart
