### ISSUE TITLE
lvl glitch on lorry[Bug]: 

### ISSUE THREAD

**Issue by nelgupp** [CMGStudios/issue-tracker#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my lorry lvl xp is on like 1822312468 and i cant lvl up When the XP display for trucking at the top of your screen it is saying an overall number which is related to the level xp you should be getting or lower.

for example it is saying 118271375/30500 and the bar is all blue as well

### Expected behaviour

the blue thing on the lorry i cant lvl up

### Steps to reproduce

nope

### Any Texture Packs? (If so list)

nope

### CMG User ID

368566

**Comment by packfile** [comment]
Thanks, this has been fixed since the latest restart
