### ISSUE TITLE
[Bug]: NEW BANK ROBBERIES 

### ISSUE THREAD

**Issue by XH41DERX** [CMGStudios/issue-tracker#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i do the new small bank robberies i often dont get money or anything from the drilling thing

### Expected behaviour

bank doesnt give me anything

### Steps to reproduce

.

### Any Texture Packs? (If so list)

no

### CMG User ID

310481

**Comment by Simonstv** [comment]
Can you provide anymore context to this with a clip of the situation so we can look at it more in depth if not then it is kind of difficult.
