### ISSUE TITLE
[Bug]: GWAGON DOORS

### ISSUE THREAD

**Issue by Raslingden** [CMGStudios/issue-tracker#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The doors dont open close properly on the g wagon on other people screens there is no doors on mine they are half open
![Screenshot 2023-09-08 001334](https://github.com/CMGStudios/issue-tracker/assets/144398169/5c93c9d0-8a28-4cad-a1b6-a09cbee389a4)

### Expected behaviour

Doors to work correctly i chose this VIP car and its very very buggy

### Steps to reproduce

N/A

### CMG User ID

380476

**Comment by crazychris2404** [comment]
Sadly this is a model issue meaning nothing can be done
