### ISSUE TITLE
[Bug]: ISO Opulence

### ISSUE THREAD

**Issue by KrissWithAK** [CMGStudios/issue-tracker#799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the gun doesn't pull out when pulled out. but you can see it in the inventory when you store. also u can see it on the side. if need clip dm me kris#4439 or https://medal.tv/games/gta-v/clips/1sa6mpNqb8eZbQ/d1337Pc9QGEq?invite=cr-MSxYMGosMTk4NjA3MDg4LA

### Expected behaviour

explained above 

### Steps to reproduce

explained above 

### Any Texture Packs? (If so list)

no

### CMG User ID

126834

**Comment by crazychris2404** [comment]
@packfile will look into this

**Comment by packfile** [comment]
This has been fixed, though it may take a week or two to come in. Please keep an eye on dev updates as it will be posted in there when in
