### ISSUE TITLE
Phone broken

### ISSUE THREAD

**Issue by Denzzzz** [CMGStudios/issue-tracker#80]
**Describe the issue you're facing**
I have an American phone number and is written differently 
**Steps to reproduce**
Needs resetting properly 
**Expected behaviour**

**Screenshots/Video**
Below 
**Additional context**
Already tried factory resetting 3x
**Any Texture Packs (if so list)**
N/a 
**Perm ID**
177964 
![image](https://user-images.githubusercontent.com/87096283/126075982-39b8ac08-d565-44e8-80c6-ed4a26d0dcc7.jpg)

**Comment by alfiellds** [comment]
Hello, thank you for the report, I will forward this to the developers to be reviewed.

**Comment by alfiellds** [comment]
Fixed -- your number should be automatically regenerated on your next login.
