### ISSUE TITLE
[Bug]: My Pd guns are brkkr

### ISSUE THREAD

**Issue by OG-SPLINTER** [CMGStudios/issue-tracker#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

acw-r 1/1
arx 1/1
Haymaker  1/1
sig saue mxp 1/1 all not spawning in. Made a ticket and Ash has spoken to Tom to fix

### Expected behaviour

Showing up in armoury but not loading/ spawning in game

### Steps to reproduce

Check guns can spawn in if not redownload them 

### Any Texture Packs? (If so list)

N/a

### CMG User ID

2725

**Comment by crazychris2404** [comment]
@packfile will look into this

**Comment by packfile** [comment]
This has been fixed, though it may take a week or two to come in. Please keep an eye on dev updates as it will be posted in there when in
