### ISSUE TITLE
[Bug]: mlo /djmenu not working properly

### ISSUE THREAD

**Issue by SJ-XD** [CMGStudios/issue-tracker#801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

as the video shows the volume dose not change not only in the menu eaven in f2 menu nothing can lower the volume of a mlo dj set and sometimes the music dose not end or stop when you press stop music or when you end the music session

### Expected behaviour

volume not changing and music not stopping 

### Steps to reproduce

https://youtu.be/lp_1zlTjpCs

### Any Texture Packs? (If so list)

no 

### CMG User ID

1133

**Comment by Simonstv** [comment]
Can confirm this is an Issue and is reproducible,
This could be all Gang Buildings which have the DJ Speaker System,
Issue seems to be the functions are not responding at all including volume adjustments as well.
This will be past on to the Dev Team to be sorted

**Comment by packfile** [comment]
Thanks for the report! This has been fixed for the next scheduled restart
