### ISSUE TITLE
[Bug]: insert taser

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you drystun someone with a taser (Using insert when holding it next to someone) you are unable to cuff them

### Expected behaviour

1. Drystun someone
2. Cuff them
3. it actually cuffs

### Steps to reproduce

1. Drystun
2. try to cuff

### CMG User ID

14009

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report! This has been fixed for the next scheduled restart
