### ISSUE TITLE
[Bug]: CMG Statistics Menu - still bugged

### ISSUE THREAD

**Issue by Macccc1** [CMGStudios/issue-tracker#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I press F9 to open the menu it show all the stats but doesn't download the status. I belive that the menu was fixed but then still was broken

### Expected behaviour

I press F9 to open the menu it show all the stats but doesn't download the status. I belive that the menu was fixed but then still was broken

### Steps to reproduce

Clicking Civilian ect turns the UI invisible
Re-add the files and see if that fixes it
Not sure what else is bugged other than the downloading statistics  

### Any Texture Packs? (If so list)

Reshade and NVE Files

### CMG User ID

741

**Comment by Simonstv** [comment]
Thanks for the Report, I'll pass this onto the Dev Team.
After testing the above, and reproducing the same steps myself, upon clicking civilian on the statistics menu, it bugs out and closes however a cursor stays on your screen until you press the same key to close it again, upon pressing the statistic menu key again it doesn't appear, and you see the cursor again as a result. 

On top of this when you press ESC the UI doesnt appear as well so have to F8 quit to regain your UI back.

**Comment by packfile** [comment]
Thanks for the report! This has been fixed for the next scheduled restart
