### ISSUE TITLE
[Bug]: Police Glock FPV

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whilst in First Person View you are unable to aim and fire the Police Glock (Unsure if it is all Pistols)

### Expected behaviour

Able to Aim and Fire Pistols like normal

### Steps to reproduce

1. Clock on as Police
2. Retrieve a Glock
3. Toggle FPV by pressing V
4. Try aiming and Firing

### CMG User ID

71613

**Comment by PIKAlmao** [comment]
Just had two officers test this, and it seems to be fine for them.

**Comment by zenabzz** [comment]
> Just had two officers test this, and it seems to be fine for them.

See Uploaded Video for reference
https://streamable.com/3twqkl

**Comment by packfile** [comment]
Thanks for the report and video! This will be fixed in the next weapon pass.

**Comment by packfile** [comment]
This has been fixed, though it may take a week or two to come in. Please keep an eye on dev updates as it will be posted in there when in

**Comment by zenabzz** [comment]
This issue is still present

**Comment by packfile** [comment]
> This issue is still present

Correct, the dev update has not been posted yet. Due to a limit we're unable to merge the commit yet.
