### ISSUE TITLE
[Bug]: Explosive containers respawning too quickly. 

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#805]
Not sure whether this is an issue that happens 100% of the time, but i've had it happen to me yesterday and today, and another person has just complained about it https://discord.com/channels/458382797103693867/458757577577070602/1150383360003289118 (he doesn't have the best clip, still just looking for mine now)

**Comment by Simonstv** [comment]
Please could you get us more context to what you mean by "Explosive Containers", or provide a video as i'm not able to open the above link.

**Comment by PIKAlmao** [comment]
Tom's already aware and is most likely being looked into.

**Comment by crazychris2404** [comment]
Confirmed
This is being investigated by developers

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart!
