### ISSUE TITLE
[Bug]: bank heist

### ISSUE THREAD

**Issue by slashhhhhh** [CMGStudios/issue-tracker#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://medal.tv/games/gta-v/clips/1tziiNNSmEY8jL/d1337AGkrtyz?invite=cr-MSxCdlQsMTcwMzUxODcyLA

lost over 3 mil trying to do the bank heist set up and not getting past the first one for the cctv and despite trying with other people it just seems to be stuck on the cctv 

### Expected behaviour

lost over 3 mil trying to do the bank heist set up and not getting past the first one for the cctv and despite trying with other people it just seems to be stuck on the cctv 

### Steps to reproduce

try doing the heist set up and seeing if this works?

### CMG User ID

332930

**Comment by packfile** [comment]
Resolved in DMs
