### ISSUE TITLE
[Bug]: Farmer job

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When your supposed to get a grain trailer it doesn't spawn one

### Expected behaviour

When you finish with the rake for it to spawn a grain trailer

### Steps to reproduce

1. Rake a field
2. Suffer

### CMG User ID

14009

**Comment by packfile** [comment]
Thanks for the report. Could you please confirm the following:
1. You are returning back to the start and pressing "Request Equipment"
2. Does the grain trailer show temporarily? (i.e. for under second)
3. If no to the above, does an additional tractor spawn?

**Comment by wooffighter** [comment]
The game doesn't explain you must request it again. it tells you to unhook the rake, then tells you to pick up your equipment at the warehouse. Which I see as pick something up that has been put there. never explains that you need to request equipment. WHen you request equipment it spawns both a tractor and the trailer. same happens when going to a new field btw with the rake

So its either a bug or incorrectly explained

**Comment by packfile** [comment]
Thanks for the feedback, we will look to make this process more clear to the end user
(Leaving the issue open as this will be sorted in the next bug fix pass)

**Comment by packfile** [comment]
Thanks for the report, this has been amended
