### ISSUE TITLE
[Bug]: Truck Fuel

### ISSUE THREAD

**Issue by zahiirr** [CMGStudios/issue-tracker#808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When u fill out a full tank of petrol in a lorry it drops to 65% instantly as soon as u start driving and its so annoying cuz u have to refill again and again 

### Expected behaviour

petrol shouldnt drop by 35% instantly

### Steps to reproduce

fill petrol and drive for 10s

### Any Texture Packs? (If so list)

no

### CMG User ID

213844

**Comment by Simonstv** [comment]
Hello, i've just tried it on a couple of trucks could you tell me which truck this is or do you have more context like a clip or something?

**Comment by zahiirr** [comment]
it happens to me on the mercedes azcros blue truck but im not sure what causes it. I dont have a clip at the moment but i can get one later when im on if you still cant see the problem.

**Comment by packfile** [comment]
This does not appear to reproduce on the Mercedes Azcros reported, if you can please provide a clip of this happening and then reopen the issue
