### ISSUE TITLE
[Bug]: gun dissapering in 200kg truck

### ISSUE THREAD

**Issue by Dylbo77** [CMGStudios/issue-tracker#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

guns just randomly dissapear from the truck

### Expected behaviour

,

### Steps to reproduce

,

### CMG User ID

258613

**Comment by crazychris2404** [comment]
Do you have any clip of this?

**Comment by packfile** [comment]
A few of your vehicles have been lock picked recently, so it's likely you left the vehicle out and other player(s) stole the items out the boot. If you believe this is a different issue then please provide the requested clip or include reproduction steps for us to investigate. This is the only report we've had, so I suspect it is the former
