### ISSUE TITLE
The y flex muscle won’t let me change anything 

### ISSUE THREAD

**Issue by RaabHtid** [CMGStudios/issue-tracker#81]
Anytime I try and take clothes off flexing the y muscle it don’t work I have to type it in nothing happens it’s frozen won’t let me click on anything on there I’ve reset fivem cleared everything hasn’t worked since I reported it ages ago

Can get video if needed

**Any Texture Packs (if so list)** no night shadows clouds but it didn’t work before I Installed that 

**Perm ID**
496

**Comment by alfiellds** [comment]
Hello, thank you for the report. Please provide a video of this issue occurring.

**Comment by RaabHtid** [comment]
Nothing will change or work

**Comment by RaabHtid** [comment]
Trying to add the video how do I do it won’t work for some reason  [](https://kapwi.ng/c/RvVkJ9ES)

**Comment by alfiellds** [comment]
Hi, thank you for the video. I will forward this to the developers to review.

In the meantime, you can use commands such as /takeoffshirt to achieve similar functionality.

Many thanks.

**Comment by rubbertoe98** [comment]
Video link is no longer working, please re-upload.

**Comment by RaabHtid** [comment]
https://streamable.com/9114co

**Comment by rubbertoe98** [comment]
What resolution & aspect ratio are you running? Have you tried in fullscreen/windowed?

**Comment by RaabHtid** [comment]
Tried everything I went onto another city and it was the same so must be a fivem bug

**Comment by Caz-Developer** [comment]
ive got the exact same error, its with anything that involves clicking stuff with mouse

**Comment by Caz-Developer** [comment]
If You Shake Your Mouse And Click Does It Change Your Hair Or Trousers, Cause it looks to me its something to do with your monitor

**Comment by RaabHtid** [comment]
Yeah tried everything changed monitor didn’t work not sure what’s gone wrong it worked before

**Comment by rubbertoe98** [comment]
I and many others are unable to reproduce this behaviour, therefore we are unable to push a fix.
