### ISSUE TITLE
[Bug]: seniors cant kick anyone

### ISSUE THREAD

**Issue by SJ-XD** [CMGStudios/issue-tracker#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the senior rank cant kick members or guests in the gang when having advanced gang lisence

### Expected behaviour

![image](https://github.com/CMGStudios/issue-tracker/assets/60179898/b703eda6-918b-4191-bbd8-ea43383becf6)
![image](https://github.com/CMGStudios/issue-tracker/assets/60179898/a34daed2-71ae-4e94-bd96-96761163c02d)
all the seniors cant kick anybody eaven the guest cant be kicked the only person that can kick it the leader

### Steps to reproduce

try to kick somebody from the guest or member 

get a message saying you dont have the permissions to kick members / guests

### Any Texture Packs? (If so list)

no

### CMG User ID

1133

**Comment by SJ-XD** [comment]
![image](https://github.com/CMGStudios/issue-tracker/assets/60179898/35be1f20-cdde-4192-8ab4-cb9d9fd6e04e)
this is what it say's when trying to kick sombody

**Comment by packfile** [comment]
Thanks for the report! This has been fixed for the next scheduled restart
