### ISSUE TITLE
[Bug]: peterol pump explosion

### ISSUE THREAD

**Issue by Scouseer** [CMGStudios/issue-tracker#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i got blown up by patrol pumps that just kept exploding after they exploded once and it has caused issues with my game where at a certain angle my screen looks white the trees far away r purple and mine and everyone hair looks messed up 

### Expected behaviour

https://cdn.discordapp.com/attachments/1004469395134881812/1151946130410709082/image.png
https://cdn.discordapp.com/attachments/1004469395134881812/1151946299445358612/image.png
https://cdn.discordapp.com/attachments/1004469395134881812/1151946426385969172/image.png

### Steps to reproduce

blow ur self up with the petrol pumps on accident 

### Any Texture Packs? (If so list)

I do not have any texture packs 

### CMG User ID

327901

**Comment by packfile** [comment]
Thanks for the report, this is fixed for the next scheduled restart (see #805)
