### ISSUE TITLE
[Bug]: Border force cannot put players in vehicles

### ISSUE THREAD

**Issue by crazychris2404** [CMGStudios/issue-tracker#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Border force cannot put players in vehicles using E menu

### Expected behaviour

be able to place players in cars

### Steps to reproduce

Cuff someone
Press e next to a car
Put in vehicle 
dont work

### CMG User ID

910

**Comment by packfile** [comment]
Thanks for the report! This has been fixed for the next scheduled restart
