### ISSUE TITLE
discord status not working.

### ISSUE THREAD

**Issue by randomahhhname** [CMGStudios/issue-tracker#813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When playing CMG there is no discord status on your account 

### Expected behaviour

no status

### Steps to reproduce

go on cmg
go to discord 
no status on your profile

### Any Texture Packs? (If so list)

Reshade

### CMG User ID

220225

**Comment by kajblm** [comment]
Ensure your game activity is on in discord settings! This is also not an ingame bug.

LOCKED AND MOVED

**Comment by packfile** [comment]
Thanks for the report, we're are aware of this issue and it is in the process of being resolved by the relevant people.

**Comment by packfile** [comment]
Fixed since last Monday
