### ISSUE TITLE
[Bug]: Smokes not working using G

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When throwing a police-issued smoke with the "g" key bind, it does throw it but it doesn't "pop" (smoke doesn't work) 

Clip: https://www.youtube.com/watch?v=aLe40i-TBuQ&ab_channel=dj_Don

### Expected behaviour

To be able to throw smokes using "g" keybind 

### Steps to reproduce

Clock on PD 
Grab AR & Smokes 
Equip AR 
Press "G"

### CMG User ID

9975

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by crazychris2404** [comment]
Closed 
Was previously mentioned as being intentional
