### ISSUE TITLE
[Bug]: HEMS Blip

### ISSUE THREAD

**Issue by JakeBrown03** [CMGStudios/issue-tracker#815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you get within a certain distance from a member clocked on HEMS there map blip disappears. 

### Expected behaviour

Blip to remain on map

### Steps to reproduce

Go near someone clocked on HEMS 
https://medal.tv/games/gta-v/clips/1urNZhV-by6PPv/d1337ybzlXpC?invite=cr-MSxoeU8sMjgwODgwNTQs

### Any Texture Packs? (If so list)

no

### CMG User ID

289670

**Comment by packfile** [comment]
Thank you for the report. I believe this is as a result of #816 which will be fixed early next week. Please keep track of that issue for further information
