### ISSUE TITLE
[Bug]: radio Blip's

### ISSUE THREAD

**Issue by 2140CMG** [CMGStudios/issue-tracker#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the introduction of the new radios, if you leave and rejoin the server whilst clocked on a whitelisted faction you will be able to see most other blips but people won't be able to see yours.
The only way to fix this is by trashing the radio you have and getting a new one.

### Expected behaviour

Have all blips visible when doing /blips on, including your own.

### Steps to reproduce

Clock on as Any faction and get an emergency radio.
F8 quit and rejoin the server and do /blips on.
Most times you will see other blips but people won't see yours.

### Any Texture Packs? (If so list)

NVE

### CMG User ID

2140

**Comment by packfile** [comment]
Thanks for the report! This has been fixed from the next scheduled restart
