### ISSUE TITLE
[Bug]: Bypass the tased animation.

### ISSUE THREAD

**Issue by cookieforpres** [CMGStudios/issue-tracker#817]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Theres a glitch when your car has been damaged so much it gives you the option to push it, if you are tased and do `shift + e` to push the car you will get back up on your feet.

### Expected behaviour

You shouldnt able to push the car while being tased.

### Steps to reproduce

1. Have a car damaged to the point it lets you push it with `shift + e` and be close enough to it when being tased
2. Get tased
3. Push the car with `shift + e` and then let go of the keybind.
4. You should be able to walk around.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

360789

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report! This has been fixed for the next scheduled restart
