### ISSUE TITLE
[Bug]: Barber Shop not letting me choose a lighter skin colour

### ISSUE THREAD

**Issue by oVexo123** [CMGStudios/issue-tracker#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I changed my skin colour to a darker shade (From lightest to the second lightest) and now I cant change it back to the lightest shade.

### Expected behaviour

Be able to select the lightest skin colour.

### Steps to reproduce

Change skin colour from lightest to a different shade.
Then try select lightest shade and it doesnt work.

### Any Texture Packs? (If so list)

n/a

### CMG User ID

238154

**Comment by PIKAlmao** [comment]
What's wrong with having a darker skin shade vexo ?

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
