### ISSUE TITLE
[Bug]: Can't connect to the server with Epic Games

### ISSUE THREAD

**Issue by jasinB1** [CMGStudios/issue-tracker#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to connect I just can't.

### Expected behaviour

Fix it as fast as posible

### Steps to reproduce

idk

### Any Texture Packs? (If so list)

no

### CMG User ID

Jason B.

**Comment by PIKAlmao** [comment]
This is not a bug mate, please to head to the appropriate channel where i can help you accordingly. https://discord.gg/sRnzebsc
