### ISSUE TITLE
Phone issue still

### ISSUE THREAD

**Issue by Denzzzz** [CMGStudios/issue-tracker#82]
**Describe the issue you're facing**
I’ve relogged and my number still ain’t changed will it be next restart 
**Steps to reproduce**

**Expected behaviour**

**Screenshots/Video**
Scroll up 
**Additional context**

**Any Texture Packs (if so list)**
N/a 
**Perm ID**
177964

**Comment by alfiellds** [comment]
Hello, could you confirm whether it has changed following today's 3pm restart? 

@Denzzzz 

Many thanks.

**Comment by alfiellds** [comment]
This issue is being closed due to a fix being pushed and no response within 72 hours. If this issue persists, please open another report, or contact me on Discord so that I can reopen this one.

Many thanks.
