### ISSUE TITLE
Radio hotkey [Bug]: hotkey just randomly saying im clicking it when im not 

### ISSUE THREAD

**Issue by FinnWWFC** [CMGStudios/issue-tracker#820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i go into my radios its all working fine but after a few seconds it would say im speaking when im not even pressing my hotkey for it and it still picks up my mic audio, and then when i leave radios i have the open mic clitch 

### Expected behaviour

i cant use my radios when i need them at most 

### Steps to reproduce

i cant lie i dont know what this means 
dm me discord finnwwfc for more explanation as its hard to explain 

### Any Texture Packs? (If so list)

.

### CMG User ID

323514

**Comment by Keegasity** [comment]
Spoken with the Finn and this has been resolved.
