### ISSUE TITLE
[Bug]: Shock patient causes patients arms to stay up in air for 15-20 seconds after reviving them on nhs

### ISSUE THREAD

**Issue by bluebandit13** [CMGStudios/issue-tracker#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

(Like when the morphine was bugged) Shocking a patient and reviving them sometimes causes their arms to be stuck in the air for 20 seconds after reviving them then they can put them down

### Expected behaviour

Revive someone on NHS
Patient can walk away freely (with morphine affect)

### Steps to reproduce

Clock onto NHS
Revive a critically injured person
Persons arms may be stuck in air for a few seconds after

### Any Texture Packs? (If so list)

No

### CMG User ID

374542

**Comment by Keegasity** [comment]
Confirmed, Thank you for the report.

Steps To Reproduce:
1: After being revived press X immediately, then let go of X

This will cause your hands to be stuck in the air for between 15-20 seconds

https://youtu.be/ACViqDWn-Sg

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
