### ISSUE TITLE
[Bug]: NHS Looting Bags

### ISSUE THREAD

**Issue by Keegasity** [CMGStudios/issue-tracker#822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Following NHS being blocked from looting bags in early November last year, it seems NHS have continued to loot bags through the following method.

https://youtu.be/NjVqIYqX8WE

### Expected behaviour

NHS Ability to loot bags

### Steps to reproduce

1: Clock on a NHS
2: Locate a bag
3: Aim at the bag and press Caps Lock
4: Loot the bag

### Any Texture Packs? (If so list)

NVE

### CMG User ID

116867

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
