### ISSUE TITLE
[Bug]: Can’t deny NHS morphine

### ISSUE THREAD

**Issue by bluebandit13** [CMGStudios/issue-tracker#824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using morphine on someone it sends a request to the nearest person, which means sometimes it goes to the wrong one. If someone denys morphine, it injects them with it anyway

### Expected behaviour

Use morphine on the closest person
If they deny it, they won’t get the animation and morphine buff

### Steps to reproduce

Clock on NHS
Purchase morphine
Click use morphine when someone is nearby and get them to deny the request
Morphine animation will continue anyway

### Any Texture Packs? (If so list)

No

### CMG User ID

374542

**Comment by Keegasity** [comment]
Confirmed. Thank you for the report!

If a patient denies the morphine, morphine is still given.

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
