### ISSUE TITLE
[Bug]: Unable to join a gang in F5 menu

### ISSUE THREAD

**Issue by Grxggan** [CMGStudios/issue-tracker#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i am unable to join the gang ive left my old one and it says invites but nothing there and no one is able to invite me because it says im in a gang already.

### Expected behaviour

unable to join gang or F5

### Steps to reproduce

![20231001163823_1](https://github.com/CMGStudios/issue-tracker/assets/146655388/ee2acf86-574f-4241-b15c-9de596ee2a93)

they cant invite me although ive left

### Any Texture Packs? (If so list)

none

### CMG User ID

309924

**Comment by Keegasity** [comment]
After speaking with the player I have confirmed this is not a bug.

If any further help is needed please feel free to message me
