### ISSUE TITLE
[Bug]: PD /impound

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When requesting an impound vehicle it is locked

### Expected behaviour

The impound vehicle not to be locked

### Steps to reproduce

Clock on PD
/impound
try to get in 

### CMG User ID

9975

**Comment by DjDoon** [comment]
Video: https://www.youtube.com/watch?v=dxUQ7oM_jPw&ab_channel=dj_Don

**Comment by crazychris2404** [comment]
Confirmed 
thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
