### ISSUE TITLE
[Bug]: MLO Has no Collision causing you to fall through it onto Land

### ISSUE THREAD

**Issue by Lo4a5dev** [CMGStudios/issue-tracker#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/CMGStudios/issue-tracker/assets/146755023/74ea0d15-be38-4ace-910d-afa2ebf41660)

On The map U go close to a wall and you fall straight through it not through the map through the MLO itself. 

![image](https://github.com/CMGStudios/issue-tracker/assets/146755023/c773aa18-ec1e-40f2-b3dd-7912e976ee7a)

### Expected behaviour

Collision instead of Falling through

### Steps to reproduce

Go Towards the Far Left as soon as u come through the opening door where u can spawn a car 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

183036

**Comment by Keegasity** [comment]
Confirmed after speaking with the player. 

Thank you for the report!

Steps To Reproduce:
1: Get a vehicle out of the garage
2: Drive onto the grass above the garage

This can only be done within a vehicle and cannot be done on foot

Video -> https://youtu.be/TXDVLua1NNo

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart
