### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xVezoh** [CMGStudios/issue-tracker#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

okay so pretty much i payed for a supporter to supreme first without paying to be a supporter so i bought the supporter after and now i cant claim any of them cos i had to be supporter to claim to be supreme i paid 35 in total and it would really be good help if someone could fix this thank you.

### Expected behaviour

![FiveM® by Cfx re -  UK_EU  CMG  ___ British Themed ___ Economy ___ Arma 3 Vibe ___ discord gg_cmg 03_10_2023 21_33_48](https://github.com/CMGStudios/issue-tracker/assets/146898154/3d999612-b9af-4174-994b-0cf03ada0196)

### Steps to reproduce

?

### Any Texture Packs? (If so list)

no

### CMG User ID

387918

**Comment by Keegasity** [comment]
Hello Vezoh,

I would like to recommend you open a Donation Support ticket within the CMG Support discord, this is not something that the Bug team can assist you with.

Sorry for the inconvenience.
