### ISSUE TITLE
[Bug]: Pilot job marker

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you are on the pilot job you the marker sometimes disappears (most common on the aircraft carrier in my experience)

### Expected behaviour

For it not to disappear

### Steps to reproduce

1. do pilot job
2. suffer after a few runs

### CMG User ID

14009

**Comment by Keegasity** [comment]
Confirmed, Thank you for the report!

**Comment by ThroughAGame** [comment]
I noticed it is when you go from the aircraft carrier which is in the cayo perico part of the world and when you go into the main island map it doesn't transfer the pinged location of where you have to fly to. Guess it is linked to how it loads the two maps.

**Comment by packfile** [comment]
Thank you for the report, unfortunately without reproduction steps we are unable to fix this issue. Once you have a reliable way to have this occur please reopen the issue!
