### ISSUE TITLE
[Bug]: Heist set up

### ISSUE THREAD

**Issue by Azonq** [CMGStudios/issue-tracker#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

after doing the train set up for bank heist when u complete it and go to the garage it will keep saying success 

### Expected behaviour

.                                                        

### Steps to reproduce

1. complete the train set up
2. go to a garage
3. it will say success every time u go onto the garage

### Any Texture Packs? (If so list)

no

### CMG User ID

1069

**Comment by crazychris2404** [comment]
Not reproducable all the time if you find a way too keep reproducing then recreate the issue please
