### ISSUE TITLE
[Bug]: my car is a 2 door and 4 seater but passengers cant get in through the passenger door

### ISSUE THREAD

**Issue by zahiirr** [CMGStudios/issue-tracker#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my car is a 2 door and 4 seater but passengers cant get in through the passenger door. It doesnt let me get anyone in through the other door

### Expected behaviour

should be able to get in through passenger door as this car is not a 1 seater

### Steps to reproduce

go to passenger side and try to open door 

### Any Texture Packs? (If so list)

no

### CMG User ID

213844

**Comment by zahiirr** [comment]
![image](https://github.com/CMGStudios/issue-tracker/assets/142173484/32fd19ea-9ce1-4fc4-99c1-9ad29718d28d)

**Comment by Keegasity** [comment]
Good Evening,

This is something that you will need to report to Car Developers if you feel there is an issue.

This is not a bug.

Thank you
