### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Zac12333** [CMGStudios/issue-tracker#832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Put my money on the blackjack table the game bugged and my money disappeared while I’m still on and it insta lost my money 

### Expected behaviour

.

### Steps to reproduce

.

### Any Texture Packs? (If so list)

No

### CMG User ID

332285

**Comment by PIKAlmao** [comment]
Without a clip there's nothing they can do, and the blackjack tables are just weird anyways. If you have a clip i suggest attaching it to this bug report, and if it was over 5m then make a [comp request ](https://cmgstudios.net/forums/index.php?/forms/2-comp-request/) which you'd obviously need a clip for.
