### ISSUE TITLE
[Bug]: Demoting in gang

### ISSUE THREAD

**Issue by Nuts-280** [CMGStudios/issue-tracker#833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought the gang licnese and accidently demoted myself in my gang. But i dont have permission to do anything now. i cant kick take or deposit money

### Expected behaviour

Cant use my gangs options

### Steps to reproduce

i dont know

### Any Texture Packs? (If so list)

no

### CMG User ID

245307

**Comment by packfile** [comment]
Was this demotion before or after the gang permission update this morning?

**Comment by Nuts-280** [comment]
before
but it has carried on to now and it says i have 0% perms

**Comment by packfile** [comment]
This has been fixed for your gang from the next scheduled restart
