### ISSUE TITLE
[Bug]: Policecamera bug

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you use /policecamera your hat disappears 

https://www.youtube.com/watch?v=r5pBPuUOiB8&ab_channel=dj_Don 

### Expected behaviour

i want to keep my hat after using police camera

### Steps to reproduce

clock on pd
put on a hat
do /policecamera 
press g 
exit camera 

### Any Texture Packs? (If so list)

NVE

### CMG User ID

9975

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next restart
