### ISSUE TITLE
[Bug]: Further LFB Tool Problems

### ISSUE THREAD

**Issue by MrMikeyTV** [CMGStudios/issue-tracker#835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi Tom,

Thanks for working on the LFB Tools! We've had multiple fixed and I really appreciate that and I know the LFB members are really excited to use them so thank you so much for your work on this.

We've still got some issues though with the following tools though:
- LFB Rescue Cushion - Individuals fall through it and still die, they also fall through and take damage - https://medal.tv/games/gta-v/clips/1xPkeZ0kcEbcZj/d13370rNeHuj?invite=cr-MSxVM1QsMjAxMTQ1OTYyLA
- Spreaders - Is there a way we can reduce the audio on them so the audio doesn't last so long after the spreader has been used?
- Extractor Fan - Is there a way we can reduce the audio on them so the audio doesn't last so long after the extractor fan has been used and is there a way to turn them up or down though.
- Ladders - at times there are issues with the ladder tool where it can't be removed and once placed at times we also can't use them - https://medal.tv/games/gta-v/clips/1xP2A6qIudEHwO/d1337WRPYId6?invite=cr-MSxyRkYsMjAxMTQ1OTYyLA

### Expected behaviour

- LFB Rescue Cushion - We should fall through and have some form of animation to land on it, and no damage should be taken. 
- Spreaders - the audio should cease when the tool isn't being used
- Extractor Fans - the audio should cease when the tool isn't being used and we should be able to turn them on and off
- Ladders - We should be able to remove/use them once placed down

### Steps to reproduce

1. Clock on LFB
2. Place down the tools
3. See the difference between the issue and expected behaviour

### Any Texture Packs? (If so list)

None

### CMG User ID

604

**Comment by Keegasity** [comment]
Thanks for the report!

Following this report I have looked into the following. 

- LFB Recue Cushion - These are not useable as they allow the player to fall through and hit the floor (Killing them)
- Spreaders - I do not believe the sound is an issue. However, there needs to be more of an animation to fit the sound (Doors instantly come off)
- Extractor Fan - These serve no purpose other that for noise and effect. A way to control speed (Audio) would be perfect.
- Ladders - This is a random occurrence and happens from time to time.
