### ISSUE TITLE
[Bug]: NHS Shirt whitelisted to only PD

### ISSUE THREAD

**Issue by oVexo123** [CMGStudios/issue-tracker#836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Shirts/Jacket 428 (index 1/2) is the shirt used for PCSOs in PD. The 3rd and 4th index of the shirt/jacket is an nhs shirt. When clocked on nhs this shirt cannot be put on due to it being whitelisted to PD only.

![image](https://github.com/CMGStudios/issue-tracker/assets/134786988/a3351ebc-3981-4c6f-800f-69323dfcf741)

### Expected behaviour

When clocked on nhs you are able to use the shirt/jacket 428 (Index 3/4)

### Steps to reproduce

1. Clock on NHS
2. Try put on shirt/jacket 428 (index 3/4)

### Any Texture Packs? (If so list)

n/a

### CMG User ID

238154

**Comment by crazychris2404** [comment]
Confirmed
Thanks for report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from next Mondays push schedule.
