### ISSUE TITLE
[Bug]: housing tax

### ISSUE THREAD

**Issue by m1stackss** [CMGStudios/issue-tracker#837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when attempting to enter my home on cmg a prompt pops up in bottom left informing me that i have outstanding housing tax however there is no option for me to pay it thus making me unable to enter my house. I am unsure how many people are facing this issue as my friend hasnt encountered it with his home. also other people are still able to enter the home by ringing the doorbell.
![Screenshot 2023-10-10 112828](https://github.com/CMGStudios/issue-tracker/assets/147499399/a1a984c0-b93f-484f-9cbf-47f34ba296bd)

### Expected behaviour

if the issue was fixed then the option to pay housing tax would return or preferably housing tax would be removed completely, either way id be able to enter my home again and have access to everything stored inside

### Steps to reproduce

go up to your home and press enter home
then the prompt should pop up in the bottom left

### CMG User ID

374010

**Comment by crazychris2404** [comment]
If you go into the house and then use the menu do you have the option there ?

**Comment by m1stackss** [comment]
it doesn't let me enter the house.  also i just bought another house and the issue transferred i cant even sell them or rent them out as it keeps prompting me to pay housing tax first

**Comment by packfile** [comment]
Thanks for the report - Is this issue still occurring for you? Looking at the backend it shows you do not have any outstanding house tax, and it was last paid on the 30/10/2023 so should you be able to enter fine

**Comment by crazychris2404** [comment]
Closed due to no response
If this issue still exists please reopen
