### ISSUE TITLE
[Bug]: HMP doors

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

HMP kitchen door 1 and shower door 1 automatically close when no HMP are on and automatically close after being opened by HMP officers. They should remain open and only be closed when you manually close them just like the gym door.
 

### Expected behaviour

HMP kitchen door 1 and shower door 1 should only close when you manually close them and should remain open when no HMP officers are online.
The HMP command mentioned in the HMP discord server how it shouldn't be open and not close by itself.them

### Steps to reproduce

Clock on when no HMP officers are on and you will see those doors are shut.

Open those 2 doors and wait a bit and those doors automatically close again.

### Any Texture Packs? (If so list)

n/a

### CMG User ID

205070

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Please make a feature request as this behaviour is currently intentional

**Comment by ThroughAGame** [comment]
This was something command at the time (Hugo) even said how they this shouldn't be the case and it is a bug and that they requested this bug to be fixed. I originally suggested it as a feature change in the HMP discord but command mentioned how they thought it was a bug that was fixed but it still hasn't been fixed. Particularly annoying when it restricts inmates when kitchen door auto closes.
Original suggestion - https://discord.com/channels/813449451443060796/813466048987791400/1161751155521630278
Andy1's response - https://discord.com/channels/813449451443060796/813466048987791400/1161951897398296687
Link to the message that made me submit this bug report. - https://discord.com/channels/813449451443060796/832021609426452480/1161751852673667213
