### ISSUE TITLE
Bugged Melees

### ISSUE THREAD

**Issue by ross717** [CMGStudios/issue-tracker#84]
**Describe the issue you're facing**
Melees being on shoulders instead of on back/hip
**Steps to reproduce**

**Expected behaviour**
Expect them to be on my back
**Screenshots/Video**
https://cdn.discordapp.com/attachments/368441194692345856/867424209646256158/unknown.png https://cdn.discordapp.com/attachments/368441194692345856/867424425812819988/unknown.png
**Additional context**
Multiple players are having this issue with melees please can this be fixed
**Any Texture Packs (if so list)**
NVE
**Perm ID**
Perm ID : 717

**Comment by alfiellds** [comment]
Hello Ross, thank you for the report.

Could you confirm the following details please:
- Do the weapons appear on your back just for yourself, or for others also?
- Does this occur 100% of the time, or only sometimes with specific weapons?

Many thanks.

**Comment by ross717** [comment]
Weapons appear on my shoulder and its for other also everyone can see it on
your shoulder when they are meant to show on the back on the hip

This occurs 100% of the time with certain melees (basic ones from shanks
shop and also customs melees depending on what melee they replace)

**Comment by rubbertoe98** [comment]
Please provide a list of melee weapons that have this issue, thanks!

**Comment by ross717** [comment]
Toilet Brush, Dildo, Shank, wonder woman shield . I am not sure on others
but I'm sure there are more that are bugged.

**Comment by alfiellds** [comment]
Thank you for the list, I will forward this to the developers. If you are able to find more please reply with them here.

Many thanks.

**Comment by rubbertoe98** [comment]
Fixed, please let me know if there any further melees with broken back positions!
