### ISSUE TITLE
Cant invite in funds again[Bug]: 

### ISSUE THREAD

**Issue by SJ-XD** [CMGStudios/issue-tracker#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I made a report about this and it was fixed but now with the new system unless you have the leader option you can't invite to guest and such even if you have the right premitions 

### Expected behaviour

Try inv someone to the guest of a gang funds 

Gives you a msg
"You do not have permission"

### Steps to reproduce

Try inv someone to the guest of a gang funds 

Gives you a msg
"You do not have permission"

### CMG User ID

1133

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report 
(Unable to test locally but have heard a fair few reports of this)

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
