### ISSUE TITLE
Bug / Fix / Change

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#841]
(Fix/Change) - When using the /impound command, there's a chance of receiving a PD vehicle (shouldn't be a thing). 
(Bug) - When aiming with a tazer it causes quite an amount of desync with the players around (this is because of the red dot to my understanding)

**Comment by Simonstv** [comment]
Thanks for the Report!

i can confirm that the /impound has been fixed so they should'nt be getting a pd vehicle anymore
secondly with the taser unless you have a clip of the desync happening i can't do anything else im afraid so would need more info however it is being looked into.

**Comment by Simonstv** [comment]
Make a new report if any other issue occur with the taser
