### ISSUE TITLE
[Bug]: Can't buy armour from VIP Island 

### ISSUE THREAD

**Issue by velosity124** [CMGStudios/issue-tracker#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i have Plat, Rebel License, supporter rank i can't buy anything from the vip island store. I bought rebel license to buy Level 4 armour but can

### Expected behaviour

When going to purchase the armour it says 
'You are unable to access this store'

### Steps to reproduce

Go to VIP island and try and buy any item 

### Any Texture Packs? (If so list)

n / a

### CMG User ID

251053

**Comment by PIKAlmao** [comment]
Do you have gang license aswell ? (that's required to also use the vip "large arms"

**Comment by velosity124** [comment]
> Do you have gang license aswell ? (that's required to also use the vip "large arms"

YES i do. I was with xeona and isac a few days ago and they told me if the problem doesn't fix at the next restart to make a bug report

**Comment by Simonstv** [comment]
Maybe try buying armour from Rebel first then getting armour form VIP, when you have plat this might resolve your issue,
as for now i cannot reproduce.
