### ISSUE TITLE
[Bug]: lock doesnt shake sometimes when robbing store

### ISSUE THREAD

**Issue by reecegpp** [CMGStudios/issue-tracker#844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when robbing a store, rarely you can circle the lock many times but there will not be a shake, sometimes theres a very subtle shake but not enough to crack the lock 

### Expected behaviour

Usually, when robbing a store, you must circle the lock whilst cracking the safe, when the lock shakes rapidly, you hit the up arrow and that number has been cracked on the safe

### Steps to reproduce

go into a store, hold a gun at the cashier, start cracking the safe and keep going until you can find the issue

### Any Texture Packs? (If so list)

no

### CMG User ID

349279

**Comment by crazychris2404** [comment]
this is not a bug
