### ISSUE TITLE
[Bug]: Time Is Bugged ( I have Plat )

### ISSUE THREAD

**Issue by Muja2008** [CMGStudios/issue-tracker#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought 0.1 plat 1h ago and it has already ran out in my /cmgclub even though its supposed to last 2.40h. Also whilst im grinding im pressing e and it shows 10 seconds and at 2.50 seconds it gives me 4 opium poppys.

### Expected behaviour

Time - 7.50 not 10

### Steps to reproduce

1. Buy plat ( 0.1 )
2. go grind 
3. after 1 hour you will see that the timer is at 10 seconds 
4, it will give you your opium poppys or whatever your grinding at 2.50 seconds

CLIP - https://medal.tv/games/gta-v/clips/1zVcWKbzsviXNN/d1337Mh4tDVl?invite=cr-MSxaeDcsMTg1NDM2MDg2LA

### Any Texture Packs? (If so list)

NOPE

### CMG User ID

1088

**Comment by crazychris2404** [comment]
This is not reproducible please reopen if you find a way
