### ISSUE TITLE
[Bug]: pilots job

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you start the pilot's job, you regularly die when you get into your plane because multiple planes spawn in the same location and it all explodes.
When previewing a plane / selecting a plane to use, it can also explode when multiple planes are there.
It would be nice to have it so you don't have to retry multiple times to just start the job.

### Expected behaviour

Not die regularly or have the planes regularly explode.

### Steps to reproduce

Do pilots job and wait for multiple planes to be at the preview plane location. Repeat at the location where you drive to when the plane spawns in and start your shift. Planes explode when there are multiple ones in the same location, it is like a domino effect and just keeps on going until an admin clears them.

### Any Texture Packs? (If so list)

n/a

### CMG User ID

205070

**Comment by Keegasity** [comment]
Confirmed! Thank you for the report

Steps to reproduce
- Clock on as a pilot
- Head to the airport and choose your plane
- Often if multiple people are just starting piloting, planes will spawn on top of each other causing all planes to exploded.

**Comment by packfile** [comment]
Thanks for the report, the planes should no longer collide when spawned.
I couldn't reproduce this when previewing the planes however (technically this shouldn't be possible either, given the preview planes are not replicated to other clients). Please provide a video in this instance
