### ISSUE TITLE
[Bug]: pd shotgun

### ISSUE THREAD

**Issue by TheRealWicks** [CMGStudios/issue-tracker#847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can this pd shotgun been looked at please
its called the USAS and it is so bad compared to other guns it is actually funny you can headshot people from point blank range and it wont kill them it is a very old police gun
litterally every other shotgun would kill them in that situation
Combat Shotgun, and the Junction JAK-12 Is so much better compared to this gun
USAS PD Issued shotgun WL 
https://medal.tv/games/gta-v/clips/1zZgo6MjyKmL7_/d1337VkcnAca?invite=cr-MSxOOGUsMzE2OTk0Nyw

### Expected behaviour

for it to do more damage

### Steps to reproduce

try the shotguns that i have listed the USAS is like you are just slapping people in the face

### CMG User ID

387

**Comment by crazychris2404** [comment]
This is not a bug
If you’re looking to get damaged changed best to make a suggestion 

it is expected for whitelist guns to be better aswell
