### ISSUE TITLE
[Bug]: Fix Putting Stretcher in Big Red and HEMS 2 Helicopter [NHS]

### ISSUE THREAD

**Issue by Gooobie** [CMGStudios/issue-tracker#848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when clocked on as HEMS and you try to put a stretcher in the back of the big red & Hems 2 the option isn't displayed for the user 

### Expected behaviour

When you have a stretcher near you or are holding it, it would normally prompt you to put it inside the helicopter first. It would pop up with a display message 'open the door' (if you aren't the driver, you cannot open the door). Once you open the door, it should then pop up with another message allowing you to put the stretcher with or without a player on it.

### Steps to reproduce

1 - Clock onto hems/nhs 
2 - Get a Hems helicopter (Big red / Hems 2)
3 - get a stretcher with the NHS medical menu by pressing "U"
4 - and then it should give you a prompt to use the stretcher around the helicopter (in this case it doesn't)

### Any Texture Packs? (If so list)

no

### CMG User ID

168410

**Comment by Keegasity** [comment]
Confirmed, Thank you for the report!

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from next Mondays push schedule.
