### ISSUE TITLE
[Bug]: Allowing Placing Wheelchair inside Ambulance and Helicopters [NHS]

### ISSUE THREAD

**Issue by Gooobie** [CMGStudios/issue-tracker#849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It's the same situation as the HEMS helicopters but in this case you can't put Wheelchairs in Vehicles/helicopters

### Expected behaviour

when you are near a helicopter/ ambulance it should prompt you with the option to put a member in the car with a wheelchair

### Steps to reproduce

1 - Clock onto hems/nhs
2 - Get a Hems helicopter/Ambulance  
3 - get a wheelchair with the NHS medical menu by pressing "U"
4 - and then it should give you a prompt to use the wheelchair around the helicopter/Ambulance (in this case it doesn't)

### Any Texture Packs? (If so list)

no

### CMG User ID

168410

**Comment by packfile** [comment]
Please open a feature request as this is currently not supported
