### ISSUE TITLE
ars on front of chest

### ISSUE THREAD

**Issue by relyzx** [CMGStudios/issue-tracker#85]
ars are no longer on front of chest can we please switch it from back to the front again
it looked loads better and actually made ars go up in price a bit due to looks

Can you fill in the information required:

Describe the issue you're facing
Everyones ARS is on their back, not the front ches6
Steps to reproduce
fix it and revert so ars are on the front of your chest
Expected behavior
diagonal across your chest 
Screenshots/Video
I don't have any 
Additional context
please fix
Any Texture Packs (if so list)
Nah
Perm ID
193326

**Comment by arthur-rl** [comment]
Can you fill in the information required:

**Describe the issue you're facing**

**Steps to reproduce**

**Expected behaviour**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**

**Comment by alfiellds** [comment]
Edited with new information. Would you be able to provide a screenshot/video for the developers to review, please?

Many thanks.

**Comment by relyzx** [comment]
when i can get on

**Comment by relyzx** [comment]
https://cdn.discordapp.com/attachments/832258403292151828/867851465879846932/unknown.png

**Comment by alfiellds** [comment]
Hello, for PD this is currently an intended feature and not a bug. It is however, on the todo list to be moved to the front of the player model on the chest (according to Gold Command). 

![image](https://user-images.githubusercontent.com/43014759/126722735-1fae79c3-acf7-4f57-83be-a7a9b2bf6bad.jpeg)

For future reference please ensure any development related suggestions are processed via the forums.

Many thanks.
