### ISSUE TITLE
[Bug]: helispawn

### ISSUE THREAD

**Issue by kwakucmg** [CMGStudios/issue-tracker#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

everytime you spawn a heli it dont move and when you try and get out it explodes ive asked mates about it and it seems to happen to them too.

### Expected behaviour

..............................

### Steps to reproduce

......................

### CMG User ID

349957

**Comment by Keegasity** [comment]
After speaking with the player, this was a helicopter based issue that has now been resolved.
