### ISSUE TITLE
Custom gun not on f2 menu

### ISSUE THREAD

**Issue by Miles-1010** [CMGStudios/issue-tracker#851]
I own a custom gun called Ares Shrike and it is not on my f2 menu. It is apparently on the f2 menu of someone else who is on the whitelist even though I own the whitelist. My permid is 162446.

**Comment by packfile** [comment]
Thanks for the report. It appears this weapon was likely brought in together, hence one person is currently the weapon owner. If you believe this is a mistake please get in contact with myself (Discord User ID 844218291555139585)
