### ISSUE TITLE
[Bug]: Sandy PD Cell

### ISSUE THREAD

**Issue by random01234** [CMGStudios/issue-tracker#852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you lock the cell door it appears locked but you can still walk through as if it is unlocked and when PD arrest someone you can walk through it

### Expected behaviour

You shouldn't be able to walk through it

### Steps to reproduce

1. go to sandy pd cells (first one on the right)
2. Lock the cell 
3. Walk through cell door
4. https://medal.tv/games/gta-v/clips/1A4M8C1uQ4JSX7/d13375oOjwDq?invite=cr-MSxVbG8sMTQ5NzAxODUs

### Any Texture Packs? (If so list)

N/A

### CMG User ID

250185

**Comment by Keegasity** [comment]
Confirmed! Thank you for the report.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next restart
