### ISSUE TITLE
[Bug]: Lorry job stopping automaticly

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you are doing the lorry job everytime you drive though lodges greenzone with the lorry it cancels it

### Expected behaviour

For it to not cancel

### Steps to reproduce

1. Start the lorry job
2. Get the one for lodges
3. Drive through lodges green
4. suffer

### CMG User ID

14009

**Comment by Keegasity** [comment]
Confirmed! Thank you for the report

Steps to reproduce
- Clock on as Lorry Driver
- Pick up your trailer and head towards any greenzone.
- Drive into the greenzone and the trailer will disappear. 

You will have a message pop up saying "You are not physically able to complete this job"

Video - https://youtu.be/4X3qRLsNfP8

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next restart
