### ISSUE TITLE
[Bug]: phone 

### ISSUE THREAD

**Issue by Azonq** [CMGStudios/issue-tracker#854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

record a video on the phone and then try view it in the gallery its bugged 

### Expected behaviour

broken                              

### Steps to reproduce

record a video on the phone
click camera roll and try to view the video
it will not load

### Any Texture Packs? (If so list)

no

### CMG User ID

1069

**Comment by Keegasity** [comment]
Confirmed! Thank you for the report.

Steps To Reproduce
- Open your phone by pressing K
- Open the camera app and record a video
- Open the camera roll (gallery)
- The video will display as a white icon, when clicked on it will state its an image and not play or open.

Video - https://youtu.be/ywFgYGmSrhM

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from next Mondays push schedule.
