### ISSUE TITLE
[Bug]: Mirror Park House 10

### ISSUE THREAD

**Issue by Street11** [CMGStudios/issue-tracker#855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Interior is still broken and still not been fixed that was report to staff member in February I am wanting to get this sold instead of sat here doing nothing and paying 25k a day in tax for nothing  https://medal.tv/games/gta-v/clips/1bTGW6FfWApyPz/d1337y8Gf3lV?invite=cr-MSxIWmIsMTU3MDE1NzI4LA  

### Expected behaviour

https://medal.tv/games/gta-v/clips/1bTGW6FfWApyPz/d1337y8Gf3lV?invite=cr-MSxIWmIsMTU3MDE1NzI4LA

### Steps to reproduce

1 walk in house 
2 find it fucked 
3 can't do anything 

### CMG User ID

958

**Comment by Keegasity** [comment]
Confirmed! Thank you for the report.

Steps To Reproduce
- Walk into the house
- Try entering any room within the house

**Comment by packfile** [comment]
Thanks for the report, as mentioned in the other issues we do not have the facility to fix this building at the moment
