### ISSUE TITLE
[Bug]: guest gang after id swap

### ISSUE THREAD

**Issue by Yiqqa** [CMGStudios/issue-tracker#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

so i got an id swap today and since my id changed i need an invitation to the guest gang in order to see their blips, etc. my old id was 354742 and my new one is 1131. the owner that is trying to invite my new id claims that it says "this id is already in a guest gang" which means i am unable to join. also if you watch the clip it doesnt even show that im still in the gang and when i press leave nothing happens

### Expected behaviour

- unable to leave guest gang even though you are not in it
- both id's that you own say that they are already in a guest gang

### Steps to reproduce

change id.
attempt to leave guest gang.
and attempt to join with new id

clip : https://clipchamp.com/watch/4kgxCpKyvt5

### CMG User ID

1131

**Comment by packfile** [comment]
Thanks for the report, I believe this is an issue with caching so should be fixed from the restart after (since gone). If this issue still occurs please reopen the issue
