### ISSUE TITLE
[Bug]: pilot job 

### ISSUE THREAD

**Issue by kimfake** [CMGStudios/issue-tracker#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not getting atc command prompts when landing at sandy airstrip with baller plane.

### Expected behaviour

I expect just like with normal planes i when I bring the plane to halt it will give me atc command instructions to follow and accept instead I have to land at another airport then I get clearance to taxi to gate ,but then I have to fly back to sandy.

### Steps to reproduce

1.fly the plane 
2.get ready for landing at sandy 
3.land the plane to a complete  stop.
4.await instructions from atc but obviously not getting nothing from sandy.

### CMG User ID

231566

**Comment by Simonstv** [comment]
Thank you for your report can confirm this can be reproduced 

https://streamable.com/8gl0t3 - Thanks to Sug

Have tried it myself in other planes to, will pass this onto the developers.

**Comment by packfile** [comment]
Thank you for the report, unfortunately without reproduction steps we are unable to fix this issue. Once you have a reliable way to have this occur please reopen the issue!
