### ISSUE TITLE
[Bug]: i cant leave the gang i am in 

### ISSUE THREAD

**Issue by slow5k** [CMGStudios/issue-tracker#858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

one of my friends started a gang and me and my friends joined it. after I took a break from the game i was the only one left in the gang. so i tried to leave and was left with the message that i cannot leave as im the only person left in the gang. so i tried to disband the gang yet it says that i do not have permission to disband the gang.

https://streamable.com/0c4dxf

### Expected behaviour

https://streamable.com/0c4dxf

### Steps to reproduce

[6](https://streamable.com/0c4dxf)

### Any Texture Packs? (If so list)

no

### CMG User ID

122456

**Comment by packfile** [comment]
Thanks for the report, you should have the leader permission in your gang now and be able to disband / edit as you like
