### ISSUE TITLE
[Bug]: ballers spawn code showing as a non lock

### ISSUE THREAD

**Issue by Declana07** [CMGStudios/issue-tracker#859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When checking spawn code of vehicles they show as not baller lock when they are I’ve discussed with owners bringing these vehicles in and confirm they are ballers 

for example the cmp hummer 
Spawn code: 24humevof

this is one of many vehicles with this issue 

### Expected behaviour

Doesn’t show as being locked 

### Steps to reproduce

!gco 24humevof

not baller locked when it is 

### Any Texture Packs? (If so list)

No 

### CMG User ID

69866

**Comment by packfile** [comment]
Thanks for the report, it appears this vehicle isn't on the locklist. This has been forwarded to donation support to investigate

**Comment by crazychris2404** [comment]
This will show as locked from next restart 
Any other spawncodes you notice with this issue feel free to dm me on discord Chris._._
