### ISSUE TITLE
ARS ON BACK REDO

### ISSUE THREAD

**Issue by relyzx** [CMGStudios/issue-tracker#86]
Can you fill in the information required:

Describe the issue you're facing
Everyones ARS is on their back, not the front ches6
Steps to reproduce
fix it and revert so ars are on the front of your chest
Expected behavior
diagonal across your chest 
Screenshots/Video
I don't have any 
Additional context
please fix
Any Texture Packs (if so list)
Nah
Perm ID
193326

**Comment by alfiellds** [comment]
Merging this with your other report.
