### ISSUE TITLE
[Bug]: Clothes wardrobe does not work when key sharing

### ISSUE THREAD

**Issue by SamWood420** [CMGStudios/issue-tracker#860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you are given a key to someone else’s house you can use there storage but not use there wardrobe because when you try to put your the outfit on nothing happens

### Expected behaviour

The wardrobe allows you to change your clothes as if it was your own house 

### Steps to reproduce

1. Receive a key to someone else’s house
2. Try change clothes on to a saved outfit
3. Nothing happens when slected

### Any Texture Packs? (If so list)

No

### CMG User ID

1232

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next restart
