### ISSUE TITLE
[Bug]: Unable to start trucking

### ISSUE THREAD

**Issue by IDontHaveAClue** [CMGStudios/issue-tracker#861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Won't let me start trucking - just tells me to go clock in at city hall (so I do) then go back to trucking and same message

### Expected behaviour

It should just bring up the menu with start job on it

### Steps to reproduce

Go to trucking
Try to start job (won't let me)
Go to city hall to clock in as lorry driver
Back down to trucking
Doesn't work

### CMG User ID

377117

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next restart
