### ISSUE TITLE
[Bug]: Pilot Job

### ISSUE THREAD

**Issue by LiamMaac** [CMGStudios/issue-tracker#862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some of the planes aren't loading in and job cannot be started in said planes

### Expected behaviour

Start Job, Pick Plane, Choose Legal or Illegal, Enter

### Steps to reproduce

1. Start Job
2. Choose Plane
3. Legal or Illegal
4. Start / Go to Plane

### CMG User ID

390586

**Comment by Simonstv** [comment]
Thanks for the Report
I can now confirm this has been fixed
