### ISSUE TITLE
[Bug]: Casino just glitched and i lost all my money?

### ISSUE THREAD

**Issue by SAastro** [CMGStudios/issue-tracker#863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I lost 10m in casino just to bad luck then i decided to go all in and the casino bugged after giving me 2 cards and the money was just gone.

### Expected behaviour

I expect to see my money back as I lost everything due to a bug. It was everything I had and I would like to prevent it from happening to others aswell.

### Steps to reproduce

https://youtu.be/wDrUOajJySQ            THIS IS THE LIMK TO THE FULL 10MIN CLIP or JUST SEND ME A DM ON DC Astro4014 for the link.

### Any Texture Packs? (If so list)

no

### CMG User ID

330746

**Comment by PIKAlmao** [comment]
To receive compensation, make a request on the following link https://cmgstudios.net/forums/index.php?/forms/2-comp-request/

**Comment by Simonstv** [comment]
Thanks for the report, as Pika says you'll need to make a compensation request
