### ISSUE TITLE
[Bug]: levels 1 3 5 6 7 are disabled for some reason on pilot job , this needs fixing with the grind boost please

### ISSUE THREAD

**Issue by DingleWarrior** [CMGStudios/issue-tracker#865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The following planes do not appear to work , this has been since the grind boost began , can this please be fixed as we’ve been waiting ages for jobs to be included. Planes 1 3 5 6 7 are disabled for some reason. Yet the others INCLUDING the top level plane are active . Can this please be fixed before the boost ends so we can actually grind please

### Expected behaviour

Go to start the job and be able to select any plane (level dependent)

### Steps to reproduce

Go to pilot job 

click any of the following planes 1 3 5 6 7

plane will not spawn and job will not start

### Any Texture Packs? (If so list)

No

### CMG User ID

208

**Comment by Simonstv** [comment]
Thanks for the report!
I can now confirm this is fixed.
