### ISSUE TITLE
[Bug]: Wheel stance on Audi ruined after server removal off stance kits

### ISSUE THREAD

**Issue by TomCMG** [CMGStudios/issue-tracker#866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

One of my cars, spawncode: rs3rks

Got it's stance all messed up after stance kits were removed from the server.

![A](https://github.com/CMGStudios/issue-tracker/assets/149547447/fb58ebb3-de90-4ef4-b5e0-3f0fb620ff72)
^Picture of the current stance

![audi2](https://github.com/CMGStudios/issue-tracker/assets/149547447/178d0928-a3f1-44ce-af62-a20de81fcc1c)
^Picture of how the stance is supposed to be like, this picture is also taken in car dev mode after the kits were removed.

I have no idea if the two other cars on this lock have the same problem, or if any other cars in the server got this problem, hopefully not.

I have tried changing the tires & rims X amount of times to see if it would reset with no luck.

### Expected behaviour

Not having a messed up stance when spawned from a garage

### Steps to reproduce

Not really sure about this as i have not seen any other having this problem, and spawning this car in car dev mode seems to spawn it with the right stance.

### Any Texture Packs? (If so list)

None

### CMG User ID

914

**Comment by crazychris2404** [comment]
This would be a issue with the model as stances being removed would not of changed this
