### ISSUE TITLE
[Bug]: NHS Drone not Spawning

### ISSUE THREAD

**Issue by oVexo123** [CMGStudios/issue-tracker#867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to use an NHS Drone with /drone, a drone does not spawn.

### Expected behaviour

Drone to spawn.

### Steps to reproduce

Clock on NHS
Spawn drone using /drone
A drone will not spawn

### CMG User ID

1188

**Comment by DjDoon** [comment]
This is also an issue with PD, /drone won't spawn a drone

**Comment by Simonstv** [comment]
Thanks for the report
i can confirm /drone is not working on the the factions

to reproduce simply clock on any faction with access to  drone
do /drone
should put you in a drone - but doesn't.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from next Mondays push schedule.
