### ISSUE TITLE
[Bug]:trucking

### ISSUE THREAD

**Issue by rryannnnn** [CMGStudios/issue-tracker#868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you start a legal trucking job the trailer doesnt appear and tells you to go to a location to pick up a trailer and when you arrive there isnt anything there. meaning you cant complete the job

### Expected behaviour

the trailer should be there

### Steps to reproduce

rent or buy a truck
start job
cant get trailer

### Any Texture Packs? (If so list)

no

### CMG User ID

391303

**Comment by crazychris2404** [comment]
This has since been resolved
