### ISSUE TITLE
cant leave my gang and it wont let me join a new one

### ISSUE THREAD

**Issue by JAMAICAz** [CMGStudios/issue-tracker#869]
I cant leave my gang but when im on the menu to join or create a new gang my mouse disappears and i cant click on anything so i am not able to join a new gang is there anyway this can be resolved..

**Comment by Simonstv** [comment]
Thanks for the Report - Will leave open for 2 more days before closing.
To be able to assist you we will need more information / any clips to help otherwise we can't help

**Comment by crazychris2404** [comment]
Closed due to no response
