### ISSUE TITLE
y wheel

### ISSUE THREAD

**Issue by twiggy96** [CMGStudios/issue-tracker#87]
** my y wheel doesn't work **

**fix it **

**Expected behaviour**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**199908**

**Comment by exmmz** [comment]
The devs already know, and are working on a fix I believe!

For now use /takeoffshirt

**Comment by arthur-rl** [comment]
Can you please fill out the fields. More importantly the `Screenshots/Video`

**Comment by alfiellds** [comment]
Due to no response for 5 days, this will be closed. If the issue persists please open another bug report with all the required information as per the format.

Many thanks.
