### ISSUE TITLE
[Bug]: Pilot Level not working

### ISSUE THREAD

**Issue by VicXRT** [CMGStudios/issue-tracker#870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have dropped the passengers off, but Im supposed to get to level 100 - something i've spent ages trying to get so I get it first and it didn't allow me to gain the xp to level to 100, tried different planes but the same issue exists. 

### Expected behaviour

To drop off the passengers and then get to level 100 max level

### Steps to reproduce

Normal pilot process at level 99 with the correct xp but it doesn't allow you to gain the xp to get to level 100

https://youtu.be/x4sE41jZqso

https://youtu.be/OjBISBijLNw

### CMG User ID

8322

**Comment by crazychris2404** [comment]
Fixed for Monday 
Thanks for report
