### ISSUE TITLE
[Bug]: Baller Planes

### ISSUE THREAD

**Issue by LiamMaac** [CMGStudios/issue-tracker#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

New Baller Planes, the one with three jets, one at either side, one on top.. When plane is running, any plane that comes behind it gets pushed by its engine thrust. I've had my plane pushed off the aircraft carrier 3 times.

### Expected behaviour

As all other planes, they should make no difference to the other planes.

### Steps to reproduce

Unclear on how to resolve, plane just needs to be sorted for the engines causing issues to other planes

### CMG User ID

390586

**Comment by LiamMaac** [comment]
https://clipchamp.com/watch/NEOtVHBgofO https://clipchamp.com/watch/TUNehw95NKG https://clipchamp.com/watch/6t87OWodvUj https://clipchamp.com/watch/4ZeL9p131Ko https://clipchamp.com/watch/CtQL2Mg9myP https://clipchamp.com/watch/oHzsMtcZ9VY

**Comment by LiamMaac** [comment]
G650 Plane causing game crash
Falcon Plane causing other planes to be propelled by its jet engines

**Comment by packfile** [comment]
Thanks for the report, this has been forwarded to the car developers to investigate

**Comment by packfile** [comment]
This is being dealt by the car developers, closing. Please contact them if you wish for an update.
