### ISSUE TITLE
[Bug]: LFB BA not working properly on Women

### ISSUE THREAD

**Issue by MrMikeyTV** [CMGStudios/issue-tracker#872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The breathing apparatus changes the undershirt when it is raised/lowered by the looks of it 

- https://medal.tv/games/gta-v/clips/1CcAvZ68T0Zp82/d1337KRs7eiK?invite=cr-MSxpbkUsMTk1NTkwOTMwLA

### Expected behaviour

BA for women should be up when up is selected
BA for women should be down when BA is selected

### Steps to reproduce

1. Clock on LFB
2. Ensure you are a woman
3. Press U and go to BA, and press BA Up
4. Press BA Down

### Any Texture Packs? (If so list)

N/A

### CMG User ID

604

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from next Mondays push schedule.
