### ISSUE TITLE
[Bug]: game crash after barrer rolls 

### ISSUE THREAD

**Issue by LushnMclovin** [CMGStudios/issue-tracker#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was trying to check if barrer rolls are giving me any extra experience during my job as a pilot, everytime i land and try to deliver passangers the game crash.. i tried it 2 times in a row and lost 150 K.....

P.S. Please also take a look at my weapons. On my first day admins gave me a weapon, i didn't use it at all, i didn't know how, and than found weapon whitelist which states: If you can see your custom weapon here please open a ticket on our support discord

### Expected behaviour

The expected behaviour of the game - plane should not crash after couple of barrel rolls 

P.S. Please also take a look at my weapons. On my first day admins gave me a weapon, i didn't use it at all, i didn't know how, and than found weapon whitelist which states: If you can see your custom weapon here please open a ticket on our support discord

### Steps to reproduce

-pilot job
-3rd plane for lvl 24 
- barrel rolls during flight 
- deliver passsangers (this is the moment game is crashing for me, just after pressing deliver)

P.S. Please also take a look at my weapons. On my first day admins gave me a weapon, i didn't use it at all, i didn't know how, and than found weapon whitelist which states: If you can see your custom weapon here please open a ticket on our support discord 

### CMG User ID

390961

**Comment by packfile** [comment]
Do you have the crash `.dmp` or `.zip` file that can be uploaded in the Discord crash-zips channel?

**Comment by packfile** [comment]
No response from OP, closing.
