### ISSUE TITLE
[Bug]: Trucking Trailer Spawn Glitch

### ISSUE THREAD

**Issue by hammy1050** [CMGStudios/issue-tracker#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trucking Trailer not appearing legal and illegal even when I end job and start job again it gives me the same spawn.

### Expected behaviour

It should work every time without it doing a glitch, not letting me do the job for three days then glitching again after two jobs.

### Steps to reproduce

Probaly just delete that trailer spawn

### Any Texture Packs? (If so list)

No

### CMG User ID

364454

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
