### ISSUE TITLE
[Bug]: NHS Stretchers not spawning when using the nhs objects menu.

### ISSUE THREAD

**Issue by oVexo123** [CMGStudios/issue-tracker#875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When pressing using the objects menu to spawn a stretcher it does not spawn. 

### Expected behaviour

Stretcher to spawn when using the objects menu button "spawn stretcher".

### Steps to reproduce

1. Clock on NHS
2. Press u to open Objects Menu
3. Go down to Objects
4. Press Spawn Stretcher

### Any Texture Packs? (If so list)

n/a

### CMG User ID

1188

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
