### ISSUE TITLE
[Bug]: Custom Pistol not showing in F2

### ISSUE THREAD

**Issue by xyzL0L** [CMGStudios/issue-tracker#877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought a custom pistol ( Glock-20 ) around 2 years ago and I don`t have it in my F2 but I still have it in small arms, its like someone else has taken ownership? I still have my AR ( M8A7 ) But my pistol is gone?

### Expected behaviour

^^^^

### Steps to reproduce

^^^

### CMG User ID

28760

**Comment by packfile** [comment]
Thanks for the report, this should be fixed in the next restart
