### ISSUE TITLE
[Bug]: HMP Bugs

### ISSUE THREAD

**Issue by zernmm** [CMGStudios/issue-tracker#878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

these are the current HMP bugs 

### Expected behaviour

ankle tags teleport you back at a certain distance

shower animation can't be cancelled

npc transport van is the default gta model and livery

### Steps to reproduce

ankle tags: once a prisonee has one on they can only go a certain distance and then they would be teleportrd back

shower animation self-explanatory 

transport van: randomly switches to the default gta model

### CMG User ID

317145

**Comment by packfile** [comment]
> ankle tags teleport you back at a certain distance

Fixed, thanks for the report!

> shower animation can't be cancelled

This is somewhat intentional. Is there a use case for this?

> npc transport van is the default gta model and livery

Fixed, thanks for the report!
