### ISSUE TITLE
[Bug]: BMW M4 GTS LBWK

### ISSUE THREAD

**Issue by Daveboy55** [CMGStudios/issue-tracker#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to put different spoilers on the car the book disapears

### Expected behaviour

Expected the boot lid to be there with the spoiler

https://github.com/CMGStudios/issue-tracker/assets/151792943/7c873cb3-3259-4fa8-8bf8-87d489bbdb51

### Steps to reproduce

Go to a car customisation shop and select spoiler to modify and it will happen when cycling through them all

### Any Texture Packs? (If so list)

None

### CMG User ID

331561

**Comment by crazychris2404** [comment]
This is a model issue
Please submit a donation support ticket with a lockslot and the fixed model to get this changed
