### ISSUE TITLE
[Bug]: RP Zones Unremoveable

### ISSUE THREAD

**Issue by MrMikeyTV** [CMGStudios/issue-tracker#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi guys, When an RP Zone is placed, at times it cannot be removed. I have provided a clip of this below.

-> https://medal.tv/games/gta-v/clips/1G9awju0J0mCQf/d1337KmU6Eb8?invite=cr-MSxOYk4sMTM5ODI0NjUs

### Expected behaviour

You should be able to click remove nearest RP zone within the RP Zone menu and it remove the closest one within 100m.

### Steps to reproduce

1. Press F2
2. Go to Functions
3. RP Zones
4. Delete nearest RP Zone

### CMG User ID

604

**Comment by packfile** [comment]
This should be fixed from a future restart. It appears the person who created the zone did it high up in the air which skewed the nearby distance checks (it was checking 3D when should have been 2D).
