### ISSUE TITLE
[Bug]: Can`t pay my house tax

### ISSUE THREAD

**Issue by xyzL0L** [CMGStudios/issue-tracker#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My friend sold me a house, and a few days later I wanted to sell it and I cant because It says I need to pay my house tax, but in the menu I don`t get an option to pay it. I cant enter it/rent it etc etc. The house is Mirror Park 40 and I know the house isn`t bugged because he had to pay the house tax to sell it to me...  I have called and asked admins and I was told to open a bug report.

### Expected behaviour

^

### Steps to reproduce

^

### Any Texture Packs? (If so list)

None

### CMG User ID

28760

**Comment by crazychris2404** [comment]
This should be fixed from next restart
