### ISSUE TITLE
[Bug]: Speeding Fines

### ISSUE THREAD

**Issue by wooffighter** [CMGStudios/issue-tracker#882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you are on HMP, PD speedtraps still fine you and give you points

### Expected behaviour

For HMP to be exempt like other whitelisted factions from these traps

### Steps to reproduce

1. Drive whilst clocked on HMP
2. Get scanned by PD speedtraps
3. Get points

### CMG User ID

14009

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
