### ISSUE TITLE
[Bug]: Game crash after repairing baller plane (tested multiple times)

### ISSUE THREAD

**Issue by sssou** [CMGStudios/issue-tracker#883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you try to repair your baller plane, approximately 9/10 times fivem will automatically crash

### Expected behaviour

significantly higher likelihood of an immediate game crash after repairing a baller plane on the pilot job

### Steps to reproduce

1. start pilot job
2(maybe optional maybe not). Complete atleast 1 job on pilot
3. go to repair station and press e to begin repair 
4. game crash

### Any Texture Packs? (If so list)

no

### CMG User ID

164449

**Comment by crazychris2404** [comment]
This shouldnt be occuring anymore
