### ISSUE TITLE
[Bug]: Removing Binoculars

### ISSUE THREAD

**Issue by taki1117** [CMGStudios/issue-tracker#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you equip binoculars you can't remove them unless you get in a car (they will be gone forever when you get in a car wich means the money is wasted). Unlike a microphone or a camera it also gets taken out of the inventory when you use it.

### Expected behaviour

I am not sure what is meant by expected behaviour.

### Steps to reproduce

I also don't know what is meant by steps to reproduce.

### Any Texture Packs? (If so list)

-

### CMG User ID

374378

**Comment by crazychris2404** [comment]
Confirmed thanks for the report
There needs to be a way to store binoculars same as microphone etc

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
