### ISSUE TITLE
[Bug]: LSD NORTH HEROIN TRADER

### ISSUE THREAD

**Issue by Pilly1** [CMGStudios/issue-tracker#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying too sell heroin at the trader within LSD NORTH, the trader prompts an error that states "Failed too sell, Please relog" and after many attempts of relogging, it just says the same over.

### Expected behaviour

Too be able too sell the H at the trader.

### Steps to reproduce

Grind some heroin, go too sell at LSD North, find the issue.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

111719

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the latest restart
