### ISSUE TITLE
[Bug]: nO FIRES FOR lfb 

### ISSUE THREAD

**Issue by babz97** [CMGStudios/issue-tracker#887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

we LFB have no fires to put out! had two fires all day

### Expected behaviour

no fires are spawning and we are not getting calls to the call manager

### Steps to reproduce

look for fires as an LFB

### CMG User ID

390747

**Comment by babz97** [comment]
only vehicle fires are showing on the call manager like 1 or 2 every hour

**Comment by MrMikeyTV** [comment]
Hello! For this issue please contact a member of Chief Fire Command or a Senior Administrator. This is not an in-game bug, it is one where the fires are turned off and need turning back on by a member of CFC or an SA. I will address this with CFC and SA's to ensure we are double checking and not turning off unless necessary but if you ever need them turning on, feel free to DM me on Discord.

**Comment by babz97** [comment]
Mikey u fixed it already thank you bro i appreciate your response

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MrMikeyTV** [comment]
Anytime, if this happens in future, just send me a DM and I will sort for you.
