### ISSUE TITLE
[Bug]: No Trailer on Truck job

### ISSUE THREAD

**Issue by Danpne99** [CMGStudios/issue-tracker#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When picking up trailer, there is no trailer to pick up

### Expected behaviour

Should be a trailer to pick up

### Steps to reproduce

Start a trucking job.

### CMG User ID

393386

**Comment by Keegasity** [comment]
After speaking with the player this does not seem to be a bug.

Thank you for using the bug report system!
