### ISSUE TITLE
[Bug]: Can't sell Taco's in the snow

### ISSUE THREAD

**Issue by dllewhe99922** [CMGStudios/issue-tracker#889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The snow prevents people from purchasing from the taco truck. Every time they try to purchase, they just pick up a snowball instead.

### Expected behaviour

Meant to be able to buy tacos

### Steps to reproduce

Customers press E

### CMG User ID

395561

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
