### ISSUE TITLE
[Bug]: falling through map

### ISSUE THREAD

**Issue by pucynyce** [CMGStudios/issue-tracker#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

fell through map whilst in my ambulance

### Expected behaviour

place to drive on

### Steps to reproduce

drive over the area

https://medal.tv/games/gta-v/clips/1IINOEme_Gytjh/d13375MWC5n6?invite=cr-MSx3aFUsMTgyOTE2NDE5LA

### Any Texture Packs? (If so list)

n/a

### CMG User ID

45535

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
