### ISSUE TITLE
[Bug]: drop not spawning on map

### ISSUE THREAD

**Issue by olik1x** [CMGStudios/issue-tracker#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the announcement in chat pops up and u can see the plane but i have not seen the redzone once although sm1 still just looted the drop

### Expected behaviour

the redzone should spawn whenever the plane drops it however even plane is not sometimes seen

### Steps to reproduce

.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

1147

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart
