### ISSUE TITLE
[Bug]: Only member in a gang with 0% control

### ISSUE THREAD

**Issue by GreenFruit1** [CMGStudios/issue-tracker#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Im the only person in the gang somehow. I would like to leave it but it doesnt let me leave or disband the gang. 

![image](https://github.com/CMGStudios/issue-tracker/assets/75586325/1ec814e7-a402-4f8f-836b-9fd83dfd7d00)

### Expected behaviour

Able to leave gang

### Steps to reproduce

Be the only member in a gang with 0% control and try to leave

### Any Texture Packs? (If so list)

none

### CMG User ID

376656

**Comment by crazychris2404** [comment]
This has been forwarded and is being investigated

**Comment by packfile** [comment]
This should have been fixed since the 19th Dec
