### ISSUE TITLE
[Bug] Behind Galaxy Nightclub

### ISSUE THREAD

**Issue by Declare5M** [CMGStudios/issue-tracker#893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

You can walk through a wall behind the "Galaxy Night Club"

https://streamable.com/t6b66w

### Expected behaviour

To not walk through a brick wall 

### Steps to reproduce

Go behind Galaxy NightClub
Walk to the alleys
![image](https://github.com/CMGStudios/issue-tracker/assets/109679930/672809d8-e6f7-4c88-91dd-cfa38acfbf7b)
Go to this location ^
You can walk through walls 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

142

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report
As per comments in discord this is a high priority issue

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
