### ISSUE TITLE
[Bug]: Shared gang funds

### ISSUE THREAD

**Issue by ZakH2** [CMGStudios/issue-tracker#894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Money keeps setting to 0 in shared gang funds and when putting money it works all good adds to the total within the logs then when you relog the total money sets back to 0 same thing for the other 2 people in the shared gang funds

### Expected behaviour

Cannot take money out gang funds

### Steps to reproduce

Try to take money out of gang funds
Put money into gang funds
relog
money sets to 0

### Any Texture Packs? (If so list)

N/A

### CMG User ID

197444

**Comment by crazychris2404** [comment]
This has been forwarded and is being investigated

**Comment by packfile** [comment]
Hey @ZakH2, could you please attach a clip of this occurring

**Comment by ZakH2** [comment]
https://medal.tv/games/gta-v/clips/1K2PZ4q8m1jVBz/d1337Pk0fh6p?invite=cr-MSxDTmUsMTk3OTA0NzA3LA @packfile @crazychris2404

**Comment by ZakH2** [comment]
anything on this?

**Comment by teethbreath** [comment]
you cant take 100k out because you only have 11k are you stupid

**Comment by ZakH2** [comment]
@teethbreath watch the clip mate says i’ve got 2m in there

**Comment by teethbreath** [comment]
yes you have 2m, but your friend has -27m which is why you cant take anything out :(

**Comment by ZakH2** [comment]
he’s not in the funds anymore and this was never an issue before it glitched

**Comment by teethbreath** [comment]
he still took the money out just because he left doesnt mean you can now spend the money if that was the case people would just spend 50m leave the gang and it would still be there

**Comment by packfile** [comment]
Issue has been correctly identified by @teethbreath
