### ISSUE TITLE
[Bug]: im stuck under the  map

### ISSUE THREAD

**Issue by d1kkk** [CMGStudios/issue-tracker#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

so what it is is that on the moterway i procceded to jump out my car and the road was clear and invisible and now im stuck under the map and when i reload back into the game i keep going underneath the map iv tried everything

### Expected behaviour

tried everything 

### Steps to reproduce

nothing

### Any Texture Packs? (If so list)

no

### CMG User ID

395613

**Comment by packfile** [comment]
Please call a ticket when you are next in game, you could also try /unstuck.
