### ISSUE TITLE
[Bug]: Gang Role Glitch

### ISSUE THREAD

**Issue by XxBunnyXx123** [CMGStudios/issue-tracker#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I bought a new computer and when i logged onto the game, I was stripped of my Senior role in my gang, meaning I no longer had permissions to withdraw/deposit etc. Im the only active member left in the gang so all my money is stuck in gang funds. So when switching computers your gang role is removed. 

### Expected behaviour

Cant withdraw my money its all in gang funds.

### Steps to reproduce

Log onto another device.

### Any Texture Packs? (If so list)

n/a

### CMG User ID

320447

**Comment by crazychris2404** [comment]
This has been forwarded and is being investigated

**Comment by packfile** [comment]
This should have been fixed since the 19th Dec
