### ISSUE TITLE
[Bug]: £ sign in G4S job

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

During the G4S job, the £ sign that floats, it is upside down. 

### Expected behaviour

Should be £, not upside down.

### Steps to reproduce

1. Do G4S job.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

205070

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
