### ISSUE TITLE
Phone - outgoing and incoming calls not appearing

### ISSUE THREAD

**Issue by Xotiic1** [CMGStudios/issue-tracker#90]
**Describe the issue you're facing**
Phone not showing who is calling me or who I'm calling

**Steps to reproduce**
get called by anyone or phone anyone

**Expected behaviour**
should play a ringtone and show me who's calling

**Screenshots/Video**
https://streamable.com/n7ejmb

**Additional context**
someone said in game support that its happening to them as well . also when I get a message it doesn't tell me either

**Any Texture Packs (if so list)**
NVE with starry sky

**Perm ID**
90861

**Comment by alfiellds** [comment]
Hello thank you for the report. The developers will review this issue shortly.

In the meantime, could you please confirm whether this occurs all the time, or just sometimes. If this only occurs sometimes could you please provide information regarding any usage of the phone up to ￼the issue occurring? 

Many thanks.

**Comment by Xotiic1** [comment]
it happens all the time the only reason I can tell I'm getting a phone call is when it goes to my ear

**Comment by Xotiic1** [comment]
also volume is 100% and dnd is set to false

**Comment by alfiellds** [comment]
Hello, thank you for the information. I will try and reproduce this myself in the morning and will forward it to the developers then.

Many thanks.

**Comment by Xotiic1** [comment]
this is fixed now

**Comment by rubbertoe98** [comment]
Please let me know if this is now fixed.

**Comment by Xotiic1** [comment]
yea its fixed
