### ISSUE TITLE
[Bug]: policerobot

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when you spawn a police robot it says its spawned but you cant see it. it doesn't work

### Expected behaviour

To see the police robot

### Steps to reproduce

Have Robot Trained in mps discord
type /policerobot

### CMG User ID

9975

**Comment by crazychris2404** [comment]
Confirmed 
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
