### ISSUE TITLE
[Bug]: Radio Menu freezes

### ISSUE THREAD

**Issue by ScarabMonkeyy** [CMGStudios/issue-tracker#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when doing the /radios command the UI pops up 
if you press ESC instead of the X in the middle to back out of it then it becomes stuck and you have to relog 

### Expected behaviour

menu should go away when i press ESC or not be frozen

### Steps to reproduce

1-/radios
2-at the menu press ESC to back out instead of X 

### Any Texture Packs? (If so list)

Natural Vision Evolved 

### CMG User ID

369718

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
