### ISSUE TITLE
[Bug]: event bug

### ISSUE THREAD

**Issue by ThroughAGame** [CMGStudios/issue-tracker#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This could be a bug for all events but this was experienced when I tried to join battlegrounds.
When you /joinevent and in the middle of doing something that could later kill you, it ends up bugging and prevents you from playing the event as you normally do.
In my case I was flying a heli and joined the event and I guess my heli crashed after I joined the event and then whilst waiting for battlegrounds to start I died and it bugged it all out from my POV and I had to restart CMG. I respawned in the middle of the air once I loaded back in.

### Expected behaviour

Not bug out and kill you.

### Steps to reproduce

1. Do something that may kill you shortly after doing /joinevent e.g. going underwater, or in my case flying a heli.
2. /joinevent when it starts.
3. Once the regular CMG bucket version of you dies, it bugs out the event for you.

### Any Texture Packs? (If so list)

n/a

### CMG User ID

205070

**Comment by crazychris2404** [comment]
Can you provide a clip of this please

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
