### ISSUE TITLE
UKBF player blip name show up as *invalid*

### ISSUE THREAD

**Issue by ScarabMonkeyy** [CMGStudios/issue-tracker#907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When being on any faction and having the show player blip setting turned on 
Being near UKBF will not show their real name but instead show up as *invalid*

### Expected behaviour

When approaching a player blip it should show their real name like Scarabmonkey not *invalid*

### Steps to reproduce

1- make a person clock on ukbf
2- do /blipson
3-turn on show player blips in the F2 misc menu
4-when enlarging the map you will notice the UKBF officer name is showen as *invalid*

### Any Texture Packs? (If so list)

Natural Vision Evolved but this issue is with everyone i have asked about in ukbf

### CMG User ID

369718

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for the next scheduled restart
