### ISSUE TITLE
[Bug]: tv/speaker systems does not work

### ISSUE THREAD

**Issue by Mitch01159** [CMGStudios/issue-tracker#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

everytime i try use my tv it doesnt connect to videos it just says unavailable ive tryed to the same videos in my friends house and it works in there and i have the same problem with the speaker systems on the /djmenu i have had a admin out and they confirmed this and told me to push a bug report to get this sorted and said it must be the house that is bugged out. my name  on the game is 
mitch_0115 - ID 362140
and the apartment is the tahitan room 6

### Expected behaviour

put all in the description

### Steps to reproduce

to get all working 

### CMG User ID

362140

**Comment by packfile** [comment]
Some videos are unable to be played (due to copyright / being music videos?). As long as the video you want to play doesn't fall into those categories it should be fine (see `AF9k7PSq3p4` playing, but `IdneKLhsWOQ` does not)
