### ISSUE TITLE
[Bug]: First prompt not showing up after landing.

### ISSUE THREAD

**Issue by SmugSug** [CMGStudios/issue-tracker#909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Tupolev Tu-144D (1:8 lock)-(spawncode: tu144d), the first prompt does not pop up after landing, forcing the player to jump out of the plane and back in to solve this. This happens 100% of the time in the pilot ped but also the standard male ped.
Clip of this happening: https://streamable.com/ebvcip
Previously confirmed by @Simonstv as it was happening to him as well in; https://github.com/CMGStudios/issue-tracker/issues/857

### Expected behaviour

Be able to land at Sandy Airfield and not have to get out of the plane for the prompt to show up.

### Steps to reproduce

1. Be a male/pilot ped
2. Start the pilot job in the Tupolev 144D.
3. Get a pick-up/drop-off at Sandy.
4. Prompt after landing won't appear.
5. Jump out then back in to continue as normal.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

922

**Comment by packfile** [comment]
@SmugSug Can you check if this issue is happening from the latest restart? There was a fix done to an unrelated issue which (may) have fixed this as well

**Comment by SmugSug** [comment]
@packfile after a few test flights, the issue still persists. Although this issue seems to magically not be an issue anymore at level 100, attempting to get it fixed for other people who may use the plane.

**Comment by packfile** [comment]
This is quite difficult to reproduce, please reopen if you're able to obtain reliable reproduction steps
