### ISSUE TITLE
DVLA driving test bugged

### ISSUE THREAD

**Issue by RealistSaid** [CMGStudios/issue-tracker#91]
Report for someone else

When trying to do driving test, takes money and doesnt load test

Steps to reproduce - go to test centre and click start driving test

Expected behaviour - Driving test to take money and start the test

Screenshots/Video - https://www.youtube.com/watch?v=bnPAWQhJ2Q4

Perm ID - 49926

**Comment by alfiellds** [comment]
Hello Realist, thank you for reporting this on behalf of another player.

I have been unable to reproduce this issue, however. This may be an issue occurring specifically for the person in the video.

Could you please ask them whether the have previously held a full driving license on CMG and whether or not they have L plates on their vehicle when they pull it out?

Many thanks.
