### ISSUE TITLE
[Bug]: policerobot

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using /policerobot the camera doesn't work and when yo delete the police robot there is still a "hitbox" left 

### Expected behaviour

to have a working camera as well as the model to be removed after deleting the robot

### Steps to reproduce

have the correct permissions 
type /policerobot
try to open camera 
type /policerobot to delete again 

### Any Texture Packs? (If so list)

nve

### CMG User ID

9975

**Comment by packfile** [comment]
I can't reproduce this issue in the live or dev server, do you have any additional reproduction steps?

**Comment by DjDoon** [comment]
Steps to reproduce
Be on the "policerobot" whitelist (have the role in discord)
clock on pd 
type /policerobot

it should spawn, when spawned you cannot access the camera and the collisions are still there after removing it. 
https://medal.tv/games/gta-v/clips/1Pu7BqwUI2zuDQ/d1337ZaGO9vJ?invite=cr-MSx5bUosNDE3Mzg1MDgs

**Comment by DjDoon** [comment]
Still have issues with the model still being there after its removed, and handling file makes it very easy to flip

**Comment by packfile** [comment]
![image](https://github.com/CMGStudios/issue-tracker/assets/97990837/c35463d0-efc2-46cd-8d1a-49d8eca0dd91)
![image](https://github.com/CMGStudios/issue-tracker/assets/97990837/97f1535a-9544-411d-9ffb-47cb70b9871e)
I still am unable to reproduce your report. Testing in the live server it spawns fine, camera works and it deletes correctly. To investigate further reliable reproduction steps will need to be provided
