### ISSUE TITLE
[Bug]: Cant Withdraw From Funds

### ISSUE THREAD

**Issue by willb07** [CMGStudios/issue-tracker#912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can't Withdraw Any Money Either Can My Other Mate's In The Gang

### Expected behaviour

Withdraw Money

### Steps to reproduce

1. Have Advanced Gang License
2. Try Withdraw Something
https://cdn.discordapp.com/attachments/1142887078095503421/1195824796257243236/image.png?ex=65b565a0&is=65a2f0a0&hm=b37cc66fa4fff6881f98a474390bfe2909df528d54decb7292ee67d3e37d350a&

### Any Texture Packs? (If so list)

N/A

### CMG User ID

1088

**Comment by packfile** [comment]
@willb07 Is this issue still persisting from the latest restart?

**Comment by packfile** [comment]
No response, closing
