### ISSUE TITLE
[Bug]: Cannot access boot 

### ISSUE THREAD

**Issue by Galooga** [CMGStudios/issue-tracker#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open my boot it say unable to use inventory, please try again later.

### Expected behaviour

When I open my boot it say unable to use inventory, please try again later. I now have waited 3hrs and refreshed my game and PC 4 times. I had a lot of valuable stuff in there and now I cant access it.

### Steps to reproduce

You press (E) on your vehicle and select open boot and it pops up a message saying unable to use inventory, please try again later. The stuff that is supposed to be in there is not appearing.

### Any Texture Packs? (If so list)

N

### CMG User ID

401389

**Comment by Keegasity** [comment]
Good Evening,

I have contacted yourself via discord. I will help you there
