### ISSUE TITLE
[Bug]: wager rounds often end after only 1 person dying in 2v2s

### ISSUE THREAD

**Issue by 2801M** [CMGStudios/issue-tracker#915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

wager round ends after 1 player dying rather than both of a team

### Expected behaviour

round ends after 1 person dying

### Steps to reproduce

play wager and die

### Any Texture Packs? (If so list)

no

### CMG User ID

2801

**Comment by Keegasity** [comment]
Thank you for the report.

This issue cannot be replicated and after testing wagers in 2v2's I can confirm these are working as intended.

Wager still continues if a member of your team dies
