### ISSUE TITLE
[Bug]: UKBF not being able to pull handcuffed people out of cars

### ISSUE THREAD

**Issue by ScarabMonkeyy** [CMGStudios/issue-tracker#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

as UKBF when putting someone in a transport van, ALT+F becomes useless as you are not able to pull a handcuffed person out a car like you should be able to but instead need to despawn ur van

### Expected behaviour

when putting a handcuffed person in a van then pressing ALT+F should take them out the van

### Steps to reproduce

1-handcuff someone
2-put them in any vehicle
3-as ukbf press ALT+F
4-person will still be in van

### Any Texture Packs? (If so list)

Natural Vision Evolved 

### CMG User ID

369718

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this is fixed from the next restart
