### ISSUE TITLE
[Bug] stuck inside my gang

### ISSUE THREAD

**Issue by Stokes114** [CMGStudios/issue-tracker#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi i cant leave my gang in game and need help as i have 0% control of the gang so therefore i am stuck inside the gang.

### Expected behaviour

it says “you cannot leave if u are the only person in there”, so i try disband the gang but i have 0% control of the gang therefore i am stuck inside of the gang.

### Steps to reproduce

1. f5     2. settings.    3. leave gang/disband gang

### CMG User ID

176232

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
