### ISSUE TITLE
Prison Sentencing - Bus Driver Teleportation

### ISSUE THREAD

**Issue by nSpexx** [CMGStudios/issue-tracker#92]
**Describe the issue you're facing**
When someone gets sentenced to prison it teleports them into the HM Prison Bus and allows the player to drive around.

**Steps to reproduce**
Fix?

**Expected behaviour**
Ruins rp.

**Screenshots/Vi 
**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**
147339

**Comment by arthur-rl** [comment]
Please follow this before making an issue: https://github.com/CMGStudios/issue-tracker/issues/89

**Comment by rubbertoe98** [comment]
Fixed from next restart.
