### ISSUE TITLE
[Bug]:outfit

### ISSUE THREAD

**Issue by jayaprila** [CMGStudios/issue-tracker#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 i changed my job to working for burger shot now my character had change as well as my cloths and i cant change my  cloths as i don't want to work for burger shot 

### Expected behaviour

cant change my outfit

### Steps to reproduce

na

### Any Texture Packs? (If so list)

na

### CMG User ID

403050

**Comment by packfile** [comment]
If you find a nearby clothing store (indicated by a green shirt on the map) you can change back to your original character there
