### ISSUE TITLE
[Bug]:  bugged mlo ...............................................................................................

### ISSUE THREAD

**Issue by martyq95** [CMGStudios/issue-tracker#922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Bug]:  hello i av been renting the vineyard manison out for 4 weeks at a time an fella i rented it to got his id changed an cancel the rent an now its not showing up on my map an i cant rent it back out i need help with this please 

### Expected behaviour

need help with my mlo    ....................................................................

### Steps to reproduce

............................................................................................

### Any Texture Packs? (If so list)

no

### CMG User ID

268120

**Comment by Simonstv** [comment]
Hello, Thank you for your report would you be able to get any additional information on this with a clip or something or even the steps to help us out more to see whats happening in more detail.

**Comment by packfile** [comment]
Closing, can be reopened once the requested information is provided
