### ISSUE TITLE
[Bug]:  Payment Plan Bug 

### ISSUE THREAD

**Issue by BRMYX** [CMGStudios/issue-tracker#923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi. So I have sold a car through the payment plan ingame system. When I go to the garage it says buyer paid first week. It’s 12.2m. I’m being told that money should go straight into my CMG account? I know it hasn’t because I have £0 in my cash & card type. 

Obviously now I’m a week out, have no funds for it but it did say the buyer has paid the first week. 
where’s the money gone? 
![IMG_5454](https://github.com/CMGStudios/issue-tracker/assets/158031670/cd6293d8-8dd8-4d52-be0c-5005a82a049a)

### Expected behaviour

 Described above

### Steps to reproduce

 Not sure 

### Any Texture Packs? (If so list)

No

### CMG User ID

389150

**Comment by packfile** [comment]
> — 22/01/2024 10:49 393138(Incentiuis) paid £12,222,223 towards the payment plan for vehicle 165781 sold by 389150(RMX)

Logs indicate this payment went through, it should've gone into your bank account. I note since there have been 3 additional payments from the buyer for this PP, I presume they've gone into your bank account fine?

**Comment by BRMYX** [comment]
Yes that first payment I opened a request about, I definitely never had
that go in to my account or bank etc. how ever since then the payments have
been working fine. But still I have 100% not seen the first £12.222.223

**Comment by packfile** [comment]
Unfortunately there is not enough information to go off here, the logs indicate this payment was successful and both parties had their balance adjusted accordingly. If you have any other information to attach please reopen the issue
