### ISSUE TITLE
[Bug]: Stuck in house

### ISSUE THREAD

**Issue by MewPrincess5** [CMGStudios/issue-tracker#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Stuck in a players house after being carried in

### Expected behaviour

stuck in house can't get out

### Steps to reproduce

Player carried me, then he went into house.

### CMG User ID

407833

**Comment by crazychris2404** [comment]
Confirmed 
This is an issue that I have seen before a potential fix would be not being able to carry other players into a house

**Comment by packfile** [comment]
Thanks for the report, this is fixed from the next restart
