### ISSUE TITLE
[Bug]: my loot disappeared 

### ISSUE THREAD

**Issue by jayaprila** [CMGStudios/issue-tracker#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

all my loot in my car disappeared and my knife that was on me disappeared as well 

### Expected behaviour

my stuff went missing 

### Steps to reproduce

all my loot in my car disappeared and my knife that was on me disappeared as well 

### Any Texture Packs? (If so list)

na

### CMG User ID

403050

**Comment by Ryddddd** [comment]
there was a boot wipe.....

**Comment by crazychris2404** [comment]
This is intentional

**Comment by jayaprila** [comment]
what about my knife i had that was on me

**Comment by crazychris2404** [comment]
You loose it as it’s a monthly bootwipe

**Comment by crazychris2404** [comment]
You lose it as part of the monthly bootwipe
