### ISSUE TITLE
Characters are escaped when they don't need to be, resulting in visible backslashes

### ISSUE THREAD

**Issue by jowsey** [CMGStudios/issue-tracker#93]
**Describe the issue you're facing**
In the rules section of the F1 menu, and possibly some other places, backslashes are visible before characters like apostrophes. It'd seem this was to escape them, however they seem to be escaped anyway, so the backslashes are visible.

**Steps to reproduce**
View the page content in the Rules section of the F1 menu

**Expected behaviour**
Backslashes should not be visible before characters

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/36897817/126840551-171c07fd-27bd-4442-a9f0-4efd9ea97ff8.png)

**Perm ID**
Unknown

**Comment by rubbertoe98** [comment]
Fixed on next server update.
