### ISSUE TITLE
[Bug]: ID swap in /store

### ISSUE THREAD

**Issue by glz444** [CMGStudios/issue-tracker#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have tried pretty much all of the ids on the list and they all say "this perm id has been redeemed by another player"

I have also had a admin confirm that the id i was trying to get is not taken by another player.

![image](https://github.com/CMGStudios/issue-tracker/assets/158830256/66d263a3-a83f-48d7-9317-987e70208a69)
![image2](https://github.com/CMGStudios/issue-tracker/assets/158830256/3214f1a4-0cab-4c9a-b858-914d899e0a22)

### Expected behaviour

should change

### Steps to reproduce

none

### Any Texture Packs? (If so list)

none

### CMG User ID

242997

**Comment by crazychris2404** [comment]
This should now be fixed if it is not please reopen this issue
