### ISSUE TITLE
[Bug]: no verification code

### ISSUE THREAD

**Issue by Vskarzy** [CMGStudios/issue-tracker#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i try connect to CMG it says im permanent ban even though this is my first time playing CMG.

### Expected behaviour

i am also not recieving any 6 digit verification code

### Steps to reproduce

.

### CMG User ID

407700

**Comment by Keegasity** [comment]
Hello,

This is not a bug and you will need to open an unban appeal via the CMG Forums.

Any problems please message me.
