### ISSUE TITLE
[Bug]: PNC Sometimes Breaks

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The PNC sometimes breaks and doesn't let you lookup a person. Noticed it happens with newer players.

Pressing search showing nothing: 
![image](https://github.com/CMGStudios/issue-tracker/assets/62995181/575cdf08-e38e-4fca-8772-a4e07f5d394a)

and in my F8 it outputs (once each time I press search):
![image](https://github.com/CMGStudios/issue-tracker/assets/62995181/4e782079-74ce-4f9c-97c9-d9c8afbd40aa)

### Expected behaviour

Should be able to search the player just fine.

### Steps to reproduce

1. Grab an ID when clocked on police
2. Run it on the PNC

### Any Texture Packs? (If so list)

N/A

### CMG User ID

2000

**Comment by DjDoon** [comment]
Just to add on this, if theres a player who hasn't changed their in-game name through the city hall it wont show up in the PNC. This limits rp so it would be nice if someone could look into it. 

A possible fix could be to "force" new players to change it for free in the tutorial

**Comment by Simonstv** [comment]
Thank you for the above report, i can confirm this is reproduceable from what the above have said this will be forwarded on to a developer team.

**Comment by packfile** [comment]
@ItsJunction When/If this happens again can you please provide the log file or F8 console as there should be additional information now

**Comment by ItsJunction** [comment]
@packfile Nothing in logs or F8 besides the same error message - Temp ID was 561 (or perm 409013). Same issue regardless of manually inputting or not

![FiveM_b2545_GTAProcess_6QPKHKXGts](https://github.com/CMGStudios/issue-tracker/assets/62995181/1531b5df-287b-4935-93f8-63a03c22fe03)
