### ISSUE TITLE
[Bug]: Voice Chat Gets Stuck Talking

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sometimes when holding your Push-To-Talk key, it gets stuck on talking

Not sure of any fixes other than relogging as doing `/vsync` and turning voice chat on/off doesn't fix it.

### Expected behaviour

Should not continue talking after I let go of my PTT key

### Steps to reproduce

1. Press your push-to-talk key
2. Let go

### CMG User ID

2000

**Comment by crazychris2404** [comment]
Hi @ItsJunction 

can you provide steps to reproduce this issue

**Comment by Simonstv** [comment]
In response to the above try to do the following and let us know if you have any success with it in the mean time ~ bind two push to talks

**Comment by ItsJunction** [comment]
Tried it just now and it didn't seem to sort it 😕

**Comment by MrMikeyTV** [comment]
This has become more and more of an issue as of late. I have had to relog 4/5 times to prevent the bug. A lot of the time it can happen when tabbing out as well.

**Comment by PIKAlmao** [comment]
I can confirm. had it happen two times this evening. Had to check whether i'm speaking in-game before i say something on discord. Fix this shite asap pls (adding a secondary bind for voice chat doesn't fix it neither)

**Comment by packfile** [comment]
Thanks for the report, unfortunately without reliable reproduction steps this can not be investigated
