### ISSUE TITLE
[Bug]: I paid 250,000,000 million for a bear and iv bin unable to ride it now for 3 weeks after making multiple in game tickets

### ISSUE THREAD

**Issue by canadiang420** [CMGStudios/issue-tracker#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

B

### Expected behaviour

B

### Steps to reproduce

B

### CMG User ID

318382

**Comment by Simonstv** [comment]
Thanks for the report please give us time to look into this.

**Comment by packfile** [comment]
Can you please elaborate on where the issue is occurring? Such as it doesn't display in the pet menu, pressing the button does nothing, etc

**Comment by canadiang420** [comment]
So 2 days ago I am able to become the bear, but when first bought I used to ride the bear as it says, I become the bear and when people see a bear they shoot on site. Being on top of bear as intended would be nic**

**Comment by canadiang420** [comment]
Yes press ride and I become the bear not ride the bear
