### ISSUE TITLE
[Bug]: I was banned for a day and now its not letting me enter CMG

### ISSUE THREAD

**Issue by 1GIANNI1** [CMGStudios/issue-tracker#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2024-02-14 100540](https://github.com/CMGStudios/issue-tracker/assets/160009310/b70b7f4e-8ee8-4031-bff4-2b19869e42de)

### Expected behaviour

I was banned and the time of being banned is past so im supposed to play

### Steps to reproduce

Chek if im still banned 

### CMG User ID

408450

**Comment by Keegasity** [comment]
Your ban duration has expired. You can now join CMG
