### ISSUE TITLE
[Bug]: Unable to take photos on the phone.

### ISSUE THREAD

**Issue by ashfaq2345** [CMGStudios/issue-tracker#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am trying to take pictures on my lb phone in game, when i open the camera app it takes the photo and it is visible in the little preview in the bottom left. However when you open the photo it is just a white screen, the photo does not load. This also happens on the birdy app, im unable to upload photos because they do not load and just show a blank image.

### Expected behaviour

When you take a photo and click it to view, it should come up and not be a white screen.

### Steps to reproduce

1. Open camera app
2. take photo
3. open photos app
4. you will see the photo is not able to be seen.

### Any Texture Packs? (If so list)

n/a

### CMG User ID

409712

**Comment by Simonstv** [comment]
Thanks for the Report - I can can confirm after reproducing these steps, 
that there seems to be an issue with this, and this will now be forwarded on to the developer team.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed for any photos and videos taken since Monday
