### ISSUE TITLE
[Bug]: script error Lua

### ISSUE THREAD

**Issue by FakeD4N** [CMGStudios/issue-tracker#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

script error:Chat/cl_chat.lua:49: no such export getplayername in resource cmg

keep getting this error when trying to load into CMG, Was perfectly fine last night.

### Expected behaviour

script error:Chat/cl_chat.lua:49: no such export getplayername in resource cmg

keep getting this error when trying to load into CMG, Was perfectly fine last night.
![image](https://github.com/CMGStudios/issue-tracker/assets/160053691/cdbce1d7-cc5e-423a-a50a-356c6f08f740)

### Steps to reproduce

Tried Deleting cache files to see if fix's. Tried restarting computer. Have also tried Running as Admin.

### Any Texture Packs? (If so list)

No

### CMG User ID

402917

**Comment by crazychris2404** [comment]
Is this still occurring ?

**Comment by Simonstv** [comment]
Thanks for the Report - This isn't occurring now and i believe it has been fixed! since people aren't have any more issues today.
