### ISSUE TITLE
[Bug]: not letting me activate my Whitelist weapon after being away for longer than 4 months. 

### ISSUE THREAD

**Issue by jmb20002** [CMGStudios/issue-tracker#941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, so I recently got unbanned after a two year perm and wanted to come back and buy my gun. I activated it 3 days ago and tried activating every day so far that I’ve been back and I still can’t buy my weapon.

### Expected behaviour

Not being able to purchase my weapon/activate my weapon after being away for longer than 4 months. 

### Steps to reproduce

1. Go to purchase my weapon, 2. Activate my weapon, 3. Wait 24 hours, 4. It doesn’t activate and going around in a repeat cycle. 

### CMG User ID

724

**Comment by Simonstv** [comment]
Thank you for your report, this will be forwarded however do you have a clip of it happening to which could also be useful to see it happening from your POV?

**Comment by jmb20002** [comment]
> Thank you for your report, this will be forwarded however do you have a clip of it happening to which could also be useful to see it happening from your POV?

- a clip wouldn’t be of any Use as it only lets you buy gun after sever restart (supposedly). I just press the activate weapon button, it says bottom left it will be in the city after next restart and rinse repeat. Gun never gets imported

**Comment by packfile** [comment]
@jmb20002 Can you please provide the name of the weapon you're trying to activate

**Comment by jmb20002** [comment]
Yes it’s the Huff N Puff SMG. - identical to the Spaceflight… that is a different issue though.

**Comment by packfile** [comment]
Thanks, this has been fixed for next Monday (please try activating it then)
