### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hgleed** [CMGStudios/issue-tracker#942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

cant get in the server and loads of people are facing the same issue

### Expected behaviour

connection failed

### Steps to reproduce

[Window Title]
Error GTA5_b2545.exe!sub_141330C0C (0x60)

[Main Instruction]
RAGE error: ERR_ANI_POOL_2

[Content]
A game error (at 0000000141330c71) caused the game to stop working.

Game memory error. Please reboot and restart the game.

[^] Hide details  [Save information] [Close]

[Expanded Information]
You can press Ctrl-C to copy this message and paste it elsewhere.21082598---------------------------
CitizenFX
---------------------------
Saved the crash dump as C:\Users\hglee\AppData\Local\Temp\CfxCrashDump_2024_02_14_19_05_24.zip. Please upload the .zip file when you're asking for support. (copy/paste to upload)
---------------------------
OK   
---------------------------

### Any Texture Packs? (If so list)

nve

### CMG User ID

236374

**Comment by crazychris2404** [comment]
This should now be resolved as was an issue outside of CMG
