### ISSUE TITLE
have eyelashes on my hair

### ISSUE THREAD

**Issue by stylescomer** [CMGStudios/issue-tracker#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

looks like pair of eyelashes in my hair

### Expected behaviour

annoying

### Steps to reproduce

tried to change hair and makeup

### CMG User ID

398780

**Comment by Simonstv** [comment]
This doesn't seem to be a bug if it is then please upload a video, of it as of right now this isnt an issue as i cant seem to to get it my self.
