### ISSUE TITLE
Farming Job (Bug ?)

### ISSUE THREAD

**Issue by PIKAlmao** [CMGStudios/issue-tracker#944]
[When doing the farming job, i am collecting all of the objectives (yellow markers - Drive on the field to plant seeds) getting my (area planted) to 100% and i'm not receiving another prompt nor payout after completing the field. Is this a bug or am i missing something ? I have tried relogging, clocking off and back on repeatedly and haven't succeeded in getting it to work](https://youtu.be/MPO76RGsjT4)

**Comment by PIKAlmao** [comment]
Just hopped on again to see if anything had changed. Believe it may just be that action/job in particular **"drive on the field to plant seeds"**, as since logging back on today, i was given a different action/job which was **"Harvest the remaining crops with your tractor"**, managed to get it down to zero (harvest all of them), and then was given a payout and a prompt after, which was to do that same bugged action/job and still had no luck.

**Comment by Simonstv** [comment]
Thanks for the report, after also trying the above, i can confirm this is an issue and will forward it on to the developer team, thank you.

**Comment by packfile** [comment]
Thanks for the report, this is fixed from the next restart
