### ISSUE TITLE
[Bug]: I have a nill perm id

### ISSUE THREAD

**Issue by Marshmallow3535** [CMGStudios/issue-tracker#945]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

My perm id is nil and my escape menu doesnt work as a result of that.

### Expected behaviour

I should have been assigned a perm id

### Steps to reproduce

No idea, ive never had one

### CMG User ID

nil

**Comment by packfile** [comment]
This is likely a visual bug with the UI, please reconnect and it will display. Alternatively you can do `/getmyid` in chat to display it
