### ISSUE TITLE
[Bug]: In game Payment Plan

### ISSUE THREAD

**Issue by H4AYCH** [CMGStudios/issue-tracker#946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I had a car on payment plan through the in game payment plan system it was an RSQ3 DARWIN spawncode: (RSQ3DARWIN) so the last payment of the car was made on 28/01/24 and i had the  missed weeks on 1 week so i should of had it back on 04/02/24 but now it has been over the week which now coming up to 3 weeks and I have not revived my car back from the failed payment so I know the payment plan is bugged so could you please sort out this issue 

### Expected behaviour

I Should of had the car back into my garage automatically after the failed payment plan.

### Steps to reproduce

Could you please fix the in game payment plan so this issue doesn't occur again.

### CMG User ID

217458

**Comment by packfile** [comment]
>  — 18/02/2024 at 22:00 Returned vehicle 333323 to 217458(HAYCH) as 243294(ed) failed payment with no missed weeks remaining.

Thanks for the report, vehicle was returned yesterday. This will be investigated however at it appears it was a week delayed.
