### ISSUE TITLE
[Bug]: No option to spawn at VIP island after death even though I own premium 

### ISSUE THREAD

**Issue by Z21X** [CMGStudios/issue-tracker#947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I purchased The premium rank upgrade from supporter a while ago and I have never since been able to ever have the option to spawn at the VIP island

### Expected behaviour

upon death anyone who owns the rank premium usually has the option to spawn at VIP island where as I have never had the option upon owning the premium rank

### Steps to reproduce

Upon any death There is never an option to spawn at VIP island

### CMG User ID

238336

**Comment by packfile** [comment]
Thanks for the report, you should be able to spawn at VIP Island now
