### ISSUE TITLE
[Bug]: heist set up

### ISSUE THREAD

**Issue by 2801M** [CMGStudios/issue-tracker#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

for the 750k heist set up for fleeca banks you are unable to grappel onto the boat meaning you cant complete the mission

### Expected behaviour

cant grappel in the heist setup onto the boat

### Steps to reproduce

do the heist and go to grappel

### Any Texture Packs? (If so list)

no

### CMG User ID

2801

**Comment by crazychris2404** [comment]
Duplicate with https://github.com/CMGStudios/issue-tracker/issues/951
