### ISSUE TITLE
Phone always in do not disturb when logging in

### ISSUE THREAD

**Issue by Jason664733** [CMGStudios/issue-tracker#95]
**Describe the issue you're facing**
Every time i log in my phone is in do not disturb mode and i have to change it to get calls.
**Steps to reproduce**

**Expected behaviour**
Phone should have do not disturb off when logging in
**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**
always day
**Perm ID**

**Comment by arthur-rl** [comment]
Hi Jason, can you do `/debugmode` and get someone to call you when you log in please. And then can you send over your latest log file.

**Comment by Jason664733** [comment]
Where do i find the log file

**Comment by arthur-rl** [comment]
> Where do i find the log file

%localappdata%/FiveM/FiveM.app/logs

**Comment by Jason664733** [comment]
[CitizenFX_log_2021-07-25T193714.log](https://github.com/CMGStudios/issue-tracker/files/6874518/CitizenFX_log_2021-07-25T193714.log)

**Comment by arthur-rl** [comment]
This is not the correct log file. I need the one of the time when someone rang you and /debugmode was a enabled.

**Comment by Jason664733** [comment]
[CitizenFX_log_2021-07-25T200325.log](https://github.com/CMGStudios/issue-tracker/files/6874535/CitizenFX_log_2021-07-25T200325.log)

**Comment by Jason664733** [comment]
Is this the correct file?

**Comment by alfiellds** [comment]
Awaiting response from @arthur-rl.

**Comment by rubbertoe98** [comment]
Fixed earlier this week.
