### ISSUE TITLE
[Bug]: Can't Buy Speed Gun

### ISSUE THREAD

**Issue by ItsJunction** [CMGStudios/issue-tracker#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As of yesterday's update, you are unable to buy a speed gun from the police armoury. https://streamable.com/0fkrrl

### Expected behaviour

Should be able to buy a speed gun.

### Steps to reproduce

1. Clock on and go to the armoury
2. Buy a speed gun

### CMG User ID

2000

**Comment by packfile** [comment]
Thanks for the report, this should be fixed from the next scheduled restart (in 20 mins). Are you able to confirm if this is still an issue after?

**Comment by ItsJunction** [comment]
No longer an issue
