### ISSUE TITLE
[Bug]: I was mid bet when the server crashed

### ISSUE THREAD

**Issue by Ili-25** [CMGStudios/issue-tracker#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was placing a bet on the blackjack table when the server restarted and then lost the hand, loaded back in the server and did not receive the money back.

### Expected behaviour

I also have a clip of the incident, thank you.[](https://medal.tv/games/gta-v/clips/1WvU5lRazUqsTy/d1337JcYeDPa?invite=cr-MSxWQWMsMTk1NzI5Mzk4LA)

### Steps to reproduce

n/a

### Any Texture Packs? (If so list)

n/a

### CMG User ID

363394

**Comment by packfile** [comment]
Can you please provide the clip @Ili-25

**Comment by crazychris2404** [comment]
Closed due to no response
