### ISSUE TITLE
[Bug]: Unable to drag as NHS within the prison grounds.

### ISSUE THREAD

**Issue by R9FVR** [CMGStudios/issue-tracker#953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While clocked on NHS, you are unable to drag a player with alt + a

### Expected behaviour

The ability to drag players.

### Steps to reproduce

Go within the prison grounds
Attempt to drag player with alt + a

### CMG User ID

21

**Comment by 2140CMG** [comment]
https://streamable.com/4ebp08 pressing Alt + A just operates the radio, you can't drag at all

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
