### ISSUE TITLE
[Bug]: my inventory closes when i click

### ISSUE THREAD

**Issue by OLIVER0184** [CMGStudios/issue-tracker#956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i open my inventory and click on a item and it closes my inventory

### Expected behaviour

when i open my inventory it closes when i click on my screen 

### Steps to reproduce

1. open my inventory 2. i click 3. it disappears

### Any Texture Packs? (If so list)

i have none

### CMG User ID

404024

**Comment by packfile** [comment]
Are you using the new or legacy inventory UI?

**Comment by OLIVER0184** [comment]
ive tryed fixing with both rn the new

**Comment by packfile** [comment]
@OLIVER0184 Do you have your left click bounded to `L` or `ESC`, as these are the only two buttons that would close the UI?
You could also try changing the mouse input mode in GTA settings?

**Comment by crazychris2404** [comment]
Closed due to no response
