### ISSUE TITLE
[Bug]: Invetory closes when i click

### ISSUE THREAD

**Issue by OLIVER0184** [CMGStudios/issue-tracker#957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i open my inventory try click a item and it closes it 

### Expected behaviour

i have tried fixing it on both inventory's

### Steps to reproduce

1. open inventory 2. click a item 3. closes

### Any Texture Packs? (If so list)

i have none 

### CMG User ID

404024

**Comment by packfile** [comment]
Duplicate of #956
