### ISSUE TITLE
[Bug]: No perms in f5

### ISSUE THREAD

**Issue by Kenzie247** [CMGStudios/issue-tracker#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Removed my self tryna remove another person with the same name from my gang f5

### Expected behaviour

No perms in my f5 and have advanced gang licence so cant make a new one

### Steps to reproduce

N/A

### Any Texture Packs? (If so list)

No

### CMG User ID

1281]

**Comment by crazychris2404** [comment]
This will be resolved by a developer for you

**Comment by packfile** [comment]
You're showing as having full gang permissions now, please let us know if this is still an issue
