### ISSUE TITLE
[Bug]: ELS Broken

### ISSUE THREAD

**Issue by DjDoon** [CMGStudios/issue-tracker#959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The ELS on police vehicles does not work. was a issue yesterday and worked fine earlier today, but broke 10 minutes ago

### Expected behaviour

I would like to have ELS on my PD vehicles

### Steps to reproduce

Grab a pd vehicle
press Q

### Any Texture Packs? (If so list)

N/A

### CMG User ID

9975

**Comment by crazychris2404** [comment]
This is a known issue and being investigated affects all vehicles with ELS

**Comment by crazychris2404** [comment]
A fix has been put in place if this occurs again please DM me your log file from the day and i will forward to developers
