### ISSUE TITLE
[Bug]: My whitelist weapon doesnt activate after restart when you choose to activate after restart

### ISSUE THREAD

**Issue by Stinky1x** [CMGStudios/issue-tracker#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i have just came back to playing and i tried to buy my whitelist ar (WF Red Tiger) and it gave me the option to activate it for next restart. It came to next restart and it just gave me the same result, i have been trying this everyday for the past 2 weeks

### Expected behaviour

The gun becomes activated after next restart and is able to be bought

### Steps to reproduce

Go to a gunstore where you can buy the whitelisted weapon (large arms, premium large arms with cmg club at vip)
buy the whitelisted weapon
activate gun for next restart

### Any Texture Packs? (If so list)

no

### CMG User ID

981

**Comment by crazychris2404** [comment]
Please make a gun ticket in the donation support discord
