### ISSUE TITLE
Bug PNC not working and freezes my game

### ISSUE THREAD

**Issue by Flinny-k** [CMGStudios/issue-tracker#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I press keybind for PNC or do t/PNC it freezes my game and brings up the mouse as if there should be something to interact with on screen but no PNC comes up and in order to unfreeze my screen i have to press the home key.  none of my other buttons work while this is happening except F8 and the home button.  cant PTT. before i realised the home button was able to unfreeze it I had to keep relogging.  I have cleared the caches on Five M  to see if that would help, i have also rebound it to another key.  I am brand new to PD so have never had to try this before.  Never experienced anything like this.  On one clip i tried T/reset first to see if that helped.
https://medal.tv/games/gta-v/clips/1XOHNAxSE2VfrJ/d1337jL4z6D3?invite=cr-MSwxZFIsMjA1NTQ3MzU4LA
https://medal.tv/games/gta-v/clips/1XQMkHqbfLOk3j/d1337K1CMWzY?invite=cr-MSxVblIsMjA1NTQ3MzU4LA

### Expected behaviour

PNC should open and be uyseable

### Steps to reproduce

t/ PNC
or press F7 which is keybind for it.

### Any Texture Packs? (If so list)

no

### CMG User ID

9733

**Comment by Flinny-k** [comment]
![F7 when trying to use PNC](https://github.com/CMGStudios/issue-tracker/assets/161505905/176e715a-7990-45dd-a248-e0818ae21fe4)
![F7 when unemployed](https://github.com/CMGStudios/issue-tracker/assets/161505905/0a2d0575-7030-412a-ae6d-6454cdbcede9)

**Comment by Flinny-k** [comment]
top screenshot is when trying to use PNC while clocked on PD second one is when pressing F7 whilst unemployed

**Comment by Flinny-k** [comment]
I have  gone to settings and gone to keybinds clicked restore all default. this has fixed the issue.  I havnt tried to put all my keybinds back to see what will happen yet.

**Comment by crazychris2404** [comment]
Thanks for the update i will close this issue if it happens again please reopen this issue
