### ISSUE TITLE
[Bug]: UKBF radios are not organzied based on rank

### ISSUE THREAD

**Issue by ScarabMonkeyy** [CMGStudios/issue-tracker#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i do not know if this is a bug or it hasnt been coded in 
but in the radios like all the factions the participants in channels are organzied based on their rank so the higher your rank the higher you will be on radios but on ukbf this is non existant and the radios are quite a mess to look at

### Expected behaviour

say an assistant immigration officer is clocked on
if you clock on as a immigration officer (higher rank) then you should surprass the assistant immigration officer in the radios
doing this will help organize it and make it good to look at

### Steps to reproduce

1- have one person clock on UKBF and on radios
2- have another person with a higher rank clock on ukbf and join radios
3- you will see that the higher rank who clocked on will not surprass the lower rank 

### Any Texture Packs? (If so list)

Natural Vision Evolved 

### CMG User ID

369718

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
