### ISSUE TITLE
[Bug]: falling through the map

### ISSUE THREAD

**Issue by Daryan277** [CMGStudios/issue-tracker#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

falling through the map into ocean

### Expected behaviour

falling through the map in a car near the scuba diving car park into the ocean

### Steps to reproduce

seen in this clip - https://medal.tv/games/gta-v/clips/1Y2ULgjTDjs873/d13373doPmWz?invite=cr-MSxDZUosMjI0MTQ2MzEs

### CMG User ID

247126

**Comment by Keegasity** [comment]
Thank you for the report!

Unfortunately this is a client sided issue, If this continues to occur please contact myself via discord, I will be able to walk you through some resolutions.
