### ISSUE TITLE
[Bug]: Driving test serious failure - reverse parking 

### ISSUE THREAD

**Issue by DingleWarrior** [CMGStudios/issue-tracker#965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

So for some reason an old bug has re appear on driving test where you will fail with 1 serious and 0 minors for reverse parking , even though the instructor tells you to reverse park into the car parking space on the top level
![Screenshot 2024-03-01 130158](https://github.com/CMGStudios/issue-tracker/assets/142728248/003dd3ee-ea02-47c1-9579-b9e217b8a65c)

### Expected behaviour

do whats told by the instructor and pass

### Steps to reproduce

Start job , do everything needed till you get to the parking area, do the reverse park and then finish. Fails you

### Any Texture Packs? (If so list)

n/a

### CMG User ID

208

**Comment by crazychris2404** [comment]
Have you got a clip of this occurring please @DingleWarrior as recently i have watched multiple people complete the test with no issues popping up.
