### ISSUE TITLE
[Bug]: Not being able to kick people from F5

### ISSUE THREAD

**Issue by hodgy-123** [CMGStudios/issue-tracker#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

So i got given perms in my friends F5 to be able to invite and kick people but i can only invite and not kick people. i have 60% permissions within the F5 and that is enough to be able to invite and kick.

### Expected behaviour

Being able to kick people that doesnt need to be in the F5 anymore.

### Steps to reproduce

1. Open the F5 menu.
2. Go to members.
3. Press on a member and press kick.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

1226

**Comment by crazychris2404** [comment]
Duplicate issue
