### ISSUE TITLE
[Bug]: spawning in dead when i f8 quit and re-join   taco seller 

### ISSUE THREAD

**Issue by mrnobody243233** [CMGStudios/issue-tracker#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.youtube.com/watch?v=FXVvhlz4cXU

### Expected behaviour

https://www.youtube.com/watch?v=FXVvhlz4cXU

### Steps to reproduce

https://www.youtube.com/watch?v=FXVvhlz4cXU

### CMG User ID

354828

**Comment by crazychris2404** [comment]
Closed due to lack of information and clip being from a different players view which does not help to identify this issue
