### ISSUE TITLE
Car broken

### ISSUE THREAD

**Issue by mason2352** [CMGStudios/issue-tracker#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i lock car it doesnt let me get back in or i have to wait abt 15 seconds

### Expected behaviour

car broken

### Steps to reproduce

https://youtu.be/jjzwMW5d89Y

### Any Texture Packs? (If so list)

martin_spencer?

### CMG User ID

324817

**Comment by crazychris2404** [comment]
This is something that was happening for a while but a fix was put in place to reduce the chance of this bug occurring without any information on potential causes of this bug there is nothing that can be done. I will recommend that you step away from car and press comma again if that does not work try e and lock car from the radial menu and it should work fine then.
