### ISSUE TITLE
[Bug]: Oil Rig Ladders

### ISSUE THREAD

**Issue by czrtier** [CMGStudios/issue-tracker#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ladder is broken at the bottom from the water so u can't climb up to floor 1, just leaves u stuck at the top of the ladder and you can't climb up. Also on top floor the ladder to crane is a bit buggy but works sometimes, just kicks u off the ladder half way up it.

### Expected behaviour

To be able to climb them

### Steps to reproduce

Fix them I guess...

### Any Texture Packs? (If so list)

No

### CMG User ID

878

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report
