### ISSUE TITLE
= wont accept IDs or people giving cars

### ISSUE THREAD

**Issue by Zakk11** [CMGStudios/issue-tracker#97]
i have 60% keyboard and the = works when typing but in cmg it wont accept but i can decline ids and things

**Comment by alfiellds** [comment]
Hello Zakk, I also use a 60% keyboard and have never experienced this issue and therefore I have been unable to reproduce this.

It may be worth looking at your controls to determine whether you have changed the function of the = key. If this is the case, try resetting your keybinds to default and then using your = button.

Hope this has helped, let us know if you need any further support in the #game-support channel in the CMG Discord.

Many thanks.
