### ISSUE TITLE
[Bug]: ELS gives Learner plates

### ISSUE THREAD

**Issue by willz651** [CMGStudios/issue-tracker#970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When clocked on to PD and i interact with my ELS it puts L plates on my car

### Expected behaviour

No L plates and only sirens

### Steps to reproduce

dont put L platyes

### CMG User ID

407517

**Comment by crazychris2404** [comment]
Please can you attach your fivem logs from today 

To find your FiveM log files navigate to this directory:
%localappdata%/FiveM/FiveM.app/logs

**Comment by willz651** [comment]
[CitizenFX_log_2024-03-04T120913.log](https://github.com/CMGStudios/issue-tracker/files/14488290/CitizenFX_log_2024-03-04T120913.log)

**Comment by crazychris2404** [comment]
Forwarded to devs
