### ISSUE TITLE
[Bug]: unknown f8 spam

### ISSUE THREAD

**Issue by DingleWarrior** [CMGStudios/issue-tracker#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Been told to send this here for the devs , F8 keeps going crazy every now and again , when this f8 issue occurs i am unable to move or type in chat. Had to re install my game twice for it to finally let me move
[CitizenFX_log_2024-03-03T191540 (2).log](https://github.com/CMGStudios/issue-tracker/files/14513748/CitizenFX_log_2024-03-03T191540.2.log)

### Expected behaviour

load in no f8 spam and able to move

### Steps to reproduce

Honestly not sure i know its been happening to others with random f8 log issues i literally just loaded in and just kept happening 

### Any Texture Packs? (If so list)

no

### CMG User ID

208

**Comment by DingleWarrior** [comment]
[bug day 2.txt](https://github.com/CMGStudios/issue-tracker/files/14531973/bug.day.2.txt)


Day 2 this is still happening , loaded in and straight away cant do anything same f8 log spam unable to move or type

**Comment by crazychris2404** [comment]
Forward to devs

**Comment by packfile** [comment]
Thanks for the report, this was fixed a few weeks ago
