### ISSUE TITLE
[Bug]: Heist setup boat not showing

### ISSUE THREAD

**Issue by zzk12121** [CMGStudios/issue-tracker#975]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description

whenever i carry on with the heist setup go in my dingha to drive to the boat the boat doesnt spawn in for me so i fail the heist

### Expected behaviour

i dont know if it just happens for me but i hope there is a fix

### Steps to reproduce

idk

### Any Texture Packs? (If so list)

reshade

### CMG User ID

312688

**Comment by crazychris2404** [comment]
Reopen this with a clip of the incident please
