### ISSUE TITLE
[Bug]: Rebel isn’t 90% off in purge 

### ISSUE THREAD

**Issue by SamWood420** [CMGStudios/issue-tracker#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When in purge if you buy any rebel guns or armour it’s full price

### Expected behaviour

Buy the gun / armour
Get it for 90% off

### Steps to reproduce

Buy the gun / armour
Get it for 90% off

### Any Texture Packs? (If so list)

No

### CMG User ID

1232

**Comment by crazychris2404** [comment]
The weapons are 90% off from what I know but will get someone to double check

**Comment by SamWood420123** [comment]
just checked and its still full price
