### ISSUE TITLE
[Bug]: UKBF Clock on Ranks and Officer of the week

### ISSUE THREAD

**Issue by ScarabMonkeyy** [CMGStudios/issue-tracker#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

on ukbf we have the special officer and advisor but the roles are useless because you need to have the HM inspector role to clock on as them 
more explanation
if you are a special officer than your role in the discord is useless because if you want to clock on as a special officer you need to have the HM inspector role and the same goes for advisor 

and for the officer of the week i do not know if this has been coded in or not but there is no extra pay for the role like all the other factions and was hoping we could get that sorted so we could start using it 

### Expected behaviour

the role IDs
Special Officer= 1124112267731026020 must be able to clock on as special officer
Advisor= 1124109483786911795 must be able to clock on as a UKBF Advisor 
HM inspector= 1124100630932361257 currently can clock on as HM inspector and special officer and advisor but should only be able to clock as a HM inspector
Officer of the Week= 1124112267731026020 must have %25 paycheck increase when the role is assigned to someone 

### Steps to reproduce

1- As UKBF you must have either the advisor or the special officer role in the discord and when you go to clock on u can see that you are not able to 
2- to fix this and be able to clock on as UKBF Advisor or special officer then you need to have the HM Inspector role because for some reason that role has perms to clock on as advisor and special officer and HM Inspector
3- and for the officer of the week 
when assigned there is no bonus paycheck

### Any Texture Packs? (If so list)

Natural Vision Evolved 

### CMG User ID

369718

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the detailed report
Much appreciated

**Comment by packfile** [comment]
Please request this feature through management, this is not a bug as these roles were not requested during the initial formation of border force.
