### ISSUE TITLE
Stepping out the vehicle

### ISSUE THREAD

**Issue by chemq** [CMGStudios/issue-tracker#98]
**Describe the issue you're facing**

**Steps to reproduce**

**Expected behaviour**

**Screenshots/Video**

**Additional context**

**Any Texture Packs (if so list)**

**Perm ID**

**Comment by chemq** [comment]
Can you guys fiox that when u step out on hills that you step on the driver side and not passenger side im losing my cancer mind pleae fix it

**Comment by arthur-rl** [comment]
This is sadly a feature from GTA5 and cannot be changed at this time.
