### ISSUE TITLE
[Bug]: Stuck in respawn menu

### ISSUE THREAD

**Issue by realShlumped** [CMGStudios/issue-tracker#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I've tried restarting me game but no luck.

### Expected behaviour

Respawn me

### Steps to reproduce

Go to the edge off the map cause you're tabbed out on pilot
Have your plane break cause you reached the map
Die cause you're outside the edge when you exit your plane
After pressing E to respawn and be stuck in the respawn menu

### CMG User ID

208089

**Comment by crazychris2404** [comment]
Please do /calladmin to get a revive

**Comment by realShlumped** [comment]
> Please do /calladmin to get a revive

Ashy revived me but it did nothing.
