### ISSUE TITLE
[Bug]: car isn’t in garage 

### ISSUE THREAD

**Issue by haz412958** [CMGStudios/issue-tracker#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I logged on yesterday and I came to my garage take my car out and it was not there I had 4 whitelisted ARS and SMGS 1.5 million worth off guns and 100k off dirty cash I am not bothered about the car I just would like all my stuff back out off the boot 

### Expected behaviour

I forgot the name off the car but it was yellow and small it’s not worth much but in the boot there was I would like all my stuff back 

### Steps to reproduce

I have not solved this yet. 
But I have rest my game 
And still doesn’t work 

### Any Texture Packs? (If so list)

No 

### CMG User ID

412958

**Comment by crazychris2404** [comment]
This has been forwarded and being looked into already as per multiple reports

**Comment by crazychris2404** [comment]
I have fixed this issue
