### ISSUE TITLE
[Bug]: it wont let me buy plat large arms weapons when i have platnium 

### ISSUE THREAD

**Issue by J2trappy0** [CMGStudios/issue-tracker#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

basically i brought platinium and it wont let me purchase weapons from platnium large arms on vip island

### Expected behaviour

a

### Steps to reproduce

a

### Any Texture Packs? (If so list)

no

### CMG User ID

403140

**Comment by PIKAlmao** [comment]
Do you have the gang license ?

**Comment by J2trappy0** [comment]
yes

**Comment by crazychris2404** [comment]
Intentional based on licenses
