### ISSUE TITLE
[Bug]: car upgrades reset 

### ISSUE THREAD

**Issue by cznac** [CMGStudios/issue-tracker#986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i bought my car from my freind and and he showed me it was fully upgraded with bulletproof tires i bought it from him and it some reason took the bulletproof tires off and made me try adn pay 2.5mil for them and this happens everytime there is a vehicle reset in the game it either takes something off the car like and upgrade or resets the coulor or wheels 

### Expected behaviour

my vehicle resets something on my car everytime there is a reset 

### Steps to reproduce

not sure 

### CMG User ID

414418

**Comment by crazychris2404** [comment]
What was the spawncode of the car?
