### ISSUE TITLE
[Bug]: Payment plan ingame 

### ISSUE THREAD

**Issue by matosmatos1** [CMGStudios/issue-tracker#988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

im getting taxed for my payment plan ingame. Takes 500k each week, admin said it was a bug. 

### Expected behaviour

im getting taxed for my payment plan ingame. Takes 500k each week, admin said it was a bug. 

### Steps to reproduce

go into payment plan and go into weekly income, i should be recieving 10m but im getting 9.5 roughly. 

### CMG User ID

372280

**Comment by packfile** [comment]
The vehicle was payment planned for £115,000,000 over 12 weeks so the weekly payment would be around ~£9,580,000. This matches the reported behaviour
