### ISSUE TITLE
[Bug]: boot does not close

### ISSUE THREAD

**Issue by ghost** [CMGStudios/issue-tracker#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I access the boot on any vehicle, after closing the inventory screen, the boot does not shut on the vehicle. This happens 9 times out of 10

### Expected behaviour

Boot should close after I exit the inventory screen

### Steps to reproduce

Not sure 

### CMG User ID

1213

**Comment by crazychris2404** [comment]
I have not had this issue occur please reopen with a clip of it
