### ISSUE TITLE
Lifepak bug, not being able to connect to patient and only fixes till restart.

### ISSUE THREAD

**Issue by JaouadAR** [CMGStudios/issue-tracker#99]
**Describe the issue you're facing**
Sometimes it happens when we try to do our NHS duties that the lifepak bug happens and the Lifepak stops working, it doesn't let us connect to the patient to get him up ( Shock Patient ).

**Steps to reproduce**
Come up to patient, flex E > CPR > nothing happens. 

**Expected behaviour**
Come up to patient, Flex E > CPR > Go into /nhs or flex U > Observations at the bottom > Shock Patient ( to get the patient back up ) However this affects more people in NHS daily and the only fix known is to wait till restart.

**Screenshots/Video**
https://youtu.be/WO23X3WTyIc
( Make sure to watch the whole 10 minute video, as i try it twice, also there is a bit of console included in the video in-case it might be of help. )

**Additional context**
I'll do quacky quacky if u fix.
**Any Texture Packs (if so list)**
Project Rogue 
NVE
LA Roads
Conversion
Terrov
And i use Reshade with a little own touch.

( However this issue affects more people not only me. )
**Perm ID**
115411

**Comment by alfiellds** [comment]
Hello JaouadAR, thank you for the report. I can confirm this issue is occurring and will now forward it to the developers.

Many thanks.

_Note for the developers:- this issue is difficult the reproduce and appears to fix following a server restart only. _

**Comment by rubbertoe98** [comment]
*Potentially* fixed from next restart, please report back if this happens again.
