### ISSUE TITLE
I keep falling through map constantly  [Bug]: 

### ISSUE THREAD

**Issue by Kaibaker19** [CMGStudios/issue-tracker#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

every time I load into the server keep falling through the map constantly

### Expected behaviour

it should not be doing this

### Steps to reproduce

dunno

### CMG User ID

[/getmyid]

**Comment by crazychris2404** [comment]
Hi this is your graphics settings if you press F2 you can change your settings there

**Comment by crazychris2404** [comment]
Game support in discord has further info listed

**Comment by Kaibaker19** [comment]
> Hi this is your graphics settings if you press F2 you can change your settings there

tried it still falls through map
