### ISSUE TITLE
[Bug]: handcuffed stances bugged

### ISSUE THREAD

**Issue by ScarabMonkeyy** [CMGStudios/issue-tracker#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when handcuffing someone they do get handcuffed and all but their stance is the stealth mode from the normal vanilla game and in rp scenarios it looks weird and when you uncuff someone then it becomes how it should be 

### Expected behaviour

when cuffing someone their hands show go behind their back instead of being in stealth mode

### Steps to reproduce

1- handcuff someone and you will see the animation for it is bugged
2- when you uncuff them it then becomes how it should be but you can press X and break out of it

### Any Texture Packs? (If so list)

Natural Vision Evolved 

### CMG User ID

369718

**Comment by crazychris2404** [comment]
Confirmed
This has been a bug for as long as i have been in CMG
