### ISSUE TITLE
[Bug]: Personal vehicle wheels/rims changing (or being reset to default) automatically upon relogging

### ISSUE THREAD

**Issue by ZXRProductions** [CMGStudios/issue-tracker#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Personal vehicles (only tested with import cars) wheels/rims being reset to default or automatically changed to something different than last applied upon relogging/rejoining the server between intervals. Once the wheels are glitched/reset due to this, going back to Mod Shop and scrolling over wheel-types no longer changes the wheels (or applies them despite purchasing).

Note that I've checked that the car model files were not deliberately changed or modified since this occurred. Relogging sometimes allows me to restore the old customized wheels to be equipped again, implying this is indeed a bug with stored car (wheel) upgrades/properties.

### Expected behaviour

Once applied, no properties of the personal vehicle should change no matter what. The car's mod shop customizations should be stored correctly and remain the same until the user decides to modify it again.

### Steps to reproduce

There are unfortunately no clear steps of reproduction I was able to come up with. This is due to the fact that this bug seems to be quite inconsistent (rather random) in nature.

As of now:
1. Join the server, spawn an existing import slot vehicle (a default imported car, **not** a vehicle that's brought in on a lock)
2. Drive for a bit and store it back in the garage.
3. Log off the server and rejoin.
4. If you're unlucky (here's where the randomness comes in), your vehicle's wheels will have been reset to default. If not, wait for the scheduled automatic server restart and try again the next day.

I have a sneaking suspicion this may either have to do with:
- Something going wrong in the scheduled daily server restarts where some vehicle values/properties are incorrectly fetched from the database or a missing model.
- Or imports incorrectly pre-loaded into player's garage with missing components, which force-resets the vehicle's wheels to default. Storing the vehicle again possibly overrides these changes, forcing the player to re-equip the wheels again from the mod shop and restoring the vehicle back into garage to possibly be overwrite the false-written vehicle (if that makes sense).

### CMG User ID

1969

**Comment by packfile** [comment]
I believe some custom wheels were removed around the time of this report. It's likely these vehicle(s) are referencing the now-removed wheels. Taking each vehicle with the issue into LS customs and selecting a new wheel should fix the issue
