### ISSUE TITLE
[Bug]: Trucking Job

### ISSUE THREAD

**Issue by cain27k** [CMGStudios/issue-tracker#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If your truck gets "destroyed" / stored it won't let you re-start the trucking job illegal or legal. 

### Expected behaviour

Be able to restart the job without logging out.

### Steps to reproduce

1. Get a Trucking Job
2. Store Vehicle
3. Try to re-get the job.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

216488

**Comment by crazychris2404** [comment]
This is no longer occuring please reopen if you experience again
