### ISSUE TITLE
[Bug]: door hacking device glitch

### ISSUE THREAD

**Issue by Latzzzzzx** [CMGStudios/issue-tracker#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Bug]: I lost a door hacking device (twice) due to a bug encountered at the fleeca bank on the west side of the map.

### Expected behaviour

[Bug]: I lost a door hacking device (twice) due to a bug encountered at the fleeca bank on the west side of the map.

### Steps to reproduce

idk what to write here

### Any Texture Packs? (If so list)

no

### CMG User ID

378511

**Comment by packfile** [comment]
Thanks for the report, this was fixed last week
