### ISSUE TITLE
[Bug]:  Car ELS not working - pdrs3md

### ISSUE THREAD

**Issue by remyscustoms** [CMGStudios/issue-tracker#995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my PD car els is not working  - pdrs3md

### Expected behaviour

I am supposed to be able to toggle the emergency lights with Q

### Steps to reproduce

Spawn the car 
Press q 

### Any Texture Packs? (If so list)

N/A

### CMG User ID

284378

**Comment by crazychris2404** [comment]
This is being looked into already car reports should not be posted here
