### ISSUE TITLE
Banned for cheaing when not cheating 

### ISSUE THREAD

**Issue by GarbyUK** [CMGStudios/issue-tracker#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i was playing and then got banned permantly for 1.01 cheating when i didnt do anything 

### Expected behaviour

banned for 1.01 cheating when not cheating

### Steps to reproduce

not ban me for cheating when i did nothing 

### Any Texture Packs? (If so list)

no

### CMG User ID

400972

**Comment by crazychris2404** [comment]
Not a bug

**Comment by GarbyUK** [comment]
Yes but I did not cheat at all on the server or on five m in general.Sent from my iPhoneOn 18 Mar 2024, at 10:10 pm, crazychris2404 ***@***.***> wrote:
Not a bug
