### ISSUE TITLE
[Bug]: west highway new mlo is bugged

### ISSUE THREAD

**Issue by TheRealWicks** [CMGStudios/issue-tracker#997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

door hacking device not work doesnt open the vault

### Expected behaviour

vault to open

### Steps to reproduce

try rob highway bacnk

### Any Texture Packs? (If so list)

no

### CMG User ID

255

**Comment by crazychris2404** [comment]
Confirmed Thanks for the report

**Comment by packfile** [comment]
Thanks for the report, this was fixed last week
