### ISSUE TITLE
[Bug]: can’t get out of plan when after putting hands up

### ISSUE THREAD

**Issue by Nanocmg** [CMGStudios/issue-tracker#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I’ve been told by multiple people that they’re having this problem and can result to then FTVL.

### Expected behaviour

Able to get out of plan after raising hands.

### Steps to reproduce

X in plane to raise hands

### CMG User ID

1052

**Comment by Keegasity** [comment]
Good Evening,

Please can you confirm what the issue is? I face no issues with putting my hands up in the plane or after exiting the plane?

Many Thanks,
Keegan

**Comment by Nanocmg** [comment]
It was reported to me durning a sit, could’ve been them bullshitting.
